### ISSUE TITLE
Specify what a competitor can bring to the solving station?

### ISSUE THREAD

**Issue by cubizh** [thewca/wca-regulations#103]
Should there be a specification, like in the form of a guideline, to specify what a competitor can/cannot bring with him to the solving station?
Often it is seen people using an arbitrary secondary cube, or a tripod camera, or an mp3 player (which obviously remain untouched during the attempt), but should there be a note about what's possible/not possible to bring, to prevent people from bringing things like weird things like a puppy, a pizza, a mirror, a kitchen sink, etc?

**Comment by lgarron** [comment]
Definitely a tricky issue. I'm sure an organizer can handle puppies and pizzas, but here are some thoughts that come to mind:
- @iVinshe pointed out to me once that a 3x3x3 on the table can be used to remember the color scheme for 4x4x4.
- Smartphones are becoming a popular choice for filming yourself... but they make it trivial to broadcast the scramble to anyone else in the room who has a smartphone. (You could even _force_ an innocent competitor to receive an MMS of the scramble on their phone.) If we restrict competitor self-filming, the audience can still do that.
- Cameras with an articulated screen (one that can face back at you) help you adjust the view of the station, but they also work like a mirror.
- Given how long competitors have to be in the competitors area sometimes, and how inconsistent the experience is, I would prefer not to ban phones outright, and I would prefer that we allowed practice cubes.
- If someone receives a phone call, what _should_ they do? Silence it? Let the judge answer it? Just the fact that someone called/texted you can be used to signal things.
- Sometimes, even 1 (binary) bit of information can be significant, because knowing something about parity can be very useful in some puzzles.

What they bring to the table is not a concern if it doesn't give them an unfair advantage (and doesn't bark at other competitors distractingly). But if we want to ban things that can give an advantage, I don't really know where to start. I think the only sane thing is to keep some level of trust in the competitors as long as they don't act suspicious.

**Comment by KitClement** [comment]
I'm actually in favor of not allowing the competitor to put cubes on the table when solving.  They should be allowed to have practice cubes, but be put in a place that is not visible during the solve.  Maybe we could have the judge use the cube cover to hide a practice puzzle?

I have already had to tell several competitors that their cameras are not allowed on the table if a screen is visible to the competitor.  I'm not too worried about the broadcasting of scrambles, I think that the information given by this wouldn't yield anything beneficial in the time allotted to the competitor.  Also, I think any suspicious activity (using cube explorer with videos at this competition) would be easily caught and shamed upon by other competitors in the area.

I'm weakly for having competitors required to silence cell phones when at the solving station and removing them from sight.  Most competitors should be used to this common courtesy when taking tests in school, and it's easy to understand how this should apply to cubing.  I believe any sound or vibration from a phone should be grounds for a DNF.

**Comment by Laura-O** [comment]
We now have [2i2](https://www.worldcubeassociation.org/regulations/history/official/2015-07-01/#2i2) for all issues related to cameras.
I currently see no need to specifically forbid anything of the above-mentioned objects, so I'm closing this for now.
