### ISSUE TITLE
2n1 "or" vs "and"

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#1108]
> 2n1) Disputes are only permitted during the competition (see Regulation 9u), within 30 minutes after the disputed incident happened, **or** before the start of any following rounds of the relevant event.

I believe that the intention behind this regulation is that all 3 requirements must be met for a dispute to be permitted. If this is the case then "and" should be used in the place of "or"

**Comment by Nanush7** [comment]
Thank you Samuel for bringing this up!

@thewca/wrc-team I think it makes sense that it should be an "and".

**Comment by lgarron** [comment]
> I believe that the intention behind this regulation is that all 3 requirements must be met for a dispute to be permitted.

I don't believe so. My interpretation is: "You have until the start of the next round. But if that starts immediately, you still always have 30 minutes."

Seems that reasonable people are disagreeing on the interpretation, so I'd be in favor of clarifying it either way.

**Comment by xsrvmy** [comment]
There is 2n2 that suggests a round must only start after disputes are resolved.

An additional clarification is needed here: the 30 minute time limit should start after the competitor is made known of an incident, not when the incident occurs, since an incident may take a while to discover. It's also unclear if a competitor has a right to dispute if an incident is discovered in the previous round after the next round starts.

**Comment by ohexter** [comment]
Amended [here](https://github.com/thewca/wca-regulations/pull/1236), will be deployed January 1st, 2025.
