### ISSUE TITLE
Darker color on front for Square-1 scrambling

### ISSUE THREAD

**Issue by Nanush7** [thewca/wca-regulations#1139]
To be discussed in the following amendment cycle.

The idea is that it doesn't make much sense to say that a Square-1 scrambled with the orange face in the front is misscrambled.

**Comment by notkevin888** [comment]
I'm pretty in-favor of this change; I can't think of a single "top player" who isn't red-orange neutral (or maybe F/B-neutral is slightly more precise?), and the only potential affect I could see it having is that CSP tracings would technically be different between the two orientations.  But even then:
- For Cale tracing, it barely affects anything - all that changes is that red-orange and green-blue swap when tracing corner permutation and edge permutation, but the net factors are the same (eg, an ordering of RGBO gives the same parity of OBGR).
- For BLD tracing, it's quite a larger net effect, as it basically "applies" 8 2-swaps between the two orientations; but the resulting parity ends up at the same value either way, and the chance the "wrong" orientation has the "better" tracing is both subjective (eg, some people prefer cases with long cycles, while others prefer many short ones) and 50/50 anyway.

I'll also admit I fully forgot about the darker-on-front regulation myself because I forgot it mattered (although I'm so used to scrambling red-front that I don't think I've personally sent out an orange-front scramble), and because I mistakenly thought that it was changed to any-on-front when Clock scrambling was changed to any-on-front.

Further, one of the historical reasons to adhere to darker-on-front was so that the colors in the scramble display match the colors on the puzzle itself.  However, there's quite a bit of variation within just popular color schemes today that already affects the images (black being substituted for white or yellow, white-top versus yellow-top [which generally changes what the left-right colors are, as well]).  So, adding front-color flexibility doesn't really affect the accuracy of the images in a substantial way.

**Comment by Sixstringcal** [comment]
I could be misremembering, but I do recall some Lin users who predict first block not being darker on front neutral.  Idk how fb prediction works, but I definitely would reach out to some of the top lin solvers before making this change.

**Comment by CarterKoala** [comment]
Discussed in the last regs update, not implementing since recognition is based on colors and some people are not y2 neutral
