### ISSUE TITLE
Suggestion to reduce cheating during blindfolded events

### ISSUE THREAD

**Issue by sebastiannielsen** [thewca/wca-regulations#1140]
I have a suggestion, how blindfolded events could be remade, to prevent cheating (eg, looking through/under blindfold etc - https://www.youtube.com/watch?v=Rdy9CeM__3A ):

Instead of using a blindfold, the solver should use a cube, where all stickers or colored pieces have been replaced with corresponding items, where the piece's identity, is only visible with UV light (or IR light).

During memorization phase, a UV or IR light will be accessible to the competitor.
Another variants could be used - for example pieces with hidden magnets in different orientations, thats only visible by placing magnet paper on the cube, but this creates the possible for cheating using magnet implants in body.

A third variant is where each cube piece has a RFID tag inside, and then cube can be "read" by placing it in a portable cube enclosure with a screen on each side that displays the current state of the cube.
The cube contains no electronics (apart from the passive RFID tags).

You understand the idea, instead of requiring the competitor to be blinded, blind the cube instead.

Surely, it would require new standards to be created for "WCA approved blind cubes" but I think it would be a healthy addon to cumber blindfolded cheating.
Another advantage is that blindfolded competitors can follow the same rules for the normal competitors with stackmat timer and everything else, since the only thing they don't see is the pieces identity on the cube.

Is there some problems with such a "regime" or could it be a good advantage to prevent blindfolded cheating?

**Comment by Nanush7** [comment]
Hi Sebastian. Thank you for your participation!
Do you mind posting this in the [WCA Forum](https://forum.worldcubeassociation.org/)? It will facilitate the discussion.

**Comment by RodrigoTeixeira01** [comment]
I think that has multiple issues. The first and most important is that people would have to buy a new cube, obligating them to use extra enpredicted money. The secound is the readability issue, if the person has to use magnet paper, they have to wait for it to show the image, if the person uses magnet,they have to recognise the magnet shape, and is fully unable to look ahead, and is obligated to phisically move their hand. If they use UV light, the colors will be completely different of what they are used to, and probabilly differ less between one another. A third issue is what faces are green and white, for the scramblers, and for the scramblers to ensure it isn't a misscramble will have to spend a big time checking each sticker, since the colors are so hard to see. The third issue is that the person would not be blindfolded anymore, but still competing on "3x3x3 Blindfolded". The last issue is that if the person can freely see their friend watching, that could just hold a paper with all the letters of the solve or smth. Basicly, I don't think this solution is good, and the literal opaque paper put between the competitor and the cube does the whole job.

**Comment by ohexter** [comment]
The WRC reviewed extensive Staff and Community feedback when selecting which topics to amend for the January 2025 WCA Regulations and Guidelines and chose not to make changes addressing this item. Previously raised items will not automatically be taken forward for consideration in future cycles so this issue has been closed. You are welcome to raise this topic again in a future cycle if desired.
