### ISSUE TITLE
2h change ”fully dressed” to ” appropriately dressed”

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#1149]
Discussed in [this forum post](https://forum.worldcubeassociation.org/t/2h-change-fully-dressed-to-appropriately-dressed/39800)

tldr - there are times where it may be appropriate not to be "fully dressed" based of the circumstances, but it would be considered culturally appropriate not to be fully dressed in that scenario. Ex. not wearing shoes

**Comment by lgarron** [comment]
I think this makes sense in the abstract, but "appropriate" is definitely vague. It sounds to me like it opens up the door to an arbitrary dress code, rather than "you just have to be wearing enough stuff".

(I also don't see an issue with shoes being optional for "fully dressed" in some venues.)

I guess I'm not arguing against a change, but I think "appropriately dressed" is not sufficiently better — maybe there's another alternative that is.

**Comment by mintydev789** [comment]
Is this really an issue, considering that the current wording doesn't seem to cause any problems? I feel like changing this would only make things weirder, cause people would notice the less strict wording and might think something else is "appropriate". I'd say just leave it as is.

**Comment by sarahstrong314** [comment]
Why not just remove 2h altogether? Doesn't [2k3 ](https://www.worldcubeassociation.org/regulations/#2k3) cover the consequences of competitors wearing inappropriate or insufficient clothing?
