### ISSUE TITLE
A7c3 and A7c4 contradictions

### ISSUE THREAD

**Issue by CelineTrammi** [thewca/wca-regulations#1194]
**Describe the typo**
[A7c3](https://wcaregs.netlify.app/#A7c3)) If the competitor signs (or otherwise marks) an attempt after starting the attempt but before the judge has **finished recording the result**, the attempt will be considered unfinished (DNF).
[A7c4](https://wcaregs.netlify.app/#A7c4)) The competitor should not sign an attempt before the judge has **recorded and signed** the attempt. The competitor is ultimately responsible for ensuring that they and the judge have signed an attempt. If an attempt is found to be missing one or both signatures after the judge delivered the score sheet to the score taker (see [Regulation A7f](https://wcaregs.netlify.app/#A7f)), it will be considered unfinished (DNF).

I think it is a bit weird to have A7c4 say that the competitor "should not" sign before the judge has recorded and signed the attempt, when the reg just before says that signing before the judge records the result is DNF. 

**Possible solution**
1. Remove "recorded and" from A7c4:
[A7c4](https://wcaregs.netlify.app/#A7c4)) The competitor should not sign an attempt before the judge has **signed** the attempt. The competitor is ultimately responsible for ensuring that they and the judge have signed an attempt. If an attempt is found to be missing one or both signatures after the judge delivered the score sheet to the score taker (see [Regulation A7f](https://wcaregs.netlify.app/#A7f)), it will be considered unfinished (DNF).

2. Remove A7c3. Or just clarify that empty boxes (i.e. no recorded results) with both signatures are still DNFs. 
A7c3 reg directly interpreted is fairly strict. I would assume most people do not follow this procedure in practice.

**Comment by lgarron** [comment]
The current phrasing allows for the situation where a judge accidentally asks the competitor sign before they do. This still happens to me once in a while (although I usually ask the judge to sign first).

A7c3 specifies that it's the recording of the *result* that determines whether the result will be DNFed, while allowing for signatures in either order afterwards.

A7c4 puts the responsibility on the competitor that both signatures are present at the end. I guess the confusing thing is that A7c4 mixes the *requirement* (both the judge and competitor must sign) with a *recommendation* (make sure the judge signs before you sign as a competitor, so that you can be certain attempt is complete when you finish signing).

I personally think that either of the solutions listed above would be a risk compared to leaving both Regs as-is, although splitting up A7c4 might make its components (requirement vs. recommendation) more clear.

**Comment by ohexter** [comment]
The WRC reviewed extensive Staff and Community feedback when selecting which topics to amend for the January 2025 WCA Regulations and Guidelines and chose not to make changes addressing this item. Previously raised items will not automatically be taken forward for consideration in future cycles so this issue has been closed. You are welcome to raise this topic again in a future cycle if desired.

**Comment by ohexter** [comment]
update status to 'closed as not planned'

**Comment by ohexter** [comment]
update status to 'closed as not planned'

**Comment by ohexter** [comment]
update status to 'closed as not planned'
