### ISSUE TITLE
Add (back) "Best of 3" for FMC

### ISSUE THREAD

**Issue by SAuroux** [thewca/wca-regulations#150]
# Proposal

**Add (back) "Best of 3" for FMC and recognize "Mean of 3" rankings for those rounds**
https://github.com/cubing/wca-documents/compare/add-best-of-3-for-FMC

Clarification: This is not my own proposal, but I created this as it is an ongoing topic within the community. Below are some senseful Pros and Cons:
# Pro
- The "No Best of 3 for Mean of 3 events" (https://github.com/cubing/wca-documents/issues/109) did neither take into account the movement of FMC to this category, nor the possibility to recognize "Mean of 3" results based on the times of "Best of 3" rounds, as added for 3x3x3 BLD at a later point. The main argument for https://github.com/cubing/wca-documents/issues/109, that "Mean of 3" needs the same ressources as "Best of 3" does not fully apply to FMC.
- "Best of 3" might be a good choice for smaller competitions/competitions without titles, where very fair conditions for placing are not of such a big importance. Competition organisers could plan FMC attempts in parallel and leave the choice to compete to the competitors. Competitors that care a lot would get the chance to obtain a "Mean of 3" ranking, while others could dismiss one or two attempts and could still place.
- "Mean of 3" can still be used as format for important competitions with titles where fair conditions for placing are of a big importance (i.e. national/continental/world championships)
# Cons
- In contrast to the above mentioned 3x3x3 BLD event, FMC has a "Mean of 3" competition format. Hence, the comparison doesn't withstand. It is arguable if a "Mean of 3" result obtained from a "Best of 3" round should be compared to one obtained from a "Mean of 3" round in the WCA rankings, now that the "Mean of 3" format is officially available.
- Reading between the lines, the only goal of this proposal seems to be having a different ranking possibility within a competition. However, competition organizers are already free to hand out certificates and prizes in any arbitrary way independently from the WCA regulations. Hence, it is arguable if this change would provide any benefit.
- It is not fully clear when it makes sense to choose "Mean of 3" to provide fairer conditions for FMC and many serious FMC competitors might be very disappointed about a "Best of 3" choice when getting beaten by a fluke.
- Leaving this choice up to an organiser can be dangerous, as the preferred format might often get ignored without a really good reason.

**Comment by KitClement** [comment]
I suggested this on the speedsolving forums, but I'll suggest it again: 

Could we have Mean of 3 be the default format, but allow Best of 3 with board approval?  I think this would help alleviate your cons, as such a format would only be approved when the competition has the correct reasoning for  the format (time constraints, logistical issues for competitors, etc.), and not simply because the organizer prefers the Best of 3 format.  

A con that I can see as a result is that this potentially creates more work for the board when approving FMC, although I'm not sure of how large of an issue that would be.  Also, it seems a bit inconsistent with the issue proposed by Justin Thomas on speedsolving: it would be strange that Best of 3 requires board approval for FMC but Best of X for 3x3 does not require board approval.

**Comment by SAuroux** [comment]
I have just updated the initial comment, as this point has been raised again on the delegate's mailing list.

For the record: I am not in favour of this change.

**Comment by Laura-O** [comment]
This proposal was written more than 2 years ago. I think it's safe to say that there is no interest in adding back "Best of 3" for Fewest Moves anymore.
If someone disagrees, feel free to open it again. :-)
