### ISSUE TITLE
Possibility of removing Feet Solving for 2015

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#175]
Here is a list of pros and cons for the what happens if Feet is removed, which was compiled from this [thread on the Speedsolving Forum](http://www.speedsolving.com/forum/showthread.php?48355).

**Note: These are merely pros and cons that would come out of its removal. They are not the same thing as "reasons to remove Feet" and "reasons to keep Feet".**
### Positive outcomes of removing Feet
- Feet is arguably the most unsanitary event, since feet can be much less clean than hands, especially when clean socks/footwear are not worn. Additionally, even when one's feet are actually clean, watching them being used can still be very uncomfortable and repulsive. Feet solving (both official solves and practice solves at competitions) can contribute to an unpleasant atmosphere to spectators and non-Feet competitors, so its removal would give more pleasant experiences at competitions.
- Fewer people are willing to judge and/or scramble for Feet relative to other events, and it's not so great to have to force people to do either at a competition (organizers are allowed to do this according to [Regulation 1e2](https://www.worldcubeassociation.org/regulations/#1e2)). Judging for Feet solves can be humiliating since judges have crouch to lift the cover and watch the solve, and may have to take a close look at the puzzle to inspect misalignments. It would also be more pleasant for scramblers and judges for other 3x3x3 events to know that competitors don't use the same cube for other 3x3x3 events right after using it for Feet solves.
- If Feet Solving is removed as an event, then it would make organizing large competitions (ones that hold all events) less of a hassle for the organizers. Feet Solving required additional floorspace (some organizers even prefer a separate room), and additional equipment such as plastic gloves, saran wrap, wipes, and sometimes new timers and mats (e.g. At Worlds 2013 and previous US Nationals, the organization team got new timing equipment just for Feet then sold them afterwards). Setting up and taking down the timing stations for Feet can also take some additional time if the event is held in a different area than where the main timing stations are. 
- A common "abuse" of the +2 misalignment penalty is to not perform the last move in a Feet solve if it would take more than 2 seconds. Removing Feet would resolve this problem. [_Note: This is a relatively minor pro, but it's not obvious and it's included in this list for the sake of making it complete as possible. This is a positive outcome from the removal of Feet, since it helps reduce the number of ways the +2 penalty can be used to one's advantage._]
- The [Sum of Ranks](https://www.worldcubeassociation.org/results/misc/sum_of_ranks), the most common and well-known way to measure the overall rankings of competitors, would be more credible without Feet Solving since it would compensate for the many competitors who refuse to compete in Feet Solving for personal reasons.
### Negative outcomes of removing Feet
- Removing the event would make all past Feet solves unofficial. It would take away Feet records that took a lot of effort to accomplish.
- Removing the event would allow no more official Feet solves, and all Feet Solves in future competitions would be unofficial and less likely to he held. This would disappoint those who enjoy participating in the event and those who enjoy watching it at competitions. 
### Neutral outcomes of removing Feet
- The popularity and appeal of Feet Solving is not the same in all countries. There are communities that love the event, and others that despise it. Its removal would satisfy some communities, but dissatisfy others.
- Media at competitions often covers Feet solves if it is held. Depending on how they portray Feet Solving and what they say about it, it can give different positive or negative impressions to the viewers about WCA competitions and the cubing community. It can both hurt and help the image of cubing, depending on what the viewers take from it. 
- How much 3x3x3 With Feet added as an event is controversial. As a 3x3x3 variant, it added another twist to solving a 3x3x3 using a regular speed method, but it also added the factor of not using hands, which made it require a new kind of skill. Its removal would be a loss in variety of events, however how large the loss is is debatable. Any additional knowledge (e.g. algorithms) that cubers have leaned for Feet Solving has not gone to waste since it can be reapplied to other events, but the techniques (e.g. tricks for performing moves fast with one's feet) used for Feet Solving may not be able applicable to other events.

**Comment by lgarron** [comment]
I would mention that a lot of these are personal views held by _some_ organizers/competitors.
Whether a reason should matter depends in part on which ones do, but I do believe that it's worth listing any view that seems to be held by more than a small handful of people.

Because of reasons like hygiene, feet is one of the events that people impacts them most even if they're not involved with it (i.e. "you can just not hold it/participate" isn't a good argument for them). How much we should listen to those concerns hasn't been determined, but we should definitely not rule anything out from either side.

Also, it would be useful if we could find citations for all the arguments. (I know, the Delegate discussions are private. But there were _some_ sensible posts on speedsolving.com.)

**Comment by cmhardwick** [comment]
Please add this comment, from António Gomes from speedsolving.com

Given this justification, lack of counterexamples where media has seriously hurt (or could hurt) the image of cubing, and given the fact that media alone is mentioned in this topic (which means it has its relevancy for feet), I would like to suggest to Sarah to move or, better yet, add a media statement to the "Negative outcomes of removing Feet:" with something like "Removing the event could debilitate the media exposure cubing currently has in certain parts of the world.".

---

Please move this comment to neutral outcomes.  Many of these comments are subjective and depend on the views/cultural upbringing of the reader.  Since this can be interpreted multiple ways, I do not feel this belongs in the "Pros" column.

"Feet is arguably the most unsanitary event, since feet can be much less clean than hands, especially when clean socks/footwear are not worn. Additionally, even when one's feet are actually clean, watching them being used can still be very uncomfortable and repulsive. Feet solving (both official solves and practice solves at competitions) can contribute to an unpleasant atmosphere to spectators and non-Feet competitors, so its removal would give more pleasant experiences at competitions."

I disagree with the following comments:

"Feet is arguably the most unsanitary event, since feet can be much less clean than hands"

The use of the word "can" makes this a very subjective comment.  Hands _can_ be less clean than feet as well.  My reading of your comment depends on my cultural and personal perceptions of the cleanliness of feet vs. hands.  This is not an objective comment, in my opinion.

"Additionally, even when one's feet are actually clean, watching them being used can still be very uncomfortable and repulsive"

I am neither uncomfortable, nor repulsed by watching a foot solver.  This comment is a subjective comment and depends on the views of the user in regards to foot cleanliness.

"Feet solving (both official solves and practice solves at competitions) can contribute to an unpleasant atmosphere to spectators and non-Feet competitors, so its removal would give more pleasant experiences at competitions."

1) Feet solving _can_ contribute to an unpleasant atmosphere.
2) ...so its removal would give more pleasant experiences at competitions

Allow me to paraphrase:
"If a person belongs in the group of people who find feet solving unpleasant, then such a person would experience a competition to have a more pleasant atmosphere".

I do not belong in the group of people who find feet solving unpleasant.  Therefore the following statement is untrue for me:
"...so its removal would give more pleasant experiences at competitions"

If feet were removed, I would find the overall experience of the competition less pleasant as I enjoy watching the feet event.

Please consider the above comments to be neutral.  They can be interpreted as they are written, but I do not interpret them this way.  I consider it as least possible that others interpret these comments in a way similar to me.

**Comment by AlbertoPdRF** [comment]
As it wasn't removed in 2015, I'm closing this one. Also, we implemented #479
