### ISSUE TITLE
Preventing Incorrect Scrambles

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#184]
I'm starting to see very many Delegate reports contain an incident or two about incorrect/repeated scrambles.

Delegates usually make good choices about how to handle those, and we already have two extra scrambles printed per round. However, _any_ missscramble is undesirable.

I'm wondering if we can do something to ensure that they happen less?
- Change the scramble images to encourage better scramble checking?
- Be more strict about requirements for scramblers?
  - Especially for final rounds?
- Scramble robots?
  - I'm half-serious. Some of them are fast enough, and probably not more than $100 or $200 if you rebuild from LEGO.
- Force scramblers to acknowledge that they've verified the scramble (e.g. on the score sheet)
  - Requiring competitor signatures has given us mixed success, but perhaps scramblers might pay more attention.

**Comment by sarahstrong314** [comment]
I'm not sure that changing the scramble images would help much. It seems like when this usually happens, the scrambler just doesn't bother to check the image, or checks but doesn't care whether the puzzle matches the image.

Maybe the scramble documents could include some text to remind the scramblers to ensure correct scrambles, and remind them of the proper puzzle orientation?

**Comment by lgarron** [comment]
Yeah, _that_'ll work. :-P

Stefan has suggested blacking out some of the scramble images to focus on a few key stickers that confirm the scramble with reasonable certainty. I've also had thoughts in that direction.
No one _actually_ checks every sticker on the image, so perhaps by some simple highlighting we can make the task of checking scrambles more inviting.

**Comment by KitClement** [comment]
That's what I was going to suggest - instructions on scramble sheets that
would remind competitors about the relevant regulations on orientation for
a particular puzzle, as well as a reminder to solve and re-scramble if the
scramble is done incorrectly.

## 

Kit Clement
University of Michigan Rackham | Applied Statistics MA

**Comment by lgarron** [comment]
Again, how many people would pay attention? There isn't much space for anything except some small text, and everyone likes to ignore warning labels.
Comparison: The "click to acknowledge" thing for new speedsolving.com threads has helped a bit, but it doesn't actually prevent stupid threads.

I'm hoping we can find something that more directly targets the actions of scramblers.

**Comment by lgarron** [comment]
Something I _would_ be in favor of: picture instructions for competitor/judge/scrambler roles. Think of airline safety cards with all their circles, arrows, and crosses.

**Comment by KitClement** [comment]
True enough - but I think that scrambling orientation reminders would be
useful for the good competitors that do forget, especially for the side
events with different regulations (Pyra, Sq1, Clock, etc.).  And it can't
make things any worse.

I find this to be on the side of drastic - but what about creating
"certifications" for these roles that involve taking online quizzes?
 Scramblers could test themselves by answering questions about the scramble
process and performing example scrambles for certain puzzles - judges would
be given simply a set of questions about the judging process.  This would
certainly become more attainable under the future account system - these
certifications could be tracked much more easily.  Requiring these to be
completed isn't something I'd be willing to move to any time soon, but it
could be a good way for organizers and delegates to identify their capable
volunteers.  (I realize that this is not a very good fix for right now, and
has possibly been considered already, but I thought I would propose it.)

I do like the picture instruction idea.  I miss having the page of examples
for misalignment penalties, and often use the examples picture on older
regulations to help train my judges on these penalties.

## 

Kit Clement
University of Michigan Rackham | Applied Statistics MA

**Comment by sarahstrong314** [comment]
Whenever I see people scramble for they first time (especially kids), a lot of them just don't know about the proper orientation, which is why I suggested the text on the scramble documents. Usually by the time someone experienced notices they're scrambling wrong and tells them, they have already scrambled a bunch of cubes. The text would have to be a reasonable size, though, which doesn't sound feasible.

I definitely like the idea of picture instructions better, especially if the instructions for scrambling are printed out at competitions to be displayed at scrambling stations. They would stand out way more than text crammed on scrambling documents, and the images would motivate scramblers to actually read them. The Delegate or organizer(s) could also require new scramblers to read it before scrambling.

**Comment by Laura-O** [comment]
I think a short description how to orient the puzzle would be nice since this is frequently asked by unexperienced scramblers.

Nevertheless I don't think reminders to check the scramble would help. In my experience the problem is not that scramblers don't care or forget, but they hurry and/or do it in a silly way (compare 2 stickers when scrambling 2x2). So blacking out parts of the images might be helpful to concentrate on what is important.
However that would not solve the problem of repeated scrambles, which is the major problem since it  definitely gives the competitor an advantage (knowing about cases, skips, cubeshape, etc.).

**Comment by lgarron** [comment]
Delegate reports frequently mention twisted corners. I think we should focus on that, especially for BLD.
In fact, I think we might want to encourage or require scramblers to check and sign off for corners during BLD scrambling.

Crazy idea: If the scrambles are being viewed from a laptop, hold up their scrambled puzzle to a webcam to check three sides. That can check the entire pattern, including twists of 7 different corners. If a cube matches on 3 sides, it's just about guaranteed to be scrambled correctly.

**Comment by lgarron** [comment]
[Skewb incident](https://groups.google.com/forum/#!msg/wca-delegates/1AsJnBrUcd8/DlGmMy7v3R4J) at Villa de Catral 2014
