### ISSUE TITLE
Clock Pin Caps

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#189]
This is pertaining to the issue brought up in the Guangzhou Wushan Open 2014 delegate report.  Here are the two additions:

https://github.com/KitClement/wca-documents/commit/883abec0b7cbca921757510dabb44e289c3c5c1a

My wording might not be perfect here, let me know if you have any changes/additions you would make.

**Comment by lgarron** [comment]
Thanks for making this.

One this is that "pins must not be identifiable from any other pin of the same side" allows you to feel which side is in front without relying on visual markings.
Unless there is really good reason to allow it (is the availability still so low that competitors are forced to settle for broken clocks for some reason than their own level of use?), I think we should treat them as similar _from either side_ by default.

Should we get information on whether anyone is using faulty clocks?

I agree that missing caps at the end of the solve should be treated the same as any other puzzles.
(Although I'm still of the opinion that "solved or not" is sufficiently fair and simple.)

**Comment by KitClement** [comment]
I'll poll a few cubing facebook groups I'm in to see if people do use clocks with missing pin caps.  I know that at Carnegie Mellon Fall 2013, I let one of the kids there borrow my clock, and he returned it with a cap missing - presumably he did some official solves with a missing cap.  

Clocks (at least Rubik's brand) are becoming somewhat difficult to find, I often search for new ones myself and it's difficult to find shipping to the USA, let alone internationally.  I wonder if the knock off clock pin caps will fit into a Rubik's?  I don't own one myself to try.

I'm pretty indifferent to any of the issues you brought up, whatever you think might be best.

**Comment by Laura-O** [comment]
From my experience those faulty clocks (with one or more missing pin caps) are used quite regularly. I always asked the delegate about this when I saw them at the scrambling table. Competitors never questioned that such a missing pin cap might help you to identify the orientation of the clock.

Nevertheless I would like to bring something else into discussion: due to their age, their design and their availability, there are more attributes which make a clock "faulty". A lot of clocks have some kind of flaws and or damages. Cases break when they are slammed too hard on the table, the inner clocks sometimes grind the case from the inside, the inlays are shredded or there is dirt inside.
Furthermore some people mark their clocks in order to identify them better. I put a small sticker on the upper side of the clock (inside the case) after it was mixed up at the scrambling table more than one time. All these things can be utilized more or less to have the same advantage that a missing pin cap might give you.

**Comment by KitClement** [comment]
This response is very late, but given Laura's comments, I'm actually considering allowing any arrangement of missing pin caps.  Rarely are the pin caps removed to create an advantage, it is just a result of a faulty puzzle.  Given that we allow custom inserts, the visual advantage can be easily created here too, as Laura mentioned.  The only extra advantage missing pin caps give is a tactile one, but this is arguably minimal.  

We should go to a vote on this, of course, but I'd recommend allowing missing pin caps.
