### ISSUE TITLE
Use 3 decimal places in averages only

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#198]
Inspired by many recent ties in 2x2 WR Average, I believe we should stop rounding averages to 2 digits.  Currently, it's possible for someone to have a faster average by as much as .0067 seconds, but lose because their single is worse.  I recall Stefan citing an example of where this actually happened, but I don't recall it.

Note that I don't wish to use the third decimal place for singles, but I do think that we should either:

1) Display the third digit in averages.
2) Don't display the third digit in averages, but change the logic used in rankings so that they are ranked to 3 digits.

**Comment by lgarron** [comment]
I have two concerns:
- Some parts of the world still have a lot of older timers with only 2-digit precision.
- The 2-digit timers were notorious for running on 60Hz but outputting hundredths. At the best, that only means some times are skipped (so the result may be off by 0.01 instead of 0.005), but it doesn't really make me trust people who use "Stackmat accuracy" as a marketing term. Stefan once did a good analysis of the distribution. I can't find it right now, but [this post](http://www.speedsolving.com/forum/showthread.php?26914-Stackmat-Timer-Accuracy-Resolution) also documents some of it. Before switching to three digits, I think we should attempt to find out exactly how accurate the 3-digit timers are.

**Comment by lgarron** [comment]
> Note that I don't wish to use the third decimal place for singles, but I do think that we should either:

Oh, I didn't notice this line before.

I'm not sure if we really need to distinguish by 1/300 of a second instead of 1/100. Since our system can handle tied records, I don't see a significant problem with the current setup.

In fact, I prefer times that "do what they say on the tin". (i.e. hidden digits don't count).
If we continue truncating individual times to hundredths but add more precision to the averages, we can still have "pathological" results:
- (0.500) (2.000) 1.009 1.009 1.009 > 1.00 officially (instead of 1.009) places ahead of:
- (0.500) (2.000) 1.000 1.010 1.010 > 1.01 officially (instead of 1.0066666)

In any case, if results are that close, it's a bit arbitrary who ends up with the record. If you beat everyone else fair and square, you get the record – else, I don't think it matters what we do as long as we're consistent.

Has anyone been especially upset or confused by the current state of affairs?

**Comment by sarahstrong314** [comment]
Kit, I think this might be Stefan's post you're referring to: http://www.speedsolving.com/forum/showthread.php?26647&viewfull=1#post514486.

In addition to TCA Championship 2011, this also happened at the Arizona Open 2011, Swedish Championship 2013, Roskilde Christmas 2013, and Slovenian Open 2014, where second place in 3x3x3 finals had the best sum of 3, but lost because of a tied average after rounding and a slower single. Swedish Championship 2013 was the only case (for first and second place in 3x3x3 finals) where the difference in the averages was maximal, at 1/150 of a second.

I honestly don't think it's a problem worth fixing because it doesn't happen that often and it would probably just add more complications than it's worth.

**Comment by lgarron** [comment]
Closing for now, since it does not solve any more problems than it could also cause. See my example in the 3rd post.

**Comment by pedrosino** [comment]
> If we continue truncating individual times to hundredths but add more precision to the averages, we can still have "pathological" results:
> 
>   (0.500) (2.000) 1.009 1.009 1.009 > 1.00 officially (instead of 1.009) places ahead of:
>   (0.500) (2.000) 1.000 1.010 1.010 > 1.01 officially (instead of 1.0066666)

We don't use the third digit for recording times. I think the "right" way would be to use the sum of the 3 times, instead of the average. Or as Kit said, rank by sum in the background, and show the average.

There has been a post recently on speedsolving: https://www.speedsolving.com/forum/showthread.php?56395-Ideas

**Comment by lgarron** [comment]
> I think the "right" way would be to use the sum of the 3 times, instead of the average.

What do you mean by "right"? Using the sum still does not prevent the problem I described.
If we're going to make a change, I think we should have specific reasons why the new way  better rather than general feelings.

**Comment by pedrosino** [comment]
The problem you described is because of timer (in)accuracy and/or our decision to only use the first 2 digits.

The issue in question is using the rounded values instead of the "raw sum" to determine the rankings.

If we were to use 3 digits, I still think the best way would be to compare the sums and not the rounded avg of 3.

**Comment by lgarron** [comment]
> I still think the best way

I understand that you think it is the best, but what is your argument that we should switch?

Just that it avoids some awkward situation where the math with the rounded values appears to have pathological cases?
As I've shown, switching to the sum will also have pathological cases, just ones that aren't as apparent. If you want, I can do the math on how often using the sum will result in a more "fair" ranking (at least, ignoring the fact that Stackmat timers don't have the right frequency to measure at full accuracy for the displayed precision, which... makes things even fuzzier.)

I think it makes sense that the average is calculated and displayed to centisecond sig-figs, and the value from that is used. It's easy to understand and read in a table of numbers.
