### ISSUE TITLE
Loose parts inside puzzles

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#219]
From [Florida Feast 2014](https://groups.google.com/forum/#!msg/wca-delegates/qUUcpkzTdkc/cmOGj4W00SoJ):

> [A puzzle] had jelly beans in all of his corner pieces, which made a maraca-like noise when it turned.  It had two logos on it, so we rejected it for that reason, but if it didn't, that would have been a legal puzzle that I wish weren't legal.  Maybe we could not allow it for being a distraction to competitors?

**Comment by KitClement** [comment]
## Proposal

I don't really have a strong opinion on this (despite this coming from my delegate report), but we could consider adding this regulation:

3h5) Puzzles can not have any loose parts or objects trapped inside of the puzzle.  

## Pros
- Disallows some kinds of puzzles that delegates may believe are undesirable.
- Adds some clarity to puzzle regulations.

## Cons
- Puzzles may unintentionally have loose parts trapped inside of them due to broken plastic, although this can be easily fixed.
- Goes against our shift towards "anything goes" for puzzle regulations.
- Adds complexity to the regulations for a case that is very rare.

**Comment by Claster** [comment]
I believe you could disallow this puzzle if it distracted other
competitors. If not, why not to let the competitor play a fool a bit?
Your proposal (besides fixing a very rare case) has another issue.
Sometimes a big cube (6x6) can pop an inner piece, but it doesn't come out
of the puzzle, keeping inside instead. So the puzzle suddenly becomes
illegal during the solve?

2014-12-31 1:06 GMT+03:00 KitClement notifications@github.com:

> Proposal
> 
> I don't really have a strong opinion on this (despite this coming from my
> delegate report), but we could consider adding this regulation:
> 
> 3h5) Puzzles can not have any loose parts or objects trapped inside of the
> puzzle.
> Pros
> - Disallows some kinds of puzzles that delegates may believe are
>   undesirable.
> - Adds some clarity to puzzle regulations.
> 
> Cons
> - Puzzles may unintentionally have loose parts trapped inside of them
>   due to broken plastic, although this can be easily fixed.
> - Goes against our shift towards "anything goes" for puzzle
>   regulations.
> - Adds complexity to the regulations for a case that is very rare.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cubing/wca-documents/issues/219#issuecomment-68403786
> .

## 

Best regards,
Oleg Gritsenko
