### ISSUE TITLE
Incidents resulting in fewer competitors advancing.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#220]
Occasionally, a retroactive correction/disqualification affects more than just the competitor in question.

Austrian Big Cube Open 2014 had an interesting case [relevant thread on results list](https://groups.google.com/forum/#!searchin/wca-results/austrian/wca-results/JsWBh7AT2jQ/or4p6jPLyUUJ):
- Matěj Mužátko's second result in [round 1](https://www.worldcubeassociation.org/results/c.php?i=AustrianBigCubeOpen2014&allResults=1#e666_d) was changed to DNF.
- As a result, Matěj Mužátko's didn't have a first round average, and didn't qualify for the second round.
- Since this reduced the number of second round competitors from 15 to 14, this means that the final round could only have 10 competitors instead of 11 (due to [91p](https://www.worldcubeassociation.org/regulations/#9p1)).
- Therefore, Viktor Kalmar had to be retroactively removed from the final round.

So, a change in someone's first round result affected someone two rounds later. This sort of thing happens regularly, although it's usually less complicated.

Although we don't want to allow organizers to get around the Regulations, this sort of change still affects competitors who had done nothing wrong.

**Comment by Jambrose777** [comment]
A conversation between WRC, WDC, and WRT happened (and died without resolution).

The best way to solve this with the least amount of collateral damage would be to word the regulations in such a way that any retroactive DNFs (ie not signing, cheating, etc) which result in the competitor not making a subsequent round when they do have results for the subsequent round will cause the remaining results in subsequent rounds to be changed to DNF. (thus keeping the number of competitors in all rounds, not allowing the competitor to keep unfairly obtained results, and can be seen as a harsher punishment than just DNFing for 1 round).

To go along with this, competitors who advanced due to a score taking error (whether it be to their own results or someone else's) shouldn't result in this.

Here was a stab at the text from the thread:
> In case of disqualification of official results as the consequence of an investigation conducted by a WCA Team or Committee, the results of other competitors must not be affected. For example, if all the results obtained by a competitor in a specific round are disqualified, his name shall remain in the official rankings an all of his results shall be listed as DNF, not to cause a possible violation of rule 9p1.

**Comment by lgarron** [comment]
I would like to write down all the edge cases for our advancement conditions! :-)
https://github.com/thewca/wca-regulations/issues/767

For when we get to this, also see #716.

**Comment by Jambrose777** [comment]
Is there any update on this?
