### ISSUE TITLE
Disallow missing/misplaced pieces in the solved state

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#223]
There are usually ruled as DNF, but this is not codified.
The "solved or not" policy would easily handle this. :-/

Austrian Big Cube Open 2014:
![austrian big cube open 2014 misalignment](https://cloud.githubusercontent.com/assets/248078/5373152/8242cee0-8007-11e4-8e73-95808cfedf15.jpg)

Montreal Fall 2014:
![montreal fall 2014 image1](https://cloud.githubusercontent.com/assets/248078/5373150/81181a7a-8007-11e4-92bc-71933edafbb3.JPG)

**Comment by SAuroux** [comment]
<< _The "solved or not" policy would easily handle this._ >>

I absolutely disagree with this.

2014-12-10 9:58 GMT+01:00 Lucas Garron notifications@github.com:

**Comment by lgarron** [comment]
> << _The "solved or not" policy would easily handle this._ >>
> 
> I absolutely disagree with this.

Um, I'm not sure it makes sense to dispute _whether_ such a policy would handle it. :-P.
(The whole point would be to make things like this clear.)

You're certainly welcome to disagree that we should adopt it; I'm aware that people are against it for various reasons, so I certainly wouldn't take such a change lightly.

**Comment by SAuroux** [comment]
I should have been more precose I guess. ;)

What I wanted to say is, that I don't see how the "solved or not" handles
these cases better in any way than our current policy, at least for the
second picture. The thing to argue about is, if such slightly out of place
pieces make a cube solved or not and the "solved or not" policy wouldn't
change anything to this point.
Am 11.12.2014 00:43 schrieb "Lucas Garron" notifications@github.com:

**Comment by KitClement** [comment]
From Brno Open 2015, Olivér Perge:

"I also send attached a picture of a 6x6x6 attempt. I gave no penalty."

![6x6x6 pop](https://cloud.githubusercontent.com/assets/6166412/6737429/f21878f4-ce41-11e4-8b03-7f9e7814beba.jpg)

**Comment by xsrvmy** [comment]
I think this is a change in the good direction since it gets rid of the debate on whether or not a defect must be fixed. Flagships usually don't pop anymore anyways. Still several problems to consider though.
- Are there still common puzzles where caps pop off when stopping the timer? Stickerless pyras come to mind.
- Are there still common 4x4 or 6x6s where the internals pop, like the weisu used to do?
- What happens if a big cube centre piece breaks mid-attempt?

**Comment by topppits** [comment]
Approximately every 30-40 solves I pop an internal on my Aosu GTSM. Tensions are probably on the looser end, though it only happens when my turning is fairly inaccurately, most of the time during OLL parity.

**Comment by dancing-jules** [comment]
About that blue 6x6: that reminds me a lot of the recent Jonatan Klosko Skewb attempt. Each one has one single-colour-piece completely separated from the puzzle (blue centre in 6x6 and red centre in skewb) and one piece half-displace from it's proper position but still attached to the puzzle (6x6 oblique and RYB floating corner in Skewb). By that logic the 6x6 state above should be DNF.

I think that @topppits has a good point and at least non-coloured internals should be allowed to go flying. I have had [this happen in a practice solve though](https://i.redd.it/wp8zx35n62r21.jpg). 

In the end I would be okay with not allowing single-colour-pieces to separate. It keeps things easier and cleaner, but I'm not a huge fan of it. I.e. keep 5b5a), throw out 5b5b), and replace 5b5c-e with  "If one or more parts with colored faces are affected, the puzzle is considered unsolved (DNF)."

**Comment by xsrvmy** [comment]
IMO fully placed should be changed to fully attached. Using the wording "fully placed" leads to ambiguity as to whether or not being off by a move violates this regulation.
Another problem: should we clarify cases where two parts of a piece become slightly separating on timer stop (eg. a split corner)?

**Comment by lgarron** [comment]
From #856:

@alexmaasswca at https://github.com/thewca/wca-regulations/issues/856#issuecomment-541326214
> Please don't make it so that a center cap falling off is illegal, that can be a big deal in 7x7 and 6x6 where pops are very common, and places people at a disadvantage compared to before. I can guarantee most experienced competitors who do many events have had solves that would have been DNFs under this regulation.
> 
> Also, lots of stickerless puzzles have the color on the center pieces, not just the center caps.

@jamesquinn1 at https://github.com/thewca/wca-regulations/issues/856#issuecomment-541329904
> All pieces attached- One center piece falling out near the end of a big cube solve and flying across the floor could now add 15-20 seconds to a solve, which is a massive margin. Feet center caps and megaminx piece caps are two other examples of how this would fundamentally change events. This change seems to have come about because of the 0.91 Skewb DNF, and fundamentally changing many events because of one incident is absurd.

@UnderwaterCuber at https://github.com/thewca/wca-regulations/issues/856#issuecomment-541336887
> Despite mixed feelings about this I’m good with it and agree with the points

@aneurinhunt at https://github.com/thewca/wca-regulations/issues/856#issuecomment-541371842
> Requiring all pieces to be fully attached does make it easier to decide if a cube is solved.

**Comment by lgarron** [comment]
> Please don't make it so that a center cap falling off is illegal, that can be a big deal in 7x7 and 6x6 where pops are very common, and places people at a disadvantage compared to before.

I agree that 6x6x6 and 7x7x7 are a good reason to be extra-careful about this change, since they are the only speedsolving events where a single DNF is usually devastating to a top competitor.

However, I think that the benefit from simplifying this for all events outweighs making special exceptions for 6x6x6x and 7x7x7.

> This change seems to have come about because of the 0.91 Skewb DNF, and fundamentally changing many events because of one incident is absurd.

Please note that this is completely inaccurate. This very issue that I'm commenting on is from 2014, and I have believed since then that this is the best choice for the WCA. Dealing with incidents from Delegate reports and talking to people about the complexity of the Regulations have reinforced that belief.

It's included as a main proposed changed for 2020 because the recent scale of the WCA makes it especially important to address simplifications like this.

**Comment by jamesquinn1** [comment]
"I agree that 6x6x6 and 7x7x7 are a good reason to be extra-careful about this change, since they are the only speedsolving events where a single DNF is usually devastating to a top competitor."

I'd like to note that this would be devastating for any competitor. Having to drop to the ground, search around for a tiny little piece that could be blending in with the floor, find it, and place it in the puzzle (especially since the piece that usually pops is a oblique, the hardest to get in) would take 20-40 seconds. This would add 6-13 seconds onto the mean (assuming they still make cutoff), which is a big deal for any competitor.

At a top level, this would turn a world record into an worse than awful solve as well.

**Comment by alexmaasswca** [comment]
my proposal for what 5b5) should be changed to:

5b5) If at the end of the attempt some parts of the puzzle are physically detached or not fully placed, the following regulations apply:
5b5a) If multiple pieces are affected, then the puzzle is considered unsolved (DNF).
5b5b) If a piece with multiple colored faces is affected, then the puzzle is considered unsolved (DNF).

if you want to patch out skewb's issue, then add in 
5b5c) If an entire square-shaped Skewb piece is affected, then it is considered unsolved, due to the piece being structurally an edge piece.

This is definitely a big improvement in simplification compared to the current regulation:
5b5) If at the end of the attempt some parts of the puzzle are physically detached or not fully placed, the following regulations apply:
5b5a) If one or more parts without colored faces are affected, the puzzle is considered solved.
5b5b) If one part with one colored face is affected, the puzzle is considered solved.
5b5c) If more than one part with one colored face is affected, the puzzle is considered unsolved (DNF).
5b5d) If one or more parts with more than one colored face are affected, the puzzle is considered unsolved (DNF).
5b5e) Regulations 5b5c and 5b5d supersede 5b5a and 5b5b.

**Comment by smhcuber** [comment]
I don’t think its fair to have this be the case for 6x6 and 7x7 as there are only 3 solves. If this were an average of 5 that would be different, but every 7x7 out there does pop and it is extremely hard to put the pieces back in. As long as all the pieces are in place but one I don’t see the issue? I don’t understand why a center cap is an issue either. The weird lockups at the end of an attempt might be an exception like that of the dnfed skewb world record, but I don’t see the point in not allowing 1 center piece or center cap to be out of the puzzle. There is no way to avoid that in competition on big cubes without making competitors times way slower. Something like tightening your cube doesn’t work either. That just makes it impossible it fix if you have  lockup or pop.

**Comment by smhcuber** [comment]
Also how does this apply to internal piece? Many of these do not neccesarily affect the functionality of the puzzle and have nothing to do with the solved state.

**Comment by xsrvmy** [comment]
> I don’t think its fair to have this be the case for 6x6 and 7x7 as there are only 3 solves. If this were an average of 5 that would be different, but every 7x7 out there does pop and it is extremely hard to put the pieces back in. As long as all the pieces are in place but one I don’t see the issue? I don’t understand why a center cap is an issue either. The weird lockups at the end of an attempt might be an exception like that of the dnfed skewb world record, but I don’t see the point in not allowing 1 center piece or center cap to be out of the puzzle. There is no way to avoid that in competition on big cubes without making competitors times way slower. Something like tightening your cube doesn’t work either. That just makes it impossible it fix if you have lockup or pop.

I can kind of agree with this. It has actually never been clear if taking out a wing to fix a center is allowed. However I don't pop my puzzles that often anyways unless I turn way too fast.

**Comment by alexmaasswca** [comment]
Anyu Zhang's recent 1:58.49 AsR 7x7 single would not have happened if not for allowing single colored pieces to pop. https://youtu.be/HvJMMra6Vro (at 1:52)

Also, can somebody please provide feedback on my regulation proposal, which would highly simplify the 5b regulations?

5b5) If at the end of the attempt some parts of the puzzle are physically detached or not fully placed, the following regulations apply:
5b5a) If multiple pieces are affected, then the puzzle is considered unsolved (DNF).
5b5b) If a piece with multiple colored faces is affected, then the puzzle is considered unsolved (DNF).

if you want to patch out skewb's issue, then add in
5b5c) If an entire square-shaped Skewb piece is affected, then it is considered unsolved, due to the piece being structurally an edge piece.

**Comment by Samuel-Baird** [comment]
> Anyu Zhang's recent 1:58.49 AsR 7x7 single would not have happened if not for allowing single colored pieces to pop. https://youtu.be/HvJMMra6Vro (at 1:52)
> 
> Also, can somebody please provide feedback on my regulation proposal, which would highly simplify the 5b regulations?
> 
> 5b5) If at the end of the attempt some parts of the puzzle are physically detached or not fully placed, the following regulations apply:
> 5b5a) If multiple pieces are affected, then the puzzle is considered unsolved (DNF).
> 5b5b) If a piece with multiple colored faces is affected, then the puzzle is considered unsolved (DNF).
> 
> if you want to patch out skewb's issue, then add in
> 5b5c) If an entire square-shaped Skewb piece is affected, then it is considered unsolved, due to the piece being structurally an edge piece.

1. Why does Anyu’s solve matter in this discussion?
2. I like your reg proposal better than the current regs but I think the 2020 proposal is is an even better

**Comment by alexmaasswca** [comment]
> > Anyu Zhang's recent 1:58.49 AsR 7x7 single would not have happened if not for allowing single colored pieces to pop. https://youtu.be/HvJMMra6Vro (at 1:52)
> > Also, can somebody please provide feedback on my regulation proposal, which would highly simplify the 5b regulations?
> > 5b5) If at the end of the attempt some parts of the puzzle are physically detached or not fully placed, the following regulations apply:
> > 5b5a) If multiple pieces are affected, then the puzzle is considered unsolved (DNF).
> > 5b5b) If a piece with multiple colored faces is affected, then the puzzle is considered unsolved (DNF).
> > if you want to patch out skewb's issue, then add in
> > 5b5c) If an entire square-shaped Skewb piece is affected, then it is considered unsolved, due to the piece being structurally an edge piece.
> 
> 1. Why does Anyu’s solve matter in this discussion?
> 2. I like your reg proposal better than the current regs but I think the 2020 proposal is is an even better

1. Because it is an example of a very world class solve that would have not been AsR under this regulation (unless he somehow placed the popped piece from the floor back in place in under 3.5 seconds. It would place 2020 solvers (especially big cube solvers) at a disadvantage whenever any piece or cap is not 100% fully placed.

2. How do you like a regulation that DNFs something as miniscule as a 3x3 center cap pops over a regulation that is fair and reasonable?

**Comment by Samuel-Baird** [comment]
> > > Anyu Zhang's recent 1:58.49 AsR 7x7 single would not have happened if not for allowing single colored pieces to pop. https://youtu.be/HvJMMra6Vro (at 1:52)
> > > Also, can somebody please provide feedback on my regulation proposal, which would highly simplify the 5b regulations?
> > > 5b5) If at the end of the attempt some parts of the puzzle are physically detached or not fully placed, the following regulations apply:
> > > 5b5a) If multiple pieces are affected, then the puzzle is considered unsolved (DNF).
> > > 5b5b) If a piece with multiple colored faces is affected, then the puzzle is considered unsolved (DNF).
> > > if you want to patch out skewb's issue, then add in
> > > 5b5c) If an entire square-shaped Skewb piece is affected, then it is considered unsolved, due to the piece being structurally an edge piece.
> > 
> > 
> > 
> > 1. Why does Anyu’s solve matter in this discussion?
> > 2. I like your reg proposal better than the current regs but I think the 2020 proposal is is an even better
> 
> 1. Because it is an example of a very world class solve that would have not been AsR under this regulation (unless he somehow placed the popped piece from the floor back in place in under 3.5 seconds. It would place 2020 solvers (especially big cube solvers) at a disadvantage whenever any piece or cap is not 100% fully placed.
> 2. How do you like a regulation that DNFs something as miniscule as a 3x3 center cap pops over a regulation that is fair and reasonable?

It simplifies the regs a pretty good amount and makes judging things very easy and far less ambiguous which makes things more fair for competitors. Competitors are ultimately the ones at fault for pops so I don’t see it a problem with punishing them in the new system, they are completely preventable.

**Comment by smhcuber** [comment]
How are they completely preventable? I find that when my puzzle pops it has no correlation with how I am turning the puzzle. It sometimes happens all the time and sometimes happens rarely. It mainly due to the hardware that is out now.

**Comment by Samuel-Baird** [comment]
> How are they completely preventable? I find that when my puzzle pops it has no correlation with how I am turning the puzzle. It sometimes happens all the time and sometimes happens rarely. It mainly due to the hardware that is out now.

Then tighten your cube :) completely preventable

**Comment by alexmaasswca** [comment]
> > How are they completely preventable? I find that when my puzzle pops it has no correlation with how I am turning the puzzle. It sometimes happens all the time and sometimes happens rarely. It mainly due to the hardware that is out now.
> 
> Then tighten your cube :) completely preventable

Any decent big cube solver would agree that tightening their cube so that center pops are impossible would have a significant impact on their speed. And speed is the goal in speed events, so this is a completely stupid argument.

**Comment by Samuel-Baird** [comment]
> > How are they completely preventable? I find that when my puzzle pops it has no correlation with how I am turning the puzzle. It sometimes happens all the time and sometimes happens rarely. It mainly due to the hardware that is out now.
> 
> Then tighten your cube :) completely preventable
> Any decent big cube solver would agree that tightening their cube so that center pops are impossible would have a significant impact on their speed. And speed is the goal in speed events, so this is a completely stupid argument.

So anything that slows down down competitors, even if it’s just a small amount, shouldn’t be implemented regardless of how much it can help the wca? 

I didn’t mention it since smhcuber kind of covered  it in his comment but competitors can also turn less aggressively. If anything implementing this reg would make times faster since competitors would turn less aggressively which would result in fewer serious pops, fewer lockup’s, they would have a bit more time to lookahead even. Also it’s such a small change that I don’t feel like it’s going to be giving future competitors a major disadvantage, pops don’t happen every solve and on the solves they do occur on it takes only a few seconds to fix them. So basically you are looking at something that may  lengthen a handful of big cube solves by 2-3% that shortens the regs, makes things easier for judges and helps remove some ambiguity, and encourages competitors to have better turning habits which can lead to some better times. Seems like a pretty good trade off to me.

**Comment by alexmaasswca** [comment]
> So anything that slows down down competitors, even if it’s just a small amount, shouldn’t be implemented regardless of how much it can help the wca?

When it happens, it is NOT a small amount. As James Quinn posted above: 
"I'd like to note that this would be devastating for any competitor. Having to drop to the ground, search around for a tiny little piece that could be blending in with the floor, find it, and place it in the puzzle (especially since the piece that usually pops is a oblique, the hardest to get in) would take 20-40 seconds. This would add 6-13 seconds onto the mean (assuming they still make cutoff), which is a big deal for any competitor."

I can safely assume that people would not consider over 20 seconds a small amount of time in world class big cube solving. 

> but competitors can also turn less aggressively. If anything implementing this reg would make times faster since competitors would turn less aggressively which would result in fewer serious pops, fewer lockup’s, they would have a bit more time to lookahead even. Also it’s such a small change that I don’t feel like it’s going to be giving future competitors a major disadvantage, pops don’t happen every solve and on the solves they do occur on it takes only a few seconds to fix them. 

flat-out assuming that tightening a cube will automatically make solves faster is ridiculous, by this logic you can assume that we can just get new records by telling the people who have them to just tighten their cubes


Also, how would you even enforce internal piece pops? A tiny internal piece could easily pop out without the judge or competitor knowing. Also, a puzzle could be submitted with an internal piece missing. (Justin Mallari has finished an official PR 4x4 average without knowing an internal piece was missing the whole time I believe). If this regulation was to be enforced, we would have to check every even layered big cube so that no internal pieces are missing.

**Comment by xsrvmy** [comment]
Two comments about big cubes:
1. There was a recent 1:58 with a popped piece in the final state.
2. What happens if a center piece breaks (not common anymore, but there are definitely still wujis around), or if a center cap/piece falls in an unretrievable location?

**Comment by Samuel-Baird** [comment]
> Two comments about big cubes:
> 
> 1. There was a recent 1:58 with a popped piece in the final state.
> 2. What happens if a center piece breaks (not common anymore, but there are definitely still wujis around), or if a center cap/piece falls in an unretrievable location?

Same that that would happen if your volt edge breaks, you just gotta take the DNF

**Comment by xsrvmy** [comment]
@UnderwaterCuber Not as reasonable in a mo3 event.

**Comment by aneurinhunt** [comment]
This affects 6x6 and 7x7 much more than other they need more leniency for this issue since they are a mean of 3 event and 6x6 and 7x7 hardware pops the most. Also what about internal pieces? Having to put those back in takes a lot of time and requires taking out multiple pieces. Does the judge have to always check all internal pieces are present?

**Comment by smhcuber** [comment]
Also in my experience tightening your cube just makes the “weird lockups” impossible to fix when they occur. I see where Sam is coming from, but this is definitely not good for a mo3 event where 1 dnf makes your entire entire mean a dnf.

**Comment by Samuel-Baird** [comment]
> @UnderwaterCuber Not as reasonable in a mo3 event.

Maybe a better example is a corner breaking during 3bld 
Edit: no that’s an awful example lol. No event other than maybe mbld or fmc are really comparable. 



> This affects 6x6 and 7x7 much more than other they need more leniency for this issue since they are a mean of 3 event and 6x6 and 7x7 hardware pops the most. Also what about internal pieces? Having to put those back in takes a lot of time and requires taking out multiple pieces. Does the judge have to always check all internal pieces are present?

This reg would be modifying B5 which specifies pieces that make up the colored faces. Internal pieces are not part of a colored face so they do not matter.

**Comment by xsrvmy** [comment]
> Maybe a better example is a corner breaking during 3bld

3bld is a bo3 event not an mo3 event. Plus I have never heard of a corner piece breaking on a 3x3.

One solution is to give extra for broken pieces but that seems like a step back given pops used to be extras.

**Comment by Samuel-Baird** [comment]
> > Maybe a better example is a corner breaking during 3bld
> 
> 3bld is a bo3 event not an mo3 event. Plus I have never heard of a corner piece breaking on a 3x3.
> 
> One solution is to give extra for broken pieces but that seems like a step back given pops used to be extras.

Bad example, I have edited my original comment. 

Or change 6x6/7x7 to median of 3 or ao5, I know there are plenty of people who would like that change. They fix lots of the current problems with the events. If one of those was the current format I doubt people would be opposing this proposal as much as they are.

**Comment by casiku** [comment]
That's unfair, the rules are fine as they are.

**Comment by alexmaasswca** [comment]
In a poll I posted in the Big Cubes facebook group stating "Are you in favor of the 2020 WCA regulation proposal to change the definition of the solved state to "Solved state: All pieces must be attached and normally placed."?"

117 people voted "not in favor" (95.1%)
4 people voted "in favor" (3.3%)
2 people voted "don't care/no opinion" (1.6%)

This shows that this should obviously not be implemented as a regulation, if over 95% of people who are affected the most by it (big cube solvers) disapprove of it.

**Comment by Samuel-Baird** [comment]
> In a poll I posted in the Big Cubes facebook group stating "Are you in favor of the 2020 WCA regulation proposal to change the definition of the solved state to "Solved state: All pieces must be attached and normally placed."?"
> 
> 117 people voted "not in favor" (95.1%)
> 4 people voted "in favor" (3.3%)
> 2 people voted "don't care/no opinion" (1.6%)
> 
> This shows that this should obviously not be implemented as a regulation, if over 95% of people who are affected the most by it (big cube solvers) disapprove of it.

Of course they aren’t going to vote in favor of it, it disadvantages them lol

**Comment by alexmaasswca** [comment]
> > In a poll I posted in the Big Cubes facebook group stating "Are you in favor of the 2020 WCA regulation proposal to change the definition of the solved state to "Solved state: All pieces must be attached and normally placed."?"
> > 117 people voted "not in favor" (95.1%)
> > 4 people voted "in favor" (3.3%)
> > 2 people voted "don't care/no opinion" (1.6%)
> > This shows that this should obviously not be implemented as a regulation, if over 95% of people who are affected the most by it (big cube solvers) disapprove of it.
> 
> Of course they aren’t going to vote in favor of it, it disadvantages them lol

It disadvantages almost everyone lol, just these people are affected the most by it

**Comment by ccbaird** [comment]
If you want any more feedback here’s mine: if it could be reasonably applied to only Ao5 events this would be fine. Otherwise if multiple pieces or multiple colors are affected it should be a DNF, a single piece of a single color should be fine.
