### ISSUE TITLE
Require competitors to take their attempts seriously.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#225]
At [Bugella Open 2014](https://groups.google.com/forum/#!msg/wca-delegates/TRjtNIWoyWQ/5HCLx2Kws2sJ), a competitor tried to get +14.
Brandon Mikel also tries to [get 69 in FMC every time](https://www.worldcubeassociation.org/results/p.php?i=2011MIKE01#333fm), which means he's not actually trying to do his "best" and is arguably wasting FMC checking time (Chris Krueger definitely thinks so).

As a community, we have a tradition of having fun, so I don't think we should attempt to regulate how much a competitor may bend the rules. However, I think it's reasonable to allow the Delegate to request competitors to stop certain behaviours (and disqualify the relevant results otherwise).

**Comment by lgarron** [comment]
Note: if we clarify this, we should pay attention that a Delegate can't just disqualify a competitor for being "slow" – that's what time limits are for (see [A1a3](https://www.worldcubeassociation.org/regulations/#A1a3) regarding changes in time limits).

**Comment by Laura-O** [comment]
Commenting here to avoid spamming #261:
why is *Intentionally DNFing a result (in a quick manner)" a non-example?

DNFing an attempt intentionally because the time isn't as good as expected or there's no lucky solution is totally against the WCA spirit and is therefore also wasting time and resources. This regulation is a good option to add this as well.

**Comment by lgarron** [comment]
Yeah, I agree; that's a weak example. Depending on how the competition is going, it may be a waste of resources.
And it can certainly still violate [A1c](https://www.worldcubeassociation.org/regulations/#A1c).

Thanks for pointing it out; I've updated the comment in #261 with other examples.

**Comment by lgarron** [comment]
Copied from [this comment](https://github.com/cubing/wca-documents/issues/261#issuecomment-102863166).
- If the competitor does something that wastes time or resources (because they're being silly, not e.g. because they're not fast at an event), the Delegate may disqualify them from the relevant attempts/events.

TODO(@Sa967St): think of a better way to word this. Consider including (quite a few) concrete examples based on past incidents. Possibly also examples of things that are not really wasting time (e.g. just being slow).

Examples:
- Intentional +16 penalties
- Intentionally poor FMC results (can waste solution checker time)
- Intentionally letting timer run to get poor results
- Solving a puzzle that the competitor does not know how to solve

Non-examples:
- Competitors who aren't fast at a puzzle, but are trying their best.
- Competitors who aren't good at FMC, but still taking it seriously.

From [Chris Krueger](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/wca-delegates/Y5LtG-9u4fk%5B76-100%5D):

> This discussion came up again among some of us today, so I want to again suggest a regulation change about allowing disqualification from a solve/event at delegate discretion for a competitor not competing in good faith. Currently, I could walk into a competition without pre-announced cutoff times and announce that I intend to complete every solve in 9:59.99, and under a strict reading of the current regulations no one could do anything about it. I'd like to change that. 
> 
> Change the wording of A1c to 
> A competitor participating in an event must be able to fulfill the event's requirements (e.g. know how to solve the puzzle within a given time limit). A competitor competing with expectation of a DNF result or intentionally poor result may be disqualified from the solve or the event, at the discretion of the WCA Delegate.
> Restore E1 to read 
> Article A1c applies to Fewest Moves Solving. 
> 
> A justification based on wasting competition resources can be read from 2J 2K and A1c. The proposed change just simplifies that.

**Comment by sarahstrong314** [comment]
> TODO(@Sa967St): think of a better way to word this. Consider including (quite a few) concrete examples based on past incidents. Possibly also examples of things that are not really wasting time (e.g. just being slow).

What about wording it like this? (This includes some of Chris Krueger and Dene Beardsley's wordings).

#### If a competitor has the intention of getting a poor result (i.e. the competitor is deliberately not performing to the best of his abilities in good faith) on an attempt, the attempt may be disqualified and the competitor may be disqualified from the event, both at the discretion of the WCA Delegate.

So A1c could be changed to this:

#### A1c: A competitor participating in an event must be able to fulfil the event's requirements (e.g. know how to solve the puzzle within a given time or move count limit). A competitor competing with expectation of a DNF result or an intentionally poor result (i.e. the competitor is deliberately not performing to the best of their abilities in good faith) on an attempt, the attempt may be disqualified and the competitor may be disqualified from the event, both at the discretion of the WCA Delegate.

And this new Guideline could be added:

#### A1c+: [REMINDER] Competitors disqualified per A1c must be noted in the Delegate Report.

This would leave it up to Delegate to determine whether a poor result is deserving of a competitor being disqualified from an event, by considering the action's severity and the degree of intention. Ideally, a Delegate would choose not to penalize a competitor who does not perform to the best of his abilities if there is a good reason that he is not doing so. Consider Sébastien's example: feeling angry at the end of a bad solve and waiting 3-4 seconds before stopping to take a deep breath and to avoid stopping harder than usual. Here's a case where a competitor lets the timer run to get a poor result, but for a good trade-off ("wasting" 5 seconds v.s. possibly disturbing other competitors).

Here are some examples and non-examples of deliberate poor results (to could be added to the Guidelines) to help illustrate the intention of this Regulation:

Examples that can result in disqualification, at Delegate discretion:
- Intentional +16 penalties (makes it hard to judge properly, even for the most experienced judges)
- Intentionally poor FMC results (can waste solution checker time)
- Intentional redundant moves in FMC (can make it harder to read for solution checkers)
- Intentionally letting timer run to get poor results (unnecessarily wastes the judge's time and takes up a station)
- Intentionally doing many redundant or non-productive turns to get poor results (same reason as above)
- Solving a puzzle that the competitor does not know how to solve (same reason as above)
- Solving a puzzle without knowing enough algorithms to solve it every time (e.g. not knowing a Square-1 parity algorithm and hoping for a parity skip every solve)
- Solving a puzzle while imposing unnecessary restrictions (e.g. solving one-handed or blindfolded in the two-handed 3x3x3 event)

Non-examples that should not result in disqualification:
- Competitors who aren't among the fastest at an event, but are trying to the best of their abilities
- Competitors who aren't among the best FMC solvers, but still put good effort into their solution

**Comment by Laura-O** [comment]
> Intentional excessive rotations and intentional redundant moves in FMC (can make it harder to read for solution checkers)

I would not mention rotations here. There is no need to use any rotations in FMC solutions, so "intentional excessive rotations" is very vague.

**Comment by sarahstrong314** [comment]
> I would not mention rotations here. There is no need to use any rotations in FMC solutions, so "intentional excessive rotations" is very vague.

I included it to cover things like intentionally putting "z z2 y x' y2 z y' y x" in a solution.

**Comment by Laura-O** [comment]
Yes, sure.

However, there's some kind of an unwritten law that cube rotations in FMC solutions are bad. I don't like that this example can be understood to support this.

Why not just combine the two FMC examples and say: "Intentionally long FMC solutions"?

**Comment by sarahstrong314** [comment]
> However, there's some kind of an unwritten law that cube rotations in FMC solutions are bad. I don't like that this example can be understood to support this.

I'm not sure what you mean. Are you saying that the wording implies that using few rotations are perfectly acceptable, and it shouldn't imply that?

> Why not just combine the two FMC examples and say: "Intentionally long FMC solutions"?

The second example covers that idea. The third example is about things that may not result in a really long solution, but make it unnecessarily difficult to check.

**Comment by Laura-O** [comment]
> I'm not sure what you mean. Are you saying that the wording implies that using few rotations are perfectly acceptable, and it shouldn't imply that?

I'm just saying that there is some room for interpretation what _excessive rotations_ are.
If you ask a good FMCer what that means for him, he will probably say >0, a CFOPer might answer >4, a beginner maybe >6 or even >8.
So what is excessive?

As said before, I would not use that as an example. Intentionally using more than necessary rotations results in a longer solution, so this is covered by the third example.

**Comment by nathandwyer** [comment]
> Commenting here to avoid spamming #261:
> why is *Intentionally DNFing a result (in a quick manner)" a non-example?
> 
> DNFing an attempt intentionally because the time isn't as good as expected or there's no lucky solution is totally against the WCA spirit and is therefore also wasting time and resources. This regulation is a good option to add this as well.

So if someone were doing a solve and a piece pops and they can't get it back in in a reasonable time, or if their solve is simply worse than they would like it to be, would they be disqualified if they intentionally DNF the solve? In the case of a puzzle defect then couldn't it be less of a waste of time and resources to intentionally get a DNF result than to sit there and attempt to reassemble the puzzle with the timer running? I understand that a competitor going into a Square-1 solve and hoping for a parity skip and DNFing the attempt otherwise, as Sarah mentioned, should be discouraged, but i don't know that this should be a zero-tolerance policy for deliberate DNFs.

**Comment by lgarron** [comment]
Thanks for closing this, Laura!

I think we've worked sufficiently well around some of the specific examples with other Regulations, and there is no pressing need to handle this in general.
