### ISSUE TITLE
Require O-Rings and padded battery compartments on all official timers?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#243]
I haven't been keeping a list, but many (probably a majority) Delegate reports include a mention of at least one timer malfunction.

These are usually not the fault of the competitor (I don't think anyone would call Stackmat Pro timers "reliable"), so we can't get rid of them all. But maybe if we require every competition to use best practices, we might be able to avoid a lot of them.

Is there any online store that sells cheap O-rings internationally? Could we convince some cube shops to start stocking them?

**Comment by strakerak** [comment]
This might work:

http://www.eachbuyer.com/300-x-rubber-o-ring-o-ring-washer-seals-assortment-black-12-sizes-p32726.html

A bit more on the expensive side, but it still seems pretty good.

**Comment by a-Maass** [comment]
http://www.bricklink.com/search.asp?itemID=106693&colorID=11

This would probably work. Would need some glue or some adhesive to attach it to the timer though.

**Comment by Laura-O** [comment]
They might work, but obviously they are not so easy to order intentionally.

It would probably be the best approach to define the size of the O-rings or give a recommendation. They are available in local stores (at least here) and in online-stores as well, so I don't see the need to search for a suitable online store.

**Comment by a-Maass** [comment]
If you click more "Show More Filter Options" you can filter it by store location, and you will see that there's places that sell it worldwide pretty much, so its pretty easy to order them internationally. 

If you were asking about the size of these o-rings, I found the size from here: 
http://wheels.sariel.pl/ (5th tire down)
![](http://i.imgur.com/ZQLtcYQ.png)

**Comment by Laura-O** [comment]
Buying specific Lego parts from an online marketplace is actually not what I would call "easy", especially when there is a much better alternative.

**Comment by lgarron** [comment]
There are some on Amazon (all using inches). Shipping is free (within the US) with Amazon Prime.
- [1/2" inner diameter, 5/8" in outer diameter](http://www.amazon.com/014-Buna-N-O-Ring-Durometer-Black/dp/B000FN0VCY/): $2.86 for 100
- [3/8" inner diameter, 9/16" outer diameter](http://www.amazon.com/110-Buna-N-O-Ring-Durometer-Black/dp/B000FN0XVI/): $2.35 for 100

I don't remember what size we needed at Nationals and don't have a Stackmat available right now, so I'm ordering both. I'll see which ones fit on Friday.

Overseas people: could you check if these are available to you? If so, how much do they cost, and how much does shipping cost?

**Comment by a-Maass** [comment]
Yeah I guess the o-rings linked above are cheaper, probably would be best to use them.

**Comment by Laura-O** [comment]
You can't order these to Germany.
However you can get some with equal sizes from Amazon.de (also Prime) and
in nearly every hardware store here.

2015-03-25 23:28 GMT+01:00 Lucas Garron notifications@github.com:

**Comment by jfly** [comment]
@lgarron, the subject of this issue mentions "padded battery compartments", but I don't see anything about them in this thread. Potentially relevant: https://www.youtube.com/watch?v=PorIzqogvdc&list=UUHxdwS9KP9z4vqzMEesIaWQ.

**Comment by lgarron** [comment]
Yes, I didn't discuss them in this thread because I wanted to be focus on
the issue of getting O-rings.
I _expect_ that procuring paper to fold and tuck in the battery compartment
is not difficult.

(I'm aware of that video, but we still need to have a solution for other
timers.)

**Comment by lgarron** [comment]
[Mishawaka Spring 2015 Report](https://groups.google.com/forum/#!msg/wca-delegates/izcsd8ZkUcg/fIKOaqzD_HYJ) by Kit Clement:

> Actually an anti-incident: we had 0 timer resets/malfunctions the entire day.  O-rings are a wonderful thing.
> 
> Actually I think putting some paper into the battery compartment would be more useful.

**Comment by KitClement** [comment]
From James:

> Would it be appropriate to put the oring size information on the guidelines? I feel like this would make the information more readily available and I wouldn't have to search my email for it.

Ideally, based on the evidence we have from delegate reports, we would like to make O-rings mandatory. Realistically, this is probably not possible. It would be nice to explicitly allow the usage of O-rings in the regulations, and then make a guideline that discusses the sizing. Thoughts?

**Comment by lgarron** [comment]
If you visit this issue on GitHub, you can see the draft language in the
fixes branch, For convenience, here it is again:

8a7+) [ADDITION] Organizers should strongly consider modifications to make
Stackmat timers to more robust against common incidents, such as making the
buttons more difficult to press by accident (e.g. by attaching O-rings
around the buttons) and securing the battery more firmly (e.g. by padding
the battery compartment).

**Comment by KitClement** [comment]
Ah -- apologies, I noticed the commits above, but didn't realize it was the fixes branch.

I will check the exact size on the package of my o-rings when I return home -- I've used them fairly extensively now and they seem to be extremely effective.

**Comment by lgarron** [comment]
[Delegate Report for Nanchang Open 2015](https://groups.google.com/forum/#!msg/wca-delegates/eAwd9hZzQZU/lTcljnEdzlYJ) by Ming Zheng:

> At the beginning, I asked them to put paper in the battery compartments to pack batteries on all the timers, except for two brand new Gen-Pro timers whose production date is 2015. Because I saw this new timers with holders in the battery compartments, and I think the batteries are not easy to be loose. But unfortunately, the only two timer malfunction caused by heavy hit while stopping happened to this two brand new Gen-Pro timers. Then I insert paper inside, the problem disappear. And I gave the corresponding attempts extra solves.

**Comment by ronaldmansveld** [comment]
As this issue is still open I'll use this one instead of creating a new issue:

During the last WC the timers were not fitted with O-rings, which has had its effect on how the finals for 3x3 and 4x4 went.
Currently, there is only an addition in the guidelines where organisers should strongly consider making modifications. ( https://www.worldcubeassociation.org/regulations/guidelines.html#8a7+ )

After the incidents during the WC, there was a clear questioning by competitors why O-rings were not fitted for a competition as important as the WC.

I would suggest changing the regulations, to make O-rings compulsory. They are cheap, easy to come by, and easy to fit, so that should not be an issue.
The guidelines can contain specific information on the size of the O-ring that is needed.

**Comment by Claster** [comment]
Are O-rings cheap and easy to buy in all parts of the world as well?
Note that it is a problem of a competitor who presses the reset button during stopping the solve.

**Comment by Laura-O** [comment]
> Are O-rings cheap and easy to buy in all parts of the world as well?

They are not. And that's why I believe that the strong recommendation in [8a7+](https://www.worldcubeassociation.org/regulations/guidelines.html#8a7+) is fine as it is.

**Comment by jfly** [comment]
Stackmats are also not cheap and easy to buy in *most* of the world. I think it is well within the resources of the wca (both financial and manpower) to send 100 o-rings to every delegate in the world and every future delegate.

If we divide up the work, this gets even easier. I feel strongly about requiring o-rings everywhere, so I'd gladly volunteer to be part of this effort.

**Comment by Claster** [comment]
Probably sending O-rings to every delegate can solve the majority of issues with timer resets. Still I'm not comfortable with making it compulsory. As we saw at WC, organizers can have some reasons not to use O-rings, be it financial reasons or forgetfulness or buying the new equipment at the last moment or the local shop doesn't work at some days or anything else. And I feel uncomfortable to disqualify the whole competition just because there are no O-rings, especially *if it is the duty of a competitor to stop the timer correctly*.

**Comment by lgarron** [comment]
> And I feel uncomfortable to disqualify the whole competition just because there are no O-rings, especially if it is the duty of a competitor to stop the timer correctly.

It's also the organizer's duty to provide officially competition-legal timers [7f](https://www.worldcubeassociation.org/regulations/#7f).
If we want make it an official requirement that standard timers are hard to reset accidentally, I think that's perfectly reasonable.

**Comment by jfly** [comment]
> As we saw at WC, organizers can have some reasons not to use O-rings

Oh! Just curious, what was the reasoning for not using o-rings at the World Championships?

> Still I'm not comfortable with making it compulsory

I get that we should not make this change overnight. I'd like to start by changing the expectations: if a competition does not use o-rings, then I'd like for the delegate to have to provide a good reason why. After 6 months or a year of that, we have enough data to have a real discussion about these various reasons and see if makes sense to start requiring o-rings.

> if it is the duty of a competitor to stop the timer correctly.

I totally agree. The problem is that it's very hard for even an experienced judge to distinguish between a competitor incorrectly stopping the timer and a timer malfunction. For example, Seung Hyuk Nahm's first solve at WC 3x3 finals where [he was awarded an extra solve](https://www.youtube.com/watch?v=KVDHY2Ksn4o&t=6h15m35s), and then later, after more video review, the extra was discarded and his first solve changed to a DNF.

**Comment by SAuroux** [comment]
One thing to keep in mind is rented equipment, where you surely cannot just glue O-rings on. I have no idea how many area in the world actually rent equipment, but I read about this in reports every now and then.

**Comment by lgarron** [comment]
> One thing to keep in mind is rented equipment, where you surely cannot just glue O-rings on. I have no idea how many area in the world actually rent equipment, but I read about this in reports every now and then.

I think O-rings+ duct tape have worked well in practice. But this is a good point, we should probably have some standard community solutions (like templates for cube covers).

> I'd like to start by changing the expectations: if a competition does not use o-rings, then I'd like for the delegate to have to provide a good reason why. After 6 months or a year of that, we have enough data to have a real discussion about these various reasons and see if makes sense to start requiring o-rings.

Could we update the Delegate report format to require reporting this data?

**Comment by KitClement** [comment]
My timers all use basic clear tape to attach o-rings, and they have lasted
several competitions. I have to replace tape on a few o-rings in between
competitions.

**Comment by Claster** [comment]
>Oh! Just curious, what was the reasoning for not using o-rings at the World Championships?

You can read it in the report :P 
(Since reports are confidential, I don't feel comfortable to share any part of them here; organizers might share if they want.)

**Comment by jfly** [comment]
> Could we update the Delegate report format to require reporting this data?

Sure! Please see https://github.com/thewca/worldcubeassociation.org/pull/1942, let's discuss the exact phrasing over there.

**Comment by lgarron** [comment]
Reopening this, since Jeremy and I are looking into a path to requiring them.

We've found a potential source that would let us buy 5000 O-rings for $100:
https://www.theoringstore.com/index.php?main_page=product_info&products_id=1201

**Comment by jfly** [comment]
I just placed an order for 13 of [these o-rings](http://www.theoringstore.com/index.php?main_page=product_info&cPath=367_23_25&products_id=1201). After they've arrived, I will update this post with information about how good of a fit they are.

**Comment by AlbertoPdRF** [comment]
Why not go and print a lot of the protectors with the 3D template that
Speedstacks posted on their website? We used them at Tembleque Open 2017
this past weekend and they fitted and worked perfectly.

El 19 sept. 2017 7:31, "Jeremy Fleischman" <notifications@github.com>
escribió:

I just placed an order for 13 of these o-rings
<http://www.theoringstore.com/index.php?main_page=product_info&cPath=367_23_25&products_id=1201>.
After they've arrived, I will update this post with information about how
good of a fit they are.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thewca/wca-regulations/issues/243#issuecomment-330433804>,
or mute the thread

**Comment by KitClement** [comment]
Any 1/2" ID o-ring should fit very well. Mine are 5/8" OD rather than 3/4",
which match perfectly.

Regarding the 3d printed protectors from speedstacks, those absolutely need
to be glued on. We tried taping some to timers last week at September
Speedcubing 2017, but they didn't stay there, or if they were taped over
the top, you couldn't push through to the button.  They're a great solution
if you own timers, but many areas rent them and we cannot glue them on.
They also don't work on Gen3 timers, which are still going to be in use for
some time.

**Comment by AlbertoPdRF** [comment]
Yes, the problem with the Gen3 timers is there.

Out of curiosity, where or from who do people rent timers? Because if they
rent them from other Delegates/Organizers they'll have to put O-rings too,
so it's not a problem to glue them.

El 19 sept. 2017 7:37, "KitClement" <notifications@github.com> escribió:

Any 1/2" ID o-ring should fit very well. Mine are 5/8" OD rather than 3/4",
which match perfectly.

Regarding the 3d printed protectors from speedstacks, those absolutely need
to be glued on. We tried taping some to timers last week at September
Speedcubing 2017, but they didn't stay there, or if they were taped over
the top, you couldn't push through to the button. They're a great solution
if you own timers, but many areas rent them and we cannot glue them on.
They also don't work on Gen3 timers, which are still going to be in use for
some time.

On Mon, Sep 18, 2017 at 10:31 PM Jeremy Fleischman <notifications@github.com
>
wrote:


> I just placed an order for 13 of these o-rings
> <http://www.theoringstore.com/index.php?main_page=product_
info&cPath=367_23_25&products_id=1201>.

> After they've arrived, I will update this post with information about how
> good of a fit they are.
>
> —
> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub
> <https://github.com/thewca/wca-regulations/issues/243#
issuecomment-330433804>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-
auth/AF4XjIZwkTbPRZ6wtOw6fT3_RVC2_uzyks5sj1GlgaJpZM4DZ4le>
> .
>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/thewca/wca-regulations/issues/243#issuecomment-330434561>,
or mute the thread

**Comment by lgarron** [comment]
> Why not go and print a lot of the protectors with the 3D template that
> Speedstacks posted on their website? We used them at Tembleque Open 2017
> this past weekend and they fitted and worked perfectly.

Do you think there's a chance we could get a puzzle manufacturer to offer a form of timer protectors that come with adhesive on the bottom? It would be nice to have a more polished-looking option for organizers who own their timers.

**Comment by Laura-O** [comment]
> Regarding the 3d printed protectors from speedstacks, those absolutely need
to be glued on. We tried taping some to timers last week at September
Speedcubing 2017, but they didn't stay there, or if they were taped over
the top, you couldn't push through to the button.  They're a great solution
if you own timers, but many areas rent them and we cannot glue them on.

What kind of tape did you use?
I used some simple double-sided tape (like [this](https://www.amazon.de/tesa-doppelseitiges-Klebeband-25m-50mm/dp/B000KTD2T2/)) to attach the prototypes I received from Speed Stacks and that worked really well.

Regarding taping protectors/o-rings by wrapping tape around it: I think we have to be really careful and specific if we suggest delegates to do that. We recently had an incident which was related to o-rings being attached with non-transparent tape so competitors couldn't see the LEDs.
I have also been to a competition where the tape was attached above the buttons. On one timer 
it was pushed down so that the reset button was pushed permanently and the timer wouldn't start.

**Comment by KitClement** [comment]
I did not have double sided tape available -- I tried taping down the
corners of the 3d printed pieces with clear packaging tape, but this fell
off over time.

**Comment by lgarron** [comment]
I spent a few minutes looking for double-sided circular adhesive.

The following looks promising (and it's even transparent, so you can see the buttons), but might be a tad too large:

https://www.amazon.com/Balloon-Rolls-Double-Adhesive-Non-liquid/dp/B074J9P5BR/ref=sr_1_5/143-3694028-3209315?ie=UTF8&qid=1505974805&sr=8-5&keywords=adhesive%2Bdots%2Bdouble%2Bsided&th=1

**Comment by jfly** [comment]
The AS568A-206 o-rings (see sizing information [here](https://www.oringsusa.com/html/size_chart.html)) I ordered from theoringstore are a perfect fit! Here's a picture:

![img_20170926_084758](https://user-images.githubusercontent.com/277474/30870028-9776a63c-a297-11e7-9dd3-fb5cd6d0496b.jpg)

Above you can also see the the [glue dots @lgarron found](https://www.amazon.com/Balloon-Rolls-Double-Adhesive-Non-liquid/dp/B074J9P5BR/ref=sr_1_5/143-3694028-3209315?ie=UTF8&qid=1505974805&sr=8-5&keywords=adhesive%2Bdots%2Bdouble%2Bsided&th=1). They're not so great. I had to use 3 per o-ring because they're too tiny, and whenever you press the button, your finger presses something sticky, which may attract dirt and become unsightly. @Laura-O how does that compare with your experience with double sided tape?

**Comment by jfly** [comment]
I requested free samples of these [3/4" x 3/4" double sided foam squares](https://www.uline.com/Product/Detail/S-11695/Double-Sided-Foam-Tape/Pre-Cut-Double-Sided-Foam-Squares-1-32-thick-3-4-x-3-4), I'll update here after they've arrived =)

**Comment by lgarron** [comment]
Idea: place circular stickers with the WCA logo in the middle of the backing squares/circles (assuming we can get them cheaply enough).

That might feel a bit weird (the logo is hidden, placed somewhere you press, and likely a bit dirty), in which case maybe just circular regular stickers are fine. Those are also pretty affordable, and allow color-coordination!

https://www.amazon.com/Assorted-Color-Code-Dispenser-Permanent-Adhesive/dp/B00MI2U2DS/ref=sr_1_15?ie=UTF8&qid=1506498734&sr=8-15&keywords=circular+stickers+1%2F%22

**Comment by Laura-O** [comment]
> Above you can also see the the glue dots @lgarron found. They're not so great. I had to use 3 per o-ring because they're too tiny, and whenever you press the button, your finger presses something sticky, which may attract dirt and become unsightly. @Laura-O how does that compare with your experience with double sided tape?

I used it for the Speedstacks protectors, so that's a bit different as they have a larger surface on the back and you can cut the tape so that it fits perfectly.

I found some [flat o-rings](https://www.alibaba.com/product-detail/FVMQ-Silicone-rubber-flat-o-ring_60610146775.html?spm=a2700.7724857.main07.377.16df36c1Jqd9oL). Maybe it's easier to attach them?

**Comment by jfly** [comment]
The [foam squares](https://www.uline.com/Product/Detail/S-11695/Double-Sided-Foam-Tape/Pre-Cut-Double-Sided-Foam-Squares-1-32-thick-3-4-x-3-4) I ordered a sample of arrived and they work pretty well:

![img_20171002_173050](https://user-images.githubusercontent.com/277474/31105267-ae2be3e2-a797-11e7-8373-94379a0670d7.jpg)

The bond is strong enough that you can lift the stackmat up by the o-ring, so I think that should be good enough for our purposes:

![img_20171002_173300](https://user-images.githubusercontent.com/277474/31105291-db2e70e4-a797-11e7-836a-a1ba758d4992.jpg)

> I found some [flat o-rings](https://www.alibaba.com/product-detail/FVMQ-Silicone-rubber-flat-o-ring_60610146775.html?spm=a2700.7724857.main07.377.16df36c1Jqd9oL). Maybe it's easier to attach them?

I asked @Baiqiang to look into these, if they are the right size, then I think we have a decent solution that should add up to ~$0.20 / stackmat.

**Comment by CadyCubes** [comment]
I'm an organizer in NC who owns my own set of timers for competitions. I have tried o-rings and they fall off pretty easily using tape or glue.
I have been modifying the [Speedstacks ](https://www.speedstacks.com/stackers/free-stuff/)provided 3D print designs and testing out what works best. The design speedstacks provided is ok, but I think it would be improved upon.
For those who own timers (i.e. delegates and regular organizers) they can super glue the 3D printed part. For those who rent or borrow timers I think using [this](https://www.amazon.com/Glue-Dots-Removable-Dispenser-03670A/dp/B001B1YTWW/ref=sr_1_fkmr1_1?ie=UTF8&qid=1518292598&sr=8-1-fkmr1&keywords=removable+glue+dots+small) would work. If you can not view the link it is a .375in removable adhesive glue dot. I have used them for projects in the past and they have worked great. They would have a place to fit on the 3D printed piece with no adhesive exposed.
Once I have finalized and tweaked the Speedstacks design to the best it can be I am implementing them onto all my timers, posting the design file, and will offer to print the pieces for delegates (for no cost).

**Comment by jfly** [comment]
@CadyCubes, are the glue dots you refer to different than the stuff I commented about here? https://github.com/thewca/wca-regulations/issues/243#issuecomment-332244953

Thanks for offering to print pieces for delegates, that would be really awesome of you. However, one of the hard things is going to be distributing the o-rings around the world (a lot of mail to send!) If you do want to take this on, please email me directly at jeremyfleischman@gmail.com and let's continue the conversation there.

**Comment by CadyCubes** [comment]
@jfly email was sent :)

**Comment by lgarron** [comment]
I'd like to keep moving towards this. Many competitions these days seem to have 3D-printed protections or O-rings!

@jfly @CadyCubes Would you mind writing up the latest state of your efforts?

**Comment by jfly** [comment]
No update here, sorry. I don't have time to push on this anymore, so I'm afraid I'm going to have to withdraw [the offer I made to help make this a reality](https://github.com/thewca/wca-regulations/issues/243#issuecomment-329536816).

That said, I still do feel that it is within the WCA's power to send o-rings around the world (especially now that the WFC has actually started saving some money for use on efforts like this), someone just needs to be the evangelist to make it happen.

**Comment by xsrvmy** [comment]
Would this be a MUST requirement? As in, what would happen if someone set a WR on a timer without an O-ring/battery padding?
Similarly, what would happen if an o-ring falls off during a comp?

**Comment by Samuel-Baird** [comment]
I think it would make sense to require O-rings for 2020. Currently O-rings are already recommended in the guidelines and getting your hands on them is pretty easy.

**Comment by alexmaasswca** [comment]
Here's a situation that could come up, what if an oring poorly glued onto the timer falls off, and a cuber goes on to get a record on that timer? would the solve be disqualified? Would the competition results be declared invalid.

I do not think o rings should be strictly required for this reason, especially since speedstacks timer rentals are a thing.
