### ISSUE TITLE
Suggestion for the use of scramble groups

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#267]
In the wake of the Rami incident where a competitor intentionally leaked the scramble to him having already seen it, there has been a great deal of discussion on how to ensure scramble security -- the main suggestion being to call up competitors such that each set of competitors (in a non-final rounds) is using different scrambles, if possible.

**Comment by KitClement** [comment]
Natan:

> Yeah, maybe we need to add something like:
> 
> 1h++) RECOMMENDATION All final rounds of all events, as well as all Fewest Moves Solving rounds, should have the same scrambles for all competitors (i.e. only 1 group). Exceptions can be made when: 1. The integrity of scrambles would be compromised. 2. No reliable scramblers can be found outside the competitors in the round.
> Can't think of other situations where we could have multiple groups.

**Comment by lgarron** [comment]
Style nitpick: we don't use "1." and "2." inline like that. Something like "Examples of reasonable exceptions: bla bla bla, blu blu blu."

Apart from that, I don't like those _particular_ ways of talking about the exceptions, but I don't have any alternatives to offer (that I'm comfortable with) at the moment.

**Comment by KitClement** [comment]
Some ideas that were generated from a discussion of groups at Vancouver Open Winter 2016: [link](https://groups.google.com/d/msgid/wca-delegates/CAO7JOY_Cs_Ww42jjA3Vps8qtk_HP7t2vR-zSFsVXNUPFZr890Q%40mail.gmail.com?utm_medium=email&utm_source=footer)

I think that regardless of the philosophy that we take in handling this issue, we should address the following issues: 
- The term "group" needs to be clearly defined. The regulations state that competitors can be divided into groups, but whether groups need to perform attempts in the same timeframe is not made clear, and I think this should be defined.
- Although 1h) does use "must," I don't think that it clearly enforces the 1:1 correspondence of groups and scramble groups. It is somewhat reasonable to believe that as long as competitors who have not been called do not volunteer as scramblers or judges, that they will not see the scrambles.
- How to balance 1h+) and 1h++) is not clearly defined.  It is possible for someone were to hold the belief that finals should give the same scrambles to all, whether that final has 12 or 50 competitors. Since the term "group" is not well-defined, it may be seen as allowable to give the same scrambles to competitors competing in different timeframes, as they could potentially be seen as the same scramble group. However, I don't agree with this philosophy -- I believe that finals should only have the same scramble groups when the final is small enough to reasonably hold the same scramble group. Also, if groups were clearly defined as a group of competitors that is called up to the competitors area at the same time, then the organizer would have to make a choice of whether to follow 1h+ or 1h++.

**Comment by Laura-O** [comment]
I basically agree with what Kit wrote.

My suggestion to handle this (I am sure I posted that before, but probably only in the internal discussion):
1. We define that any unit using the same scramble sequences is a group.
2. We require that every competitor in a group is called to compete for a round at the same time.
3. To emphasize that every group has to use different scrambles, we could also change [1h+](https://www.worldcubeassociation.org/regulations/guidelines.html#1h+) to: _Competitors in the same group should use the same scramble sequences. Different groups **must** use different scramble sequences._

Explanations:
- This fixes one of the main problems I see here: delegates and organizers coming up with new constructs for groups by simply giving them different names. So regardless whether it's called a heat, a constellation or a flamingo, those units are defined and handled as a group by the regulations.
- By requiring that the whole group is called at the same time, the competitors competing in a group have to submit their puzzle and wait in the Competitors Area. The relevant regulation is
  [A2a](https://www.worldcubeassociation.org/regulations/#A2a): _When called for a round, the competitor submits a puzzle, in its solved state, to the scrambler. The competitor then waits in the Competitors Area until they are called to compete._
- This avoids situations like in the report linked above, where groups are called one after another in a large time frame, using the same scrambles and risking that people who haven't competed yet volunteer as judges or scramblers.
- [A2a](https://www.worldcubeassociation.org/regulations/#A2a) doesn't say that competitors have to submit their puzzle immediately and someone might have the strange idea to call competitors and tell them they should wait another 30 minutes in order to use the same scrambles for a round. I am not sure if we should also close this loophole. However, as letting them wait is another form of grouping, so this would be an abuse of the regulations as well.
- I have thought about different popular formats how rounds are handled (like podium finals head-to-head, two at a time, competitors staying at the solving station, etc.) and I cannot think of any problems the proposed regulation changes would cause.
- This also forbids that groups overlap and scramble sequences are given to both groups (i.e. a competitor in group 1 has done 4 attempts when group 2 starts and he gets the fifth scramble of the second group for his last attempt). A few delegates have criticized that this would slow down competitions. I think it's safe to say that this effect is small and it's still possible to do that by using two different scramble sets at the same time. This would require that it can be easily identified which group a competitor belongs to.
- Regarding discussions about the advantages of easy scrambles: we have to keep in mind that using different scramble sequences in a round does not mean that every single competitor is using different scramble sequences or they are assigned in a completely random way. It's common that large finals are divided in groups according to the ranking in the preceding round. In general this means that the best competitors are still competing together with the same scramble sequences. Of course, this does not mean that no one profits from easier scrambles.

**Comment by Laura-O** [comment]
Here is a initial draft on how this issue could be solved. I didn't create a pull-request yet, so please take a look at the changes and the comments:

Regulations: 74c2b3414926b0b823f5d1296e7864b0f1f91522
Guidelines: 25fd09af5c532c1dbeb66983723c70d76416b7f5

I currently see one loophole:
If all competitors in a group are called at once, submit their puzzles and wait in the waiting area, there is still an option for the organizer or the Delegate to scramble the puzzles in different timeframes. That means that the whole problem is moved from the competition area to the waiting area. It also adds the problem that competitors whose cubes are not scrambled in that timeframe would be sitting next to the other competitors who are just doing their attempts and might get information about scrambles.
However, holding back some cubes would be an extreme way to bypass or even abuse the regulations. Therefore, I'm not sure if we should close that loophole by also requiring that all competitors in the waiting area are actively competing, i.e. their cubes are scrambled and they are called by judges or runners.
The latter would be difficult to implement and forbid other approaches like letting one competitor do all attempts with a higher priority so that he is available for scrambling afterwards (that's a common approach in side-events which are difficult to scramble, i.e. Clock).

**Comment by Claster** [comment]
> I have thought about different popular formats how rounds are handled (like podium finals head-to-head, two at a time, competitors staying at the solving station, etc.) and I cannot think of any problems the proposed regulation changes would cause.

Actually I see a small problem with "two at a time" format. What I usually have seen is that all finalists go to another room, except 11th and 12th places who submit their puzzles and compete, then 9th and 10th places go back, submit their puzzles and compete and so on. The contradiction to the proposed regulations is that competitors use one scramble sequences but are called to compete (that is, submit their puzzles) at the different time. Following the letter of these regulations would require all competitors to submit their puzzles at once, then the best 10 go to another room, and 11th and 12th compete. That seems to me a bit strange: why would we ask to give their puzzles if we don't use them anyway?

Therefore I would propose an exception that if competitors who haven't compete clearly have no way to get an access to scrambles (e.g. they are in another room), they can be called in different timeframes. But if this exception seems odd, I'm ok with asking all competitors to submit the puzzles at the same moment.
