### ISSUE TITLE
3d3) "tiles or stickers" or "stickers or tiles"

### ISSUE THREAD

**Issue by kotarot** [thewca/wca-regulations#280]
In statement 3d, "stickers" and "tiles" appear in this order, in other words, "tiles" is described after "stickers".
It would be more natural if we change statement 3d3 to

```
If the coloured parts are stickers or tiles,
```

instead of

```
If the coloured parts are tiles or stickers,
```

**Comment by KitClement** [comment]
I'm going to leave it alone for now, just because these regulations are still functional without the change, and since translations have started, the fewer changes between now and July 1st, the better.  

I also feel okay about this since the first time, it mentions "colored tiles" and "colored stickers" and the next time it is simply "stickers or tiles," which is not exactly the same statement.

**Comment by kotarot** [comment]
OK, I see.
