### ISSUE TITLE
Remove 3k?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#294]
Per [a discussion in the Delegate list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wca-delegates/hVVIBvfIYxg/ixGumMBJBAAJ), with this post from Daniel Sheppard:

> I should clarify that I've never actually given an extra because of a clear advantage - I've never come across a situation where a competitor used a cube that gave a clear advantage. It's always bad logos or dodgy stickers.
> However, because of 3k, I would struggle to justify giving a DNF.
> I don't like 3k now that I think about it - please tell me if there's a delegate out there who actually checks all puzzles and thinks this is a feasible regulation to follow!
> If 3k was removed, I'd be OK with giving DNFs where the puzzle is clearly illegal.
> 
> 3k) Puzzles must be approved by the WCA Delegate before use in the competition.

In practice, the Delegate never inspects puzzles. This task is informally delegated to scramblers (via 1c), but they don't always know/remember to check.

Also, a penalty for 3k is never specified. That basically means it's the Delegates fault if it isn't followed, so we can't retroactively disqualify solves with illegal cubes.

**Comment by Laura-O** [comment]
> In practice, the Delegate never inspects puzzles. This task is informally delegated to scramblers (via 1c), but they don't always know/remember to check.

This is not true.
There are several delegates who inspect puzzles. Most of them probably do not do this for every single group, but they do it frequently.
However, I totally agree that it's not possible to do that every time.

Still, I don't like the idea that results should be DNFed retroactively.

**Comment by lgarron** [comment]
Good point. I meant "never inspects all puzzles" (or at least never that
I've heard of.)

**Comment by pedrosino** [comment]
I think DNFing past attempts is not fair, since most (or all?) of the "illegal" puzzles we have are those with multiple logos or crappy stickers. Even if the latter can give tactile recognition, I don't think it's possible to get significant advantage from that in events other than bld.

I believe we should have something that says "If a puzzle is found to be illegal during a round, the competitor must submit a new one which complies with the regulations. The past attempts remain valid". It could be a 3k1

**Comment by lgarron** [comment]
> The past attempts remain valid

As pragmatic as this sounds, it seems like an invitation for competitors to sneak things past us.

**Comment by lgarron** [comment]
> The past attempts remain valid"

As pragmatic as this is, this sounds like an invitation to abuse the rules. :-/

If we say "at the discretion of the Delegate", that sounds reasonable to me, though.

**Comment by Laura-O** [comment]
I agree with Lucas.
Also having a regulation assuming that **most** of the illegal puzzles are illegal because of stickers and logos is bad. What if a competitor uses a modified puzzle allowing him to solve it a lot faster?

Furthermore, using an illegal puzzle is already defined in the regulations as an incident in 11a1 (_"Incorrect execution of event procedures, by officials or competitors."_). And I think "at the discretion of the Delegate" is already covered by 11b (_"If an incident occurs, the WCA Delegate determines an impartial and appropriate course of action."_).

**Comment by Laura-O** [comment]
I was reminded of this issue by [this delegate report:](https://groups.google.com/d/msg/wca-delegates/nQATjkUVXLA/JATVpyhGCQAJ)
_"One competitor completed four skewb solves before we caught that there were two logos on the puzzle. We decided that this was a pretty minor issue, so we left the four solves alone and asked the competitor to remove the logo for the fifth solve."_

I think we should go for Lucas' suggestion and make this "at the discretion of the Delegate" in 3k1.

**Comment by pedrosino** [comment]
I agree.
Em 27/09/2015 08:16, "Laura Ohrndorf" notifications@github.com escreveu:

**Comment by Laura-O** [comment]
I don't know why we did not include this change in the 2016 regulation change...

[Here is another incident](https://groups.google.com/d/msg/wca-delegates/vNnwMr7H5Uk/uYPajMEDBwAJ) where this addition could have been helpful (competitor names removed by me):

> [...] And of course, it were the most experienced competitors who had submitted illegal logos. Thus I granted an extra attempt to x, y and z. They all had a success on the attempt which I had to delete, but fortunately they did another success with similar time, so the ranking would have been the same with the original attempt.

**Comment by xsrvmy** [comment]
I've never personally encountered incidents with illegal cubes when scrambling so I don't actually know how they are handled. I did have to tell several people to remove extra logos or to remove logos for blind though. I don't actually think extra logos are a big problems. The bigger one would be logos in the incorrect location (eg. a Z logo on a corner sticker for 7x7)
I think this is actually becoming more important with the rise of stickerless cubes. For example, my wuji actually developed faint markings on some of the corner pieces. With a lot more controversial cubes around, this addition should clear up a lot of indicents
