### ISSUE TITLE
Competitor can communicate with the delegate during an attempt?

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#297]
From https://groups.google.com/d/msgid/wca-delegates/CAD6HhcRtr%3DsJYwa6bV7pyNQmW%2BRqYp3vGwPAAmRN-rG%2BpeuPvg%40mail.gmail.com?utm_medium=email&utm_source=footer

I believe communicating with the delegate or judge is fine, so my proposal would be to simply add "or the delegate" to A5a

**Comment by Laura-O** [comment]
Natán in the above-mentioned discussion:

> I don't feel strongly either way (maybe I like allowing competitors to ask judges/delegates questions about regulations and allowing small talk if initiated by the competitor slightly better), but I do feel this should be specified in the regulations.

I think that's exactly what matters here: is A5a really relevant in practice so that it would be reasonable to add the delegate? If I should make a list with the most-ignored regulations it would definitely be in the Top10.
I'd rather suggest to rephrase A5a completely in the way Natán described.

**Comment by KitClement** [comment]
Just circling back to this based on an incident from Reno Spring 2017:

> Mitch had a single center piece pop on his 7x7, and asked his judge, Lauren Klemz, if he could solve the cube without this center re-attached to the cube. Lauren did not know the response, appealed to me, and I refused to answer, as I considered this giving assistance to the competitor by A5b -- there was a possibility he would have (unnecessarily) reattached the piece by the end of the solve and added time to his solve, but he left the piece out despite not having his question answered. However, I realize that A5a allows for communication with the judge, but this seems to be in regards to the necessary communications between judge and competitor like '8 seconds' and '12 seconds' rather than actual conversation. Can questions like this be answered during attempts?

As I stated in the report, I would argue that the initial spirit of the regulation regarding judge communication was to prevent a contradiction in the regulations that requires judges to communicate during inspection and when calling "okay" or "penalty" after the timer is stopped. However, I do think it is reasonable to communicate regarding regulations questions during a solve -- anyone who is not sure about the regulations is already at a clear disadvantage than if they had known the proper way to rule that situation, so I can't see this possibly being abused.

But if such a situation arises again, would we feel equally comfortable with a competitor asking someone (besides their judge) who is a non-delegate a question? I feel like it's a bit weird to allow for judge communication regarding regulations questions when some oddly specific questions might not be readily known by the judge. Some competitors may be at an advantage due to the knowledge of the judge they have if a delegate is not readily available, and this seems like a potentially strange inconsistency.

**Comment by garrett-webster** [comment]
I think asking regulation questions is appropriate to the judge and delegate. I don't think that the delegate not being available/the judge not knowing the answer, thereby creating a "disadvantage", is a problem. Competitors are already expected to know the regulations.
