### ISSUE TITLE
Change format for Feet to "Average of 5"

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#299]
Adam Polkowski (from [this discussion](https://groups.google.com/d/msg/wca-delegates/eZU7sSa8h2s/1f3W6c9fBwAJ)):

> After the first day of Kaliska Open 2015 we had a general meeting of Polish Cubing Association. 
> We had a lot of interior topics, but also one which I must send to you. 
> In first round of 3x3x3 with feet, Jakub Kipa had problem with timer. 
> Timer didn't start. I know that is his mistake, but he didn't proceed. The skill level of this event around the world is growing up very fast.Let's change the format for averages of 5.
> What is your opinion?

**Comment by rwcinoto** [comment]
I take 3x3 WF seriously. It is really sad when you DNF one attempt in WF, like it is sad when you take BLD seriously and DNF too many cubes in your 15 cube attempt in multi, or DNF one FM attempt in a Mo3 round or has two pops in the Rubik's cube final round.

Apart from the sad part, I agree that WF rounds took too long before, but now it is really fast, at least here in Brazil. To avoid people taking 20 minutes to do a Mo3, even though it is rare here, we usually have a cutoff of 4 minutes, but more than 50% of our competitors take less than 3 minutes and around 1/3 take less than 2 minutes.

Comparing it with 6x6 and 7x7 is difficult to me because scrambling big cubes influence a lot in the duration of these events, and in 3x3 WF the scrambling part is barely noticed. Also 5x5 and Mega have the problem of scrambling taking too long.

About the logistics, we have learned that WF should be the first event, so we can leave everything prepared for it, as the layout is different from the rest. If we have more than one round, we also do the others one after another because of this. Another option is doing it right before or after lunch, so we can use part of lunch time for preparing the sations.

In my opinion, we should change it for Ao5 format and those who prefer can still do a combined round with only 2 attempts for the slower ones. And you still have the option of not holding WF at all.

**Comment by Laura-O** [comment]
A lot of arguments for/against the format change can also be applied to the removal of Feet as an event. Pros and Cons for that can be found in #175.

To keep track of "format only"-arguments I will collect them here:

### Pros:
- Mean of 3 is an unfair format as one bad attempt will result in a bad mean
- After the format change of Clock, Megaminx and Sq-1 to Average of 5, keeping "Mean of 3" for Feet is inconsistent
- Competitors have become fast, so a format change would not necessarily mean that Feet rounds would take much more time (even without strict cutoffs)
- Average of 5 could bring away Feet from the role of a "second class" event 

### Cons:
- Cutoffs for an average would be lower
- Feet has always been a controversial event and a complete removal could be more reasonable (continue here: #175)

Edited: 18.08.2015

**Comment by pedrosino** [comment]
Cutoffs would be lower (instead of higher).

**Comment by Laura-O** [comment]
Thanks, fixed!

**Comment by Laura-O** [comment]
The mean of all official Feet solves in this year has dropped below 2 minutes to 1:54. That's only one second slower than the mean Megaminx solve in this year:

| Year  | Mean of all official Feet solves   |
|---|---|
| 2004 |  7:35 |
| 2005   |  4:36 |
| 2006   |  3:14 |
| 2007  |  2:34 |
| 2008   |  2:41 |
| 2009   |  3:12 |
| 2010   | 2:59  |
| 2011  |  2:53 |
| 2012   | 2:38 |
| 2013  |  2:27 |
| 2014  | 2:18  |
| 2015   |  2:01  |
| 2016  | 2:08  |
| 2017  | 1:55  |

**Comment by jfly** [comment]
That excludes DNFs though, right?

**Comment by Laura-O** [comment]
Yes.

**Comment by Laura-O** [comment]
Complete tables:

**Feet**:

|  Year|   Mean|  Solves|  DNFs|  DNSs|  Total|
|-----:|------:|-------:|-----:|-----:|------:|
|  2004|  07:35|       2|     0|     0|      2|
|  2005|  04:36|      25|     3|     0|     28|
|  2006|  03:14|      38|     7|     1|     46|
|  2007|  02:34|      62|     9|     2|     73|
|  2008|  02:41|     156|    32|     0|    188|
|  2009|  03:12|     273|    46|     3|    322|
|  2010|  02:59|     494|    69|    22|    585|
|  2011|  02:53|    1111|   185|    47|   1343|
|  2012|  02:38|    1597|   186|    29|   1812|
|  2013|  02:27|    1949|   188|    36|   2173|
|  2014|  02:18|    2525|   290|    61|   2876|
|  2015|  02:01|    3349|   334|    26|   3709|
|  2016|  02:08|    3413|   375|    27|   3815|
|  2017|  01:55|    3208|   283|    24|   3515|


**Megaminx**:

|  Year|   Mean|  Solves|  DNFs|  DNSs|  Total|
|-----:|------:|-------:|-----:|-----:|------:|
|  2003|  04:10|       5|     0|     0|      5|
|  2004|  05:12|      13|     1|     0|     14|
|  2005|  04:58|      27|     3|     0|     30|
|  2006|  03:45|      98|     3|     0|    101|
|  2007|  03:35|     276|     9|     3|    288|
|  2008|  03:30|     968|    31|    10|   1009|
|  2009|  02:56|    2622|    89|    16|   2727|
|  2010|  02:36|    5507|   196|    70|   5773|
|  2011|  02:31|    6624|   306|    98|   7028|
|  2012|  02:28|    7754|   281|    80|   8115|
|  2013|  02:26|   12121|   532|   140|  12793|
|  2014|  02:18|   15947|   802|   149|  16898|
|  2015|  02:14|   17468|   988|   158|  18614|
|  2016|  02:03|   24068|  1409|   151|  25628|
|  2017|  01:54|   25919|  1224|    95|  27238|
