### ISSUE TITLE
Explicitly state what formats combined rounds can have

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#301]
https://www.speedsolving.com/forum/showthread.php?54587-Unusual-rounds

**Comment by Laura-O** [comment]
The thread is full of questions and answers, so what is the concrete issue here?
- Specify that a combined round can consist of all formats mentioned in [9b)](https://www.worldcubeassociation.org/regulations/#9b)?
  or 
- Specify that the format of a combined round is Best of 2/Average of 5 or Best of 1/Mean of 3?

Personally I think neither of them is necessary. I don't see why delegates would choose an uncommon format just because they can, but there might be scenarios where it's necessary.

**Comment by Laura-O** [comment]
This is partly related to #453 so I am closing this one.
