### ISSUE TITLE
Results for rounds with cumulative time limits

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#303]
We had some discussions about the results of attempts done in rounds with a cumulative time limit, particularly results for attempts done (or better to be done) after the time limit has been reached. This case is not mentioned in the current regulations.
So, if the cumulative time limit is 10 minutes in a "Best of 3"-format and the competitor has done 2 solves in 10 minutes (e.g. each solve 5 minutes, so the time limit has been reached), is the third solve not recorded at all, a DNS or a DNF?

From my point of view, a DNF would be the right decision:
- Leaving the result blank would change the format of the round. If the format is "Best of 3", recording only two results would change it to "Best of 2". As every competitor is allotted the number of attempts defined by the round format, having no results for one or more attempts is not possible.
- A DNS doesn't seem to be appropriate either, as 9f5) says "The result of an attempt is recorded as DNS (Did Not Start) if the competitor is eligible for an attempt but declines it.". In this case, the competitor is not eligible for an attempt, so it can't be a DNS.
- A DNF seems to be the most reasonable result for me, although it's a bit strange. According to A1a4) the judge stops an attempt when the competitor reaches the time limit of a solve/round and the result is DNF. In this case, the time limit would be reached after 0 seconds, so the judge would literally stop him even before the attempt has begun.

I suggest to add a way to handle these cases to A1a2). Any thoughts or ideas?

**Comment by SAuroux** [comment]
This is indeed a really tough corner case. I had some more thoughts about
it and I believe that all comes down to the question "Is a competitor
eligible for an attempt if the time limit is zero seconds?". Actually, I
believe that the answer to this is "yes."

So first of all, you completely convinced me that a blank result is no
option for this case, as a time limit cannot effect the round format. Now
let's stick to your scenario: A competitor has done 2 attempts and has
exactly zero time left for the 3rd one. Now comes the tricky part:
1. There is no regulation that says, that zero seconds is no valid time
   limit for an event.
2. The only way that a competitor can become ineligible for future events
   are cutoffs (9g) or a disqualification (2j). But since there is no cutoff
   in this case and as there is no reason for a disqualification at first,
   none of this applies.

So technically, the competitor is eligible for a third attempt with a time
limit of zero seconds. Now comes the next tricky question, but which solves
the issue in my opinion: Does the competitor decline the attempt or not?

If yes: According to 9f5), a DNS should be assigned.
If not: Well, this is a case for fools which surely results in a DNF, but
it is a valid case strictly going by the regulations. There are two
possibilities for the following:
- The dumb way: The competitor's puzzle actually gets scrambled, he
  actually starts the attempt, but gets stopped immidiately after starting
  the timer as he has surpassed the time limit.
- The senseful way: The competitor gets a DNF according to A1c) right away
  after confirming, that he is not declining the attempt.

So, as a result I think that with the current regulations, DNS and DNF are
both possible for this scenario, but that DNS should be the default
decision for every senseful competitor.

2015-09-08 12:37 GMT+02:00 Laura Ohrndorf notifications@github.com:

**Comment by pedrosino** [comment]
Sebastién has a nice point. I agree that competitor should understand the situation and just decline. I'm not scrambling any puzzle for a person who has 0 seconds available for a solve...

**Comment by Laura-O** [comment]
Well, the whole issue is not about _scrambling_ a puzzle or not, it's about how this situation can be handled theoretically. We should not judge by thinking about the concrete situation or even arguing that scrambling the puzzle again is time consuming etc.

Also, something I didn't ask in my first comment: we assign a DNF if a competitor reaches the time limit in a single attempt. Why should we handle this differently if a competitor reaches a time limit for three attempts?

**Comment by Claster** [comment]
I agree with Sébastien. The competitor has the right to choose between DNF and DNS. If the cumulative limit is reached and the competitor decides not to continue, the next attempt is not started, therefore DNS.

> we assign a DNF if a competitor reaches the time limit in a single attempt. Why should we handle this differently if a competitor reaches a time limit for three attempts?

We do assign DNF for the attempt in which the limit was reached, but that doesn't automatically imply we should do this for further ones.

**Comment by Claster** [comment]
So how about we will clarify that it should be DNS?

**Comment by viroulep** [comment]
Clarified in #353 .
