### ISSUE TITLE
Allow custom mats?

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#304]
I remember someone saying they made custom mats or took a gen2 one and cut it in half.

I think this is a good and valid idea, and don't see the point in requiring a 80cm-wide mat just because they are sold that way.

**Comment by Laura-O** [comment]
See #90 and maybe also #216, there are some links to prior discussions/arguments on the delegate mailing list.

**Comment by Laura-O** [comment]
With the new Speed Stacks cubing mats the term "full-size" will have a different meaning anyway, so I think there's no further need to define that.

**Comment by pedrosino** [comment]
What do you mean? We'd leave "full-size" there with no further explanation or remove it?

**Comment by Laura-O** [comment]
Yes, just leave "full-size".
The new mat has about half the length of the old mat, so I think using an "old" mat that was cut in half is fine as well. I don't see a benefit in defining a specific length.

However, I would leave the "full-size" because this clarifies that a small piece of cloth is not enough.

**Comment by lgarron** [comment]
At this point, I think we should just specify some rough dimensions, e.g. at least 40cm wide by 30cm deep.

**Comment by pedrosino** [comment]
I agree that requiring "full-size" and allowing 3 different sizes with no explanation is a little confusing.

**Comment by Laura-O** [comment]
Just saw [this](http://www.championscubestore.com/index.php?main_page=index&cPath=371) (several colourful fake mats with Speed Stacks Gen3 mountings).

Do we care about the colours of the mat?
In the discussion about the design of the G4 cubing mat someone mentioned that a mat should not be distracting. A pink mat with Hello Kitty characters might fall into this category. :-)

Personally I don't see a problem with this mats as they have a proper mounting mechanism, but tastes differ...

**Comment by pedrosino** [comment]
I don't think colors matter, since even the official gen 2 mats have many
different colors.
Em 25/01/2016 12:24, "Laura Ohrndorf" notifications@github.com escreveu:

**Comment by viroulep** [comment]
I don't think an "anything goes" policy would be good here, we probably want to give the delegate the right to not permit the use of a mat if its image is inappropriate.

**Comment by Laura-O** [comment]
Note:
The new Speed Stacks cubing mat ist 18 x 11.2 inches (45,72 x 28,45 cm).

**Comment by Laura-O** [comment]
The [Maru Cube Pad](http://thecubicle.us/maru-cube-p-1252.html), which is sometimes used by Asian organizers is 40x30 cm, so the recommended size shouldn't be smaller than this.

**Comment by a-Maass** [comment]
Also, something related, I notice people in Taiwan competitions using mats that are not quite compatible with the timers, is this okay? https://www.youtube.com/watch?v=JeIro2JsfmA

**Comment by pedrosino** [comment]
I think 40x30 cm is fine.

**Comment by a-Maass** [comment]
I thought the mat was supposed to be compatible such that it had to clip on those round pegs (referring to gen-3)

**Comment by Laura-O** [comment]
Alex, the regulations require the timer to be "attached" to the mat.
I don't know if they did that in Taiwan, but I heard that some delegates attach them by putting tape below timer and mat (when they are not using the Speed Stacks mats). That's not an optimal solution, but it is a solution.

The reason why they use those Maru mats is that they get them for free. Speed Stacks equipment is expensive and many communities in poorer countries have to raise money for a rather long time in order to buy new timers. I completely understand that they prefer to buy timers if they get the Maru mats for free.

**Comment by Laura-O** [comment]
Fixed in #335
