### ISSUE TITLE
Z4) Limit the number of competitors

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#311]
> Z4) The organisation team may limit the number of competitors per event, on either a "first come first serve" basis or based upon qualification times or rankings in the WCA world rankings of a previously announced calendar date.

According to Z4 the number of competitors can be limited **per event** only. In fact it's common practice that organizers set a competitor limit for the total number of registered competitors.
This number is likely to be equal to the number of competitors in 3x3 for most competitions, but it's not allowed to do that according to the current regulations.

However, the main goal of this regulation is to avoid venues to be too crowded, so setting a limit for the total number of competitors for a competition or a day of a competition (for >1 day competitions) is what is usually needed. I would suggest to add that to Z4.

**Comment by garrett-webster** [comment]
I realize that this issue is over a month without any updates, but if this is actually going to be considered, I think the following is important.

"However, the main goal of this regulation is to avoid venues to be too crowded, so setting a limit for the total number of competitors for a competition or a day of a competition (for >1 day competitions) is what is usually needed. I would suggest to add that to Z4."

Not always. For example, my first (and so far only) comp I've organized (KCubing 2015) I set the competitor cap at 75. I did this because I didn't want to have a logistical nightmare on my hands by having to many people sign up, like what happened at Lawrence Spring 2015. It turns out that the venue couldn't take much more than that, but that was not the primary reason.

I don't think there needs to be any reason other than the organizer and delegate agreeing that there should be a cap at X.

**Comment by Laura-O** [comment]
In general every issue that is marked as open is still considered, so feel free to comment. :-)

I don't understand what you mean by "logistical nightmare"? Managing registrations? Preparing everything?

**Comment by pedrosino** [comment]
Maybe as a first time organizer it was too difficult to plan for a huge competition.
I see that as a valid reason too. Sometimes you have the space but don't have the personnel required to hold 150 competitors.

**Comment by garrett-webster** [comment]
It was especially for pre-comp logistics as I had never done any thing like this before. I.E I wasn't sure how I was going to assign heats, and it took a couple of tries till I found a flow I liked.

I feel like now I could handle a larger amount of competitors (Which I hope to do at my next comp.) In general, I think an organization team should be able to set a total competitor limit for any reason they want.

**Comment by viroulep** [comment]
Closed via #327
