### ISSUE TITLE
Remove 2i2a? (camera monitor must be out of sight)

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#313]
Natán suggested the removal of _2i2a): Each camera monitor must be blank or out of sight of the competitor_

>   I think that the fact that this regulation is hindering fun, plus the fact that we don't have conclusive evidence that people could really gain a significant advantage from being able to see the back of the cube on a small screen, are heavier considerations.

(see [this discussion](https://groups.google.com/d/msg/wca-delegates/424omzKIDgo/1gITVlknBAAJ) on the delegate list)

**Comment by mrcrt** [comment]
"we don't have conclusive evidence that people could really gain a significant advantage "
Have you ever tried it? 

For example, to me, during a 3x3x3 with feet solve having a monitor or a mirror would help me a lot, since i wouldn't need to turn the puzzle or lean forward to take a look at the pieces on the back side.
I've tried to do a dozen solve while filming with my phone in a way I could look at the monitor while solving. Being able to see the edges on the back side made it really easy to solve the first 2 layes.
I did an average around 52 seconds. Mine all time personal best is still 54, but i usually average around 58. 
So yes, a monitor could help.

**Comment by lgarron** [comment]
While I don't mind loosening this Regulation in principle, I think the current version is the most reasonable and practical line to draw in the sand.

> being able to see the back of the cube on a small screen

If we explicitly allow arbitrary screens, someone can just bring an iPad next competition.

In addition, if they are allowed to have an active device in view, this makes it hard to control how they can communication. The device could show a notification or literally anything while filming.

> hindering fun

As far as I understand, everyone thinks the Regulation is reasonable when they hear it.

The main concern is that attempts are sometimes disqualified because a competitor didn't think about this and the judge didn't pay attention. I think we should focus our efforts on the judge side of things to prevent it from happening (cf. #236).

**Comment by shelchang** [comment]
I don't think there's a problem with the regulation. The problem is with
judges (especially inexperienced volunteers who get roped into judging when
short staffed competitions get busy, though it also happened once at US
Nationals) not knowing this particular rule or not paying attention.

**Comment by Laura-O** [comment]
Quoting my reply in the Hessen Open 2016 thread, where "solving in a mirror" was an unofficial event:

> Interestingly enough, some competitors soon started to practice solves using their front facing camera in "normal" solves and were quite excited about how easy it was to integrate it in their usual solving procedure by using the display to fill the back slots during F2L. Of course, they didn't plan to do that in official solves, but practiced it for fun. However, I've seen this as some kind of proof that it's good that we have this regulation. :-)

I take that as a proof that a mirror/camera display can be an advantage, so I am closing this issue for now.
