### ISSUE TITLE
Include something about propaganda.

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#330]
Motivated by [this incident](https://www.worldcubeassociation.org/forum/viewtopic.php?f=9&t=2006).

**Comment by lgarron** [comment]
I think we need to be a bit careful about this, especially because we don't define "propaganda".

People could argue that this change prevents:
- competitions from raising money for a charity cause (which happens often already!)
- competitors from wearing shirts that support a cause
- competitors from wearing hijabs, yamakas, etc.

Disallowing racial/hateful speech is a good idea for a [code of conduct](http://confcodeofconduct.com/), but a cold, hard "objective" rule also tends to hurt those who are already marginalized.

If a competitor is being actively disruptive, the Delegate can already use their discretion and invoke 2k3/2k4.

**Comment by lgarron** [comment]
Also, the link to the incident is currently broken; is there an updated link?

**Comment by lgarron** [comment]
After re-reading the change a few times, I realized that "demonstration" might have been in the narrow sense of "group of people actively rallying".

If the demonstrating people are not competitors, we are limited in power. And in any case, I think we can still handle it by giving the Delegate strong discretion to handle disruptive people.
If a demonstration is especially rowdy or uncomfortable to some competitors, that would certainly qualify.

**Comment by KitClement** [comment]
I'm a bit concerned with the strength of such a regulation. It's very common to use churches or other places of worship as venues, and many of the materials they have at their venues could be construed as religious propaganda.

**Comment by Claster** [comment]
Lucas:
You can read these two threads:
https://groups.google.com/forum/#!topic/wca-delegates/STh6uXgYJ5A
https://groups.google.com/forum/#!topic/wca-wrc/OVCDwWm1NHA

Indeed, I didn't take churches into account. So do you think the regulation is not needed because of 2k3/2k4?

**Comment by KitClement** [comment]
Based on this incident, it may be good to have some sort of regulation/clarification on this, especially since this wasn't just any competitor, it was the orgnaizer.  Rough idea:

8g) WCA officials, competitors, and spectators must not make any demonstration or spread propaganda supporting a political, religious or racial cause during the competition.
8g+) [CLARIFICATION] The competition venue may support opinions that are political, religious, or racial in nature, but must agree to not associate such opinions with the organizers or the WCA.

My only thought about this is that it might preclude charity events for the WCA, although I'm not sure how to modify this to account for that.

**Comment by lgarron** [comment]
I still think that tweaking the current suggested change is overly broad. As an alternative, I would suggest basing the change on the _effects_ of such propaganda:
- Is it uncomfortable to competitors?
- Is it a polarizing topic (vs. a more of a "promoting awareness" issue)?
- Is it disruptive to the competition?
- Does it violate the spirit of the WCA?

At the competition, I think the Delegate can already handle it.
I think Board discretion is fine for something like a competition name, but we might want to find a way to make sure the Board is aware of the meaning of any non-straightforward competition names.

**Comment by Laura-O** [comment]
I support Lucas approach. Referring to the effect such a propaganda has also avoids possible discussions if something is propaganda or not.

However, I tend to disagree that this can already handled by Delegates. I remember an incident that happened at Worlds last year and was repeated at German Nationals:

> N21. I asked a couple competitors to change or cover their T-shirts as they showed a man kicking a woman and calling her a bitch. ([Link to the report](https://groups.google.com/d/msg/wca-delegates/t1SFVaS1PAc/cWksQur5WeEJ) and [this link for German Nationals](https://groups.google.com/d/msg/wca-delegates/1xU72uCaOQc/laDJ9Dt7CAAJ)).

Of course, this is less severe than the incident quoted by Oleg and has nothing to do with propaganda. I remember that we were unsure if this can be handled by the current regulations (especially 2k3) because they refer to "behaviour" and not to "silent statements". This is probably a question of interpretation and you can discuss if wearing such a shirt is also behavior, but maybe we can find a good generalization to handle all those incidents.

**Comment by Laura-O** [comment]
Let's revive this issue!

Another alternative I would support is making this a guideline for 2k3) like this:

> 2k3+) Examples include: behaving in a way that offends or persuades others for political, religious, or racial reasons.

**Comment by Claster** [comment]
I'm still worried about competitions in churches. In theory, organizing a competition in a church can be considered as "behavior that is offending others for religious reasons", or "persuading" as well (therefore, let's disqualify organizers). On the other hand, this is at the discretion of a delegate anyway, so 2k3 is a better place for that than 8g.

**Comment by UnderwaterCuber** [comment]
I think creating a guideline giving some examples would be the perfect way to solve this issue. Example should probably include that competitors who intentionally behave in a way that offends or persuades others for political, religious, or racial reasons should be disallowed

**Comment by xsrvmy** [comment]
We need to be very careful in specifying what is allowed, especially with respect to clothing. For example, wearing a cross necklace should be fine, but something offensive would not be fine.
Also what if competitors start talking about religion in the audience?
