### ISSUE TITLE
Clarify A6c => A6e implication

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#373]
Currently every violation of A6c automatically implies a violation of A6e, as a competitor touches a puzzle before a judge inspected it. Thus, violation of A6c is rewarded with +4 (or DNF), strickly speaking. We could clarify that if A6c is violated, but no moves applied, it is not counted towards A6e (though a second touch triggers A6e).

> A6c) The competitor must fully release the puzzle before stopping the solve. Penalty: time penalty (+2 seconds).
> A6e) The competitor must not touch or move the puzzle until the judge has inspected the puzzle. Penalty: disqualification of the attempt (DNF). Exception: If no moves have been applied, a time penalty (+2 seconds) may be assigned instead, at the discretion of the judge.

Inspired by 2nd Guwahati Open 2016 report.

**Comment by SAuroux** [comment]
I would simply go with:

A6e) **After releasing the puzzle**, the competitor must not touch or move the puzzle until the judge has inspected the puzzle. Penalty: disqualification of the attempt (DNF). Exception: If no moves have been applied, a time penalty (+2 seconds) may be assigned instead, at the discretion of the judge.

This corresponds to the wording in A6c and makes A6c and A6e mutually exclusive.

**Comment by notkevin888** [comment]
I'm obviously looking at corner cases, but just to check, what would happen if I stopped the timer still holding the puzzle, and I may have done my final turn during or after my timer stop?  The new A6e _technically_ doesn't check against this, since the competitor technically didn't touch or move the puzzle after releasing it.  I realize this is a very dumb and overly literal interpretation of the new suggestion, but I feel like we should at least try to make sure it's clear from the regulations what happens in this case (which, I feel, should be DNF - if a move was made after the timer was stopped, it should certainly be a DNF, so if a move _may_ have been made, then it should be a DNF).
