### ISSUE TITLE
+2 on Rubik's Clock

### ISSUE THREAD

**Issue by kingmathyall** [thewca/wca-regulations#381]
I, along with everyone I talked to about this, believe that there should be a +2 on Rubik's Clock. When you are solving the clock and then stop the timer and every single clock one one side is off by one notch (or even more than one), you're the equivalent of a turn away. You're one turn of the gear away from it being solved. On a 3x3, one turn away is a +2, so why not on clock? Clock is by far the most DNFed event (other than BLD - and nothing to back me up on this, just it seems like common sense) and I think adding this rule would prevent an absurd amount of DNFs.

**Comment by Claster** [comment]
... Or we could just remove clock.

There is a difference between 1 move on a twisted puzzle and 1 move on a clock. If you make 1 move on a twisted puzzle, every non-cuber can solve it. If you make 1 move on a clock, it is not obvious, which pins one should push and which wheel one should turn to solve it. An implication is that if we introduce +2 penalty for clock, judging "misalignments", especially for judges that cannot into clock, will become a pain.

**Comment by kingmathyall** [comment]
I still think it should be considered a +2. Obviously they know how to get it to 12 if all the clocks are off by just one notch. I don't see  how "misalignments" would be a pain as all they need to see if if all clocks on one side are off by one notch.

**Comment by Claster** [comment]
No, it's not enough to check that clocks on one side are pointed at the same direction. You need to check that clocks on the other side are solved except corner ones, otherwise it is not 1 move away. Not so easy, is it? And this is not the only possible position. What about: on one side upper, right, upper-right and center clocks are off, on the other side upper-left clock is off, the rest clocks are solved. This still can be solved in one move. How about: on one side all clocks are off, except for upper-right, on the other side all clocks are solved, except for upper-right, down-right and down-left. This is still "+2", and good luck explaining to judges which positions are off by one move.

**Comment by kingmathyall** [comment]
You bring up good points. I take back what I said as I never thought about all that other stuff.
