### ISSUE TITLE
Could we avoid linking to the delegate list?

### ISSUE THREAD

**Issue by Randomno** [thewca/wca-regulations#388]
I know many people who discuss stuff here are delegates, but it's hard for some people to contribute to the discussion when little is posted other than a link to a discussion on the delegate list. Quoting the posts in the discussion seems easy enough.

Sorry if this is a bad place to post this, since it's not a regulations issue, more of a meta discussion.

**Comment by Laura-O** [comment]
Well, transparency has often been discussed here (see #144 or #174 as an example).
However, I think you can see this repository and especially the issues from different perspectives. On the one hand, it can be seen as a discussion forum to discuss different issues with the WRC. On the other hand, and this is actually how I see it, it is as a way to make the work of the WRC more transparent in order to give others an idea what we are working on, invite people to post their regulation proposals and document all regulation changes and discussions.

I can understand that it would be interesting to read relevant discussions on the delegate list, but I do not think there are any issues here which just link to a discussion without summarizing it.

In general, information on the delegate list is confidential and delegates write their messages assuming that they will stay confidential. So we have to be careful, even if we anonymize them. Furthermore, the links often refer to long discussions and not to single statements. It would be a lot of work to transfer them here and make them readable and comprehensible for everyone else.

**Comment by Randomno** [comment]
Yes, I haven't found anything that had absolutely no description other than a link. There are some issues that have little description though, and you can't tell what you're missing.

**Comment by jfly** [comment]
Very relevant: https://github.com/thewca/wca-regulations/issues/410.

Unfortunately we do not currently have a way for delegates to have a publicly viewable discussion. This is one of those things where the incentives are all screwed up: the people who have the power to change this are not affected by this, and the people who are affected by this do not have the power to change it.
