### ISSUE TITLE
Clarify Declining an Extra Attempt and How Extra Attempts Can Occur.

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#399]
Throughout the regulations there is no specifications as to what happens if a competitor is offered an extra (because of an incident such as the lights in the room turned off and back on) but then declines it to keep their original time. The only regulation talking about the competitor declining an attempt is 2u1 where he/she will be awarded a DNS, which is not what the competitor would want. But in certain situations, it would be completely okay to decline an extra attempt if one is not neccessary (i.e. a situation that does not benefit the comeptitor). 

Also while reading 11e, I am slightly confused as to the procedure that must be followed for an extra to be granted. I have witnessed 2 different types of situations in which incidents occur, those in which the competitor would appeal for an extra (i.e. the judge was yelling "get a world record" during their inspection time). And incidents where the Delegate takes initiative and grants the competitor an extra without an appeal (i.e. incorrect procedure done by the judge that the delegate notices but the competitor doesnt). 

If there is anything that is unclear as to what I mean please ask and I will further verify.

**Comment by lgarron** [comment]
[11e](https://www.worldcubeassociation.org/regulations/#11e) makes it clear that extras are replacements. That means that you've started the attempt at least once if you decline an extra solve.

I think the only reasonable interpretation is a DNF unless the first solve turns out to be valid, and we could add a guideline to that effect.
Has this ever been a problem in practice?

**Comment by Jambrose777** [comment]
At Athens Fall Late Night, incident 6 was discussed to be either a DNF or DNS a complete conclusion has not been reached.

A competitor was awarded a DNF by the judge for a megaminx touching his body. This was incorrect procedure by the judge as this is allowed. Later at the end/after the competition the competitor was awarded an extra, but declined it. Hence the confusion of whether or not a DNF or DNS was the correct call.

**Comment by xsrvmy** [comment]
There were several incidents at our Alberta comps with bad judges actually, usually involving the judge interfering or disturbing the competitor in some way without causing a DNF. In that case, if the competitor got a good time, it would be preferable to decline the extra attempt.

Also, if the delegate is not in the room, how does regulation 11e) work. And does "finishing the attempt" mean stopping the timer? Because there can be incidents after the timer stop.

**Comment by Laura-O** [comment]
@xsrvmy I'm sorry, but this is not a discussion forum for incidents which happened at specific competitions, but the place where we discuss possible regulation changes.

Furthermore, please read the regulations if you have questions. The questions you asked here are clearly defined, so I am not going to search and c&p the answers for you.

You can also post your questions on [speedsolving.com](https://www.speedsolving.com/forum/threads/one-answer-wca-competition-and-regulations-question-thread.50221/) or, if you want to share specific issues which need our attention, you can send us an email.
