### ISSUE TITLE
Placement of cubes under cover in MBLD

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#403]
It seems fairly obvious that we should not allow competitors to request how cubes are placed in Multi, but it appears that this happened this weekend for Shivam's 35/42, and this issue was brought up on SS here:

https://www.speedsolving.com/forum/threads/indian-nr-shivam-bansal-official-mbld-35-42-cubes-in-1-00-00-wr5.62814/#post-1209188

We have regulations that prevent competitors requesting a specific orientation of the puzzle (A2e1) in any event, but the arrangement/placement issue in MBLD is unique.  Should we have a regulation in the style of A2e1 for article H to make it clear that competitors cannot request a specific arrangement?

**Comment by viroulep** [comment]
I would support such clarification.

**Comment by Randomno** [comment]
Could someone explain this a bit? I can't really see why Shivam requested a specific placement. There seems like a very small disadvantage to spending a few second separating them once the attempt has started.

**Comment by lgarron** [comment]
> Could someone explain this a bit? I can't really see why Shivam requested a specific placement. There seems like a very small disadvantage to spending a few second separating them once the attempt has started.

There is also a "small" disadvantage to getting your cubes in inconsistent orientations, but we forbid that.

Anyhow, I support this idea, but I fear it won't be enough. In 2013, the Regulations specified that competitors cannot request puzzle orientations, but after [high-profile incidents](https://www.worldcubeassociation.org/forum/viewtopic.php?f=9&t=1231) we had to explicitly randomize the orientations (#74).

In a similar way, I worry that saying the competitor is not allowed to *request* an arrangement is not enough, because it doesn't prevent organizers/scramblers from *providing* cubes in the competitor's desired arrangement – either intentionally unintentionally. For example, If the competitor places the puzzles on the table and someone scrambles them "in place", the competition has high plausible deniability that they weren't trying to help the competitor, and that maintaining the arrangement is perfectly legal as long as the competitor did not explicitly request it.

If we want to address this, I think we should specify a standard arrangement (e.g. packed* columns of X cubes, with a partial row back-aligned if there are not a multiple of X cubes). Ideally we'd also randomize cube locations, but I can't think of a way that is not slow and error-prone.

*Note: The Regulations currently allow differently sized cubes in the same multi BLD attempt.

**Comment by AlbertoPdRF** [comment]
We are currently discussing the placement of MBLD cubes in #444, but maybe we should add a Regulation like we have [A2e1)](https://www.worldcubeassociation.org/regulations/#A2e1) for orientation, but for placement. This regulation could be on [Article H](https://www.worldcubeassociation.org/regulations/#article-H-multiple-blindfolded), as it's only for MBLD.
