### ISSUE TITLE
7f2a) "For Solving With Feet, the Stackmat must be placed directly on the floor."

### ISSUE THREAD

**Issue by Randomno** [thewca/wca-regulations#404]
I think this has been brought up [before](https://github.com/thewca/wca-regulations/issues/216) but this may be a slightly different issue (a lot of that thread is delegate discussion links).

The problem is that I don't see where the line is drawn at what constitutes the floor. If you have a carpeted venue, it is accepted (as far as I know) that the stackmats can be placed on the carpet. However this isn't actually directly on the floor, assuming that underneath the carpet there is a hard floor.

Therefore if you put a small carpet on the floor, is that allowed? I would have thought not, although at my last competition one of the delegates was planning to bring a carpet to use and I assume he knows if it's allowed (in the end he forgot the carpet).

I think the best solution would be allowing competitors to use other surfaces, including not using a mat at all (I know this has been suggested before since it's in the issue I linked). Are there disadvantages to this?

**Comment by lgarron** [comment]
> Are there disadvantages to this?

*Competitions* should provide a consistent, fair environment.
If top feet cubers can do significantly better on some surfaces, then those who can lug around their desired surface get a consistent advantage.

I would rather standardize on something like "a single standard-thickness Stackmat on a hard, flat floor" and require competitions to bring flat boards or move to another room if the main room has carpet.

However, I'm not very familiar with the effect a floor has on performance – perhaps a wooden sprung floor behaves differently from concrete.

**Comment by Mollerz** [comment]
I think it's fairer to let people put what the want under the stackmat. For example, let's say there are two competitors who average ~40 seconds when practicing at home. Competitor 1 practices in their kitchen on hard floors, and Competitor 2 in their bedroom on soft floors. You get to a competition and it's a hard sports hall floor. Competitor 1 has a significant advantage here.

I also really dislike your argument for the hard floor you suggest. With that change you would _force_ people to change their practice at home to be on hard floors. In colder countries, most rooms have carpet, and a lot of the venues also have carpets. So people have to go really out of their way to practice feet if they want consistency with their home practice and competition solves. And it also forces organisers to carry even more equipment which seems completely unnecessary.

Some other arguments I've heard are:
1. We don't want to encourage people to bring bits of surface with them to competitions.
This doesn't really matter does it? People already bring a lot of cubes, sometimes suitcases full of them. Also for some people a towel is perfectly enough to replicate the surface they use at home, what's wrong with putting a towel under the mat?

2. Consistency argument.
If we want to make competitions consistent then we should also provide cubes so they are all the same for competitors as well right? I really hate this argument in the case of feet solving.

All other UK delegates agree with my opinions here, we've discussed it a lot. 

And surprisingly, I actually agree with the sentiment of not using a stackmat if the competitor wants as well. At the UK Championship 2016 we had a carpeted venue, and during warm up for feet, several competitors complained about the stackmats moving around a lot on the floor because there was no grip between the mat and the floor. So we taped down the mats, it didn't really help. At the end of solves people had twisted and folded mats and it was just a mess really. Also there's nothing in the regulations about solving off of the mat, as long as there is a mat. A lot of people start their solves, and immediately move the cube off the mat. So I think not using a surface for feet is absolutely fine.

And at the end of all this, instead of having all these seemingly ludicrous exceptions for feet solving. I think the best solution is actually still removing the event. ¯\\\_(ツ)_/¯

**Comment by Randomno** [comment]
> I would rather standardize on something like "a single standard-thickness Stackmat on a hard, flat floor" and require competitions to bring flat boards or move to another room if the main room has carpet.

Based partly on what James said I would mind if "hard floor" was replaced with "carpet", but I'm definitely a bit biased...

> However, I'm not very familiar with the effect a floor has on performance

I'm not either to be honest, all I know is that carpet = good, hard floor = bad (for me) :p

> So we taped down the mats, it didn't really help.

oops


Regardless of what the proposed change is, is there an issue with the current regulations? Basically what I said in the OP except the last paragraph.

**Comment by xsrvmy** [comment]
I think softer floor does make turning easier so carpets should not be allowed

**Comment by Samuel-Baird** [comment]
@lgarron this issue can be closed
