### ISSUE TITLE
Introduce the WCA List of Recognized States

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#406]
The complete proposal is [here](https://docs.google.com/document/d/1CKxQQugBg_jAni3BLByp58F1Kp7_q9PYkucUGcHIQC4/edit).

The main changes:
1. Replace UN members list from wikipedia with our own list (with explanations how and why it differs from UN members list);
2. Introduce "Stateless".

**Comment by Randomno** [comment]
Where do the choices for the names come from? Some seem a bit odd compared to others.

**Comment by Mollerz** [comment]
The UN Charter, with some accepted shortened substitutes. For example Venezuela is actually the Bolivarian Republic of Venezuela etc.

**Comment by Randomno** [comment]
I think the additional substitutes would be good:

- Federated States of Micronesia -> Micronesia
- Democratic People's Republic of Korea -> North Korea
- Republic of Korea -> South Korea

Also made [a list](https://docs.google.com/document/d/1NlH-CUDzKrbj8w1OMi5Xud6YVAauOxMwkNZ9OXwwU-A/edit#) before I realised it wasn't really worth it.

**Comment by Mollerz** [comment]
For Micronesia it doesn't often get shortened. If we get some competitors from there and they request it to be shortened then it makes sense but for now we'll stick with the long form. 

As for Korea I had a long discussion with the delegates and we ultimately concluded that they don't like being called south and north because that's not their countries names. We also couldn't go forward with both of them being listed under just Korea as they are listed separately in the UN. So we settled for their long form names.

**Comment by a-Maass** [comment]
I believe cubers of the countries you planning to change names of should be inquired for feedback, for example Korea might not like their name being much longer.
It's interesting to see these changes though, (I'm sure Kim Jong Un will love his North Korean NRs!).

Also, could you link to the UN charter page where you are getting all of the country names from? I can't seem to find it.

**Comment by Mollerz** [comment]
We've spoken to the countries where we are amending their names and we are using names that are agreed upon. For countries that are listed that nobody has competed for, they won't show up in the drop-down list until someone actually competes for them; they will only show up in the regulation until then.

Here's the UN website, enjoy: http://www.un.org/en/index.html

**Comment by a-Maass** [comment]
http://www.un.org/en/member-states/index.html ah found the list here

**Comment by Mollerz** [comment]
In case anyone missed it, I finished updating all of the ISO3166-2 codes, so they are now available for every country.

Also another very small note. How do people feel about EuR instead of ER? All other continents use the first two letters to denote the continent, NAR, SAR, AfR, AsR, OcR. Seems weird that there is an odd one out. Of course people are used to ER, but it just feels inconsistent,

**Comment by viroulep** [comment]
We will also need to associate each of the states to a continent.
Is there any tricky cases or can I go ahead and complete with information I could find on the internet (eg: Wikipedia)?

**Comment by lgarron** [comment]
Russia, Turkey, Middle East, Central America?

**Comment by Mollerz** [comment]
Russia: Europe
Turkey: Europe
Middle East: Asia
Central America: NA

**Comment by jfly** [comment]
Would the WRC be willing to maintain the `eligible_country_iso2s_for_championship` table @Baiqiang proposed in [championship competitions](https://docs.google.com/document/d/1tgIfNxJqYni_PFsMt-hpDSh1YpfoCseLORvLX6d7-l4/edit)?

**Comment by KitClement** [comment]
Not sure if this is already accounted for, but we also currently consider
Israel in Europe.

**Comment by Laura-O** [comment]
>Would the WRC be willing to maintain the `eligible_country_iso2s_for_championship` table @Baiqiang proposed in [championship competitions](https://docs.google.com/document/d/1tgIfNxJqYni_PFsMt-hpDSh1YpfoCseLORvLX6d7-l4/edit)?

Yes, sure.

**Comment by viroulep** [comment]
I tried coming up with a migration for the website to see what changes would be needed.
For the `users` table we have a bunch of accounts to update, here are the needed updates I spotted, as well as what I think the update should be:
- VG (Virgin Islands) -> UK
- AW (Aruba) -> Netherland
- GF (French Guinea) -> France
- PN (Pitcairn Islands) -> UK
- PR (Puerto Rico) -> USA
- IM (Isle of Man) -> UK
- PF (French Polynesia) -> France
- XA/XE/XS -> wtf... No idea how they managed to register with these unreal countries

Please correct me if I made a mistake in countries' substitution!

In the `Persons` and `Results` tables we only have to migrate people from Aruba and Puerto Rico.

**Comment by Laura-O** [comment]
Thanks, Philippe!
Changing "XA/XE/XS" to "wtf" doesn't sound like a good idea, but the rest looks good. :-)

**Comment by viroulep** [comment]
Yes of course :)

**Comment by lgarron** [comment]
> Also another very small note. How do people feel about EuR instead of ER? All other continents use the first two letters to denote the continent, NAR, SAR, AfR, AsR, OcR. Seems weird that there is an odd one out. Of course people are used to ER, but it just feels inconsistent,

I actually like this change. However, while trying to find supporting evidence, I found:
- It is easier to find [precedent for "ER"](https://en.wikipedia.org/wiki/2016_European_Athletics_Championships).
- `EUR` is already used as the currency code for Euro.

**Comment by Mollerz** [comment]
> I actually like this change. However, while trying to find supporting evidence, I found:
> 
> - It is easier to find precedent for "ER".
> - EUR is already used as the currency code for Euro.

I dislike this precedent for ER, athletics will always try and use 2 letter acronyms, WR, OR (Olympic Record), CR (Championship Record), SR (Stadium Record), etc. I don't think we should have one continent be inconsistent with the rest because of athletics. I thought we were trying to be more independent of other organisations?

SAR is the currency code for Saudi Riyal (The currency of Saudi Arabia), and we use that. Again I think it's another reason just purely for counter-arguments sake. Also, how many people are going to look at a records page and think, "Huh, I wonder why that time has Euros next to it?" I highly doubt that would happen. Unless this is a really particular programming problem I'm unaware of, you'll have to find some way around that. 😄 

As an aside, EU/EUR are often shorthand for the European Union or Europe in general. Given how often it is denoted by EU/EUR already I believe EuR actually helps identify it better than ER currently does.

**Comment by Randomno** [comment]
The original six continents, as far as I know:

AfR
AsR
AuR
ER
NAR
SAR

They all contain the first letter/s of the continent, and the ones with the same letter also contain the second letter.

Then AuR was later changed to OcR, rather than OR to avoid confusion with Olympic Record.

So unlike the other continents, I don't see any good reason to make it 3 letters.

**Comment by Mollerz** [comment]
Not changing something because of "That's how it always has been" is a really bad reason not to change something, a system should always try to be improved upon if possible. I think to keep consistent, it _does_ make sense to change it to 3 letters, because it is the _only_ two-letter acronym for a continental record. Whilst it may not have had a reason in the past to become a three-letter acronym, maybe this is the reason to make it one.

I just personally value keeping all of them consistent very highly. Since ER is inconsistent with the rest due to this reason, changing it to three letters keeps it consistent.

**Comment by viroulep** [comment]
I just updated the country list with their continent id (WCA db format).
I wasn't sure about Azerbaijan and Kazakhstan so I left them empty.

I'd appreciate some double/triple check on this!

**Comment by Laura-O** [comment]
I checked everything and apart from the Israel -> Europe issue (already commented) didn't find any mistakes.

**Comment by viroulep** [comment]
Thanks a lot for the proofreading!
