### ISSUE TITLE
Revisit "similar pieces" on Clock

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#409]
Currently we have:

> 3j) Puzzles must be clean, and must not have any markings, elevated pieces, damage, or other differences that significantly distinguish any piece from a similar piece. Exception: a logo (see Regulation 3l).
> 3j2+) CLARIFICATION On Clock, all eighteen inner clock faces are considered similar pieces.

That implies that all 18 inner clocks must be the same color. This, however, not always the case (probably almost never the case?): all clocks on one side have one color, but these two sides differ.

It would make sense to consider inner clocks only on one side as similar pieces. Or get rid of it completely, allowing inner clocks to have different colors. It becomes easier to distinguish top side and to avoid a common mistake when competitors "solve" a Clock with all clocks pointing at 6 or 3 or 9 instead of 12. However, this advantage can be gained with currently legal ways, just by writing "this is up" on an insert.

**Comment by pedrosino** [comment]
I agree with your last part. The original inserts have the numbers written, so I don't think it makes sense to not allow the inner clocks to be different.

**Comment by xsrvmy** [comment]
I think we should just remove this for clock as really it gives no advantage whatsoever

**Comment by kingmathyall** [comment]
I agree that the inner clocks on one side should be seen as similar pieces, allowing the 9 on one side to be different from the 9 on the other side, rather than all 18 being similar pieces (requiring all 18 to be the same color). However, I do think that all 9 on a side should be the same color rather than allowing individual inner clocks to be different from the other 8 on that side.

Example: making the top three clocks one specific color would require the competitor to modify the puzzle in such a way that allows them to have more information regarding the orientation than original puzzle already does. This completely goes against [Regulation 3h](https://www.worldcubeassociation.org/regulations/#3h)

**Comment by xsrvmy** [comment]
Custom inserts can still make it easier to find 12 o'clock.

**Comment by lgarron** [comment]
> I think we should just remove this for clock as really it gives no advantage whatsoever

I've softened on this, and have come to agree with this stance. Apart from occasional embarrassing mistakes, most competitors don't really have a problem keeping their clock upright. As as long as we still have inspection, competitors don't really benefit from a lower solving time by being able to tell the clock orientation at a glance. And as long as the dials are solid circles with minimally decorated radial lines, it's still requires the same recognition and the same solving technique.

However, I also trust Laura's judgment here., and will defer to her if she feels strongly.

**Comment by Laura-O** [comment]
All good Clock solvers are orientation-neutral, which means they do not change the orientation during the inspection so that 12 is on top. What really happens in the inspection is that you try to find the best orientation by checking for lucky cases, using the best pin position etc.

I think having 12'o clock encoded with colored inner clocks (top row with darker/brighter clocks) can definitely be helpful as it visualizes the solved state better. So yes, I see an advantage here.

**Comment by AlbertoPdRF** [comment]
> I think having 12'o clock encoded with colored inner clocks (top row with darker/brighter clocks) can definitely be helpful as it visualizes the solved state better. So yes, I see an advantage here.

That can also happen if the clocks have tape or stickers of different colors or patterns on the sides (where the two transparent cases join).

**Comment by Laura-O** [comment]
> That can also happen if the clocks have tape or stickers of different colors or patterns on the sides (where the two transparent cases join).

Yes, but you do not look at the outer case during your solves.

Edit: Or if you do, you will lose time.

**Comment by lgarron** [comment]
> I think having 12'o clock encoded with colored inner clocks (top row with darker/brighter clocks) can definitely be helpful as it visualizes the solved state better. So yes, I see an advantage here.

Would it be sufficient if clock faces on a given side are indistinguishable (and, to quote myself from above, "solid circles with minimally decorated radial lines")?

**Comment by Laura-O** [comment]
> Would it be sufficient if clock faces on a given side are indistinguishable (and, to quote myself from above, "solid circles with minimally decorated radial lines")?

What you mean is that all clocks on one side have the same color/design, right?
Yes, sure, that's fine. The inner clocks and inlays of the original Rubik's Clock have different colors on each side (one side is darker/brighter than the other), so that's what most competitors are currently using.

**Comment by kingmathyall** [comment]
So all of this would change the guideline to:
3j2+) CLARIFICATION On Clock, the nine inner clocks on a face are considered similar pieces.

Thoughts?

**Comment by Laura-O** [comment]
> 3j2+) CLARIFICATION On Clock, the nine inner clocks on a face are considered similar pieces.

I would change this to "on one face", the rest is fine for me.

**Comment by kingmathyall** [comment]
3j2+) CLARIFICATION On Clock, the nine inner clocks on one face are considered similar pieces.

**Comment by Laura-O** [comment]
Same here: @kingmathyall Why was this closed?
