### ISSUE TITLE
Regulation 9p2: What is a "cutoff time"?

### ISSUE THREAD

**Issue by jfly** [thewca/wca-regulations#429]
[Regulation 9p2 says](https://www.worldcubeassociation.org/regulations/#9p2):

> 9p2) The competitors who advance to the next round must be determined by either a cutoff ranking or a cutoff time in the preceding elimination round.

I was just chatting with @Laura-O about this, and we realized that it's not very clear what a "cutoff time" is. There are at least 2 problems with this regulation as written:

1. It forgets about events where your result is not just a time, such a 333fm and 333mbf. The way this is addressed in other regulations is to talk about "results", rather than "times".
2. It totally forgets about rounds where people are ranked by average, rather than single. It seems like right now 9p2 would allow you to run a round of 333 ave5 and allow competitors to advance if they got a best solve < 10 seconds. This is certainly not the intention of the regulation!
  - Note: Rewording 9p2 to address this is going to be tricky: remember that not all rounds are ranked by average, and 333bf is ranked by single, but an average is computed for the event.

**Comment by AlbertoPdRF** [comment]
Problem 1 is solved with the rewording suggested on #423 

I would solve problem 2 removing the possibility of advancing to a next round by result, as this is barely used and also has some problems: for instance if more than 75% competitors beat said result, some competitors won't proceed to the next round even when they met the requirements to do it. If my example wasn't clear, I'll try to explain it better.

Also, I think that this issue should have been a comment on #423 in order to keep the discussion about this regulation all in the same place.

@thewca/wrc-team Can we discuss how to deal with that regulation? I can make the PR when we are done :)

**Comment by pedrosino** [comment]
@AlbertoPdRF I think there is no need to remove completely the possibility of advancing by result. Your proposal in #423 solves this, I think, and it may be useful if you only want people under a certain result to advance (because you don't have a lot of time for the next round).

**Comment by AlbertoPdRF** [comment]
I think that adding a clarification (Guideline) stating that by result we mean the single or average that determines the ranking in the respective Round would fix problem 2 that @jfly pointed out. Thoughts?

**Comment by jfly** [comment]
@albertopdrf, I don't love that we'd need a new guideline to make this clear, but I don't right now have a better suggestion. Could you send in a PR implementing what you suggest and we can comment on it there?

**Comment by AlbertoPdRF** [comment]
I also don't love it, but I can't see an easier or more elegant solution at the moment. I'll open the PR once we organize all of our branches for the upcoming changes :)
