### ISSUE TITLE
Inconsistent timers

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#436]
So about a year ago I had an incident at a competition. I DNFed an attempt because I was using a stackmat two, which has the longer waiting time. Maybe they need to be removed from the allowed list of timers.
Another problem occurs with gen4 timers. I don't think a competition should be allowed to use both gen4 and other timers (at least not for the same round of the same event) to avoid any unfair advantages.

**Comment by KitClement** [comment]
As far as I understand, preventing the use of Gen2 timers or mixes of timers is not something the WCA is ready to do. In many regions of the world, acquiring equipment is very difficult and expensive, and we would rather not have a blanket ban on this.

I can see a guideline being added that competitions should avoid using multiple models of timers, but a blanket ban would hinder competitions in many parts of the world.

**Comment by lgarron** [comment]
> I can see a guideline being added that competitions should avoid using multiple models of timers, but a blanket ban would hinder competitions in many parts of the world.

I think we should avoid such a guideline, too. Else we're basically telling organizers "if you're using old timers, please keep trying to buy old timers".

(*Maybe* about a Guideline to use as many new timers as are available, to encourage a quicker transition once those timers are available? That doesn't seem much better to me, though.)

**Comment by Laura-O** [comment]
Yes, it's not realistic to force organizers or delegates to buy new equipment just because of the different waiting time. Furthermore, compared to the Gen3 timers, Gen2 timers seem to have a higher lifespan and a lower error rate. It would be weird to throw reliable hardware away for a minor reason.

I also do not consider this to be a huge problem. We often mix Gen2 and Gen3/4 timers here and I don't think the number of timer start failures is significantly higher than at competitions where we only use Gen3/4.
