### ISSUE TITLE
Missing signatures on score sheets

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/wca-regulations#443]
After some delegates asked for the consequences of competitors or judges not signing on the score sheets, the WRC has decided to add to Article A ([A7)](https://www.worldcubeassociation.org/regulations/#A7) specifically) of the Regulations something like:

> If the competitor and/or judge's signature is found to be missing after the score sheet has been delivered to the score taker, the result is considered a DNF. Exception: If the judge and/or competitor can be tracked down to vouch for the recorded time before the end of the competition day, then the recorded time may be considered valid, at the discretion of the WCA delegate.

**Comment by Jambrose777** [comment]
I still think that if a judge does not sign, the attempt should still be accepted.
With me, as a competitor, having to remind judges to sign then after I have completed my attempt have to sit there and watch my judge sign just to validate my result seems like more than what a competitor should do.
Not signing yourself is you doing the action, signing an incorrect attempt is still you doing the action. Having a judge not sign your attempt is the judges fault, not an action of the competitor.

**Comment by lgarron** [comment]
> Having a judge not sign your attempt is the judges fault, not an action of the competitor.

That doesn't mean we can't make it required of the competitor. I think it's reasonable that the competitor needs to ensure that the attempt is finished if they want it to count – and an attempt cannot be finished if the judge has not signed. (If the judge refuses to sign, A7c1 already covers it.)

**Comment by SAuroux** [comment]
I think that the regulations should simply require the judge to sign FIRST
(to acknowledge that the result has been written down correctly) and the
competitor SECOND (to acknowledge that everything is correct). This way, it
is trivial to say that a competitor should never sign before the judge has
already signed.

2017-06-12 22:19 GMT+02:00 Lucas Garron <notifications@github.com>:

**Comment by lgarron** [comment]
> I think that the regulations should simply require the judge to sign FIRST
> (to acknowledge that the result has been written down correctly) and the
> competitor SECOND (to acknowledge that everything is correct). This way, it
> is trivial to say that a competitor should never sign before the judge has
> already signed.

I think this is okay from a procedural perspective. However, it is toothless if there is no penalty – and it seems pretty pedantic to have a penalty for this.

(We also already have too many kinds of penalties as-is.)

**Comment by cubemasterzach** [comment]
I personally think that giving a DNF is the right call because it signifies that the solve is complete and you are verifying that the time written down is in fact the time you should receive. Therefore if there is no signature than I'm not sure whether or not the time written is the correct one. There are times where a judge believes the cube is solved. Turns out to be DNF. Doesn't change it to said result and then competitor doesn't sign for it since it was a DNF and now an incorrect time is entered.

**Comment by pedrosino** [comment]
Proposal:

> A7c2) The competitor must not sign an attempt on the score sheet before the judge has recorded the final result for that attempt **and signed**. If a competitor signs (or otherwise marks) an attempt before they have begun it, or before the judge has finished recording the result, they forfeit the attempt and the result will be considered DNS.

Alternative proposal:
> A7b) The judge records the result on a score sheet **and signs next to the result**.
>...
>A7c) The competitor must check the recorded result, and sign (or initial) the score sheet to acknowledge that the result is correct, complete, properly formatted, and clearly readable. This finishes the attempt.

**Comment by SAuroux** [comment]
I like this proposal. :) It looks like a clean implementation of what I
proposed earlier and also addreses Lucas' concern.

2017-06-28 12:55 GMT+02:00 Pedro Santos <notifications@github.com>:

**Comment by pedrosino** [comment]
Which one? :)

**Comment by SAuroux** [comment]
What exactly do you mean? my reply again less ambiguously:

- I like your proposal.
- It's a clean implementation of required the judge to sign before the
competitor does, which I proposed before.
- I addresses Lucas concern of not having a penalty, because the
integration into A7c2) includes DNS as a penalty.

2017-06-28 13:50 GMT+02:00 Pedro Santos <notifications@github.com>:

**Comment by SAuroux** [comment]
Ok, Laura just pointed out that your message includes a "proposal" and an
"alternate proposal". :D

I overread that and understand this as one proposal including two changes,
which work perfectly together in my opinion!

2017-06-28 14:16 GMT+02:00 Sébastien Auroux <sebastien.auroux.sa@gmail.com>:

**Comment by pedrosino** [comment]
Ah, I see. Well, my proposals are not excludent. They may be a little redundant, but that is fine. I'll make a PR.

**Comment by timreyn** [comment]
Have we considered giving an extra attempt if the judge didn't sign?  To me this feels like a procedural error, similar to A3c3+.  It seems inconsistent that the judge is responsible for the timer being reset, but the competitor is responsible for ensuring that the judge signed the attempt.

**Comment by jfly** [comment]
> Have we considered giving an extra attempt if the judge didn't sign?

I think the problem with this is it's hard to define the moment in time at which "the judge didn't sign" vs "the judge just hasn't signed *yet*". With timer resets, there's a distinct moment in time at which the judge has clearly failed to do their job. I think it's less obvious with signing the scorecard.

**Comment by timreyn** [comment]
I don't really get that distinction.  What about when the moment the runner picks up the scorecard (or more generally, when the judge yields possession of the scorecard to someone else without their signature)?  I think that's the clear moment at which the judge has failed to do their job.

In any case, when the scorecard gets to the data entry table, I don't think that "the judge just hasn't signed yet" is possibly the case anymore.

**Comment by jfly** [comment]
Talking about "runners" and "data entry tables" doesn't feel like it would work to me, because those are not defined in the regulations.

"The moment the judge yields possession of the scorecard to someone else without the judge's signature on it" sounds like something that could work, but I think we'd get into some weirdness with "yielding possession". For example, I have definitely had judges pass me a scorecard (for me to sign) where they had not signed yet. Does that count as "yielding possession"? Or are they still in possession and are just asking someone else to sign a piece of paper in their possession? We don't actually have to sort this out right here and now unless you want to, I'm just trying to point out that this might be a similarly weird rabbit hole.

**Comment by Laura-O** [comment]
Yes, exactly what @jfly said: it's not a problem to verify results when the competitor is still present and the missing signature is identified during the competition. Usually, competitors remember their judges, so we can ask the judge to verify the result.

I think Pedro's proposal is consistent: we say that competitors are responsible for checking their results, so making them check if the result is correct and signed should be fine as well.
