### ISSUE TITLE
Clarification of cube rotations used in FMC solutions

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#456]
The current regulations allow the following notation for cube rotations (listing only 90 degree clockwise rotations here, same can be applied to 90 degree anti-clockwise and 180 degree):
- small letters in square brackets: [f], [b], [r], [l], [u], [d]
- x, y, z

Competitors like mixing these notations. We have seen:
- small letters in parentheses: (f), (b), (r), (l), (u), (d)
-  x-/y-/z-notation in square brackets: [x], [y], [z]
-  x-/y-/z-notation in parentheses: (x), (y), (z)

As it has lead to countless and endless discussions whether solutions using this wrong notation should be DNF or not, we need a clear decision here. This should also be clarified in the regulations or guidelines.
Maybe reworking the FMC sheet would be a good idea as well.

**Comment by lgarron** [comment]
> As it has lead to countless and endless discussions whether solutions using this wrong notation should be DNF or not, we need a clear decision here. This should also be clarified in the regulations or guidelines.

I don't know why this is a subject of debate. The letter and spirit of E2c++ is clear:

> E2c++) CLARIFICATION The competitor's solution must only use moves that are exactly defined in Regulation 12a. Examples of notation and moves that are not permitted in competition: [F], [R, U], [R: U], R'2, L'w, f, M, U2'.

**Comment by Laura-O** [comment]
It might be clear for you. It is not clear for a large number of delegates and competitors, who approve or use the wrong notation described in the first post.

**Comment by lgarron** [comment]
Yeah, reworking the FMC sheet is probably a good idea to address that. We should probably enumerate all moves and add a line saying "anything moves not explicitly listed here will result in a DNF".

**Comment by pedrosino** [comment]
I personally have no problem with [y] or (y) since it's very clear what the intent is.
(I use to draw ( ) around rotations when grading to help me count the moves...maybe this is not a good idea?)

What would that reworking of the FMC sheet looke like? Would we allow more moves or give more counter-examples?

**Comment by Claster** [comment]
Well, the intention of M, S, E moves is also clear, and most delegates probably understand [M, U2]. Yet we disallow these.
I guess reworking of FMC sheets means adding counter-examples.

**Comment by pedrosino** [comment]
Yeah, my wording was not so great.

I would be in favour of allowing [ ] or ( ) around x/y/z or lowercase letter to mean rotations.

**Comment by lgarron** [comment]
> I would be in favour of allowing [ ] or ( ) around x/y/z or lowercase letter to mean rotations.

I am against this. FMC isn't meant to be an easy or forgiving event, and I think we can expect people who want to take it seriously to learn what notation is allowed. We're never going to allow everything that people use informally, and I'd prefer to keep what we have right now.

I'll take a stab at rethinking the FMC sheet this week.

**Comment by Laura-O** [comment]
Well, if we want to make FMC a tough event for people who take it seriously, we should forbid any cube rotations... 

Anyway, adding counter-examples or explaining what is **not** allowed is bad practice as long as it's not necessary. There will always be people who misinterpret or skip negations, so the result could be worse than without counter-examples.

I would suggest giving clear definitions for the notation in a "this and only this"-style: "Cube rotations must be written either as x, y, z or as small letters in square brackets" (or something similar).

**Comment by lgarron** [comment]
> Well, if we want to make FMC a tough event for people who take it seriously, we should forbid any cube rotations...

I *would* support this. I certainly tried to remove the redundancy of having *two* rotation notations in the past. ;-)

> I would suggest giving clear definitions for the notation in a "this and only this"-style: "Cube rotations must be written either as x, y, z or as small letters in square brackets" (or something similar).

I think this is a good starting point. However, there are some good international ways to signal *NOT*, and I think we should at least consider a design with them.

**Comment by lgarron** [comment]
Alright, I've come up with three proposals.

## Option 1

This does not require any change the Regulations. It simply lists a useful set of moves, and cautions not to use anything else unless you know Article 12. Unfortunately, it has the downside that it doesn't list all possible moves. Judges/solution checkers may not realize that `Rw`, `x`, `1Rw`, or `3Rw` are permitted, and that `U2'` and `U'2` are not.

![2 notations lenient - full sheet](https://user-images.githubusercontent.com/248078/29019833-c1d451e0-7b14-11e7-925d-ad45b8a0b8d5.png)

## Option 2:
Change the Regulations to disallow [outer block moves](https://www.worldcubeassociation.org/regulations/#12a2) for FMC. This allows us to list exactly all possible moves. If the still ask, we can tell competitors/judges/solution checkers that any notation (or an variant) is not permitted unless it is literally printed in the instructions.

![3 notations strict - full sheet](https://user-images.githubusercontent.com/248078/29019834-c40ec94a-7b14-11e7-954e-8d4a53d3b4e2.png)

## Option 3:
Like option 2, but we also remove axis rotations in the pursuit of simplicity.

![2 notations strict - full sheet](https://user-images.githubusercontent.com/248078/29019837-c679ab3c-7b14-11e7-889c-341573a8e77f.png)


Some notes:
- Even though I don't like `[f]` notation (I never see it outside of FMC Regulations), it is simpler to understand, so I've preferred that in these examples. I'd be happy to prefer `x`, `y`, `z` if we think competitors would also prefer it.
- I've removed the "Rotations x, y, and z follow R, U, and F" bullet, but laid out the moves so that the columns match.
- None of the bullets list negative examples – I tried to design and word everything to discourage the competition from using anything not listed on the page (unless they are sure it is valid).

Option 1 is easier to implement, since it doesn't involve changing the Regulations. However, I prefer either of the other options if other WRC members are willing to make a change to FMC Regs.

**Comment by Claster** [comment]
How about we go the first option and list all possible moves, but not in the beautiful table, rather in the raw line?
Btw, we do need some changes in Regulations, at least to clarify that [x] and (x) are not allowed.

**Comment by lgarron** [comment]
> How about we go the first option and list all possible moves, but not in the beautiful table, rather in the raw line?

I can try that. I don't like the old, crowded approach of using commas to separate moves, but I'll try to think of something.

> Btw, we do need some changes in Regulations, at least to clarify that [x] and (x) are not allowed.
Do you mean [E2c++](https://www.worldcubeassociation.org/regulations/guidelines.html#E2c++) or a new Regulation?

**Comment by Laura-O** [comment]
I think this discussion is moving a bit to a "we change regulations because... why not?"-direction.

The problem is that the regulations do not allow a notation which is frequently used by competitors, and delegates or FMC-checkers apply the regulations inconsistently.

Thinking a bit further, the origin of the problem is that this bracket-notation is confusing and people obviously have problems to remember the correct form or just think that's not relevant. Maybe that's because a non-programmer doesn't see a difference between them?
However, I also see no point in making a difference here. We don't want to distinguish function calls and arrays, so why should we care about it?

The simplest solution would be that all cube rotations must be written in small letters and put in [brackets](https://en.wikipedia.org/wiki/Bracket).

So the valid notation would be:
- Face moves: `F, B, R, L, U, D`
- Cube rotations: small letters put in brackets: `f, b, r, l, u, d` in  `[  ], ( ), { }, < >`
- Wide moves: Face moves + w: `Fw, Bw, Rw, Lw, Uw, Dw`
- Invert moves and rotations by adding an apostrophe
- Double moves and rotations by adding a 2

And as the x, y, z-notation is widely used it should be allowed as well.

**Comment by lgarron** [comment]
> I think this discussion is moving a bit to a "we change regulations because... why not?"-direction.

I disagree. There are several benefits to reducing the amount of valid notation for FMC, and I think that this can go hand-in-hand with trying to write down a small, clear set of moves on the FMC sheet. I think it's very reasonable to restrict FMC to face moves and a single kind of rotation notation, because this is sufficient for most competitors to express their solutions fairly directly. (If we exclude rotations, then a competitor with rotations in a draft solution has to remap all subsequent moves to remove the rotation. But they can locally convert convert moves like Rw into [r] L.)

We're never going to allow all notation which is frequently used by competitors, else we should be allowing `r` for `Rw` or commutator/conjugate notation.

> Thinking a bit further, the origin of the problem is that this bracket-notation is confusing and people obviously have problems to remember the correct form or just think that's not relevant.

Do you think my proposals above help with that? They state "only the exact notation listed below" (and "one move per bar").

> The simplest solution would be that all cube rotations must be written in small letters and put in brackets.

This would also be a change in the Regulations, right?
Could you specify a way to describe exactly how your bullets should be interpreted? Are any of the following valid?

- `[f b r]`
- `{f b>`
- `1Fw` / `2Fw` / `3Fw`
- `U2'` / `U'2` / `U''2'`
- `{r}2`
- `(R')`
- `<R u>`

I think it would be tricky to specify exactly which rules can be combined, which is why I'm strongly in favor of reducing the permitted moves to a concrete, enumerated set.

**Comment by Laura-O** [comment]
> I disagree. There are several benefits to reducing the amount of valid notation for FMC, and I think that this can go hand-in-hand with trying to write down a small, clear set of moves on the FMC sheet. I think it's very reasonable to restrict FMC to face moves and a single kind of rotation notation, because this is sufficient for most competitors to express their solutions fairly directly. (If we exclude rotations, then a competitor with rotations in a draft solution has to remap all subsequent moves to remove the rotation. But they can locally convert convert moves like Rw into [r] L.)

Well, the only thing I am suggesting is to allow other types of brackets. I am not suggesting any weird notation, removing restrictions or something else.

I am not sure if you are misinterpreting the bullet points, but the intention was to briefly summarize the current regulations to show that the moves we allow are reasonable and consistent.
This was not meant as a draft for the FMC sheet or even a suggestion for the regulations.

I don't have a perfect wording for this now, but I think we only need to add a clarification that cube rotations may also be written in a pair of curly brackets, a pair of round brackets or a pair of angle brackets. We do not have to change the guideline about allowed moves ([E2c++](https://www.worldcubeassociation.org/regulations/guidelines.html#E2c++)).

I have probably (double-)checked several 1000 FMC solutions in the last years and allowing an "any bracket" -notation for cube rotations is definitely nothing that makes checking slower or adds room for interpretation.
My main annoyance is usually bad handwriting and people intentionally spreading a sub 40 solution over all 8 lines. But I guess that's nothing that should be covered in the regulations...

**Comment by lgarron** [comment]
I am strongly against allowing new kinds of brackets, but it seems like that will be a longer discussion.

Is there any chance we would be able to agree on an update to the instructions without changing the Regulations? @jfly wants to cut a new TNoodle release, and I think updating FMC sheet instructions is overdue.

**Comment by pedrosino** [comment]
How about we say something like "anything that is not defined in Article 12 as OBTM will not be considered when checking your solution"?

If we were to change the instructions, I would very much like them to be translate-able

**Comment by lgarron** [comment]
> How about we say something like "anything that is not defined in Article 12 as OBTM will not be considered when checking your solution"?

I think our current problem is that no one has Article 12 memorized, and our FMC sheet instructions do a bad job of conveying exactly what moves are allowed per Article 12.

**Comment by lgarron** [comment]
@Laura-O: Would you be alright with updating the FMC sheet but keeping current Regulations?

We can use bullets instead of table formatting if everyone prefers that.

**Comment by Laura-O** [comment]
> @Laura-O:  Would you be alright with updating the FMC sheet but keeping current Regulations?

Yes, sure. As long as it's a reasonable update. 🙂

**Comment by lgarron** [comment]
WRC members: would you all be alright with implementing [option 1](https://github.com/thewca/wca-regulations/issues/456#issuecomment-320611555) for now?

(Using plain text formatting if the table layout implementation turns out to be a little messy.)

**Comment by Laura-O** [comment]
@lgarron Yep, I think that's a good start.
I wouldn't worry about judges/checkers: I think we should assume that these are usually people who know the notation.

**Comment by AlbertoPdRF** [comment]
I also think that option 1 is a good start.

**Comment by kingmathyall** [comment]
Option 1 looks like a good start!

**Comment by Claster** [comment]
Yes, sounds good.
That doesn't require any changes of Regulations, does it? Only in TNoodle.

**Comment by Laura-O** [comment]
@lgarron We are still waiting for your PR...

**Comment by Laura-O** [comment]
Closing this for now as we have a new FMC sheet - let's hope things get better. 😄

**Comment by lgarron** [comment]
We still disagree about whether `[R]`, `(R)`, or `{r}` automatically DNFs a solution under the current Regulations, right?
