### ISSUE TITLE
A1a2++ Clarification on possible combinations for combined cumulative time limits

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#457]
[A1a2++](https://www.worldcubeassociation.org/regulations/guidelines.html#A1a2++) is not clear about what can be combined with a cumulative time limit: 
> Cumulative time limits may be enforced for a single event or a combination of events.

Time limits are enforced for rounds or a combination of rounds, not for events. This should be clarified.
Additionally, we should decide whether it should be possible to use cumulative limits for a combination of rounds of the same event (like "15 minutes for BLD attempts in round 1 and 2").

I don't have a strong opinion, but I think it's not the intention of this regulation to combine limits of several rounds of one event. Furthermore, this could cause weird cases/results if competitors have reached the combined time limit and still proceed to the next round.

**Comment by KitClement** [comment]
I have used a combined time limit for multiple events with small BLD
competitions. We had multiple "sessions" for 4bld and 5bld between other
events during the day, and you could choose which attempts to do during
each session. The combined time limit for the two events was chosen based
on the amount of total time in all sessions. Having this combined time
limit gave people flexibility to focus on one of the two events without
costing us loads of time.

**Comment by jfly** [comment]
@KitClement, nitpicking on your comment. You said:

> The combined time limit for the two events...

Would it be more accurate to say "The combined time limit for 4bld round 1 and 5bld round 1"? (In this particular case, they're the same thing, because you probably only had 1 round of 4bld and 5bld.) The point I'm trying to make here is that you don't assign time limits to events, because events can have multiple rounds. For events that usually have exactly 1 round, it's easy to forget this.

**Comment by KitClement** [comment]
Yep, got it -- I realized that I totally misread Laura's post. Rounds makes
total sense.

**Comment by AlbertoPdRF** [comment]
Fixed already!
