### ISSUE TITLE
Cumulative time limits and timer fails

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#462]
What happens when there is a cumulative time limit, and the timer got reset or did not start? "Time elapsed" is not always clear in these cases.

**Comment by Laura-O** [comment]
Well, if there is a timer malfunction, an extra attempt should be granted. If the timer didn't start and it's the fault of the competitor the judge should notice that immediately, so the result should be DNF and the time elapsed is 0:00.00.

In all other cases there are several ways to estimate the time:
* If the judge says it was "5 minutes and something" it should be written down as 5:59 (worst possible result).
* If another competitor started at the same time and didn't finish the attempt yet, you can use this time as an estimation.
* If the event started at exactly 14:00 and it's 14:05 when this incident happens you could use this.

So that's an incident that should be handled at the delegate's discretion and which can't be defined in the regulations as there are so many different possibilities.

**Comment by xsrvmy** [comment]
Don' feel like opening another issue for this, but here's another situation with cumulative limits:

A competitor gets a +2 for a bad timer start on a 3bf attempt, then Dnfs. Does the +2 count towards the cumulative limit, or does the dnf 'override' it?

**Comment by Laura-O** [comment]
> A1a2) Cumulative time limits may be enforced (e.g. 3 results with a cumulative time limit of 20 minutes). The time elapsed in a DNF result counts towards the cumulative time limit.

So no, only the elapsed time counts.
