### ISSUE TITLE
Rule C1 might be too strict.

### ISSUE THREAD

**Issue by priazz** [thewca/wca-regulations#464]
Good evening. 
I would like to make a complaint about rule C1c, due to an incident that occurred to me in the final round of the 3x3 one-handed event at Verona open (September 24th 2017). I was on my third solve and after a really good start I dropped my cube due to a lockup; the cube fell on my right hand (I solve with left) which was placed still on the stackmat timer. I then proceeded in picking up the cube with my left hand and kept on solving; it ended up being the second 13s solve in the average (this would have given me a really good shot on getting NR average which is 14.8s). The judge appealed to rule C1c that states: "During the solve, once a competitor touches the puzzle with one hand, they must not touch the puzzle with the other hand. Penalty: disqualification of the attempt (DNF)." Because of my right hand, the cube rolled further away from me (giving me a major disadvantage in time waste); I didn't attempt to use my right hand to stop the cube because I thought that C1c concerned only intentional gestures, and I didn't want the penalty to occur. I let everything happen.
I then asked the delegates' help (there were Lorenzo Vigani Poli, Matteo provasi and Simone Cantarelli) to solve this problem: Lorenzo seemed to agree with my claims, but was reminded by Matteo that rule C1c doesn't allow exceptions and that in past occasions similar cases were ruled as DNFs (this was later confirmed by old reports), so he told me "even if you were right, these are the rules, so we must play by them"; Simone wasn't even summoned because we felt there was no need. My solve was converted into a DNF: because of 2n3 I accepted the decision and went on with the average, very upset and distracted, and ended up getting very bad times.
I think C1c should be revisited in order to prevent incidents like this from happening in the future: I didn't attempt to cheat, nor did I get any unfair advantage form it. Rule C3b1 states that "If a puzzle defect occurs, and parts of the puzzle briefly come in contact with other body parts without the competitor's intention, this is not considered touching the puzzle, at the discretion of the judge." Isn't a very bad lockup a puzzle defect? maybe if I had been solving with two hands, the same lockup would have ended up in a pop (two hands, double the force and more intense the grip); I didn't have any way to prevent the puzzle form hitting me. Moreover, rule 5a gives "Examples of puzzle defects", not all of them, so a cube drop might as well be taken into consideration. I feel that if the rules are there to make competitions fair for everyone, things like this should not happen: I felt robbed and cheated (not by someone in particular), I hope we can make one handed better and more enjoyable for everyone. There are very specific rules in the WCA Regulations, that were shaped with time; I feel like this one should be developed as well since it can be misleading and can appear to be irrational.
I'm sorry if I made any mistakes or if I sounded inappropriate: english is not my main language. I hope you can take this into consideration.
Best regards.

Tommaso Raposio (WCAID 2014RAPO01)

**Comment by lgarron** [comment]
> Isn't a very bad lockup a puzzle defect?

It seems clear to me that the incident was handled correctly as far as the current Regulations are concerned, since the only examples of puzzle defects in 5a) involve fully detached or misplaced parts. I don't think we can expect Delegates to consistently rule that lock-ups are covered by 5a) unless we actually modify the Regulations to do so. Cube drops are definitely not a *puzzle* defect by themselves.

I don't think it would be practical to come up with a good definition of "lock-up" and expect judges to observe and handle incidents consistently, and I don't think there is a strong need for this.

However, I think it is *reasonable* to propose that `C1b3)` be extended to other accidental interaction. Do you have a proposal for how we might extend it to cases where the competitor accidentally touches the cube but "clearly" wasn't trying to cheat, without allowing subtle abuse or requiring subjectivity by the judge?
In particular, such a proposal should also make clear what happens if the competitor *catches* a cube, e.g. because it is falling off the table or because it is otherwise out of control. Note that in this case the competitor's intention can be hard to infer (they can claim it was by instinct). But arguably they have acted to gain an advantage, since they don't have to retrieve or assemble the cube from the a more out-of-control situation.

**Comment by priazz** [comment]
I do agree on the correct handlement of the case and didn't want to make a point on cube drops being puzzle defects; it was just to show that it could be interpreted in different ways (and rules should not).
An incident similar to mine occurred to Charlie Stark (2014STAR05) and the solve was reasonably allowed by Evan Liu and James Molloy because he apparently didn't touch the cube with his right hand, even if from the video it looks like it, and he didn't gain any advantage from the situation. In the comments under the video, there were very different opinions: 
"I went through these rules months ago Lucas might say that it's 100% not a defect but many of the delegates who argue dropping into the lap is a DNF are arguing by the letter of the regulations so I allowed myself the same liberty. the cube dropping out of my hand is misplacing parts, all the parts. and so you can argue it's a defect. 
I think this case should probably be a DNF because of precedence but also think it's kind of shitty and the regs should be changed but I'm not smart enough to think of a precise way to state them that would allow it and not be open to abuse.";
"Delegates are human and interpret the rules in different ways. He didn't actively try and do moves with the other hand, he just dropped the cube. Therefore I decided to be a decent human being and allow the solve.";
"it's your responsibility to not drop the cube. you are assisting your solve with other parts of your body by keeping it from falling. you don't have to make a turn to help the solve. the cube is only allowed to touch one hand, and the surface. that's it. It's a DNF if any other part of your body touches the cube. that's my thoughts";
"C1b says only one hand and is not specific about whether that excludes just the other hand or the rest of the body but C1b3 gives an exception allowing pieces of a defective cube to touch other parts of the body. This would suggest that the intention of C1b is to exclude the rest of the body.";
....
This variety of opinions suggests the urge of clarification. 

After a day of intense thinking, the only reasonable solution I came up with is this (I'm writing a list and not a set of possible rules because I'm not 100% sure of my english skills): 
The competitor should be allowed to use only one hand to touch the cube while the other must be placed on the timer; many people do it already and this will prevent the intentional or unintentional use of the other hand and therefore cheating. 
The unused hand should not be considered part of the table in order to prevent table-abuse-like situations. 
The unused hand can obviously be used during inspection, but then must be still al throughout the solve. 
If the cube drops we can have three cases:
a) the cube drops on the table/ground; current rules apply perfectly.
b) the cube drops on the body (is the term lap correct?); Since we cannot instantly disappear, we should be good human beings and take this aspect into consideration.  If you are not actively touching the cube with your body, you should not be given penalties. You may argue that you can get a time advantage if the cube doesn't drop on the floor, but luck is a factor in speed cubing (scrambles, skips...) therefore I don't see the problem.
c) the cube drops on the right hand (this happened to me and the other most "famous" case I know happened to Mats Valk). If the competitor is forced to keep the hand on the timer, it will be considered the same as case b. You can't cheat if your hand is standing still on the timer. 
Puzzle defect rules are kept as they are.
The right hand must be lifted from the timer only when it is clear that the cube is out of reach; the competitor can't use it to prevent the cube from falling since they would gain an advantage (unless obviously we are in case c and the cube doesn't fall because it touched the hand, if this happens it still can be considered luck). 
In case of cube drop, the unused hand must be placed on the timer before continuing with the solve.
In case of puzzle defect, the hand can be lifted from the timer but must be placed back before continuing with the solve.
C1c gets affected by what I suggested in the other points.
When the incident happened to me, I tried to be strong enough to control my instinct of catching the cube, because I immediately associated this idea with the fact that I wasn't cheating and that I wasn't getting any advantage. With the unused hand on the timer, the claim of "acting by instinct" doesn't matter anymore because it will be against the rules and therefore we won't have similar cases judged differently depending on the delegate. Also the judge's work will be easier and less affected by subjectivity: The hand is either on the timer, or is not; the cube falls on the body and the solve can continue regardless of his opinion...
If the participant catches the cube with his solving hand, he will rightfully gain an advantage from one of his skills: reflexes. If the participant for example closes his legs and prevents the cube from falling, I think it should be also considered legal. It should not be when the cube is caught with the non solving hand, because he would have lifted it from the timer with the cube still in reach.

I would also be ok with changing the rules the other way round, but only if these rules were to be followed in every competition. In my case, if I were at a comp with other delegates rather than Lorenzo and Matteo (which handled the situation very well), I could have had my solve allowed. I really disagree with unequal treatment, especially If I am the one following the rules; i think anyone can relate to this. If we for example stated that "no body part whatsoever apart from the solving hand can touch the cube. penalty DNF, no exceptions allowed", I would be ok with it; it would be a bit of a harsh solution but I would be ok with it: it's simple,reasonable and not open to interpretation. Good rules or bad rules are in the end rules. We can't all be emperor Giustiniano and make perfect laws but I am surprised no-one had come up with complaints before. If I was unclear I am willing to rearticulate my thoughts, but I hope my ideas came trough.
Thank you for your time and consideration.

Tommaso Raposio

**Comment by pedrosino** [comment]
Hi Tommaso

I see your points and think you have a valid concern. However your proposal of requiring the other hand to be on the timer is not a good idea. Many people already do this, but many do not. I don't think we should establish a rule on what people must do with their body parts while solving. We have muscular memory and being forced to adopt a certain position may affect the solving.

Also, keeping your other hand on the timer is dangerous because if you accidentally touch the sensor with the solving hand, the timer will stop and you'll get a DNF.

The part about the cube falling on the lap is indeed controversial. I like your argument that the competitor cannot get out of the way that quickly. Maybe we could rewrite the Regulations so that only intentional touching is punished.

**Comment by kingmathyall** [comment]
Hi Tommaso
I agree that this needs to either have a guideline added or have the regulation changed altogether. I do have some issues with some of what you recommended as a whole. It should not be required that the competitor keeps their other hand on the timer at all times as this essentially doubles the chances of accidentally stopping the timer with your arm. I think there should be a guideline added worded similar to the following:

C1b+ Clarification: If the puzzle accidentally comes in contact with another body part, so long as it was accidental and did not give the competitor any advantage over any other competitor. Whether this is accidental is up to the discretion of the judge.
C1b+ Example: If the puzzle falls off the table and the competitor reaches their other hand out to catch the puzzle, the attempt will be disqualified since they purposefully reached their hand out to prevent the puzzle from falling.
C1b+ Example: If the puzzle falls into the lap of the competitor, the competitor must pick up the cube with the same hand they are solving with and may continue the solve with no penalty from the fall so long as the the judge deems it an accidental drop.

What are your thoughts on these?

**Comment by Mollerz** [comment]
As per referencing #465 I would prefer to make the regulation more specific in regards to touching the cube with other parts of the body during the attempt. I recommend a change to the following:

C1b) During the solve, the puzzle must only have contact with one hand and the surface. Penalty: disqualification of the attempt (DNF).

This means if it is dropped in the lap, or touches any other part of the body, then it is a DNF by default, whether or not the touch was intentional or not. It might be harsher but the regulation would be much easier to apply.

**Comment by AlbertoPdRF** [comment]
I prefer the change proposed by @Mollerz as it's simplier and it's sure that
it will be enforced equally around the world.

El 29 sept. 2017 10:46, "James" <notifications@github.com> escribió:

As per referencing #465
<https://github.com/thewca/wca-regulations/issues/465> I would prefer to
make the regulation more specific in regards to touching the cube with
other parts of the body during the attempt. I recommend a change to the
following:

C1b) During the solve, the puzzle must only have contact with one hand and
the surface. Penalty: disqualification of the attempt (DNF).

This means if it is dropped in the lap, or touches any other part of the
body, then it is a DNF by default, whether or not the touch was intentional
or not. It might be harsher but the regulation would be much easier to
apply.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thewca/wca-regulations/issues/464#issuecomment-333069108>,
or mute the thread

**Comment by jfly** [comment]
@Mollerz, I'm not opposed to your suggestion, but I'd like to discuss some scenarios in light of your proposal:

1. Dropping the cube on the ground, picking it up with one hand and doing the rest of your solve. Previously ok, now DNF.
2. Dropping the cube on the table and it touches the stackmat on the way down (such as Mats Valk's famous 5th solve from WC2013). Previously ok, now DNF, because [7f1d](https://www.worldcubeassociation.org/regulations/#7f1d) very clearly states that "The timer is not considered a part of the surface.".
3. Popping and having one piece fall on the ground. Placing the rest of the cube on the surface, picking up the popped piece and reassembling the cube on the surface and continuing your solve. Previously ok, now DNF.
4. Two center caps pop off and land on the ground. Picking up both those center caps and reassembling the cube to continue your solve. Previously ok, now DNF?
5. One center cap pops off and lands on the ground. Picking up that center cap and reassembling the cube to continue your solve. Previously ok, now DNF? (I included this one alongside 4 because it seems like a likely thing for beginners to do: they don't know what's okay, so they go ahead and reassemble the cube more than is strictly necessary because they don't want to risk a DNF)

**Comment by pedrosino** [comment]
Agreed with @jfly here...

Unintentional falling of the cube to the ground/timer/over a still hand should not be a DNF automatically...

The cube falling on the lap is a tricky one. As I said, we can't expect the competitor to move out of the way in a split second...on the other side, if the cube fell out of the body, it probably hits the ground and may have a worse fate. But this is dictated by luck, I think, so shouldn't be penalised.

**Comment by Mollerz** [comment]
Ah I see I have made an oversight that @jfly has certainly picked up on. Yes I would think it would be fine if the cube were to be dropped and bounce off the mat, table, etc. Akin to Feliks' WR [video](https://www.youtube.com/watch?v=r2H-cnti8GI) where he drops it, rolls off the side of the table and continues.

How do we solve these two issues whilst keeping the regulation simple?

**Comment by kingmathyall** [comment]
The only changes below are a change to C1b and an addition of C1b4. Wording might need to be changed slightly, but let me know what you think. I believe that could not result in all DNFs in the case of drops, or accidental cube drops in a lab, so long as the judge deems it accidental. 


C1b) During the solve, the puzzle must touch only the stack-mat, surface, and must not intentionally touch any part of the body other than one hand. Penalty: disqualification of the attempt (DNF).
       C1b2) If a puzzle defect occurs, and the competitor chooses to repair it, they must repair it using only the solving hand. Penalty: disqualification of the attempt (DNF).
       C1b3) If a puzzle defect occurs, and parts of the puzzle briefly come in contact with other body parts without the competitor's intention, this is not considered touching the puzzle, at the discretion of the judge.
       C1b4) If the puzzle falls, and the puzzles comes in contact with other body parts, the competitor must pick up the puzzle with the solving hand and continue solving so long as the drop/contact is unintentional at the discretion of the judge.

Addressing all of the issues Jeremy brought up:
1. Dropping the cube on the ground, picking it up with one hand and doing the rest of your solve. Still okay, so long as it was unintentional.
2. Dropping the cube on the table and it touches the stackmat on the way down (such as Mats Valk's famous 5th solve from WC2013). Still okay as it states it's okay to touch the timer or stackmat. 
3. Popping and having one piece fall on the ground. Placing the rest of the cube on the surface, picking up the popped piece and reassembling the cube on the surface and continuing your solve. Still okay.
4. Two center caps pop off and land on the ground. Picking up both those center caps and reassembling the cube to continue your solve. Still okay.
5. One center cap pops off and lands on the ground. Picking up that center cap and reassembling the cube to continue your solve. Still okay.

**Comment by xsrvmy** [comment]
I strongly support explicitly specifying that the cube can touch the ground during a solve, as the likelihood of a cube sliding off the table following a drop is dependent on the location of the solving station as well as the width of the table.

However, I think whether dropping the cube on other body parts is allowed need more consideration. For instance, a competitor may instinctively block the cube with the other hand/arm if it falls off the table.

**Comment by BrandonMikel** [comment]
I like Matthew’s proposal. I think it allows for non intentional contact between the cube and other body parts. I think the current regulations are too strict and that his proposal would be more fair. 

At KCubing 2017, there was an incident where the competitor unintentionally fumbled the cube during OH and it hit his chest before he caught it with his solving hand. It will have to be changed to a DNF due to the current regulations.

**Comment by SAuroux** [comment]
Hm, the main problem I see from many of the proposed modifications to C1b is that aspects that are currently fine for all events (touching the floor or timer) are unintentionally ruled out. How about simply keeping C1b and C1b2 as is and instead generalizing C1b3 (basically just remove the puzzle defect part)?

C1b) During the solve, the competitor must use only one hand to touch the puzzle. Penalty: disqualification of the attempt (DNF).
C1b2) If a puzzle defect occurs, and the competitor chooses to repair it, they must repair it using only the solving hand. Penalty: disqualification of the attempt (DNF).
**C1b3) If the puzzle (or parts of the puzzle) briefly come in contact with other body parts without the competitor's intention and without causing moves made, this is not considered touching the puzzle, at the discretion of the judge.**

**Comment by lgarron** [comment]
> C1b3) If the puzzle (or parts of the puzzle) briefly come in contact with other body parts without the competitor's intention and without causing moves made, this is not considered touching the puzzle, at the discretion of the judge.

Somehow "this is not considered touching" sounds like doubletalk to me. How about changing "touch" to "operate" throughout those three Regulations?

**Comment by kingmathyall** [comment]
I like the addition of C1b3, and would also want to keep the addition of C1b4, but would want the wording to be changed to the following:

C1b) During the solve, the competitor must use only one hand to manipulate the puzzle. Penalty: disqualification of the attempt (DNF).
C1b2) If a puzzle defect occurs, and the competitor chooses to repair it, they must repair it using only the solving hand. Penalty: disqualification of the attempt (DNF).
C1b3) If a puzzle defect occurs, and parts of the puzzle briefly come in contact with other body parts without the competitor's intention, this is not considered manipulating the puzzle, at the discretion of the judge.
C1b4) If the puzzle falls, and the puzzles comes in contact with other body parts, the competitor must pick up the puzzle with the solving hand and continue solving so long as the drop/contact was unintentional and so long as no moves were made, at the discretion of the judge.

I chose "manipulate" as it's the word used in the regs regarding feet solved and I feel like the restrictiveness of WF is similar to that of OH.

**Comment by Laura-O** [comment]
@kingmathyall Why did you close without a PR?
