### ISSUE TITLE
Remove Qualification Rounds?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#49]
Ron asked us not to remove them for 2013, but they're hardly ever used.

---

[Delegate email, December 08, 2013](https://groups.google.com/forum/#!topic/wca-delegates/iue2cPOSc0U)

**Comment by lgarron** [comment]
# Proposal (December 07, 2013)

**Remove qualification rounds.**
View exact proposed changes: https://github.com/cubing/wca-documents/compare/qualification-rounds

## Pros

Removing qualifications rounds would:
- Simplify the Regulations a bit (we can remove all of [9r](https://www.worldcubeassociation.org/regulations/#9r), and I'm always a fan of removing unneeded Regulations).
- Make all events to be consistent: every competitor an event proceeds through rounds in the same way.
- Not really change how competitions are run: Qualification rounds have only been used at two competitions since 2010.
  - [AsianChampionship2012](https://www.worldcubeassociation.org/results/c.php?i=AsianChampionship2012): qualification rounds could have been replaced with combined finals .
  - [RabbitAndTurtle2013](https://www.worldcubeassociation.org/results/c.php?i=RabbitAndTurtle2013): the qualification round for 3x3x3 was basically a first round that some fast competitors skipped.

## Cons

As far as I understand, the main reasons for a qualification round are:
- A qualification rounds round allows more competitors to participate in an event.
- A qualification round allows new competitors a chance to participate in large championship (that may require pre-qualification otherwise). See [9r+](https://www.worldcubeassociation.org/regulations/guidelines.html#9r+)

But these competitors can just be added to the first round. If there isn't enough time to give slow competitors all their attempts, the first round can be turned into a combined round. Thus, _qualification rounds, in their current format, don't really save time versus other options_ (and therefore, don't really allow more competitors). The 2013 World Championships ran fine with 580 competitors and no qualification rounds, and [very few competitions have had even 1/3 as many competitors](https://www.worldcubeassociation.org/results/statistics.php#most_persons).

Another possible argument:
- A qualification rounds allows (once-)fast competitors guaranteed entry into the first round, and extra solves for newcomers.

However, I don't think anyone would argue that there is a significant need for this.

**Comment by okayamat** [comment]
I'd like to comment on the competitions I participated in.
- AsianChampionship2012: qualification rounds could have been replaced with combined finals .

The qualification rounds were held on Friday, and the first rounds were held on Saturday.
Simple replacement could not be done. If replaced, all the competitors must go to the comp
from Friday, but thanks to the qualification rounds, (already) qualified competitors enjoyed
sightseeings or something fun on Friday (or arrived there on Friday) instead of the competition.
- RabbitAndTurtle2013: the qualification round for 3x3x3 was basically a first round that some fast competitors skipped.

IIRC, the intention of the qualification round was that 1) saving a time, and 2) making a chance
for (relatively) slow competitors to set "multiple", "average" records. One of the purposes of the
organizer was holding beginner-friendly competition. Some of beginners (especially in Japan)
feel abashed if super-fast cubers are solving next to them, or in the same round, which has kept
them away from attending a competition. As one way to remove the psychological barrier, the
organizer chose the qualification round, where only non-fast cubers participated.

I don't intend to oppose this proposal, but just add information on this.

**Comment by lgarron** [comment]
That's great feedback; thanks for sharing some specifics. :-)

Although those are valid reasons, every other competition in the last three years has been able to run without them. Some thoughts:
- We don't currently have a prohibition against holding rounds over days. If it is strongly desirable to to split competitors in groups across two days for the reason mentioned above, the Board could approve it.
- The psychological barrier reminds me of the arguments for having separate age categories. While it might be a good idea to encourage certain cubers to compete, it hasn't been significant enough to warrant us restructuring our round formats.

I know there aren't exact numbers, but I'm also curious: How many competitors felt comfortable _showing up at all_ because of the format, and how many _would have shown up anyhow, but felt more comfortable_ because of it?
In the US, I usually find that cubers are afraid to compete because they think they are too slow. Competitions themselves can still be intimidating, but fast cubers are usually nice and encouraging.

**Comment by okayamat** [comment]
- I see, I confirmed the change of 9l) from 2012's to 2013's.
- Yes, I don't think that all competitions should have such policy/spirit, but I think it's all right some competitions do.

I am not the organizer, and as you expected I'm not sure about the numbers/percentage of such competitors.
Sorry for that.

In Japan as well, I think it (they think they are too slow to compete against others) is one of the reasons for
not coming to the comp. The point described above (super-fast cubers around them) may be also one of the
reasons. Maybe there are other reasons. The organizer might have thought that if removing one of the reasons
motivates some newcomers, the competition is viewed as a success.
Yes, fast cubers are nice and encouraging for some competitors in Japan as well, even for some beginners,
but just not for all.

(Again, I don't intend to oppose this proposal, and I don't claim that all competitions should do like that.)

**Comment by lgarron** [comment]
Although @okayamat's comments are good to keep in mind, the fact that there is delegate support (and no opposition) for this, and that they have only been used twice in the last three years, should be sufficient groups. I'm going to go ahead and merge the change.
