### ISSUE TITLE
4g1) addition of 5x5

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#502]
Should 5x5x5 cube be added to the events in 4g1) so that it is not necessary for the scrambles to be correct?

As of now it is one of the harder event to hold due to the restriction that scrambles have to be right.

This is also not considered a scramble dependent event.

**Comment by Laura-O** [comment]
I do consider 5x5x5 a scramble dependent event. A partly solved center (which happens from time to time with generated scrambles) clearly gives you an advantage.

There also is a proof that it's possible to prepare 5x5 solves: [https://youtu.be/89GpRik3q48](https://youtu.be/89GpRik3q48), so adding 5x5 to 4g1) could give room for cheating.

**Comment by Jambrose777** [comment]
isn't the same true for 6x6, 7x7, and Megaminx?

**Comment by Laura-O** [comment]
In general, yes. However, a higher movecount for solving means that the advantage through a lucky start is smaller and it's more difficult to prepare scrambles.

Additionally, what I forgot in my first reply: I think scrambling 5x5 is much easier than 6x6 and 7x7. Moves are either single or double slice. I assume most scrambling mistakes on larger cubes happen because people accidentally do a 2Rw instead of a 3Rw and vice-versa.
When I scramble these puzzles and concentrate on it, I can do ~99% of 5x5  and ~90% of 6x6 and 7x7 scrambles correctly. 

In general, I would rather suggest removing 4g1) completely instead of adding more puzzles.

**Comment by Laura-O** [comment]
Closing this as I see no requirement for a change here.
