### ISSUE TITLE
Explicitly state that choosing not to repair a defect should not give an advantage. 

### ISSUE THREAD

**Issue by AlphaSheep** [thewca/wca-regulations#533]
Based on a question raised [here](https://www.speedsolving.com/forum/threads/one-answer-wca-competition-and-regulations-question-thread.50221/page-47#post-1272344):

> If a center cap falls off during the memorisation phase of blindfolded events, am I allowed to not put the cap back, and use the missing center cap to my advantage during the solving phase?
> Nothing in the regulations dictates that puzzle defects must be fixed immediately.

**Comment by AlphaSheep** [comment]
The regulations give the competitor a choice whether to repair the puzzle

> 5b) If a puzzle defect occurs during an attempt, the competitor may choose to either repair the defect and continue the attempt, or to stop the attempt.

And state that the repair should not give an advantage

> 5b2) Any repair to a puzzle must not give the competitor any advantage in solving the puzzle. Penalty: disqualification of the attempt (DNF).

I think a regulation (or maybe just a clarification in the guidelines) should explicitly state that choosing to continue without repairing should also not give an advantage. I think it's although worth thinking about the timing, e.g. choosing to wait until the end of a blindfolded attempt to repair a popped centre cap.

**Comment by xsrvmy** [comment]
It appear that this would have unintended consequences. For example, an edge cap pop on the yuxin 7x7 gives the solver a slight recognition advantage but is virtually impossible to fix properly without glue or some sort of filler. Personally, I would prefer adding the following instead, so that only BLD pops are affected:

If a piece pops out during a blindfolded solve, the competitor must not continue turning the puzzle until the pop is fixed. Penalty: DNF. Exception: for multiple blindfolded solving, only the puzzle is considered unsolved.

**Comment by AlexKatyukov** [comment]
I think, there are
> 5b2) Any repair to a puzzle must not give the competitor any advantage in solving the puzzle. Penalty: disqualification of the attempt (DNF).

But this item is good for Guideline (5b2+), for example, as in **xsrvmy** post.
