### ISSUE TITLE
Regulation A6e) Revisement

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#534]
> A6e) After releasing the puzzle, the competitor must not touch or move the puzzle until the judge has inspected the puzzle. Penalty: disqualification of the attempt (DNF). Exception: If no moves have been applied, a time penalty (+2 seconds) may be assigned instead, at the discretion of the judge.

There are 2 issues with this regulation:

1) "until the judge has inspected the puzzle" is very ambiguous. 
When does the judge inspect the puzzle? Are they able to inspect the puzzle without seeing all sides? How long does it take? When can the competitor be sure that the judge has inspected the puzzle? This creates unfair solving conditions as some judges may be more attentive than others and can inspect the puzzle faster than others.
Example: At CubingUSA Nationals 2017 3x3 Finals, Lucas Etter's solve 4: https://www.youtube.com/watch?v=YSo8w1yPetE&feature=youtu.be&t=1h22m12s the judge stated that he inspected the puzzle in the half second before the competitor touched the puzzle, no penalty was awarded for A6e.

One possible soultion would be to change the regulation to until the judge has _signed the scorecard_.

2) "If no moves have been applied, a time penalty (+2 seconds) may be assigned instead"
This regulation should read "If no moves have been applied, a time penalty (+2 seconds) may be assigned **instead of a DNF**"
_Many_ delegates have misinterpreted this regulation in this way and award no penalty because the +2 may be awarded.

**Comment by xsrvmy** [comment]
1. I believe that "inspected" the puzzle refers to the judge telling the competitor that the cube is "OK" (A7a). However, that regulation is often not followed unless the result is a +2 or if the event is BLD.\
I think the best way to handle this is to allow the competitor to touch the puzzle after the judge starts recording the time, after he calls "OK", or after he explicitly allows the competitor to do so (in case of an incident).
2. The fix is definitely needed. Also, there appears to be ambiguity in what the phrase "at the discretion of the judge" modifies - Does it modify the entire sentence, or just which penalty to assign? The latter interpretation does not seem correct. Perhaps "at the discretion of the judge" should be moved to the start of the sentence.

**Comment by julesDesjardin** [comment]
1. Clarifying this can indeed be a good way to ensure fairness and consistency between judges (I personally would have given Lucas a +2 without any doubt since I am quite strict on this rule).
I like the "until the judge has signed the scorecard", but I'd add "or the judge explicitly tells the competitor" (I've asked many times my judge if I could pick my cube after the solve, for example to show a friend an alg I used or something like this, and most of the time the judge hadn't finished writing)
2. I never thought this could be misinterpreted, but it's actually quite obvious now that you say it. It is worth adding this at least in the guidelines. (the rule could also be rewritten the other way around, saying "it's a +2, but if a move has been applied it is a DNF")

**Comment by kotarot** [comment]
I also agree with adding some words to fix ambiguity like 2 !

Also, related to #793 , Jules Desjardin said in a WRC email recently that we could allow video proof as an exception to A6e. I also think the issue here is the "If no moves have been applied" part. How can we detect the "no moves"? Before the judge inspects the puzzle state, no one knows if no moves were applied or not. I think video evidence that Jules mentioned could be one of the reasonable evidence if they have recorded a video. If they don't have the video, we have no proof for judging movements, and it cannot be helped with a +2 sec penalty.

**Comment by xsrvmy** [comment]
The difference is that to decide whether or not a move has been made, looking only at three sides is enough (if the puzzle is not in a DNF state). Inspecting the puzzle to check if it's solved requires checking the other aides as well. So there isn't really a problem.
The more problematic situation is when the competitor touches a puzzle too close to 45 degrees off.

**Comment by UnderwaterCuber** [comment]
#200

**Comment by Samuel-Baird** [comment]
This got added to regulations 2019 - initial triage but it never got implemented into the regulations? 

@lgarron

**Comment by UnderwaterCuber** [comment]
@lgarron @Ivan-Brigidano 
Bump

**Comment by Ivan-Brigidano** [comment]
@UnderwaterCuber thanks for pinning us. I'm aware of this and we may include it on the final 2020 Regulations draft.

**Comment by Samuel-Baird** [comment]
> @UnderwaterCuber thanks for pinning us. I'm aware of this and we may include it on the final 2020 Regulations draft.

Can’t seem to find it anywhere in the draft. I’m guessing it’s not being implemented this year?

**Comment by Ivan-Brigidano** [comment]
> > @UnderwaterCuber thanks for pinning us. I'm aware of this and we may include it on the final 2020 Regulations draft.
> 
> Can’t seem to find it anywhere in the draft. I’m guessing it’s not being implemented this year?

The final 2020 Regulations draft isn't made yet ;-) It will probably be included as a "systematic lenient" rule.
