### ISSUE TITLE
Megaminx scrambling correctness

### ISSUE THREAD

**Issue by zhouyichen** [thewca/wca-regulations#541]
Refer to [4g1](https://www.worldcubeassociation.org/regulations/#4g1) of the regulation. I think most of us can agree that we should ensure correctness of scrambling 4x4 and 5x5, while it is relatively okay to scramble 6x6 and 7x7 wrongly. By the same standard (I would say it is solving time, which shorter events are more dependent on the scrambled state), Megaminx should be in-between 4x4 and 5x5, which means Megaminx should be one of the event which correct scrambling has to be enforced.

**Comment by xsrvmy** [comment]
Pros:
- An easy star is arguably more beneficial to the solver than an easy 5x5 center. From personal experience, I get more easy stars on megaminx than stupid 5x5 starts (eg. solved 2x3 block).
- The number of states on megaminx and 5x5 are similar.

Cons:
- The scramble of a megaminx is 70 moves long, which is longer than the scramble for a 5x5. Even though only 6 different moves are used, it is easier to make accidental turns when scrambling a loose/flimsy megaminx compared to any 5x5.
- When a non-mf8 color scheme is used, scramble checking is harder due to the number of colors.
- When the correctness of a scramble actually matters (eg. solved star), the delegate can enforce scramble checking under the current 4g1.

**Comment by cubewhiz** [comment]
I'd take this a step further and suggest eliminating 4g1 completely. Having Regulation 4g1 implies that the scramble state of those puzzles does not matter. If people are careful, they won't make mistakes when scrambling those events.

**Comment by lgarron** [comment]
Note that Megaminx was individually added to 4g1. See fcba23224f58b3dd4caa57ceaff8aa0b8970c0bf and #61.

**Comment by lgarron** [comment]
> I'd take this a step further and suggest eliminating 4g1 completely. Having Regulation 4g1 implies that the scramble state of those puzzles does not matter. If people are careful, they won't make mistakes when scrambling those events.

I would make a strong bet that removing 9g1 will result in delegates/organizers/scramblers ignoring the regulation and sweeping mis-scrambles under the rug. I think it's pointless to remove 9g1 unless we have stronger measures to detect and prevent mis-scrambles (#184, #214).

(I'm not saying that we *can't* make sure all scrambles are correct. I'm saying that competitions don't currently have the discipline, and most delegates don't have the diligence to enforce it.)

**Comment by lgarron** [comment]
Possible compromise: require correct scrambles for final rounds, at least at competitions of a certain caliber. (e.g. at least X competitors, or regional championship events)

**Comment by Laura-O** [comment]
The problem with Megaminx is that it's clearly the WCA puzzle which is most difficult to scramble correctly. The moves are monotonous, so it just happens that scramblers miss one move or just can't remember if they had already done a move or not.

My best guess would be that ~60-70% of the Megaminx scrambles are not correct. For 6x6x6 and 7x7x7 it's probably around 80-85%, even if scramblers are experienced and pay attention.
Solving and scrambling these puzzles again takes a lot of time, especially when all fast competitors are competing in a round. So removing 9g1 completely would make these rounds take significantly more time than before.
I am not saying that time is more important than correct scrambling, I just think there needs to be some compromise.

I agree with Lucas that scrambles should be 100% correct in major competitions, but I think that's already a standard (although it's not mentioned in the regulations).

**Comment by xsrvmy** [comment]
I'm thinking about the retrospective scramble checking a bit: Has there been any incidence where an incorrect scramble on 4x4 or 5x5 has lead to a incident regarding any kind of record? Also, it is hard to confirm a correct scramble or a misscramble for bigger puzzles if the solve is not recorded on video, since the start on a misscramble can possibly be the same or too similar for the competitor to notice a difference.

**Comment by timreyn** [comment]
Another complication with megaminx is that checking scrambles is harder.  This is because there are twelve colors and many different color schemes (this is less true than it used to be, but there is still much less consistency than on cubes).  Each face might only have one or two colors that appear more than once, and the scrambler often needs to figure out what those colors should be on the puzzle they're scrambling.

**Comment by xsrvmy** [comment]
Comment on @timreyn 

Another problem is that a U or U' done in the wrong orientation affects a small number of pieces and may be missed in the scramble checking process.

**Comment by zhouyichen** [comment]
I do agree that correctly scrambling Megaminx is a bit harder than 5x5. However, I think the decision about whether to enforce correct scrambling should be focused on the impact of incorrect scramble, which is larger for Megaminx. While mega is harder to scramble, maybe we can develop some new scrambling methods to make it easier?

I also agree with the idea Lucas mentioned, that we should enforce correct scrambling for at least the final rounds (probably should apply to 6x6 and 7x7 as well?). And I think this needs to be mentioned in the regulation so that people will follow.

**Comment by xsrvmy** [comment]
Maybe a guideline can be added instead of a regulation. Otherwise, consider this scenario:

A competitor gets a misscramble that is very similar to the correct scramble, and the scramblers fail to notice.

After the competition, the video is uploaded and the scramble is discovered to be incorrect.

Now the issue has to go to the WRC because it is obviously unfair to DNF a single result in a mean due to a scrambling error.

**Comment by lgarron** [comment]
> Maybe a guideline can be added instead of a regulation.

Are you proposing to add something between "must be scrambled correctly" and "may be scrambled incorrectly", i.e. "should be scrambled correctly, but mis-scrambles may be allowed at the discretion of the Delegate (and/or WRC)"? I think that is not a good idea.

For one, we have a strong precedent to DNF all known attempts with incorrect scrambles (OH WR excepted, but that is under discussion).

In addition, I don't think Megaminx warrants special treatment special here – I don't think there is a good way to judge if a scramble was significantly easier than intended, so the only way to make consistent decisions would be to always DNF Megaminx mis-scrambles or never to do so. But then there's no point in leaving it to anyone's discretion instead of specifying it in 4g1.

> Now the issue has to go to the WRC because it is obviously unfair to DNF a single result in a mean due to a scrambling error.

It's not more unfair than for any other puzzles (though I agree mis-scrambles are a big problem in that they are unfairly outside the competitor's control). Also note that Megaminx [does not have a "Mean of X" round format](https://www.worldcubeassociation.org/regulations/#9b1) since 2010.

**Comment by xsrvmy** [comment]
I was referring to 6 and 7 for the DNF and the mean.

My point here is that a competitor should not lose a competition for breaking a record on a mis-scramble for 6x6 or 7x7.

Requiring correct scrambles for 6 and 7 also possibly makes the event take significantly longer at smaller competitions.

**Comment by Laura-O** [comment]
> I also agree with the idea Lucas mentioned, that we should enforce correct scrambling for at least the final rounds (probably should apply to 6x6 and 7x7 as well?). And I think this needs to be mentioned in the regulation so that people will follow.

Requiring that 6x6x6 and 7x7x7 are correctly scrambled in the final rounds affects the vast majority of competitions as most competitions only have one round.

In general, I think discussing this is quite pointless at the moment. Of course, we should be aware of this problem and pay attention to correct scrambling at major competitions (and as I said, I think this is what we already do). However, it's currently not realistic to enforce correct scrambling of Megaminx, 6x6x6, and 7x7x7 as it would more or less destroy schedules.

Making a simple calculation: just imagine there are 12 people in a 7x7x7 final, the fastest solver available needs ~4:30 and the scramble accuracy is 70%. This would take nearly 50 minutes of additional solving time. Yes, that's quite simplified and there might be more than one available solver and you could also let competitors solve their cubes, but I think it still illustrates the problem.
