### ISSUE TITLE
Change 3k2 for illegal puzzles used in Multi BLD

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#545]
Currently, according to 3k2, an attempt is a DNF when an illegal puzzle was used.

This is quite harsh for Multi BLD, so we should add an exception that using an illegal puzzle does not disqualify the whole attempt but only the specific puzzle.

**Comment by xsrvmy** [comment]
I believe this should also apply to accidentally making a move during memorization.

Also, if a competitor is clearly trying to cheat by using an illegal puzzle, he should still be disqualified.

**Comment by lgarron** [comment]
Sounds good. Do you think we should make this "DNF by default, but count the individual puzzle as unsolved instead at the judge's discretion"? Or just make it the default action, and leave stronger consequences for cheating to 2k?

**Comment by lgarron** [comment]
> Also, if a competitor is clearly trying to cheat by using an illegal puzzle, he should still be disqualified.

Also note that [2k2](https://www.worldcubeassociation.org/regulations/#2k2) covers this:

> - 2k) At the discretion of the WCA Delegate, a competitor may be disqualified from some events (a single event, multiple events, or all events) if the competitor:
>   - 2k1) Fails to check in or register in time for the competition.
>   - 2k2) Is suspected of cheating or defrauding the officials during the competition.
>     - 2k2a) The WCA Delegate may disqualify any suspected results.

**Comment by lgarron** [comment]
Also see #536.

**Comment by kingmathyall** [comment]
I think that there should be an exception with MBLD. Any non-permitted puzzles being used in a MBLD attempt will simply be considered unsolved at the end of the attempt. If someone accidentally has a cube with a logo on it in a 30 cube attempt, DNFing the attempt all together is way too harsh, in my opinion.

I think if someone is found using a non-permitted puzzle, that shouldn't be a factor toward asking for an extra due to it being at the fault of the competitor. Otherwise, I could see this potentially being abused if it were allowed to be grounds for an extra.
