### ISSUE TITLE
MBLD times under 10 minutes are rounded to the nearest second

### ISSUE THREAD

**Issue by MatteoColombo** [thewca/wca-regulations#549]
I was looking Kaijun's results and I noticed that the time of his last MBLD attempt (2/2 in 58 seconds) was rounded to the nearest second, but [rule 9f1](https://www.worldcubeassociation.org/regulations/#9f1) states that all the timed results under 10 minutes are measured and truncated to the nearest hundredth of a second.

I couldn't find any Regulation (or Guideline) about this except 9f1 and 9f2.  Did I miss it or it doesn't exist?

**Comment by xsrvmy** [comment]
Looks like all multibld attempts do not have centiseconds in the results.

**Comment by jfly** [comment]
It is not actually possible for our database to store 333mbf results with a finer granularity than seconds. https://www.worldcubeassociation.org/results/misc/export.html has a decent explanation of how this works.

**Comment by lgarron** [comment]
Sounds like we have two options:

1) Make the Regs match our results: update the Regs to specify that all multi BLD results are truncated to seconds.
2) Make the results match our Regs: require all future results under 10 minutes to record centiseconds. Either grandfather all old results, or change all X:YZ results under 10 minutes to X:YZ.99

I think 1) sounds much better, since it is much more practical.

In addition, centiseconds for multi BLD:
- are less accurate if a stopwatch was used,
- would only be needed for results under 10 minutes, which is less likely to affect results that need to be distinguished (E.g. for podium)
- are even less necessary than for other events to distinguish results, since time only matters after number of cubes solved/attempted.

So I think we should do 1). Anyone up for making a PR?

**Comment by ronaldmansveld** [comment]
One comment: Instead of truncating to seconds, I'd round to seconds, just like we do for results > 10 minutes to keep everything consistent.
