### ISSUE TITLE
7h1 doesn't name a penalty.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#552]
7h1 doesn't say whether the penalty is disqualification from the event, or something else:

> 7h1) The organization team may require that a competitor who has been called to compete must remain within the Competitors Area until the competitor has finished all attempts for the round.

A [Ponikva Open 2018 incident](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wca-wrc/88NGMpBOjio/0p8S6CXdAQAJ) may use 7h1 to prevent counting a competitor's solves from counting as official, but  7h1 doesn't actually clarify whether this should technically mean DNF/DNS/no result.

**Comment by julesDesjardin** [comment]
Since this rule can be broken during the round, it makes no sense in my opinion to put it as "no result". Therefore I'm in favor of a disqualification of the event, with 2j2) applying as always. This also means that if the team forgets to announce it (but thinks it's implicit) and a competitor doesn't comply, results should stay.

**Comment by lgarron** [comment]
> Therefore I'm in favor of a disqualification of the event, with 2j2) applying as always.

That leaves a question: do we count this as "cheating"?

If a competitor leaves the competitors area after 4 solves (in an avg5 round), they will still have an average. Should they be disqualified from the event (which prevents them from advancing, even if the average is otherwise good enough), or just the round?
