### ISSUE TITLE
Require competitor limit for all competitions

### ISSUE THREAD

**Issue by cubewhiz** [thewca/wca-regulations#553]
Currently Regulation Z4 allows for a limit to the number of competitors for a competition with Board approval. However, I believe that all competitions should require a competitor limit. Every competition has a limit to the number of competitors it can accommodate due to space, equipment, staff, and other factors. I can think of no good reason to make the competitor limit optional, especially as the WCA continues to grow.

**Comment by pedrosino** [comment]
I agree with that. Not listing a limit does not make sense, since you can't just have 1 million people.

**Comment by lgarron** [comment]
Do you think this should have a default limit, like time limits?

**Comment by xsrvmy** [comment]
What about competitions with per event limits for every event?

**Comment by cubewhiz** [comment]
@lgarron I think it would be best to just make the competitor limit field required on the competition form
@xsrvmy even those competitions are limited by the sum of the per event limits

**Comment by cubewhiz** [comment]
To give some background to this issue, there have been a few instances in which delegates have requested limits after first confirming without one because they received more registrations than expected (usually in areas that have had only a few small competitions).

**Comment by Jambrose777** [comment]
Just want to chime in and say I'm all for this. Typically asking delegates to add one just in case will result in one being added. I haven't come across any reason ever not to have one since there is always some factor to limit the capacity that a competition can hold.

**Comment by lgarron** [comment]
@SAuroux Is it easy to gather per-year counts on the # of competitions that do vs. don't have total competitor limits?

If we're trending to a high fraction of competitions with limits, I think we should just enact this. If not, I'd like to know which Delegates we should talk to about why they don't tend to have them (and if they have any reason they want to keep it that way).

**Comment by Jambrose777** [comment]
From what I can find, that functionality was added in 2017.

In 2018: 902 have competitor limits, 140 do not.
in 2019 12 have competitor limits, 0 do not.

So far, while announcing competitions, its always strongly recommended to add a competitor limit if there is not one. Generally the reason for not having one is "we don't expect to get many competitors". Which isn't a great argument since this opens the door to "I'd like to add a competitor limit, we received more competitors than expected".

Here is 2017 broken down by month once the feature was added:

month | competitorLimit | COUNT(*) 
-- | -- | --
7 | NO | 54
7 | HAS | 17
8 | NO | 34
8 | HAS | 41
9 | NO | 39
9 | HAS | 46
10 | NO | 26
10 | HAS | 62
11 | NO | 22
11 | HAS | 63
12 | NO | 28
12 | HAS | 62

Here is 2018, broken down by month:

month | competitorLimit | COUNT(*) 
-- | -- | -- 
1 | NO | 18
1 | HAS | 61
2 | NO | 17
2 | HAS | 59
3 | NO | 20
3 | HAS | 93
4 | NO | 19
4 | HAS | 93
5 | NO | 16
5 | HAS | 73
6 | NO | 12
6 | HAS | 97
7 | NO | 11
7 | HAS | 77
8 | NO | 12
8 | HAS | 77
9 | NO | 4
9 | HAS | 98
10 | NO | 7
10 | HAS | 88
11 | NO | 4
11 | HAS | 63
12 | HAS | 23

**Comment by Jambrose777** [comment]
Specific delegates with more than 2 competitions without competitor limits in 2018:

name | count(*)
-- | --
Ronan Felipe Jorge | 14
Tomi Ronkainen | 8
Hikmət Mürsəlzadə | 8
Daniel James | 7
Akula Pavan Kumar | 7
Akash Rupela | 7
Ujjawal Pabreja | 6
Cendy Cahyo Rahmat | 6
Hari Anirudh | 5
Olli Vikstedt | 5
Reto Bubendorf | 5
Somya Srivastava | 5
Rafael Werneck de Andrade Cinoto | 4
Marlon de V. Marques | 4
Gustavo Riveiro | 4
Pablo Eduardo Nikolais Teixeira Bonifácio da Silva | 4
Rodrigo Ugarte | 4
Liam Orovec | 4
Niko Ronkainen | 4
Mohamed Ali Bizid | 3
Novianto Pambudi | 3
Brandon Harnish | 3
Trịnh Nguyên Anh | 3
Alexander Olleta del Molino | 3

**Comment by cubewhiz** [comment]
Will this be included in the 2019 Regulations?

**Comment by AlbertoPdRF** [comment]
Article Z should be moved to the Competition Requirements Policy entirely in my opinion, please take a look at the draft.

**Comment by lgarron** [comment]
> Article Z should be moved to the Competition Requirements Policy entirely in my opinion, please take a look at the draft.

Is the draft sufficiently ready that we can move things out of the Regulations?
(Can you make a PR for that?)

**Comment by AlbertoPdRF** [comment]
It is now. I'll take care of the PR!

**Comment by AlbertoPdRF** [comment]
This is handled now in https://github.com/thewca/wca-documents/pull/40, so I'm closing this issue!
