### ISSUE TITLE
Exception in A6g does not match the main regulation

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#556]
```
A6g) The judge determines whether the puzzle is solved. They must not make moves or align faces when examining the puzzle. Exception: For Clock, the judge will usually need to pick up the puzzle to verify both faces.
```
Why is the exception about picking up the puzzle when the main regulation only forbids the judge from moving/aligning the puzzle?

**Comment by Laura-O** [comment]
It's in the guideline:
_A6g+) ADDITION While the judge is determining whether to assign a penalty for misalignment, they should not touch the puzzle._

That's indeed a bit chaotic and difficult to grasp. Maybe we should fix that by adding the guideline to the regulation.

**Comment by xsrvmy** [comment]
Should MBLD be added to the exception as well? On most/all large MBLD attempts I have seen in videos, the judges pick up every puzzle.

**Comment by pedrosino** [comment]
Agreed with both points. I'll try to come up with a proposal.

**Comment by julesDesjardin** [comment]
MBLD is not enough, the judge must also pick up the puzzle to check centers in 4BLD and 5BLD. To some extent they should also pick it up for all cubes >=4 because of centers, although solving methods usually don't leave room for an unsolved center to go unnoticed.

Removing the exception and allowing the judge to pick up the cube, but only after "determining whether to assign a penalty for misalignment" (to quote current A6g+), would be simpler.

**Comment by pedrosino** [comment]
I updated the PR.

**Comment by dancing-jules** [comment]
@julesDesjardin - why is it necessary for 4bld and 5bld? If 5 sides are solved the 6th one must be solved as well - independently of cube size.
