### ISSUE TITLE
Change round format when a round has started

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/wca-regulations#558]
Right now, the format of a round can be changed when it has started. Real example: a Besr of 2 3x3x3 Fewest Moves round can be changed to a Mean of 3 3x3x3 Fewest Moves round adding one attempt after one or the two attempts are over, which is permitted.

This is unfair as some competitors might have taken certain decisions or strategies given the round format, and can also lead to an abuse of power. So, I'm proposing to explicitly forbid this in the Regulations.

**Comment by xsrvmy** [comment]
What about tentative FMC or MBLD attempt?

**Comment by lgarron** [comment]
Do you feel that time limits have the same issues? https://www.worldcubeassociation.org/regulations/guidelines.html#A1a3+

Or just round formats?

**Comment by AlbertoPdRF** [comment]
> What about tentative FMC or MBLD attempt?

This would work the same as how a tentative round or event works right now. 

> Do you feel that time limits have the same issues? https://www.worldcubeassociation.org/regulations/guidelines.html#A1a3+
> 
> Or just round formats?

I think that A1a3) already makes people consider heavily if changing a time limit is appropriate, so I don't feel that time limits have the same issues right now.

**Comment by SAuroux** [comment]
> This would work the same as how a tentative round or event works right now.

The problem is: this won't work with the regulation you propose - unless the given regulation has an explicit exception for "tentative attempts" of FMC/MBF, which then again requires to explain what a tentative event/attempt is in the first place.

(Personally, I don't think that there should be such a thing as "tentative FMC/MBF attempts" at all.)

**Comment by cubewhiz** [comment]
I agree with Sebastien. I don't like the idea of tentative FMC or MBLD attempts.

For most events, changing the format of a round is impossible without Board approval because there is only one acceptable format. For the remaining events, changing the format changes the strategy, so I do not think that should be allowed in those events either.

@lgarron I do feel that time limits should not be changed after a round has begun. It can create some very unfair situations.

**Comment by lgarron** [comment]
@AlbertoPdRF: are there recent examples where this ability was (mis)used?

If not, this sounds like a good trade for low flexibility impact against professionalism and fairness.

**Comment by HippolyteM** [comment]
@lgarron : Yes, this issue was created following an incident (which should not be made public here).

I agree with Sébastien and cubewhiz that it is totally unfair to add an attempt for a round once the attempt has started.

(I would also go further and say that so-called "tentative events" have no reasons to exist at all, but that's another topic)

**Comment by HippolyteM** [comment]
There's also something that we may face with such a regulation (even if I strongly support it): The need to cancel an attempt due to any particular situation. Thus we would also have to add an exception stating that the format can be changed by canceling an individually scheduled attempt at the discretion of the delegat. Only adding one attempt would be forbidden.

**Comment by theoleinad** [comment]
I also agree that a round should not be added once the round has started.
Example:
FMC bo2:
Attempt 1, I get 30 moves which place me in first.
Attempt 2, I try to get sub-30 but dnf in the attempt, however I already won Gold if no one gets a 30 in attempt 2, and since there’s no mean, I don’t search for a 37 move solution.
They open attempt 3, and some guys get a mean, they knocked me out from podium and I ended up at 14th place...

This is possible with current regulations, right?
We need to fix this before any issues arise.
