### ISSUE TITLE
DNF due to turning off the Alarm during 4BLD

### ISSUE THREAD

**Issue by vinitnalhe** [thewca/wca-regulations#567]
Hi @all,
During 4BLD  round, 3rd solve at Indian Nationals 2018, my cell phone was being used as a timer (since I average way above 10 minutes, time that stackmat timer can record). My phone was kept on Airplane mode as soon as I entered the solving room.

While I was memorising the cube my alarm started ringing withing a second I swiped it off(instinctive reaction so that others arent disturbed during blindfolded round). I completed the solve the times were noted and the Delegate in the room didnt object about it.
Some time later I was given a DNF on that solve stating regulation 2i

> 2i) While competing, competitors must not use electronics or audio equipment (e.g. cell phones, MP3 players, dictaphones, additional lighting).

Firstly I wasn't using any electronic device. My cellphone was being used as a timer (I just tuned the alarm off).
Secondly  what would have happened if the alarm was let to ring and I didnt turn it off, disturbing other participants?

**Comment by akashrupela** [comment]
Thanks Vinit for opening this up. This indeed was a very difficult incident
to handle.
@ All, i was one of the delegates who made the call that this should mostly
be a DNF, similar to Max Park and Alexandre Carlier's solves of interacting
with electronic devices like a camera/phone. What makes this different is
that the phone was also running the timer and not turning off alarm may
disturb other competitors, however this was done by Vinit himself without
asking a judge/delegate to do that with a good intent and instinct. We are
also going to mention this in the competition report.

It is obviously clear that Vinit had no bad intent (just like some other
results that were disqualified by 2i), however due to it being really
similar to how WCA regulations have handled similar cases, we decided that
a DNF was the right course of action. I would definitely like to hear what
others think of this decision and we can revert the decision if necessary.

Regards
Akash

**Comment by xsrvmy** [comment]
We seem to have another problem: If the phone screen dims during memo, can the competitor tap it to prevent it from sleeping? Also, can the competitor stop the timer (rather than the judge)

**Comment by vinitnalhe** [comment]
Also the comment above by @xsrvmy reminds me of one more incident that happened to me during the 1st attempt of MBLD at the same competition.

Due to shortage of judges in this attempt the judge was shared between me and another participant seated in the row in front of me. The jude was sitting in the front row. I was using a harmonica stand during this attempt. The judge had two stop watches in his hand (one for each participant) and started the attempt on the stopwatch held by him. In between the solve I wanted to check the time so I asked the judge to show me the time, he passed the stopwatch to me which I took (interacted with an electronic device) and kept it on my table. Which again should be a Dnf according to regulation 2i. 
@all Should this be a DNF ??
@akashrupela kindly take note.

**Comment by xsrvmy** [comment]
I don't think stopwatch is considered an electronic device. We used it for fmc in China.

**Comment by lgarron** [comment]
Most phones and stopwatches are electronic devices. If you are using them, you are clearly violating 2i) as written.

I think there are at least two things here:
1. Are there ever circumstances where competitors should be allowed to interact with their phones (without being disqualified)?
2. Are there ever circumstances where competitors should be allowed to interact with competition-provided timers (without being disqualified)?

## 1. Are there ever circumstances where competitors should be allowed to interact with their phones (without being disqualified)?

I think it's *reasonable* to say "no" to 1; it's certainly a very effective avenue for hard-to-detect cheating. I think it's also reasonable to expect competitors to silence their phones and turn off alarms that might be noticeable to them during their attempts.

On the other hand, I would also be interested in a proposal that allows for "honest mistakes" at the expense of allowing some obscure cheating.

A wild idea: Allow interactions like disabling a phone alarm, but add a significant penalty if it happens (e.g. +10 seconds or -1 multi BLD score). We've had a lot of success adding Regulations with a standardized tradeoff of leniency instead of forcing an uncomfortable DNF decision for what is usually an accident.

## 2. Are there ever circumstances where competitors should be allowed to interact with competition-provided stopwatches (without being disqualified)?

As for 2, I do think we need to refine this:
1. **Stackmat timer**. A Stackmat timer is obviously electronic. We should probably note that this is an exception to 2i (if not in a Reg, at least in a Guideline).
2. **FMC**. I've been to quite a few competitions without a wall clock. I've used competition-provided stopwatches on my desk when an FMC wall clock wasn't available (and may have even used my own cell phone for this years ago). This *should* be solvable by requiring more consistent conditions from organizers, either by providing wall clocks or stopwatches. I don't think we should allow using your own phone for timing.
3. **Stopwatch during long attempts**. I think there are two perspectives here: A) we have to trust the competitor a little anyhow, so let them interact with the stopwatch, and B) we can draw an easily enforceable line by saying that the competitor is not allowed to touch the stopwatch, but they should be able to find out the current stopwatch time if they want. (A strawman idea: they have the right to request that the judge place the stopwatch in such a way that the running time is visible to them, else they may ask the judge for the time whenever during the solve they want).

**Comment by danieljames-dj** [comment]
I was a delegate in the BLD room.
In this case, I suggest it not to be DNFed because he just tried to avoid disturbance. The judge was supposed to turn it off. But the case can be the phone is participant’s and judge didn’t turn it off because he/she doesn’t know how to do it. @vinit please tell why the judge didn’t do it, I can’t remember it exactly.

**Comment by vinitnalhe** [comment]
@djdany444  I dont quite remember why judge didnt do it. As a matter of fact i did not request him to do it. As I mentioned earlier, my reaction was instinctive as I immediately jumped to turn off the alarm to avoid any disturbance in the BLD room. I do agree that the right thing to be done in this situation would have been to let the alarm ring and in the mean while explain the judge/call the delegate to turn off the alarm. But my involuntary  instincts could not let the alarm ring for so long and I turn it off.

**Comment by vinitnalhe** [comment]
@lgarron I had a similar point. What about the solves where in the mobile is the stopwatch.
In most of the comps, points 1 and 2 are overlapping where in mobile phones are used to record times rather than stop watches. (In my case mobile phone was being used as a stop watch)
Should mobile phones not be allowed at all to record times for longer events ?

Also in my opinion there should be judge/delegate discretion included in 2i to account for such situations.

**Comment by BhaktijPatil** [comment]
@vinitnalhe @akashrupela do you not think that regulation 2i needs heavy changes? Interacting with an electronic device in so many situations means absolutely nothing. For eg: accidentally touching your tripod, turning on your camera in inspection, pressing the power button on your phone to mute a call and wearing a smartwatch is technically interacting with an electronic device. I suggest that 2i should have an exception where the delegate at the competition or the wca board should be able to decide the legality of the solve. In my opinion , as long as interacting with an electronic device doesn't give a visual/audio output, it cannot help the participant in anyway. So it should be legal to use electronic devices in other ways.

**Comment by Laura-O** [comment]
I don't have the time to write a longer comment here now, but there is one main problem with the issue: I think that it should not be allowed to use the phones of competitors to time their attempts.
We had several cases when judges used their phones to time inspection, which is also something I do not like, but which is acceptable as there is some randomness (i.e., judges use their phone for judging *all* competitors).

I remember we had discussions about forbidding phones at the solving station some time ago (like in several other sports). Maybe we have been too lenient when we decided not to do so - I think this incident shows why it's bad and what situations can arise through that.

Additionally, I think it would be awful to allow switching off an alarm during an attempt. I mean, how is it possible to check whether this is an alarm or friend sending the competitor the correct algorithm?

**Comment by xsrvmy** [comment]
@Laura-O what about phones used as cameras?

As for using phone as BLD timers, I do think that this should be banned. Phones can receive notifications in the middle of an attempt. Stopwatches should be fine though.

**Comment by lgarron** [comment]
> @Laura-O what about phones used as cameras?

[2i2](https://www.worldcubeassociation.org/regulations/#2i2) regulates competitor interaction very strictly, so I think we're good on that.

> I think that it should not be allowed to use the phones of competitors to time their attempts.
> We had several cases when judges used their phones to time inspection, which is also something I do not like, but which is acceptable as there is some randomness (i.e., judges use their phone for judging all competitors).

I will continue to advocate that [cubing.net/inspection](https://www.cubing.net/inspection/) helps me consistently be a better judge. :-)

That said, I think it's probably a good goal to avoid using indivduals' phones as timers for longer attempts. I wasn't actually aware this was done anywhere; do we have data on who does this, and if it would be a burden on any organizers? (Perhaps this should be a delegate poll.)

I think we should be prepared to accommodate organizers who want to use cheap organizer-owned smartphones for creative new ways to run competitions (i.e. custom apps that automatically transfer times to the results system) – but we can discuss that if it comes up.

**Comment by Laura-O** [comment]
I think everything has been said here, so I am closing this.
