### ISSUE TITLE
Clarify whether competitors are allowed to touch or stop stopwatch timers.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#581]
From https://github.com/thewca/wca-regulations/issues/567#issuecomment-392616988

> I think there are two perspectives here: A) we have to trust the competitor a little anyhow, so let them interact with the stopwatch, and B) we can draw an easily enforceable line by saying that the competitor is not allowed to touch the stopwatch, but they should be able to find out the current stopwatch time if they want. (A strawman idea: they have the right to request that the judge place the stopwatch in such a way that the running time is visible to them, else they may ask the judge for the time whenever during the solve they want).

I still think the strawman works:
- The competitor is never allowed to touch the stopwatch.
- If the stopwatch face is not visible to the competitor (when they don't have a blindfold on), they may ask the judge to move it so that they can see the time.

**Comment by lgarron** [comment]
Also see #540.

**Comment by xsrvmy** [comment]
What should happen if the stopwatch is placed in a location that obstructs the arrangement of multi-blind puzzles?

**Comment by xsrvmy** [comment]
Also, what about FMC?

**Comment by kingmathyall** [comment]
I think competitors should be allowed to move the stopwatch once the attempt has begun. I'd say 9 times out of 10, during a big BLD attempt, the judge will start the stopwatch and place it in such a way that the time is upside down to me. The judge often places it down and then immediately goes elsewhere. Rather than wasting precious time calling over the judge and ask them to turn around the stopwatch, I just quickly turn the stopwatch so I can read the time. I don't think this gives any advantage to the competitor.

However, it might need a clarification that the competitor must not interact with the stopwatch in such a way that affects their time (stop/start it quickly to save a few seconds)

**Comment by danielkcsheppard** [comment]
It would cause awful situations if it were disallowed. It's very common for multibld competitors to touch the stopwatch, and I have no doubt that we'd have numerous instances of hour attempts being DNFed because of this non-advantageous infraction.
The competitor would rightly find it really stupid and as Delegate I would find it way too harsh and awful to tell them that it's a DNF.

**Comment by lgarron** [comment]
I would still prefer that we found a way to run competitions so the competitor can peek at the time without easily being able to tamper with the running time, but unfortunately that would either require dedicated judges or new equipment. So at this point I'd rather clarify that the competitor can touch the stopwatch and we can reconsider in the future.

@kingmathyall, could I ask you to draft a change 1) updating 2i to allow touching the stopwatch, and 2) clarifying that the competitor must not tamper with the timer?

**Comment by xsrvmy** [comment]
@lgarron Idea: judge start two stopwatches then take one for time keeping. Competitor can touch the other one.

**Comment by lgarron** [comment]
> @lgarron Idea: judge start two stopwatches then take one for time keeping. Competitor can touch the other one.

I think we can think of lots of clever ideas that work if the organizers plan ahead of time or have more resources (e.g. more judges, more stopwatches, special hardware or apps). However, we need something that works for the competitor no matter what conditions they have for the attempt.

**Comment by Jambrose777** [comment]
Concern:
If the competitor stops their attempt and the judge does not stop the stopwatch timer, now the competitor will be disallowed to stop their attempt on their own.

**Comment by lgarron** [comment]
> If the competitor stops their attempt and the judge does not stop the stopwatch timer, now the competitor will be disallowed to stop their attempt on their own.

Indeed. I think it's important that the judge stops the timer, so that they know they stopped it from a running state.

It's also much simpler to understand "stackmat => competitor manages the timer", "stopwatch => judge manages time".

**Comment by Jambrose777** [comment]
So I could potentially have >5 seconds added to my time due to the judge not stopping the timer and not being reactive? 

With how many comeptitions are run, there is not a single judge designated per competitor, so mistakes like this are very possible.

**Comment by lgarron** [comment]
> With how many comeptitions are run, there is not a single judge designated per competitor, so mistakes like this are very possible.

Then I strongly believe we should run competitions better (or get better technology). I don't think "some competitions schedule their events so they don't have enough resources to run them reliably" is a good excuse. :-/
(It's not a good excuse for mis-scrambles and duplicate scrambles, and it's not a good excuse here.)
