### ISSUE TITLE
What stickers can be used in FMC and how?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#584]
- Can the stickers be different shapes?
- Can they be colored? Patterned? Textured?
- Can you write on them?
- Can they be numbered ahead of time?
  - If so, can they contain more information? Is there a clear boundary for what counts as [assistance](https://www.worldcubeassociation.org/regulations/#A5b)?
- Can you do anything to the puzzles except apply and peel the additional stickers?

Branched out from https://github.com/thewca/wca-regulations/pull/538#issuecomment-405521337

**Comment by xsrvmy** [comment]
"What counts as assistance?"
The wording in the requirement for logos is probably good enough.

**Comment by xsrvmy** [comment]
"Can the stickers be different shapes?" Modern cube sticker sets are different shapes to begin with. If not, they can always be distorted by the competitor.

Also, an additional question: Can you write on the puzzle?

I think disallowing distinguishing the stickers at all partially defeats the purpose of the stickers for insertion finding, especially for anything more than a 3 cycle.

**Comment by theoleinad** [comment]
Checking the reg: 
**E3c) Stickers (self-supplied).**

So they can be any shape. 
Any Color, with pattern or texture.
Yes, we can write on the stickers and we can numbered them before the attempt.
_(Assistance comes from speedsolving not fewest moves solving, so N/A)_
You basically can turn apart the cube, and reassemble if you want, there's no limitations on this.

If we want to clarify, maybe we should just clarify that basic labeled stickers are allowed, I personally use: 
1,2,3...8,9 (corners)
A,B,C,D,E,F (edges)
X, X, X... (free)

So we avoid algorithms written in the stickers... 
(Which I have thought)

Shall we limit number of stickers as well? 
20 sounds enough for one attempt for me... 

Also, we could state that all of this items are upon delegate's approval.

**Comment by Laura-O** [comment]
> Shall we limit number of stickers as well?
> 20 sounds enough for one attempt for me...

Looking forward to adding an hour to each FMC attempt because I have to count the stickers of each competitor first! 😃 

But seriously, any additional restrictions regarding stickers might sound nice in theory but it's completely unrealistic to check that before, and also during an FMC attempt. Competitors often bring several sheets of stickers which makes it impossible to check the texture, color or writings on all of them. I think we all agree that writing down algorithms is a 100% clear case of assistance, so we don't need to discuss this.

Additionally, I'd go with "If it ain't broke don't fix it" and leave this an "anything goes"-regulation as long as we do not find any serious loopholes or inconsistencies which need to be clarified.
