### ISSUE TITLE
Fangshi cubes with both black and white plastic. Competition legal, or no?

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#59]
Fangshi now makes 3x3x3s with a white "body" with black caps, and vice versa. Should it be clear in the regulations whether they are allowed? They've been used in competition before, and they don't appear to give an advantage to solving.

![13704857680](https://f.cloud.github.com/assets/5139750/904886/e049a4dc-fbe2-11e2-9e75-2245e5aca34a.jpg)

**Comment by lgarron** [comment]
The point of the Guidelines is to have clauses about interpretations details like this. This might be just a little too specific to warrant a Guideline, but maybe something along of the lines of "if the cube is weird, the main thing that matters whether pieces can be distinguished and used to your advantage".

(I'm not exactly in favor of a specific list of things because it can get out of date very fast, and we don't have a place to put it. But we _could_ just start adding lists of things so that competitors can easily interpret their Regulations on their own.)

**Comment by shelchang** [comment]
Might want to specifically mention it, at least in the Guidelines. On the
one hand, similar pieces can't be distinguished from each other. On the
other hand, you could argue that it violates the "one uniform color per
side" rule. On the alien third hand, that cube looks ridiculous.

**Comment by sarahstrong314** [comment]
The "one uniform colour per face" rule (3d2) appears to be about sticker colours, not plastic colours. I can't find a regulation that says they're not allowed, but they're questionable since they're a new idea.

I think a list of "weird puzzles" that are allowed and not allowed in the Guidelines would be useful. The regulations don't mention things like like Dayan Megaminxes with ridges either (the only way we know for sure they're allowed is because of Tim's post about them in the WCA forum).

**Comment by lgarron** [comment]
See https://github.com/cubing/wca-documents/issues/13

It doesn't directly address this, but I think should be a sufficient guide for deciding whether these are okay.

**Comment by Laura-O** [comment]
As this is about a rare and old puzzle and the issue is covered by the other issues mentioned above, this can be closed.
