### ISSUE TITLE
Should we change 2c++ "should" to "must"?

### ISSUE THREAD

**Issue by pedrosino** [thewca/wca-regulations#590]
Right now it says:
- 2c++) [ADDITION] Competitors must not provide intentionally misleading information, and returning competitors _**should**_ provide information consistent with past information (e.g. exact name and WCA ID).

But why would we be ok with people giving different information everytime? It's always bad to discover this before the competition or when posting results.
Some will still do it anyway (creating a new account or whatever), but I think maybe changing this to "must" would call people's attention.

**Comment by xsrvmy** [comment]
"Must" does not seem to make sense since both name and country change (especially country).
Also I was personally asked to add my Chinese name when competing in China so that's a factor to consider.
But 'must' definitely should apply to WCA Id

**Comment by Laura-O** [comment]
> "Must" does not seem to make sense since both name and country change (especially country).

If that happens, you do not change your data by just giving different information when registering, but by sending an email to the WRT and providing documents as a proof. Therefore, the information is consistent with past information and I agree with Pedro's proposal.

**Comment by lgarron** [comment]
How about adding "must" and adding a Guideline to clarify what to do if
your name or country have changed?

**Comment by xsrvmy** [comment]
How about:
Returning competitors must provide the same WCAID, and must not change other information (eg. name, country) without approval from the WCA.

On a sidenote, what happens if a competitor changes citizenship in the middle of a year and no longer keeps the original one? Specifically, how does he prove he no longer has the original citizenship? (2e2)

Also is it even possible for the competitor to change name/country through the WCA registration page?

**Comment by lgarron** [comment]
I'm a bit skeptical that modifying the Regulations will make a dent in behaviour, but how about moving some of this to the Regs?

> - 2c2) If a competitor has previously compete, they must provide identity information (name, country, date of birth, and gender) consistent with their WCA profile. If they wish to change their identity information between competitions, they must [contact the WRT as described on the WCA website](link goes here).

We already have a precedent for linking to another page (linking to the scramble program page in 4f), so I think that's fine.

I think this needs some Guidelines, though. They need to cover:
- Specifying what a WCA profile is. (At the moment, a profile with a WCA ID assigned to a competitor after they have results from one competition. This could be associated with a user account on the WCA website – but that is not always the case, since competitions can still have independent registration sites.)
- What if you sign up for a second comp before you have a WCA profile?

And 2e2 should probably link to 2c2.

@pedrosino, how does that sound?

**Comment by pedrosino** [comment]
Similar to you, I'm not confident this will change people's behaviour drastically, but at least this way we would have a regulation (with a must) to point them to.

**Comment by xsrvmy** [comment]
I have a question. Is it OK to allow the competitor to contact the delegate instead of the WCT if the change is minor? (eg. adding local characters in brackets)

**Comment by Laura-O** [comment]
1. You should never contact the WCT in those cases. It's the WCA Results Team, which does the changes.
2. Delegates cannot change names in the database, so the request would go to the WRT anyway.
