### ISSUE TITLE
Orientation in 4d can be ambiguous

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#595]
Right now regulation 4d specifies that white, green and yellow are used to determined orientation. It is not possible to have two shades of white, but what if there are two shades of green or yellow (eg. a megaminx)?

I am suggesting:
- Yellow refers to the lightest yellow shade on the puzzle
- Green refers to the darkest green shade on the puzzle or the darkest adjacent green shade
(If a megaminx had black instead of white, and cream is next to light green but not dark green, does the scrambler use cream and top and light green in front, or instead choose the darkest adjacent color in front? I have personally used a scheme like this before unofficially)

Also, for consistency, should 4d3 specify a default front color? I can see why this was a problem before because colors schemes were not consistent, but nowadays the stock color scheme on any good square 1 would require red to be in front.

**Comment by pedrosino** [comment]
About your first question: NxNxN puzzles and Megaminx are scrambled starting with the white face (if not possible, then the lightest face) on the top and the green face (if not possible, then the darkest adjacent face) on the front.

So if there's no white, but there's cream (and it's the lightest), it would be on top, and then light green on front.

About the second, I don't think we need to add red as default. People can use whatever color they prefer. Some square-1 may not even have a red face.

Perhaps NxNxN cubes have default colors because you can scramble starting on any orientation. This is not true for square-1, so the choice is easier to make.

**Comment by dancing-jules** [comment]
@pedrosino What if there are two different greens next to white? On my custom megaminx color scheme both greens border white.

**Comment by pedrosino** [comment]
@dancing-jules yes, that situation is not clear. By logic I always use the darkest green, but I agree that a guideline should be added as suggested.

**Comment by dancing-jules** [comment]
@pedrosino: instinct also tells me to go with the darker green. But technically it's not covered by the regulations.

**Comment by xsrvmy** [comment]
My question was actually if green refers to darkest adjacent green or the darkest green on the puzzle.
