### ISSUE TITLE
The number 2 has multiple meanings in FMC

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#598]
2Rw is currently valid notation in FMC but can cause ambiguity. For example: U2Rw can mean both U2 Rw and U Rw. This type of situation can arise if the competitor writes on different sheet of paper.
Should we specify that 2Rw is invalid (ie. only Rw is allowed) to avoid this type of situation?

**Comment by lgarron** [comment]
Do you know if this issue happens in practice, especially given the prevalence of FMC sheets?

It's not really a goal of the notation to avoid this ambiguity, but I'm not strongly opposed to changing 12a2 in https://github.com/thewca/wca-regulations/pull/575/files#diff-74877114b316d206b6795d90dfaf17e5R320

**Comment by Laura-O** [comment]
I am strongly opposed. 😄 

Double wide moves are a well-known notation, so we should not remove them. This will only cause unnecessary DNFs.
Additionally, I think we should not make regulations because someone had the idea this could happen. I can't remember I have ever seen such a case and even if that would happen, a resolution is easy: take a ruler and check if the 2 is nearer to the single move or the wide move.

**Comment by lgarron** [comment]
> Double wide moves are a well-known notation, so we should not remove them.

How often have you seen 2Rw as opposed to Rw?

**Comment by Laura-O** [comment]
> How often have you seen 2Rw as opposed to Rw?

Probably way less, maybe 1:10?
I checked old FMC sheets I have at home and found 2 solutions with 2Xw moves in ~50 sheets.

(However, I wouldn't take German FMC solutions as a standard. Compared to other countries, competitors use way fewer cube rotations and wide moves, so this is probably not representative. 😄 )
