### ISSUE TITLE
Are multiple stopwatches allowed?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#600]
We allow a stopwatch as a back up to the Stackmat timer, and it's very clear which timing device to use for the result:

> A1b2) If a time from the Stackmat timer is available, it is the original recorded time. Otherwise, the stopwatch time is the original recorded time.

The multi blind WR used two stopwatches, neither of which was designated as the sole official stopwatch. I think we should either disallow the use of an official backup stopwatch, or specify exactly how they are to be used.

**Comment by capitalcubing** [comment]
Hi,

In my opinion, the main reason to allow use of backup stopwatches is to account for any issues with one stopwatch. For example, a stopwatch may run out of battery or sometimes when organizers do not have enough stopwatches, often a mobile phone is used in place and there have been a few instances of stopwatch accidentally stopping or crashing. It is better to hedge the risk of granting an extra in a big multi attempt for example due to a stopwatch malfunction.

I can think of two approaches:
1. Designate on stopwatch as a primary stopwatch, and use the other one only if there is any issue with the primary.
2. Measure time as (average,min or max)?  of 2 stopwatches.

**Comment by akashrupela** [comment]
Hi,

In my opinion, the main reason to allow use of backup stopwatches is to account for any issues with one stopwatch. For example, a stopwatch may run out of battery or sometimes when organizers do not have enough stopwatches, often a mobile phone is used in place and there have been a few instances of stopwatch accidentally stopping or crashing. It is better to hedge the risk of granting an extra in a big multi attempt for example due to a stopwatch malfunction.

I can think of two approaches: 
1. Designate on stopwatch as a primary stopwatch, and use the other one only if there is any issue with the primary.
2. Measure time as (average,min or max)? of 2 stopwatches.

**Comment by Laura-O** [comment]
Using two stopwatches is not new and also the usual approach for larger attempts in some countries.

I also think we shouldn't see the two stopwatches as the reason for the issue with the MultiBLD WR. It was basically the judge not paying attention and not stopping the stopwatches in the right moment.
Therefore, disallowing a backup stopwatch seems not reasonable here.
