### ISSUE TITLE
Explicitly forbid (or allow) tentative events

### ISSUE THREAD

**Issue by zeecho** [thewca/wca-regulations#614]
Right now some competitions use what we call "tentative events" although the WCA regulations do not say anything about them.

Since the WQAC is currently trying to define what an official competition must have (https://github.com/thewca/wca-regulations/issues/610), I'm wondering what we'll do with tentative events, as I don't see why they exist in the first place. The WQAC seems to want to officially introduce the term with this sentence: "Events may be tentative, tentative events must be listed in the official events". That's why I think now is the good time to talk about this.

I personally think organisers (with the help of their delegate) must be able to provide a realistic schedule. Therefore, why do tentative events exist? If we want to be as fair as possible, I think competitors must know which events will be held at the competition they register for and which events will not. And since we're trying to look more and more professional, I don't get how we can say "our schedule might work but maybe not so I don't know if we'll hold this event or not" (that's exactly what tentative events look to me)

That being said, we all know serious unpredictable issues can occur so we can still have an exception which would let the delegate use their discretion to remove some events but **if and only if** it's an absolute necessity.

What do you guys think? I know US organisers/delegates use tentative events quite often so I'm also interested in having their arguments on this topic.

**Comment by pedrosino** [comment]
I personally prefer adding more rounds of existing events if there's time left at the end.
Some people care a lot about some particular event, and may be tempted to attend a competition if their favourite event is tentative. I don't have any data on how often tentative events actually happen or not. This would be interesting to know.

**Comment by Laura-O** [comment]
> I personally think organisers (with the help of their delegate) must be able to provide a realistic schedule. Therefore, why do tentative events exist? If we want to be as fair as possible, I think competitors must know which events will be held at the competition they register for and which events will not. And since we're trying to look more and more professional, I don't get how we can say "our schedule might work but maybe not so I don't know if we'll hold this event or not" (that's exactly what tentative events look to me)

I generally agree with that while I can also understand that it can be difficult to make a realistic schedule with a large number of newcomers attending a competition. However, this can also be dealt with differently (especially by changing advancement conditions or also, as @pedrosino  mentioned, by adding more rounds).

I think it would also be interesting to hear something from Chinese delegates. They have competitions with > 50% newcomers quite frequently, but as far as I know, they do not use tentative events. Would you mind sharing your experience @Baiqiang ?

**Comment by jfly** [comment]
(I also do not like tentative events)

> However, this can also be dealt with differently (especially by changing advancement conditions or also, as @pedrosino mentioned, by adding more rounds).

Other fun options include:

- Running 3x3x3 finals head to head, and even doing competitor walkups with short bios and music
- Adding fun mystery events
- Ending the competition ahead of schedule

**Comment by FatBoyXPC** [comment]
My competitions frequently have 30% or more newcomers, and tentative events definitely helps us maintain a schedule easier. I also have a very difficult time getting help in general, even when I don't have as many newcomers.

I'm not sure I see the issue with "If we have time we will do these events". The entire reason we have a schedule we can't force to maintain is because we don't have a dedicated staff to be able to run the competition. Even at competitions like CubingUSA Nationals we end up getting behind occasionally.

I think forbidding events is going to have the effect of schedules only getting more strict, which will ultimately mean fewer events happen, and that seems to be against the spirit of the WCA.

**Comment by julesDesjardin** [comment]
(sorry, I'm not answering to your points in order) 

> The entire reason we have a schedule we can't force to maintain is because we don't have a dedicated staff to be able to run the competition. Even at competitions like CubingUSA Nationals we end up getting behind occasionally.

I'm not sure having a dedicated staff can have a direct effect on whether or not you can handle the schedule. I've been to almost non-dedicated-staff comps, even over 100 competitors (only exceptions being Worlds, Euros and French Nats 2018), and these didn't show a tendancy to fail to follow their schedule (obviously some were late, some were ahead, but WC17 and Euro18 also had some delays at some point, and all these delays could be traced back to scheduling errors). As you mention, US Nats also had delays sometimes. 

> I also have a very difficult time getting help in general

Some comps I have been to also lacked a lot of help, but this was usually resolved by threatening competitors to disqualify them for not helping. Such comps were however an exception, in most cases either there is no need to call staff as competitors are gladly helping, or just one call "we need judges" is enough to get a few more judges to fill in the blanks. This might a difference of competition culture across regions. 

> I'm not sure I see the issue with "If we have time we will do these events".

I can imagine how frustrating it must be to have a main event, see a comp at reasonable distance (neither so close you would go anyway, nor so far you wouldn't), but not knowing whether or not you will compete in your main event. Different people give different values to events, so maybe you as a competitor wouldn't care if a random (for you) event was held or not, but someone else is only interested in that event, and are basically going to comps only to compete in that event. I think this effect is also much more higher in the US, where comps are usually 1day comps, with very different sets of events, so a smaller chance to find a comp with your main event than in Europe.

**Comment by Jambrose777** [comment]
> I can imagine how frustrating it must be to have a main event, see a comp at reasonable distance (neither so close you would go anyway, nor so far you wouldn't), but not knowing whether or not you will compete in your main event. Different people give different values to events, so maybe you as a competitor wouldn't care if a random (for you) event was held or not, but someone else is only interested in that event, and are basically going to comps only to compete in that event. I think this effect is also much more higher in the US, where comps are usually 1day comps, with very different sets of events, so a smaller chance to find a comp with your main event than in Europe.

I'd take having my main event be tentative any day over not having it at all. And I know that if I go and help out, that the event will be more likely held since the comp is receiving more help. It's a win win.

**Comment by AlbertoPdRF** [comment]
Going back to the professionality point of view, I can't imagine a tennis tournament where they say: "if volunteers help harder and players finish their individual matches soon, we will host a doubles tournament too".

**Comment by jfly** [comment]
> I'd take having my main event be tentative any day over not having it at all. And I know that if I go and help out, that the event will be more likely held since the comp is receiving more help. It's a win win.

This is not obviously a win win to me. What if someone goes, works really hard throughout the day, and because other people aren't working hard, or just because the schedule was ridiculous in the first place, the tentative event doesn't happen? I could see that being very frustrating.

I think we can summarize the points raised in the this thread so far as:

## Tentative events are good because:
  - "My competitions frequently have 30% or more newcomers, and tentative events definitely helps us maintain a schedule easier" (@fatboyxpc)
  - Getting rid of them means "schedules only getting more strict, which will ultimately mean fewer events happen, and that seems to be against the spirit of the WCA" (@FatBoyXPC)
  - "I'd take having my main event be tentative any day over not having it at all." (@Jambrose777)
  
## Tentative events are bad because:
  - how can they be part of a "realistic schedule" (@zeecho)
  - unfair? (@zeecho) - I (@jfly) personally think this is a stretch. We're not treating people differently here. Everyone is attending the same competition with ultimately the same schedule, we just don't know what it is yet. Maybe people who know the delegate/organizers better get more say in which of 2 tentative events gets to happen if there's only time for 1 event? Or maybe people who know the organizers better will have more insight into what the schedule is *actually* going to look like? We don't have any rules about when tentative events must be announced as "this is actually going to happen" or "this actually is *not* going to happen", do we?
  - unprofessional (@zeecho, @AlbertoPdRF)
  - frustrating to attend a comp hoping to compete in an event and it doesn't happen (@julesDesjardin)

## Why are we even discussing this when there are *other* things you can do with extra time at the competition, such as:
  - adding more rounds of an existing event (@pedrosino)
  - allowing more people into subsequent rounds (@Laura-O)
  - running 3x3x3 finals head to head (@jfly)
  - adding mystery/unofficial events (@jfly)
  - ending the competition ahead of schedule (@jfly)

(apologies if I missed anyone's points) We could go on and debate the validity of some of these points, but I would say that we can all agree there are some positives to tentative events and some negatives. What might be useful to focus on is if the positives outweigh the benefits, *given* that we have other things you can do with extra time at a competition that don't have the negatives of tentative events. Does that sound like a useful way to frame this? @Jambrose777 and @FatBoyXPC, I'd be interested to hear your thoughts.

**Comment by Jambrose777** [comment]
Positive: (somehow left out of any previous comment) Usually with a tentative event you are going to produce a schedule that is more lenient and can allow to get ahead when things go well. Once they do you can add the tentative event. If I was not allowed to use a tentative event anymore, I’d produce a schedule that is stricter just to add the event in; but once things go south I’ll be forced to cut the event.

It’s a matter of I’d rather add an event and make competitors happy about an addition than to remove an event and make competitors upset about a deletion.

Though a competitor may be upset that a tentative event was not held, it was tentative, there was a chance it wouldn’t happen. If they just had their event was removed, they would be much more furious.

I think it’s worth asking @delegates aside from just 2 of us giving comments of our own use. There are many more delegates that use tentative events as well.

**Comment by AlbertoPdRF** [comment]
Is that positive though? It could be interpreted as "instead of doing proper planning and being realistic, I'll add some tentative events and we'll see".

**Comment by julesDesjardin** [comment]
I'll expand my previous point, since we only adopted the point of view of someone who can afford to go to any comp they want, and just is happy with whatever events there are there. 
Assume you only have enough money to do 5 comps in a year. Would you prefer to have 10 available comps with your main as tentative, or 5 that don't hold your main event and 5 that do ?

**Comment by jfly** [comment]
@Jambrose777, I think we can all agree that there are situations where using some extra time to make a tentative event actually happen results in happiness. However, we also have a list of 5 other things you could do with that extra time that would also result in happiness, and don't have any of the downsides of tentative events.

**Comment by lgarron** [comment]
Has anyone here tried to gather opinions from regular competitors yet?

**Comment by julesDesjardin** [comment]
Just asked on 2 international Messenger convs, I got 6 answers : 4 were against (2 Europeans 2 North Americans, since this seems to be a strongly region-related issue I think it's better to add this), 1 North American was OK with it but prefers to have additional rounds, 1 North American prefers tentative events than rounds.

His 2 arguments in favor of tentative events rather than tentative rounds were those ones : 
- not everyone makes those extra rounds (although, as answered by someone else right after, not everyone makes extra events either)
- more events add more variety to the competition

I also got 2 other negative points that weren't said before : 
- Annoying for organizers because everyone keeps asking them if the said event is going to be held or not
- It can be announced very quickly so the event may start without any warmup time

I also got an exact example of "I didn't go there because my main event was tentative but the competition ended up having 2 rounds of it".

I'll edit this if someone adds other points that weren't said here.

We could ask on the big Cyoubx's Friends Facebook group, but serious discussions there usually don't work that well.

**Comment by FatBoyXPC** [comment]
@jfly yeah I like the way you've framed this, however, I'm not sure I agree with "since we have other things we can do with free time let's just ignore tentative events". I know without a doubt (and this goes to @lgarron's comment above) competitors in FL want more events rather than more rounds. Will they object to more rounds? Certainly not. 

@AlbertoPdRF What percent of competitions that you organized went completely according to plan? If that number is less than 100% I think this idea of "Proper planning" is fairly insulting. I've already brought this up, but I suppose it's worth repeating: Even at competitions like CubingUSA Nationals where efficiency is probably the highest I've seen, we still end up behind sometimes. We also end up ahead a lot of the times. Sure, I understand we don't hold "tentative events" there, but that's primarily because we don't need to (since we run all the events...except we've lately not been doing feet). When you have such an experienced staff, a _known_ competitor base (0 newcomers as there are qualifications), with a very carefully planned schedule, and still get ahead, I'm not sure how "proper planning" will fix this "getting ahead" problem. The only reason we don't end up with an extra hour mid day like we do at some comps is because at Nats we call heats up at the designated time due to having multiple stages and rooms, and it's important that Event A Group C happens at the same time as Event B Group A etc.

**Comment by Baiqiang** [comment]
@Laura-O The reasons that Chinese competitions don't have tentative events have been listed above by others: unfair, unprofessional and weird to attend a competition hoping the tentative event to be held. Another reason is China has the biggest amount of competitions in recent years. Holding tentative events makes something unexpectable and it has some trouble dealing registration and refundment.

>It could be interpreted as "instead of doing proper planning and being realistic, I'll add some tentative events and we'll see".

@AlbertoPdRF I agree with you about this. Proper schedule is better than hoping it will get advanced to hold tentative events.

**Comment by Claster** [comment]
I feel the phrase "it is unprofessional" is often used in our community when people are talking about something they personally don't like :P

Having tentative events is as "unprofessional" as having imperfect schedules. However, imperfect schedules, or rather schedules that are not followed, happen here and there, this can happen for many reasons, out of your control and sometimes unforeseeably.

Adding more rounds of existing events instead of tentative events might be not very good idea. Only best people can participate in new added rounds, while everybody can participate in tentative events, so that seems a bit elitist.

**Comment by cubewhiz** [comment]
In addition to the "other things you can do with extra time at the competition", you could host events unofficially. I would strongly prefer that events that are not included on the schedule are not held. Is competing in an event you enjoy less fun just because the results will not be recorded into the database?

Some competitions, though, include unofficial events in their schedule already, prioritizing them over some official events.

**Comment by lgarron** [comment]
> Is competing in an event you enjoy less fun just because the results will not be recorded into the database?

Yes. That's why we hold competitions instead of just unofficial meetups, right?

I think having the option of tentative events can be better than adding rounds or adjusting the number of competitors who advance in a given event. Now I agree that *most* competitions should be able to budget a schedule fairly well, but I think it's still a useful option to support the mission of the WCA because it can **allow more people and more fun**.

Tentative events can be used to support a schedule for a competition with an uncertain number of newcomers. Myself, I showed up to my first competition and signed up day-of because of a news article a few days ahead of the competition. I think we should *encourage* that kind of openness, even if it leads to uncertain last-minute signups (e.g. if there is a big publicity ramp-up, or the competition is associated with a larger event that might draw kids who can solve the cube but don't know of the competition ahead of time). If there are a lot of signups, the original schedule is more fun for those new competitors. If there are fewer newcomers, then this reduces to the extra competition time situation discussed in this issues.

When a competition does have extra time, then I believe that tentative events can lead to more fun for more people. Since fast competitors tend to be fast across multiple events, adding more rounds or letting more competitors advance tends to favor the same competitors. By contrast, a tentative event for a more accessible puzzle (e.g. Pyraminx) is extra fun available to all competitors.
I'd also like note that changing the number of competitors who advance from a round can be against the spirit of the Regs, e.g. [9p2a](https://www.worldcubeassociation.org/regulations/#9p2a). (Also see [A1a3+](https://www.worldcubeassociation.org/regulations/guidelines.html#A1a3+) for an example of "please note that changing the the shape of an event can affect competitor strategies".)

There are also other reasons I've held tentative events in the past. I've seen it draw competitors who might not otherwise have come (with full awareness that there were no guarantees about the event). I've also used them as a response to competitor requests for once-niche events: "if we reach a handful of competitors who want the event and the schedule stays good, you're welcome to handle each other's scrambling/judging and hold the event on part of the stage". However, I think these are weaker reasons as of 2018.

And since I'm sort of addressing all the "stuff you can do with extra time" points, I don't think that *watching* head-to-head finals has a strong appeal for cubers at smaller competitions – although *participating* can be a lot more fun for those few competitors who make it.

I do want to mention that I *love* mystery puzzles and unofficial events – they provide novelty value, allow people to shine if they're good at learning to speedsolve new puzzles rather than practicing a finite set of official ones, can sometimes be used to get non-cubers to participate, and they're a good way to explore the direction we should take official events in the future. But this approach currently doesn't seem to be a priority for organizers, and I don't think that tentative schedule gaps lend themselves to a high-quality selection of mystery puzzles or unofficial events.

I don't mean to argue that tentative events are strictly better than other options for all organizers, and I would agree that we should should limit the kinds of competitions that can have tentative events – and how many. But it sounds from this thread that some organizers prefer it as a way to hold a competition with more people and more fun, and I think the option should remain.

**Comment by viroulep** [comment]
@FatBoyXPC in reply to @AlbertoPdRF 
> What percent of competitions that you organized went completely according to plan? If that number is less than 100% I think this idea of "Proper planning" is fairly insulting. I've already brought this up, but I suppose it's worth repeating: Even at competitions like CubingUSA Nationals where efficiency is probably the highest I've seen, we still end up behind sometimes. We also end up ahead a lot of the times. Sure, I understand we don't hold "tentative events" there, but that's primarily because we don't need to (since we run all the events...except we've lately not been doing feet). When you have such an experienced staff, a known competitor base (0 newcomers as there are qualifications), with a very carefully planned schedule, and still get ahead, I'm not sure how "proper planning" will fix this "getting ahead" problem. The only reason we don't end up with an extra hour mid day like we do at some comps is because at Nats we call heats up at the designated time due to having multiple stages and rooms, and it's important that Event A Group C happens at the same time as Event B Group A etc.

I don't think "proper planning" is about going exactly as scheduled, but rather having a moderately accurate schedule if nothing wrong happen, and having some rounds' attributes to adjust when things go slightly off what was scheduled.
If you end up an hour ahead/behind mid day and nothing extraordinary happened (such as a storm preventing people to come, or the Delegate being caught in a warzone¹), then something is very wrong with how the time allocated for each event has been computed, regardless if the comp has a high proportion of newcomers or if it's US Nats.

### Tentative event usage overview

I've gathered some data about tentative events usage during past WCA competitions (since 2016, the introduction of competition tabs), the data are [here](https://docs.google.com/spreadsheets/d/1Z-KhDm0exKqowobE1fLLM8GssPAId0Q0GMb9q5SRaH0/edit?usp=sharing).
(there is a summarizing tab and a detailed tab with all the competitions, I did this a couple of months ago, so it is missing recent competitions)
It's worth noting that there may be inaccuracies: I've gathered this list of competitions by looking for tabs mentioning "tentative", and manually removing the numerous false positive (typically there were a lot of cases where the organization team would mention that "the schedule is tentative and may be adjusted later"). 

I've added a couple of extra information (such as which tentative events were actually held), and some comment when I took the time to quickly review the public schedule (but unfortunately I didn't take this time for all the competitions in there).

Unless I missed something, it's clear that it is almost only used in specific parts of the US.

Before going through some more detailed remarks I have on the above document, I'd like to describe quickly how I think schedules for competition should be handled.
To me there are clearly 3 time frames where you are making or adjusting a competition schedule:

#### Before announcing the competition

The schedule can only be designed through the estimated number of people attending each event of the competition.
In a moderately established community (or fully established), it's relatively easy to get a rough idea of how many competitors would compete in which events.
From there, a reasonable amount of stations should be chosen (depending on how many competitors can be accommodated in the waiting area, and how many helping people you can reasonably expect for a round).

This should provide a reasonable first draft of schedule, definitely enough to announce the competition.

#### When getting closer to the competition's date

At that point it should be pretty clear from the registrations who will competes in the events, how many newcomers will be here, etc.
Obviously a couple of actions are available to adjust the schedule:
  - adjust the cutoff and time limit based on the actual registrations
  - increase the number of qualified competitors if you got some extra time
  - decrease it if on the contrary you need to save time, or even remove rounds if tightening the cutoff or time limits would not help.
  - add/remove rounds

#### During the competition

If the competition is not running as expected, it is very much possible to adapt to it live by using some of the previously described adjustments (on upcoming rounds of course, and if the changes are fair).


#### Some more detailed remarks

I didn't go through *all* the competition's reports, schedule, and registrations from the above spreadsheet, but I did some of them.
And from what I've seen, there are quite a lot of examples where I think there has been no schedule revision from the announcement until the competition day.
Basically some of the delays (either being ahead of time of behind) was simply due to bad calculations (examples from the top of my head: 30 minutes for a 12 people pyraminx final with 8 timers, rounds that were clearly allocated too much time with respect to the number of registrations and timers).

Examples of situations where tentative events made no sense:
  - tentative FM attempt, or multi blind attempt. These are events which needs quite a bit of logistic, and I don't get how you can say "We may be one hour ahead of schedule". As I stated before, you get enough information from the registrations psychsheet to not be in this situation.
  - having like 3 or 4 events listed as tentative. This would definitely take more than one hour to hold them all, and again being an hour ahead of schedule results from missing something in adjusting the schedule.
  - I found a competition where 2x2 was listed as an event, and later turned into a tentative event because there was a low amount of registered competitors. This makes no sense, as it makes the event even faster.

Some people care about specific events, and make travel plans according to the events that will be held. We should be able to deliver what we plan. We have the means to guarantee we can hold (or not) an event, since we can react to unexpected situation during the competition by many ways; for instance:
  - the Delegate forgot to switch the scrambles for a group, and it needs to be restarted. This leads to at least 15 minutes of delay, that can be partially caught up be adjusting cutoff of the number of qualified people in other rounds;
  - a lot of people ended up not showing up. It can be caught pretty early during the competition, and eventually adding a round or raising the number of qualified competitors would use up some time.

When something goes terribly wrong, then some events may have to be cut, but that would have happened even with tentative events.


I also have a couple of comments regarding some arguments in favor of tentative events:

> @Jambrose777 Positive: (somehow left out of any previous comment) Usually with a tentative event you are going to produce a schedule that is more lenient and can allow to get ahead when things go well. Once they do you can add the tentative event. If I was not allowed to use a tentative event anymore, I’d produce a schedule that is stricter just to add the event in; but once things go south I’ll be forced to cut the event.

You have way more options than having to cut the event.
Also a first round of an event is rarely less than 45 minutes, so if you're enough behind to think about cutting the event (like 30 minutes?), it certainly started to go wrong a while before this event, and you can react to that by adjusting a bunch of rounds in the schedule (cutoff and number of qualified for instance).
Surely you can turn a 45 minutes event into a 30 minutes one by drastically lowering the cutoff: some competitors would be a bit disappointed to not have an average, but at least they would have competed in their event.
And if you notice things go wrong quickly, you can save the time lost by slightly changing several rounds attributes instead of drastically changing one.


> @FatBoyXPC  "My competitions frequently have 30% or more newcomers, and tentative events definitely helps us maintain a schedule easier"

So does changing cutoffs, and the number of qualified people per rounds (and if you're ahead of time, I'm quite sure the newcomers would enjoy some extra qualified competitors in subsequent rounds).

> @lgarron When a competition does have extra time, then I believe that tentative events can lead to more fun for more people. Since fast competitors tend to be fast across multiple events, adding more rounds or letting more competitors advance tends to favor the same competitors. By contrast, a tentative event for a more accessible puzzle (e.g. Pyraminx) is extra fun available to all competitors.

Having enough extra time to add a tentative event accessible to a lot of competitors means you have a lot of extra time.
Which means something went wrong when computing the time allocated for each rounds.


Overall tentative events seems to be a step backward to me: a while ago the organizers and Delegates were asked to announce the events hold at a competition, and stick to it (there was a time were you could add an event on the fly, which was not great because some competitors may have decided to come if that event was announced).
With tentative events competitors can't be sure about all events that will be hold, which is basically the same reason that lead to the change above.

Having better (more accurate and flexible) schedules would naturally solves the need for tentative events, so I'd rather focus on improving the Delegates skills on this part: we've had some many competitions, with so many different situations (number of newcomers, judging systems, etc), and we also have so many ways to cope with the unexpected that it's definitely something we can do.


1: these are no jokes, they actually happened!

**Comment by lgarron** [comment]
The WRC consensus is to disallow this for 2019. However, this now belongs in the draft competition requirements, rather than the Regulations.

@AlbertoPdRF, could you take this on?

**Comment by AlbertoPdRF** [comment]
Sure!

**Comment by AlbertoPdRF** [comment]
This is handled now in https://github.com/thewca/wca-documents/pull/40, so I'm closing this issue!
