### ISSUE TITLE
Possible bug with stopwatches and timer resets

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#616]
According to A1b2, it seems that if the time limit for an event is over 10 minutes, the competitor is not DNFed for a timer reset, and instead the stopwatch time is used. This is inconsistent with events with time limits under 10 minutes. Is this considered a bug or intended?

**Comment by lgarron** [comment]
I'm not sure I follow. If the competitor exceeds 10 minutes, a time from the Stackmat timer is not available and the stopwatch time is used. Could you describe more specific scenarios that highlight the inconsistency you see?

**Comment by xsrvmy** [comment]
A time from the stackmat is also not available if the competitor stops the timer improperly and resets it, or if the timer malfunctions and turns off. If the time limit is under 10 minutes, the first scenario is a DNF and the second scenario leads to an extra attempt. But if the time limit is over 10 minutes, then the competitor can argue that the stopwatch time should be used by A1b2.

Basically the problem is that A1b2 intends to cover the case where the stackmat timer runs over the 10 minute limit, but also covers timer resets and malfunctions.

**Comment by lgarron** [comment]
Ah, now I understand – by "timer reset" you meant something the competitor did rather than the timer shutting off automatically.

I actually don't see a huge issue with using the timer time instead of the Stackmat time, although I don't think this was an intended consequence, so this is a good question.

**Comment by theoleinad** [comment]
A1b1 and A1b2 are both under 
**_A1b) If the time limit for a solve is greater than 10 minutes, a stopwatch must be used for timekeeping._**
If the competitor is using a stackmat timer, that will be the official recorded time, if timer turns off after 10 minutes (or it has a malfunction while stopping it) , you'll keep track of the time with the stopwatch. _(no extra attempt)_ 
This only applies for events where the limit for a solve is greater than 10 minutes (as stated un A1b)

I hope I understood the question as well...

**Comment by Goosly** [comment]
@theoleinad The "possible bug" Max is talking about is not in the stackmat malfunctioning, but in the competitor making an error in usage of the stackmat. Consider these situations:

1) Time limit is under 10 minutes. A competitor accidentally stops or resets his stackmat timer during the solve = DNF
2) Time limit is over 10 minutes. Therefore, a stopwatch is used in addition to the stackmat timer. A competitor accidentally stops or resets his stackmat timer during the solve. Strict interpretation of A1b2 would take the final time from the stopwatch as the result (because a time from the Stackmat timer is not available)

In situation 1, the competitor is punished for his own mistake, in situation 2 he is not. This is inconsistent.

**Comment by theoleinad** [comment]
@Goosly In that case I don't see any issues, since this rules are intended this way for those specific events.
To "fix" that inconsistency we might add that only in the case the timer stops at 10 mins due to factory nature of the stackmat timer. 
But I don't see it necessary...

**Comment by dancing-jules** [comment]
Another issue is that A1b is rarely even followed by judges when judging 3bld. Many people don't use stopwatches at all if the competitor expects to finish under 10 minutes, even if the (usually cumulative) time limit is e.g. 15 minutes. In my experience slower competitors need to remind their judges to use a stopwatch and faster competitors react confused when asked whether they need one. 

So even if it is a "feature bug", I find it somewhat unfair if it's availability depends on how well your judge knows the regs.

**Comment by theoleinad** [comment]
@dancing-jules 
Yeah, but then there's no regulation to fix.
If something ever happen to you or someone else, just contact your delegate and raise the incident, keep your community aware. 
So can we consider this closed?
@Laura-O

**Comment by dancing-jules** [comment]
@theoleinad Back to the original question: Is the interpretation of that rule, that a stopwatch would cover for a timer-malfunction or accidental timer reset, correct?

**Comment by theoleinad** [comment]
Yes, it's meant to cover both as per my understandings.
