### ISSUE TITLE
Article 5 & A5b: Addendum for spectator assisting with popped piece

### ISSUE THREAD

**Issue by Mollerz** [thewca/wca-regulations#624]
As discussed in the ABHC 2018 delegate report, we should really specify what happens when an unknowing spectator helps by retrieving popped pieces from an attempt. In the past it was common to immediately award an extra, however the competitor should not be given an automatic extra since there has been a pop where the time is almost certainly going to be worse.

https://www.worldcubeassociation.org/regulations/#article-5-puzzle-defects
https://www.worldcubeassociation.org/regulations/#A5b

A5b) While inspecting or solving the puzzle, the competitor must not receive assistance from anyone or any object other than the surface (also see Regulation 2i). Penalty: disqualification of the attempt (DNF).

Perhaps the addendum should be added here. Something along the lines of "If a spectator picks up a piece, the judge should tell them to put it on the table and the solve should continue".

**Comment by lgarron** [comment]
> Perhaps the addendum should be added here. Something along the lines of "If a spectator picks up a piece, the judge should tell them to put it on the table and the solve should continue".

I support this approach. It roughly matches a policy we're already heading towards, is consistently enforceable, and strikes a balance of practicality without giving an advantage (given that you've already had a POP).

Two slight concerns:

1. Allowing others to put pieces on the table would allow someone to arrange them for the competitor in a way that is particularly convenient for assembly. I think this is *probably* okay (imagine someone collecting corners and edges separately, in order to count them), as long as no one touches the pieces once they've deposited them on the table.
2. Should the competitor be allowed to communicate whether they are still missing more pieces?

**Comment by Mollerz** [comment]
1. I think we should just be encouraging judges to not ask the spectators to help but if they see an unknowing spectator pick it up they can just say "Just leave it on the table and don't touch other pieces".

2. It's pretty common that if another piece is missing that they are looking around them or maybe mention that they are missing a piece. I wouldn't be against allowing judges point out pieces that are sitting on the floor for example, as long as they don't actively group up or assist gathering the pieces in any way.

**Comment by dancing-jules** [comment]
I don't think I'm comfortable with encouraging any assistance to the competitor, including pointing.

**Comment by lgarron** [comment]
I just realized that no one drafted a change for this! I'll draft something right now.
