### ISSUE TITLE
Clarify if competitions with multiple locations can have different registration requirements

### ISSUE THREAD

**Issue by Claster** [thewca/wca-regulations#629]
For example: if FMC competition takes place in several locations, it totally makes sense to specify a different competitor limit and registration fee.

**Comment by xsrvmy** [comment]
However, it would not make sense to have different qualification requirements.

**Comment by lgarron** [comment]
I think this should be pretty uncontroversial; we just need a good proposed change for Article Z.

**Comment by xsrvmy** [comment]
Additional comment about clarity: Can there be a competitor limit at each venue, but also an overall competitor limit that is lower?

**Comment by lgarron** [comment]
I haven't heard any good reasons for competitor limits other than physical space or scheduling constraints. There's a bit of coordination overhead, but I actually don't see a reason to allow an overall competitor limit in addition to per-venue limits.

Assuming this doesn't cause too much trouble for e.g. the software team, I'd rather just switch to limits per venue.

(We've also recently had to figure out what to do with per-day limits for a competition when competitors might attend either or both days. However, this case is similar because it's very unlikely that a competitor would be in multiple venues for our only current simultaneous format.)

**Comment by AlbertoPdRF** [comment]
This should be handled in https://github.com/thewca/wca-documents/pull/40, so I'm closing this issue!
