### ISSUE TITLE
Require all competitors to sign every attempt?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#63]
I sign every attempt, but sometimes competitors will sign once and draw an arrow over the entire column to avoid having to sign again. This defeats the point of an official acknowledgment, even if it technically prevents them from disputing it.

(If they're being lazy and come back with video evidence when it was recorded wrong, that's just inconsiderate.)

I'm not saying I support changing this, but I think it should be discussed.

---

[Email to Delegate list, December 08, 2013](https://groups.google.com/forum/#!topic/wca-delegates/O_J6NlRSuvg)

**Comment by pedrosino** [comment]
A7c requires that the competitor signs _after_ the solve and after the judge has verified the puzzle.

I know some people just sign everything in advance, and that is bad. I'll make sure to tell them the purpose of the signing, and that if they signed, they can't really complain later if something is wrong.

**Comment by sarahstrong314** [comment]
I support changing this, or at least making this more clear. Often when a competitor does the line/arrow thing, he doesn't realize that by doing so he has acknowledged in advance anything the judges write. At Worlds when I judged people who did this to their scorecards, I would say something along the lines of "Hypothetically, if I were to write 'DNF' by mistake, and you realize after the timer was reset, you wouldn't be able to do much about it since you've already signed it" then I suggested to them to cross off the arrow and sign each of their individual completed attempts.

**Comment by KitClement** [comment]
I don't like the term "final result," this could be easily confused with the 5th (or 3rd) solve in the average.  I think that the term "result" suffices.

**Comment by lgarron** [comment]
I had the same concern. However, I want it to be completely ambiguous that
everything (in particular, including the final time after penalties) has
the be written down. We use the term "final result" elsewhere, and I
haven't thought of anything better. "Completed result" comes close, though.

**Comment by KitClement** [comment]
I think substituting the active for the passive voice makes it seem
less ambiguous, it also makes inserting "for that attempt" less
clunky.

A7c2) The competitor must not sign an attempt on the score sheet
before the judge records the final result for that attempt. If a
competitor signs (or otherwise marks) an attempt before he has begun
it, or before the judge has finished recording the result, he forfeits
the attempt and the result for the attempt will be considered as DNS.

## 

Christopher Clement
University of Michigan Rackham | Applied Statistics MA
