### ISSUE TITLE
Engraved/Embossed parts-Regulations and Guidelines disagree

### ISSUE THREAD

**Issue by jamesquinn1** [thewca/wca-regulations#656]
[Regulation 3l2](https://www.worldcubeassociation.org/regulations/#3l2)
The logo may be embossed, engraved, or consist of an overlay sticker.

[Guideline 3j+](https://www.worldcubeassociation.org/regulations/guidelines.html#3j+)
In the past, engraved/embossed parts have been permitted. This is no longer permitted.

At a comp yesterday they went by the regulation, allowing them, but I decided not to risk it. So are they allowed? Also sorry if this isn't in the right format or anything, I'm new to github.

**Comment by kingmathyall** [comment]
I agree that this is not very clear and I too have turned away cubers with engraved/embossed logos because they had engraved/embossed parts. Ideally, I'd like for only overlay stickers to be allowed as those are generally not raised to lowered significantly so that a competitor can easily distinguish the center from others.

I'd like to see something such as:
Regulation 3l2
Logos may only consist of overlay stickers. 

Guideline 3j+
In the past, engraved/embossed parts have been permitted. This is no longer permitted.

**Comment by xsrvmy** [comment]
Here's my interpretation: 3j has an exception for logos. Since 3j+ clarifies 3j, this guideline does not apply to logos.
Also qiyi budget cubes print logos on the plastic so only allowing overlays is a terrible idea.

**Comment by kingmathyall** [comment]
Yeah, you're right - that was a pretty dumb suggestion :P I guess it might be best to then simply clarify that only logos may be embossed/engraved:

Regulation 3l2
The logo may be embossed, engraved, or consist of an overlay sticker.

Guideline 3j+
In the past, engraved/embossed parts have been permitted. This is no longer permitted. Exception: Logos are still allowed to be engraved/embossed

**Comment by jamesquinn1** [comment]
The discussion about should we allow them at all may also need to be had, as they do provide grip assistance (specifically on angstrom square-1s)

Unrelated, but why aren't logos allowed to be on any piece? The argument of you can feel them to know where a piece is on the cube isn't valid IMO because of of the fact that 4x4 logos are allowed be on center pieces, which is a moving piece during the solve. There is also this issue on 2x2, 6x6, pyraminx, skewb, and as a stretch megaminx. (knowing which center is where on the back while doing s2l)

**Comment by kingmathyall** [comment]
@jamesquinn1 , I believe the reason behind no logos on all parts because allowing it on, let's say, a corner, can be useful during a solve in that it can inform the solver of what corner is in the back. 

Let's say you're holding a 3x3 in front of you and in the UBR corner you see a white sticker with a logo - you know that the red/white/blue corner has the logo on the white sticker so, without looking around the cube, you know which corner that is - could be helpful during certain steps of the solve

For 5x5, 6x6, 7x7, I would support allowing logos on any center piece rather than just the center piece.

I understand this still would be an issue for events such as Pyraminx and 2x2 :/

**Comment by jpbulman** [comment]
Couldn't knowing which center is where be an advantage too? On even numbered cubes (or any bigger cube on wing centers), you could have the center in the back of the cube, feel it with your fingers, find which center piece has a logo, and then be able to determine what color sticker that is, without even looking at it.

**Comment by lgarron** [comment]
> For 5x5, 6x6, 7x7, I would support allowing logos on any center piece rather than just the center piece.

The current Regulations allow that, no?

> Couldn't knowing which center is where be an advantage too?

They could! The current Regulations for logos are a compromise with practicality.

**Comment by jamesquinn1** [comment]
> The current Regulations allow that, no?

I believe 5x5 and 7x7 allow only the center center, and 4x4 and 6x6 allow any of the 4 middle centers

**Comment by jamesquinn1** [comment]
The current regs allow the logo to be placed on any center piece, my post I deleted was wrong.

**Comment by jpbulman** [comment]
[3I](https://www.worldcubeassociation.org/regulations/#3l1)

**Comment by jamesquinn1** [comment]
> @jamesquinn1 , I believe the reason behind no logos on all parts because allowing it on, let's say, a corner, can be useful during a solve in that it can inform the solver of what corner is in the back.
> 
> Let's say you're holding a 3x3 in front of you and in the UBR corner you see a white sticker with a logo - you know that the red/white/blue corner has the logo on the white sticker so, without looking around the cube, you know which corner that is - could be helpful during certain steps of the solve

Never actually realized this argument, only ever thought about feeling for the logo. This makes sense, and I agree.

**Comment by hanwu85** [comment]
To sum it up,
3j) is talking about the overall appearance of the puzzle.
3l) is talking only about the logo it self.
Since we agree that the current regulation make sense, I'm going to close this issue.
