### ISSUE TITLE
Reconsider the use of the phrase "the WCA Delegate"

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#674]
> [1c](https://www.worldcubeassociation.org/regulations/)) The WCA Delegate may delegate responsibilities to other members of the organization team, but is ultimately accountable for how these responsibilities are carried out.

There are many things that are responsibilities of "the WCA Delegate" throughout the Regs/Guidelines. However, there are issues with that phrase:

- There may be multiple Delegates for the competition. (But there may be WCA Delegates at the comp who may be part of the organization team, staff, competitors, or audience members!)
- In practice, many responsibilities are carried out by people other than the Delegate.
- We can't distinguish well between "the Delegate is responsible for [something]" and "we want the Delegate to be the literal person doing [something]" – see #651
- For people reading a Regulation without context (e.g. new competitors), it's not clear that "the Delegate" doesn't need to be a literal Delegate. And if they *know* that sometimes it doesn't mean a literal Delegate, they may assume that it doesn't actually matter who carries out the responsibility (e.g. people trying to help make authoritative +2 decisions without the Delegate).

I would love to see us use something that is clear to people who do not have 1c in the front of their mind.

**Comment by c-goodyear** [comment]
The Code of Ethics uses the term "Listed Delegate" which could also be used here, if first defined under the Wording section of the regulations.

This would allow for all competitors to know who the regulations refer to more specifically. Especially since the listed Delegate is public information, and must be altered with a change request after a competition announcement(?) it would be possible to trace which Delegates were listed during the competition, and therefore should have been performing the mandatory tasks as required by the regulations.

**Comment by xsrvmy** [comment]
Some other related issues:
- What happens if two listed delegates disagree on something (eg. whether or not to give an extra, whether or not to allow a puzzle)?
- If a delegate with higher power than the listed delegate(s) is at a competition (eg. WRC member, senior delegate, full delegate at a comp delegated by a candidate), can he overrule the delegate's decision?
- Who gives the delegate extra attempts?

**Comment by zeecho** [comment]
> If a delegate with higher power than the listed delegate(s) is at a competition (eg. WRC member, senior delegate, full delegate at a comp delegated by a candidate), can he overrule the delegate's decision?

There is no such thing has "a delegate with higher power":
- WRC members are not necessarily Delegates (actually, only 1 of them has the Delegate status right now)
- Senior Delegates have the right to promote/demote Delegates in their area but during a competition they are just Delegates (if they are listed as such) or competitors (if they are not listed)
- Full Delegates are mainly Delegates with the right to vote but during a competition they are just Delegates (if they are listed as such) or competitors (if they are not listed)
- Candidate Delegates are Delegates without the right to vote but during a competition they are just Delegates (if they are listed as such) or competitors (if they are not listed)

Anyway, the listed Delegates are the only ones who can take decisions. If others Delegates or WRC members are attending the competition, the listed Delegate(s) can ask them for advise if they want but they must be the ones to take the decision in the end
