### ISSUE TITLE
FMC Tools

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#68]
[Regulation E3](http://www.worldcubeassociation.org/regulations/#E3) is not very clear.

See [WCA delegate discussion started by Yohei Suzuki on August 03, 2013](https://groups.google.com/forum/#!searchin/wca-delegates/FMC$20suzuki/wca-delegates/mA9BpLyqn-U/T1mOfqVuStQJ).

**Comment by Laura-O** [comment]
In order to clarify this, I would suggest to change this from "coloured stickers" to "stickers". The question why the regulations require them to be coloured is repeatedly asked, so it's time to change this and close the issue. :-)
The term "coloured" can be confusing because most FMCers simply use white stickers and mark them with numbers or letters.

**Comment by sarahstrong314** [comment]
I agree with changing "coloured stickers" to just "stickers". 

We could also add a clarification in the Guidelines (Ec3+) that "stickers" include post-it notes and don't just refer to traditional puzzle stickers.

**Comment by Claster** [comment]
Would that include tape, either transparent or not?

**Comment by Laura-O** [comment]
If you cut the tape in smaller pieces I would say yes.
