### ISSUE TITLE
A5 should state: "During the attempt:"

### ISSUE THREAD

**Issue by Mollerz** [thewca/wca-regulations#683]
https://www.worldcubeassociation.org/regulations/#A5

It mentions that "While inspecting or solving the puzzle" in both A5a and A5b, so surely this is part of the attempt and not the solve? Minor issue but should be consistent.

**Comment by lgarron** [comment]
The attempt also includes signing the scoresheet, so that "during the attempt" would be a semantic change. And A5) should remain "During the solve", since it falls between A4) Starting the solve and A5) Stopping the solve.

I don't see a big issue with the way it currently is, but I'd be happy to review a PR that e.g. splits both A5a and A5b across A3 and A5.

**Comment by Mollerz** [comment]
Ok that makes sense, I was just looking for consistency between attempt and solve.
