### ISSUE TITLE
Requiring scramble signatures in 2020

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#686]
As voted in #655 (and previously discussed in issues like #640 and #591), we'd like to move towards a mandatory scramble checkers – or a similar system with sufficient accountability and power to prevent mis-scrambles.

**Comment by lgarron** [comment]
Continuing from https://github.com/thewca/wca-regulations/issues/655

@Jambrose777:
> Hey WRC, I was wondering what the planned repercussion is planned to be in 2020 for a scrambler forgetting to sign an attempt. Would this invalidate the attempt making it a DNF?

@lgarron:
> Yeah, it would have to be.
> We could also allow an extra attempt if the judge or competitor notices the missing signature during the attempt.

@xsrvmy
> @lgarron Doesn't that potentially give rise to issues of a scrambler intentionally not signing an easy scramble? And what abour video?

**Comment by lgarron** [comment]
> Doesn't that potentially give rise to issues of a scrambler intentionally not signing an easy scramble?

I suppose, but then the judge is not doing their job and the Delegate should be able to track that down and take action (scramble tables usually have fairly few scramblers).

The Regulations should instruct the judge to check for the signature, allowing the scramble to be re-checked at the scramble table and signed by a scrambler before the competitor sees the scramble.

> And what abour video?

Could you elaborate?

**Comment by xsrvmy** [comment]
Will a competitor be allowed to use recorded video to check against the correct scramble if the scrambler forgets to sign?

**Comment by lgarron** [comment]
> Will a competitor be allowed to use recorded video to check against the correct scramble if the scrambler forgets to sign?

Ah. Good question, which we should probably discuss thoroughly.

**Comment by xsrvmy** [comment]
I want to add a quick point here in regard to a recent incident at WC2019, where a competitor did not try his best after believing the U perm scramble to be a miscramble. I believe it should be explicitly state in the reg that the competitor has the right to see if the scrambler has signed for a scramble before an attempt (and specifically the scorecard cannot be used as a SQ1 insert or be otherwise placed inside the box). Also a scrambler who DELIBERATELY does not follow the scrambling procedure (eg. the 4.xx OH and 3.22 scrambles, handscrambles) should be penalized. This way the competitor will have confidence that easy scrambles are likely to be correct.

**Comment by Jambrose777** [comment]
I don’t understand how the two points you bring up are correlated. (Having easy scrambles vs scramblers giving out intentional easy scrambles).

I think it’s a bad idea to enforce harsh punishments for misscrambles (especially unintentional). Good help is already hard to find, giving harsh consequences for mistakes is only going to cause less people to be good at scrambling.

**Comment by xsrvmy** [comment]
@Jambrose77 At worlds someone got what could be a wr fail on the U perm scramble, believing that is was an intentionally easy scramble

**Comment by Jambrose777** [comment]
Right, that is a stupid assumption by the competitor. What does this have to do with scramble signatures? Are you going to punish someone for giving the correct U-Perm Scramble?

**Comment by xsrvmy** [comment]
If we enforce a policy of punishing intentional misscrambles then this type of assumptions shouldn't happen any more.Unfortunately right now the chance of a misscramble is probably still higher than getting something like a u perm on skewb, which is why the assumption is even being made

**Comment by sarahstrong314** [comment]
If a competitor finishes their solve and discovers as they are signing the scorecard that there is no scrambler signature, what is the outcome? I don't see a good solution to this assuming that scramble signatures are mandatory.

Making the result a DNF seems unfair since the competitor doesn't necessarily have a good opportunity to check the scorecard before they begin inspection. After all, the runner hands the scorecard to the judge while placing the puzzle cover onto the mat. An alternative solution is to give an extra per 11e (since the runner should not have sent out the puzzle in the first place) but that can be upsetting especially when it was a fast solve (e.g. a record of some sort). 

Why not keep scramble signatures as a strong recommendation? They serve many useful purposes, but penalizing or replacing results that are missing them is quite extreme.

**Comment by jamesquinn1** [comment]
@lgarron 

"Doesn't that potentially give rise to issues of a scrambler intentionally not signing an easy scramble?"
"I suppose, but then the judge is not doing their job and the Delegate should be able to track that down and take action (scramble tables usually have fairly few scramblers)."

Then why need scramble signatures at all :p 
I am in favor of scramble signatures in general though, just playing devils advocate.

I don't like the idea of making them mandatory, I would prefer to keep them as a suggestion but become more and more passive aggressive about wanting them. CF comments pointing out missing ones recently has been nice IMO.

**Comment by cubewhiz** [comment]
This should be kept as a recommendation until a solution to the currently presented problems is provided. Once a competitor solves a puzzle, it is too late to ask a scrambler to verify the scramble and sign. This is much unlike asking a judge if they remember judging an official solve for someone.

**Comment by sarahstrong314** [comment]
> This is much unlike asking a judge if they remember judging an official solve for someone.

To add on to this, judges can verify whether or not they judged an official solve for someone by checking whether the time was written in their handwriting. There is no such comparable for asking a scrambler whether they scrambled a particular puzzle for a particular attempt, since many puzzles look and feel the same as each other.

**Comment by alexmaasswca** [comment]
Requiring scramble signatures is a terrible idea, we would have many incidents of a scrambler forgetting to sign, competitor notices, puzzle has to be sent back, causing delay. The competitor should not have to keep remembering to check for scrambler signature every single solve.

**Comment by xsrvmy** [comment]
@alexmaasswca I have nothing again it being an organization requirement, but there should be no penalty for a missing signature (although if an NR or something like that happens then there nweds to be the normal scramble check)

**Comment by alexmaasswca** [comment]
no penalty as in if the competitor notices it, they don't have to do anything about it?

it would still be an issue if it would delay the competition whenever someone forgets to sign the signature

**Comment by CubeShepherd** [comment]
I am not completely sure that scramble signatures are needed to become a regulation. I understand the point, (and have been making the scramblers at the competition I have been to make sure to sign, and there have only been a few missing signatures in total), so it is not to hard to get people to do, but having it as a regulations that if a scrambler forgets to sign the competitor getting a DNF, seems a bit harsh to the competitor, since the only control he has it to check before the attempt (which I guess could work, just like he/she has to check after the attempt that the judge signed).

If it does become an official regulation, then I think that you either have to make sure the delegate enforces the scramblers to make sure he/she signed, as well as make sure the judges checks every time before he starts the stopwatch for the competitor.

If that is enforced/strongly encouraged, but someone still misses a card, then again I don't think giving the competitor a DNF is the best option, but rather a extra should be given.

**Comment by xsrvmy** [comment]
It's definitely shouldn't be a DNF. I don't even think giving an extra is very justified.

BTW personally I find signing after each scramble disrupts the scrambling flow by a lot. I have to take out the scoresheet to sign when I don't have too if I don't need to sign.

Also have we figured out whether or not the delegate has to approve every single 6/7/mega misscramble and sign yet, or can this responsibility be delegated to the scrambler?

**Comment by CubeShepherd** [comment]
> BTW personally I find signing after each scramble disrupts the scrambling flow by a lot. I have to take out the scoresheet to sign when I don't have too if I don't need to sign.


Yeah, I agree with that, but the only thing I would say different, is that from what I have noticed and experienced myself is that it doesn't disrupt scrambling flow that much. After figuring out a system that works and is efficient for scrambling and signing it goes really fast.

But that is a pretty minor issue right now, and the bigger issues is if it will be a new regulation or not.

**Comment by xsrvmy** [comment]
I don't have a problem with requiring scramble signatures organisationally. I have a problem if they affect the validity of individual attempts. I personally miss a signature maybe once every group, but it seems that my score sheet miss signatures way more and that is very concerning.

**Comment by AlexKatyukov** [comment]
One more problem. Just example that I saw very often.

Scrambler A forgot to sign attempt 1. After the end of attempt 1 judge said to scramblers "don't forget to sign!". Scrambler B took a scorecard and signs attempt 1. Delegate says "never sign not your mistakes".

We should avoid scramblers that signs for another attempts. Maybe I am the only Delegate who see this problem but I think no.
