### ISSUE TITLE
Multi BLD combined rounds.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#687]
The 2019 draft Regs specify which round formats can be combined, and do *not* include Multi-Blind.

Euro 2014 had a Multi-Blind combined round: https://www.worldcubeassociation.org/competitions/Euro2014/results/all#e333mbf

I suppose that a combined round allows more talented competitors more flexibility about safety vs. stretch attempts, without extending the time given to everyone. Using an additional round instead of a combined round would increase the pressure for safety solves.

Since we have a precedent for this format in Euro 2014, I will send a PR to include the format to the 2019 draft Regs, and I think any  discussion in this issue should focus on whether to "remove" this format.

(Note that cumulative time limits are sufficient for 4BLD 5BLD to ensure that more talented competitors get more attempts without giving too much time to others.)

**Comment by EdHollingdale** [comment]
I think there is a space for multi-blind cutoffs due to the logistics required of holding it. E.g. you want to hold 3 attempts over 3 days, but you only have room to host it for 15 competitors on the 3rd day. I guess if it depends on if you want to allow space for strategy and safety, but it would lead to different competition environments depending on the preferences of the organisers.
