### ISSUE TITLE
Which regulations should every competitor know before they compete?

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#69]
Often, on a competition site or by email, the organizer requests that the competitors read and be familiar with the regulations before the competition. [2t](https://www.worldcubeassociation.org/regulations/#2t) even states this. Many competitors don't read them thoroughly or at all because there's so much information and they can learn most of the important details at the competition.

I think it would be helpful for new/new-ish competitors if there were a list of specific regulations that every competitor should know. I don't think it should be required know even the most basic misalignment penalties, but other avoidable penalties that first-time competitors aren't aware of (e.g. karate chopping to stop the timer) can be listed. Would it be a good addition to the guidelines?

**Comment by SAuroux** [comment]
That's a difficult task. A shortened "lite" version could definitely be beneficial.

**Comment by sarahstrong314** [comment]
Unfortunately I never got around to start compiling a list of such regulations. Should we all go through it together?

I made this thread a while ago to get an idea of what people thought were the top regulations to know (and to trick people into carefully reading the regulations): http://www.speedsolving.com/forum/showthread.php?43475

**Comment by sarahstrong314** [comment]
https://github.com/cubing/wca-documents/compare/regulations-each-competitor-MUST-know

It still needs some work, but that should cover most of the necessary regulations.

**Comment by lgarron** [comment]
That's still 247 lines. Do you consider that concise enough?

**Comment by SAuroux** [comment]
Looks reasonable. This should probably be published as an official "lite"
version of the regulations. It could be sent to the delegates to get
feedback, if something crucial is missing, before being published along
with 2014's regulations.

2013/12/10 Sarah Strong notifications@github.com

**Comment by sarahstrong314** [comment]
@lgarron it's more concise than just saying "read everything".

The distinction between regulations marked with \* and *\* will help a lot, I think.

**Comment by lgarron** [comment]
Since it will likely fall to me to put this somewhere, could you two start a discussion (preferably including speedsolving.com, where much of the audience who would benefit from this is) about where this should go?

The WCA website is already confusing, and we need this additional document to make things _simpler_ while still making clear what the official Regulations are.
Also, a plan for handling translations would be good.

Strawman proposals:
- Add yet another page with the simple/summary Regulations
- Merge the Regulations and Guidelines (#71), and add this as the second document.
- Highlight the important Regulations inline. Perhaps toggle the visibility (or color) of the others?

**Comment by lgarron** [comment]
If you'd like this to be ready for Jan. 1, I need to know where this would go.

**Comment by lgarron** [comment]
I don't think a second version of the Regulations is ever going work, especially since no one really has the time to make it happen/keep it maintained.

I think something like a competitor guide on the WCA website is much more feasible.
