### ISSUE TITLE
Specify exactly which round formats are allowed

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#693]
We occasionally get (and have recently received) clarifying questions about exactly what round formats are allowed. We've specified most of them in 9b, and I've just landed https://github.com/thewca/wca-regulations/pull/692/files, which specifies that 9b enumerates all valid formats. But apparently 9b is missing more (formerly) valid formats.

I'd love it if someone can run stats on
- which formats have been used for which events,
- at how many competitions,
- tallied by year.

This allows us to see exactly which event formats we are "removing", and how much their use has tapered out.

**Comment by jfly** [comment]
This gets tricky because combined rounds have 2 phases with different formats, but we only store the format of the second phase. AFAIK, we can only deduce the format of the first phase by looking at results to see how many skipped results there are for people who didn't make the cutoff. I hacked together Ruby script that does this, and prints out a warning if the people who didn't make the cutoff didn't all complete the same number of solves.

<details>

```ruby
# frozen_string_literal: true

require 'set'

RoundKey = Struct.new(:competition_id, :event_id, :round_type_id)
all_results = Result.all # .limit(10000)
results_by_round_key = all_results.group_by { |r| RoundKey.new(r.competitionId, r.eventId, r.roundTypeId) }

def get_only_element!(arr)
  throw "Uh oh" if arr.length != 1
  arr.to_a[0]
end

Round = Struct.new(:competition_id, :year, :event_id, :phase_1_format, :phase_2_format)
rounds = []

results_by_round_key.each do |round_key, results|
  format_id = get_only_element!(results.map(&:formatId).to_set)
  if %w(c d e g h).include?(round_key.round_type_id)
    missed_cutoff, _made_cutoff = results.partition(&:missed_combined_round_cutoff?)
    potential_phase_1_formats = missed_cutoff.map { |result| result.solve_times.reject(&:skipped?).length }.to_set
    # We expect all the people who didn't make the cutoff to have the exact
    # same number of unskipped solves. If they don't, there's something weird
    # going on, and we can't deduce the format of the first phase of this
    # combined round.
    if potential_phase_1_formats.length > 1
      url = "https://www.worldcubeassociation.org/competitions/#{round_key.competition_id}/results/all#e#{round_key.event_id}_#{round_key.round_type_id}"
      puts "Weird. Check out #{url} when you get a chance"
      next
    end
    phase_1_format = get_only_element!(potential_phase_1_formats).to_s
    phase_2_format = format_id
  else
    phase_1_format = format_id
    phase_2_format = nil
  end

  year = /[0-9]{4}$/.match(round_key.competition_id)[0].to_i
  rounds << Round.new(
    round_key.competition_id,
    year,
    round_key.event_id,
    phase_1_format,
    phase_2_format,
  )
end

counts = rounds.group_by { |round| [round.year, round.event_id, round.phase_1_format, round.phase_2_format] }
               .map { |key, items| [key, items.count] }

puts(counts) # <<<
```

</details>

To run this script, clone the [WCA website repo](https://github.com/thewca/worldcubeassociation.org/), and place this script in the `WcaOnRails` directory in a file called `identify_formats.rb`. You can run it by doing:

```
$ bin/rails runner identify_formats.rb
```

Unfortunately, it's **quite** slow (I think it takes 8-9 minutes on my laptop). @lgarron, hopefully this is enough for you to push this over the finish line! I'm timing out for the day.

**Comment by Jambrose777** [comment]
@SAuroux  has a similar script for this counting the number of blank results in a round. Maybe that can help here.

**Comment by timreyn** [comment]
https://pastebin.com/NXNYKrda

333 | a | 5 means average of 5, and someone did the full 5 solves.
333 | a | 3 means average of 5, and someone did 3 solves and then didn't make the cutoff.

**Comment by Jambrose777** [comment]
It's worth mentioning that there are some rounds that were investigated and have been manipulated to "make sense" a lot of the events like "event | a | 3" came from this.

**Comment by lgarron** [comment]
Thanks!

I'm going to revert ea29e0936c252281258711562d561f6128b08557 (Clarify that 9b specifies the valid combined rounds.) until we have this figured out.

**Comment by lgarron** [comment]
Okay, I've run the numbers: https://docs.google.com/spreadsheets/d/13GGhkz0Y62Fzkdp5uxwy_H1d5Ue0FbDzogUXZKhbRi0/edit#gid=2105530667

<img width="676" alt="screen shot 2019-01-20 at 02 39 05" src="https://user-images.githubusercontent.com/248078/51438125-b3c34a80-1c5c-11e9-9b04-91da03aa1fe4.png">
<img width="674" alt="screen shot 2019-01-20 at 02 39 15" src="https://user-images.githubusercontent.com/248078/51438127-b3c34a80-1c5c-11e9-90e2-dd358c2cbfec.png">
<img width="671" alt="screen shot 2019-01-20 at 02 39 23" src="https://user-images.githubusercontent.com/248078/51438128-b45be100-1c5c-11e9-9648-597b02106cbf.png">
<img width="671" alt="screen shot 2019-01-20 at 02 39 30" src="https://user-images.githubusercontent.com/248078/51438129-b45be100-1c5c-11e9-9af4-c1b1aaaae16a.png">

**Comment by lgarron** [comment]
@thewca/wrc-team: I'd like to send a PR to crystallize the following formats as official, with formats boxed in this screenshot:

<img width="681" alt="screen shot 2019-02-13 at 12 20 01" src="https://user-images.githubusercontent.com/248078/52741219-b4b07900-2f89-11e9-8f0f-feca7d1afd63.png">

I think the only controversial ones might be:
- Bo2 for Multi-Blind.
  - Mainly since Bo2 is actually more common than Bo3.
  - Keeping only Bo1/Bo3 would have the nice effect that every event has exactly one "full" format, and one "truncated" format.
- No Bo2 for Fewest Moves
  - This is kind of inconsistent with Multi-Blind. I presume this is uncommon because FMC has a mean, while multi does not – so the step from 2 to 3 hours is more "worth it".
- No combined rounds for Fewest Moves.

In general, I would love to see us move away from Mean of 3, due to the harsh impact of a DNF in those events. However, that's out of the scope of this change.

Do the choices in the screenshot look reasonable?

**Comment by lgarron** [comment]
@thewca/software-team: any thoughts/concerns about simplifying the list of formats as described in the previous post?

**Comment by Jambrose777** [comment]
FMC Combined Rounds: I agree that this makes little sense. If a competition can support x people in the room for an attempt it takes no extra resources (besides paper) to support x people in the next attempt. This decision seems great to me!

FMC bo2: The 6 competitions with this in 2018 were: 
- MundetOpen2018 5 DNS, 18 Competitors
- Murcia2018 4 DNS, 13 Competitors
- NoPlaceForDNFSpring2018 8 DNS, 18 Competitors. From Report "We ended up compromising on 2 attempts, which, in retrospect is silly (some people just showed up for 1 attempt because they wouldn't be able to get a mean anyway). In the future, if I delegate a competition with FMC, I will either have best of 1 or mean/best of 3."
- BasauriOpen2018 0 DNS, 7 Competitors
- Tlaxcala2018 10 DNS, 41 Competitors
- CUBIFMA2018 2 DNS, 9 Competitors
Also interestingly, 5 of these competitions were Spain / Latin America (and the other being US). I seem some merit in keeping this format since it is an event which requires a dedicated hour of resources and the jump from 1 to 3 hours is a lot. However, I also see the issue which was pointed out in the report of it's a bit pointless to hold and the resources can be better spent for another event at a competition and make the FMC round fairer. Overall, I'm also in favor of removing this possibility for this reason and that it just isn't used that much.

MBLD bo2: I see a lot of merit in keeping this due to the resources needed to hold the event (this is the hardest event to hold organizational-wise on a large level).

MBLD Combined Rounds: I have to disagree with this decision. As stated above, MBLD is the hardest event to hold as an organizer. In order to accommodate a large amount of competitors the staff for the competition have to be dedicated, as well as a large amount of time for the event (generally speaking it will take longer than 1 hour for an average competition). For larger events, using a cutoff allows, for example, dedication a large amount of time and staff for the event for the first attempt while having the other two attempts only be for a small number of competitors. This allows more people to compete while not causing a detriment in the amount of time used from the competition. So, I would really like to see the combined formats stay for multi-blind.

**Comment by lgarron** [comment]
> MBLD Combined Rounds: I have to disagree with this decision. As stated above, MBLD is the hardest event to hold as an organizer. In order to accommodate a large amount of competitors the staff for the competition have to be dedicated, as well as a large amount of time for the event (generally speaking it will take longer than 1 hour for an average competition).

Hmm, the way we're calculating stats shows only one combined round for multi. The earlier accidental removal shows a few more examples: https://github.com/thewca/wca-regulations/pull/690#pullrequestreview-191970955

However, our approach might have lots of false negatives. Do you have a way to find/calculate how often this is actually used in practice?

**Comment by Jambrose777** [comment]
MBLD Bo2 with Bo1 Cutoff:

Competition | # of Competitors Cutoff
-- | --
Euro2012 | 17
Euro2014 | 28
Euro2016 | 33
WC2011 | 17

MBLD Bo3 with Bo1 Cutoff:

Competition | # of Competitors Cutoff
-- | --
CzechOpen2014 | 5
KievSuperBlind2019 | 9

MBLD Bo3 with Bo2 Cutoff:

Competition | # of Competitors Cutoff
-- | --
NordicChampionship2018 | 17
WC2017 | 56

Queries: 
`SELECT competitionId, COUNT(DISTINCT personID) FROM Results 
WHERE eventId = '333mbf' AND formatId = '2' AND value2 = 0
GROUP BY competitionId, roundTypeId`
`SELECT competitionId, COUNT(DISTINCT personID) FROM Results 
WHERE eventId = '333mbf' AND formatId = '3' AND value2 = 0
GROUP BY competitionId, roundTypeId`
`SELECT competitionId, COUNT(DISTINCT personID) FROM Results 
WHERE eventId = '333mbf' AND formatId = '3' AND value2 <> 0 AND value3 = 0
GROUP BY competitionId, roundTypeId`

So as you can see, its generally only the big competitions that have utilized this, which makes sense why the number of times utilized is low since we have so few of them.

**Comment by Jambrose777** [comment]
Just noticed: I’m also fine completely removing the cutoff for 3x3. Its is always recommended not to use, and hasn’t ever caused an issue per say. I’ll run some stats tonight for 2x2, pyraminx and skewb as those events are recommended not to have a cutoff (not as strongly as 3x3) and the cutoffs typically provide no value unless hey are extremely low. So maybe some other restriction on this would be good?!?

**Comment by viroulep** [comment]
I agree with Jacob about the cutoff for Multi: it's use very rarely but in these case it was pretty useful.
It's worth noting we could have had a much stricter qualification limit for WC2017 (it was >= 5 points, cutoff was >= 10 points), but we wanted to accommodate as many competitors as possible and we were not able to accommodate the 90 competitors registered on Saturday because of staff constraints.


I think we need to keep the cutoff for 2x2/Pyraminx/skewb.
Again in big competitions you could want to keep these events open to everyone (ie: no qualification time), yet you have not infinite time and cutoff is a reasonably reliable tool to make sure X competitors only do 2 solves (to use the WC2017 example, we needed to have 300 competitors be done with 2x2 in 30 minutes, we couldn't have done this without setting the cutoff appropriately; the same applies to Euro2018, and will most likely apply to WC2019).

**Comment by lgarron** [comment]
Okay, I'll send a PR that conservatively keeps:

- FMC:
  - Bo1
  - Bo2
  - Bo1/Bo2
  - Mo3
  - Bo1/Mo3
  - Bo2/Mo3
- Multi-Blind:
  - Bo1
  - Bo2
  - Bo1/Bo2
  - Bo3
  - Bo1/Bo3
  - Bo2/Bo3
- 3BLD, 4BLD, 5BLD:
  - Bo3
- Everything else:
  - Ao5
  - Bo2/Ao5

**Comment by jamesquinn1** [comment]
@lgarron 
mbld mo3? assuming that being added was just a mistake.

**Comment by lgarron** [comment]
> @lgarron
> mbld mo3? assuming that being added was just a mistake.

Are you referring to https://github.com/thewca/wca-regulations/commit/ddb6a6638f5295630af944e7a20036f027754a33#r32347538 ? That's already fixed!
