### ISSUE TITLE
A1c and time limit

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#694]
Following a recent post on CF where someone got 5 DNFs in an event due to time limit, it beg the question: Does A1c intend to cover time limit DNFs? A competitor could always get lucky so there needs to be discussion on this.
One way to prevents this is to make the time limit the default cutoff for anything other than a Bo-X format.

**Comment by Goosly** [comment]
> One way to prevents this

To prevent what?

**Comment by xsrvmy** [comment]
> > One way to prevents this
> 
> To prevent what?

Prevent a competitor from wasting time by going over the time limit every solve

**Comment by SAuroux** [comment]
The right way to do this would be setting a cutoff. Without a cutoff, every organizer has to be prepared for someone taking 5*time limit for an average. It is as simple as that.

And yes, A1c does of course cover DNFs caused by a time limit. However, not everyone reaching the time limit 5 times should have been stopped using A1c. If the time limit is 1:00, a competitor averaging 2:00 certainly competes with the expectation of DNF (and can immidiately be disqualified once it is clear that he is nowhere near solving the puzzle when reaching the time limit), but a competitor averaging ~1:05 clearly doesn't (and might only get a non-DNF within attempt 3-5).

**Comment by xsrvmy** [comment]
@SAuroux I was just wondering since a competitor can potentially still make cutoff by, for instance, trying to get a EPLL skip on feet (1 out of 12 solves). However I have never heard of anyone with a lower success rate on 5bld being banned.

**Comment by SAuroux** [comment]
If a competitor normally being far from making the time limit is even able to make a cutoff, then this pretty much equals very very bad scheduling. I really don't see any issue needing to be solved.
