### ISSUE TITLE
Allow to wear camera on any part of the body

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-regulations#708]
David Adams shared this feedback with the WRC a couple of days ago:

>I would like to propose the exception in 2i2b (https://www.worldcubeassociation.org/regulations/#2i2b), which allows a head mounted camera, be changed to the following wording: 
> > Exception: the competitor may wear a camera mounted on their ~~head~~ person, as long as it is out of their sight and it is clear that they are not interacting with it (apart from wearing it).
>
> Reasoning: This exception is overly narrow. If a competitor has a different way to mount their camera on their person it should be allowed as long as it is clear they are not interacting with it. A specific example is a camera mounted on the strap of a backpack which is a common set up used for live 'IRL' streaming and was disallowed at SacCubing VI 2019. 
>
> I see no downside to making this change.

The 2i2b exception was added in 2015 (#178, #264), adjusting the Regulations because some cubers started to do youtube videos with camera mounted on their head.

I don't know how popular other setups are, but this is something we might consider.

There is one concern I have: David mentioned this is a common set up for 'IRL' streaming, and I'm concerned about the fact a competitor in the waiting area may very well be watching the streaming and get a very nice angle and a lot of information on their upcoming solves.

But this is more something that has to do with "IRL streaming" during competitions rather than the proposed change of wording (which I think should be ok).

**Comment by pedrosino** [comment]
Probably a typo:
> Exception: the competitor may wear a camera mounted *on their head person*, as long as it is out of their sight and it is clear that they are not interacting with it (apart from wearing it).

I'd suggest "...on their body ..."

This sounds fine to me as well.

**Comment by viroulep** [comment]
Right, "head" was actually stroke-through in the mail but I lost the formatting.

**Comment by lgarron** [comment]
Just noticed I haven't commented on this issue yet.

I'm against this change because I think we need to be extremely careful when it comes to making allowances for electronics during the solve — particularly cameras. I view filming solves as more of a privilege than a right, and I think it's important to restrict the possible ways that a competitor can do it, if we want judges to be able to make consistent calls about what is safe enough.

If we think David's experimentation is valuable, I think we should find a way to give permission to try this at individual competitions, until we understand better what the practical implications are.

**Comment by hanwu85** [comment]
I am going to close this issue.  If anything new comes up regarding cameras , you are welcome to reopen this one.
