### ISSUE TITLE
Create a list of events that should not be ever removed

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#711]
Since feet removal was announced there have  been discussions about the removal of other events, mostly clock, but also less popular events like 6, 7 and 5bld. Should we keep a list of events that should not be removed so we don't have to worried about getting into an event just to have it removed in a year?

**Comment by Jambrose777** [comment]
I would see this as WCA favoring some events over others, which I don't think is an appropriate action for WCA to take. If WCA ever wants to remove an event it's removal should be announced long before it is actually removed so that no one is surprised by the removal.

Further, if we do create this list, I'd like to see each of the 18 events listed as should never be removed.

**Comment by lgarron** [comment]
I also disagree with such a list. The most "permanent" decisions we could make would be to enshrine something in the by-laws, which I don't thinks is appropriate.

As I've stated in other places, I would much rather see the line between official and unofficial events be softened, so that official status for an event isn't make-or-break for competitors who like it.

**Comment by J-Rohault-dF** [comment]
We already know that the main event (3x3x3) should stay, it is in the idea of the WCA.
I will however link to the #636 case, as it could be part of a shift in the WCA's stance since 2014 on events.

**Comment by Samuel-Baird** [comment]
Events aren’t just removed willy nilly, if they are getting removed there is a valid reason behind it. No reason to lock in the events when we may need to or want to change them in the future.

**Comment by lgarron** [comment]
I'm closing this in favor of #758, which is about the general concept of splitting events into tiers. One tier would be expected to have rare changes.
