### ISSUE TITLE
What happens if the judge forgets the opaque object during BLD?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#712]
We have a precedent that an extra is not needed: https://www.worldcubeassociation.org/incidents/5

However, I'm uncomfortable with the effect that that not blocking the competitor's sight is "okay" as long as it was an accident.

**Comment by xsrvmy** [comment]
In some ways there are two seperate concerns here:
1. judge forgets paper
2. competitor forgets to put up sight blocker, and judge fails to intervene

I think we need to clarify whether the competitor is responsible for raising the sightblocker, or if the judge isresponsible for using paper if necessary

**Comment by kingmathyall** [comment]
I believe we shouldn't punish an innocent competitor for a judge's mistake adn it's very hard to put that in as a regulation as judges could then take advantage of this if they are judging someone they may not like so much (or something of the sort).

I think that if the delegate has reason to believe the competitor may have gained an advantage from not having the blocker, then they should accept the extra. However if there is no suspicion that the competitor gained an advantage from a missing paper due to the judges error, I say the result should stand.

**Comment by kingmathyall** [comment]
Also, the same precedent here:
https://www.worldcubeassociation.org/incidents/21

**Comment by lgarron** [comment]
I think these incidents are now happening at a rate that is unacceptable or WCA standards.

I am very concerned about setting bad incentives — particularly for organizers and judges — so I think I think that an extra should be used if the incident is discovered at the competition. @thewca/wrc-team, what do you think?

I also think we should find a way to provide an incentive to prevent these kinds of mistakes, such as:
- Requiring stronger measures/more resources to prevent such issues when they are found at competitions by a given organizer.
- Charging a fee to the organizer, possibly used to reimburse the competitor.
- ...?

One problem here is that presumably sloppy competitions are correlated with sloppy reporting. Videos can help catch some cases, but I don't want to to introduce an antagonistic "bounty".

**Comment by lgarron** [comment]
Wild idea: allow competitors to say "sight blocker, please" so that experienced competitors can reduce the chance of incidents with their solves.

**Comment by xsrvmy** [comment]
I don't think charging a fee to the organizer is reasonable since most of the time random competitors are judging.
Also such an idea may cause incidents if a competitor wants a large reimbursement for a CR/WR fail due to judge error. (Note that after the 3.47 Qiyi and Moyu both require video to claim the prize money, so getting away with not uploading a video is not an option.)

**Comment by viroulep** [comment]
I think this is the only kind of incident where we don't have a "clean" record about what to do, here is what I've found so far regarding our decisions.
  - [Incident](https://www.worldcubeassociation.org/incidents/5) where the Board made the decision (extra available)
  - [Incident](https://www.worldcubeassociation.org/incidents/21) where the WRC made the decision (extra available)
  - [Incident](https://www.worldcubeassociation.org/incidents/30) where the WRC made the decision (no extra available)

I quickly went through our history and we have a lot of incidents where no extra was available (I've linked all of them to the relevant incident entry), and where the result was just accepted!

When an extra was available there was a couple of occurrences:
  - Dayton 2017, the WRC decided to take the original attempt
  - PBQ Oshawa 2019, the WRC decided to take the extra attempt
  - PBQ Berkeley 2018, an extra was available, Lucas said it was fine to use the existing time (no WRC discussion)
  - SacCubing VI: initially the extra was kept following the "usual" approach that valid attempts are better than attempts where the procedure was not followed.
  - Manchester Open 2019, TGBBO2019: was detected during the competition, UK Delegates gave an extra and kept it (no WRC discussion)

Slightly related, as it was detected during the competition:
  - Melbourne cube days 2018: detected during the competition. The Delegates found the PBQ Berkeley 2018 incident and didn't grant an extra attempt.

So when no extra available I think we have a clearly followed policy: if we don't suspect anything fishy, we accept the attempt (and usually there is the video showing part or all of the solve).

We need to clear what to do when it happens during the competition (ie: give an extra, do not give an extra), and what to do after the competition if we have an extra.

>I believe we shouldn't punish an innocent competitor for a judge's mistake adn it's very hard to put that in as a regulation as judges could then take advantage of this if they are judging someone they may not like so much (or something of the sort).

I think in this particular example we could disqualify the competitor per [2k4](https://www.worldcubeassociation.org/regulations/#2k4), but in general I agree with the "we shouldn't punish a competitor for a judge's mistake".

We have this usual approach of considering that a "proper" extra attempt is better than an attempt where some procedure has not been followed properly, which I find very sound.


I think I'd rather opt to use the extra attempt all the time.
It's pretty much the same situation as for miscrambles: when it's detected after the competition and we judge no advantage has been obtained we keep the original attempt; when it's detected during the competition or an extra is available we keep the extra.

Maybe stating that reviewing the video evidence of the solve could lead to keep the original time is something we could clearly put forward?
A lot of competitors film their solves so that may be done in a bunch of cases.

**Comment by xsrvmy** [comment]
There is a special case that I just mentioned in another issue. I think we should discuss what happens if the sightblocker is missing because the competitor stats the solve when the judge is not ready. In that case it should probably be a DNF instead.

**Comment by lgarron** [comment]
> So when no extra available I think we have a clearly followed policy: if we don't suspect anything fishy, we accept the attempt (and usually there is the video showing part or all of the solve).

I don't really like this precedent, but I don't have any great alternatives without punishing the competitor or relying on a general approach to #121.


> We have this usual approach of considering that a "proper" extra attempt is better than an attempt where some procedure has not been followed properly, which I find very sound.

I agree with this.

> I think I'd rather opt to use the extra attempt all the time.

Given how you laid things out, I think this is the best option.

Would you mind drafting a Guideline for this?
(It might even be worth making a general Regulation for "procedural mistakes that are not the competitor's fault, but are caught at the competition", and referencing this from multiple Guidelines.)

One minor remaining concern that comes to mind is "should we treat records specially?"
The de facto WCA policy (at this point) is to verify the scramble for every WR. Unless footage is available at the competition, it's not possible to verify the use of a sight blocker for BLD. But if we later find evidence/footage of a BLD record that didn't use a sight blocker, it would make me rather uncomfortable. :-/
(However, note that a mis-scramble can be useful to a competitor regardless of whether they meant to gain an advantage, while BLD solvers would intentionally need to look under their blindfold in order to gain an advantage.)

**Comment by xsrvmy** [comment]
@lgarron 
> It might even be worth making a general Regulation for "procedural mistakes that are not the competitor's fault, but are caught at the competition", and referencing this from multiple Guidelines.

There are procedural mistakes that cannot be taken advantage of, so these should probably not be included in the guideline. Examples that come to mind include the cover being lifted too early and missing inspection call outs (provided no penalty occurs of course).

Additionally I feel like this may give the judge too much room to force an extra and say it was an accident.

**Comment by lgarron** [comment]
> There are procedural mistakes that cannot be taken advantage of, so these should probably not be included in the guideline. Examples that come to mind include the cover being lifted too early and missing inspection call outs (provided no penalty occurs of course).

I think these should get an extra.

> Additionally I feel like this may give the judge too much room to force an extra and say it was an accident.

I think we should be more concerned about judges who make mistakes than malicious judges right now.
