### ISSUE TITLE
More clarification on 9p

### ISSUE THREAD

**Issue by Baiqiang** [thewca/wca-regulations#716]
I searched the repo and couldn't find relative issues. If there's one, please let me know.

There were some extreme situations especially on some small rounds. I think it's better to add clarifications

Let's say a competition has an event with 2 rounds. The advancement of final round is 75%. On first round there're 20 competitors so at most 15 competitors can advance. It happens that there're 3 competitors ranking 15th.

1. If 2 of the 3 competitors said they "would withdraw" the final, can the rest one advance?
2. If all 3 competitors said they "would withdraw" the final, can the competitor ranked 18th advance?

My thought for those above 2 is NO. According 9p1, they can't advance. Thus they are not qualifying competitors and can't withdraw.

**Comment by pedrosino** [comment]
If 3 people are tied at 15th, none of them can advance, even if someone withdraws.

**Comment by xsrvmy** [comment]
> If 3 people are tied at 15th, none of them can advance, even if someone withdraws.

A slightly different question: does this still apply if the limit is not the 75% maximum?

**Comment by Jambrose777** [comment]
> > If 3 people are tied at 15th, none of them can advance, even if someone withdraws.
> 
> A slightly different question: does this still apply if the limit is not the 75% maximum?

It's up to delegate discretion. This isn't restricted by the regulations in that case.
Similar to how if you take top 50% and that comes out to be 24.5 competitors, the delegate choses between 24 and 25.

**Comment by Baiqiang** [comment]
@Jambrose777 I think @xsrvmy was saying another question. For example, the advancement is 50%. In first round there're 20 competitors so 10 competitors will advance. What if 3 competitors tied 10th? What if 8 competitors tied 10th?

**Comment by lgarron** [comment]
Sorry for not replying on this issue earlier.
I thought I had posted a comment right after @Baiqiang started the issue, but it looks like it got lost. :-(

I think there are two a priori reasonable interpretations of what is allowed:
1. Advance up to 75% of the previous round, allow withdrawals **only from those who have qualified to advance** at this point, repeat as desired.
2. Remove **all those who are withdrawing from the next round** from consideration, and take up to 75% of total number of competitors the previous round, subject to 9p2 (which implies competitors with matching ranks must advance together).

I think we should go for option 2, because option 1 violates [incentive compatibility](https://en.wikipedia.org/wiki/Incentive_compatibility).

Suppose there are 20 competitors in an FMC round, and the following results:

| Rank | Person | Attempt 1 | Attempt 2 | Attempt 3 |
|-|-|-|-|-|
|14|A|29|29|29|
|15|B|30|31|32|
|15|C|30|30|33|
|15|D|32|31|30|
|18|E|35|35|35|

Let's say we go with interpretation 1, and suppose B and C withdraw. Then D can't advance. But if D would have done significantly *worse* by getting a 40-move solve on the last attempt instead of 30 then they'd be allowed to advance!

I think we should codify interpretation 2. In the spirit of the WCA, I think we should also recommend that organizers should prefer to advance more people rather than fewer (i.e. if competitors at the cutoff rank are tied, let them all advance rather than none advance, as long as no more than 75% advance).

This would mean the following:

> 1. If 2 of the 3 competitors said they "would withdraw" the final, can the rest one advance?

Yes, competitor D can advance.

> 2. If all 3 competitors said they "would withdraw" the final, can the competitor ranked 18th advance?

Yes, competitor E can advance. I believe organizers commonly "chain" [9p3](https://www.worldcubeassociation.org/regulations/#9p3), allowing next-ranked competitors to keep qualifying advancement every time someone additional withdraws.

> For example, the advancement is 50%. In first round there're 20 competitors so 10 competitors will advance. What if 3 competitors tied 10th? 

In this case, the recommendation would be to advance 13, although 9 is also acceptable (and theoretically any amount ≤15 is okay per 9p2a).

> What if 8 competitors tied 10th?

If not enough withdraw, only 9 can advance.
If at least 2 competitors with rank ≤17 withdraw, all the others can advance (although only advancing from the top 9 is acceptable).

**Comment by xsrvmy** [comment]
We may want to consider round limits in regard to this as well. If the cutoff of the third-to-last round is top 8, and there is an 8th place tie, then one person has to withdraw in order to hold as many rounds as scheduled. This can result in a competitor unsportingly asking another competitor to withdraw in order to get an extra round. I would think that in the case the organizers should be required to let the tie advance to prevent this type of behaviour. (Also the proposed code of conduct can be helpful here)
