### ISSUE TITLE
Expand 2g3 to include not talking about times

### ISSUE THREAD

**Issue by Jambrose777** [thewca/wca-regulations#720]
https://www.worldcubeassociation.org/regulations/#2g3

In the US it is very common for competitors to talk about their times in the waiting area. This can inherently give information about the scrambles even if it wasn't intended.
An example would be if I said during a 2x2 round: "I got a counting 1." Well everyone would know since I average 3-4 seconds that there are 2 good scrambles in the set. 

I know when I went to Euros, competitors rarely talked about their times; I'm not sure how this compares to the rest of the world with talking about times.

**Comment by xsrvmy** [comment]
One could argue that a loose interpretation of 2g3 already covers this.
Simply banning talking about time will just cause a lot of accidents. There is actually not too much benefit from learning about a fast time that does not result in a reaction. Easy scramble are usually obvious, especially on 2x2.

The events this might actually present a problem for are pyra and skewb. For skewb, easy layers are less obvious. However a lot of faster solves from less advanced solvers come from knowing an alg. Pyra does actually present a problem: knowing a beginner got a fast time probably indicates easy V-first solution, but top first is also popular.

Here is a reasonable alternative:
The delegate reserves the right to disqualify a competitor for indirectly conveying information about a scramble in any way in the competitor's waiting area. If the communication was not intentional, the competitor must be given a warning first.

btw in term of the region issue, China would be even worse since you can see other people's times while lining up, and I recall seeing a cheating incident related to this before.

**Comment by Samuel-Baird** [comment]
Easiest way to avoid this would probably be to disallow competitors from taking in the competitor waiting area.

**Comment by maconard** [comment]
> Easiest way to avoid this would probably be to disallow competitors from taking in the competitor waiting area.

Except that's unreasonable, and people will stop going to competitions if they're too restricted and not allowed to be social

**Comment by Samuel-Baird** [comment]
Not really, it makes it far easier to enforce than just disallowing them to specifically talk about scrambles. Also it’s just a few minutes for each event, you still have plenty of time to socialize.

**Comment by Jambrose777** [comment]
> Not really, it makes it far easier to enforce than just disallowing them to specifically talk about scrambles. Also it’s just a few minutes for each event, you still have plenty of time to socialize.

Hey Sam, this comment makes me think that you haven't gone to a competition. Let's take a look at my upcoming competition: https://www.worldcubeassociation.org/competitions/GACubersSunset2019#competition-schedule

I'll probably make all finals, and all finals are 1 group, so I would have to not talk for approximately an hour and a half. This is certainly on the lower end of consecutive competing time that many competitors experience.

**Comment by Samuel-Baird** [comment]
> > Not really, it makes it far easier to enforce than just disallowing them to specifically talk about scrambles. Also it’s just a few minutes for each event, you still have plenty of time to socialize.
> 
> Hey Sam, this comment makes me think that you haven't gone to a competition. Let's take a look at my upcoming competition: https://www.worldcubeassociation.org/competitions/GACubersSunset2019#competition-schedule
> 
> I'll probably make all finals, and all finals are 1 group, so I would have to not talk for approximately an hour and a half. This is certainly on the lower end of consecutive competing time that many competitors experience.

I have actually been to several comps, just didn’t think it through. I’m usually chatting away while helping scramble or while hanging out so I didn’t consider things like back to back to back finals. My bad on that one :) 

If you would like to still allow talking how would you enforce discussing results? Currently there is already very little being done about competitors discussing scrambles too so I feel like we already are lacking there.

Also something else I thought of, spectators who react to solves. By reacting they are informing competitors of a good result, should we add a something for disqualifying competitors or removing spectators from the venue for reacting perhaps? It would be pretty nice to not hear screaming and see people running from all over after fast solves.

**Comment by xsrvmy** [comment]
@UnderwaterCuber Not allowing talking in the competitor area and preventing reactions are both unreasonably strict and basically impossible to enforce. To some extent though there is a different solution. All rounds can be done stationary the Chinese way so there is less interactions between competitors as a whole.

You are not going to solve the seeing times problem unless competitors is visually seperated from each other and that is not reasonable for organizers.
