### ISSUE TITLE
Update 3h2a

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#736]
3h2a states that stickerless puzzles with transparent parts are not allowed. This no longer appear to carry the intended meaning since puzzles like the gans X and the gts3 have transparent parts in the mechanism but not the colored parts. One potential fix would be to change 'part' to 'colored part'.

**Comment by lgarron** [comment]
I think we should revisit this, but I think we need even more nuance:

- Transparent plastic with colored stickers is not okay.
- There are a lot of translucent "jelly" puzzles. Some are barely translucent and arguably provide no more of an advantage than stickerless, but I would prefer to make the simple decision that these are never allowed.

**Comment by xsrvmy** [comment]
Transparent puzzles with stickers don't belong in 3h2a to begin with. Tha should be a seperate reg.
Another thing we need to consider is that scs is in the process of developing transparent coated stickerless puzzles, so there needs to be a clear policy on whether that is allowed.
Also there is another possible wording: if a stickerless puzzle has a transparent part, it must not expose extra information to the competitor (exception: a logo)

**Comment by Sixstringcal** [comment]
[YouTuber "JPerm" has released this video on this scs coating](https://www.youtube.com/watch?v=fPrTDthq1sM).  Apparently it has been used in competitions (not sure how many), but it is more than just a coating it seems, it also seems to be extra transparent stickers.  I'm not sure how it all works, but I'd imagine that with the current wording of 3h2a this would not be allowed since there are transparent stickers additionally?  I'm also not sure how the coating part works with this reg, especially since I don't understand the coating part.

**Comment by hanwu85** [comment]
My personal view is:  although the clear coating could be considered "transparent parts" but they give no advantage, since the whole puzzle is uniformed with this coating, it should be competition legal.

**Comment by xsrvmy** [comment]
I think there is an interpretation issue. The whole point of 3h is the amount of information that is provided to the competitor. Under this interpretation, another possible wording is "transparent parts which reveal more information about the puzzle are not allowed".
