### ISSUE TITLE
Update "must have at most ___ subsequent rounds"

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#755]
"must have at most ___ subsequent rounds" implies that there must be at least one subsequent round. We should use a different phrase that is as clear as possible (inc. to non-native English speakers).

**Comment by pedrosino** [comment]
9m) Events can have at most four rounds.
9m1) Rounds with less than 100 competitors can have at most two subsequent rounds.
9m2) Rounds with less than 16 and more than 7 competitors can have at most one subsequent round.

**Comment by Jambrose777** [comment]
You would also need a case for <7 otherwise an event with 6 competitors can have 3 rounds acording to the criteria

**Comment by Ranzha** [comment]
It's a little less elegant, but "must have no more than _ subsequent rounds" may be a slight improvement. I'm not sure if this keeps the "lower bound" implication in other languages.

**Comment by maconard** [comment]
Is it unreasonable to just use "total rounds" as the metric? That's what makes the most sense to me.

9m) Events can have at most 4 total rounds.
9m1) Events with fewer than 100 competitors in round 1 can have at most 3 total rounds.
9m2) Events with fewer than 16 competitors in round 1 can have at most 2 total rounds.
9m3) Events with fewer than 8 competitors in round 1 cannot have any additional rounds.

That's what seems to make most sense to me, and would also be least confusing to non-native English speakers as well since it's clear and doesn't use obscure phrasing.

**Comment by maconard** [comment]
I don't think "must have at most x subsequent rounds" implies that there must be a subsequent round, since 0 will always be <= x. However, I think the "must have" and "at most" and "subsequent rounds" make for a mouthful of a phrase that would definitely be confusing to non-native English speakers, and likely even typical English speakers taking a first glance at it.

**Comment by poiuytre121** [comment]
Hi to You all, first comment here :)
@maconard Your current proposal with total rounds allows for 4 rounds where in first round we have 100 competitiors, in second round 3 competitors, in semi-final 2 competitors and a single competitor in the final, which is not possible under current regulations and definitely was not intention of this regulation.

Personally I would go with slightly upgraded version of @pedrosino proposal:
9m) Events can have at most four rounds.
9m1) Rounds with 99 or fewer competitors can have at most two subsequent rounds.
9m2) Rounds with 15 or fewer competitors can have at most one subsequent round.
9m3) Rounds with 7 or fewer competitors cannot have any subsequent rounds.

But if phrase "subsequent round" is the problem here, perhaps "following round" would be better? We already have it in Regulation 2n1. That would leave us with:

9m) Events can have at most four rounds.
9m1) Rounds with 99 or fewer competitors can have at most two following rounds.
9m2) Rounds with 15 or fewer competitors can have at most one following round.
9m3) Rounds with 7 or fewer competitors cannot have any following rounds.

I don't see how "at most" could be troublesome even to non-native speakers, but if it is a trouble then maybe something like this:
9m) Events can have at most four rounds.
9m1) Rounds with 99 or fewer competitors can have maximum of two following rounds.
9m2) Rounds with 15 or fewer competitors can have maximum of one following round.
9m3) Rounds with 7 or fewer competitors cannot have any following rounds.

For me first option is best one, but any of them seems fine.

**Comment by maconard** [comment]
You're correct, was an oversight and is why I should be sleeping instead of commenting at midnight :-)

I don't think "at most" or "must have" are difficult on their own, it just seemed like a lot of phrasing when all mashed together. Your second version in your comment seems great! Maybe "further" instead of "following" :)

**Comment by lgarron** [comment]
> Is it unreasonable to just use "total rounds" as the metric? That's what makes the most sense to me.

We can't quite do this, because 100 → 3 → 2 → 1 is not allowed (and I don't think it should be). :-(

**Comment by maconard** [comment]
@lgarron Yeah, I understand, realized reading my own comment the next morning.

**Comment by maconard** [comment]
Just another attempt at wording that includes the "total rounds" phrasing and also clearly states all the numbers without obscure wording. I believe this also accounts for @lgarron's original concern that it implies there must be more than 0 additional rounds, too.

9m) Events may have 1, 2, 3, or 4 total rounds.
9m1) A round with greater than 99 competitors may have 0, 1, 2, or 3 additional rounds, not exceeding 4 total rounds.
9m2) A round with 16 to 99 competitors may have 0, 1, or 2 additional rounds, not exceeding 4 total rounds.
9m3) A round with 8 to 15 competitors may have 0 or 1 additional rounds, not exceeding 4 total rounds.
9m4) A round with 0 to 7 competitors may not have any additional rounds.

Thoughts? (Can use English words or numerals, whatever is preferred for the document. Probably <=20 as English and >20 as numerals.)

**Comment by poiuytre121** [comment]
I don't like it because I had to read it 3 times to get what this is all about + "A round with 0 to 7 competitors may not have any additional rounds." implies there can be a round with 0 competitors. Also "not exceeding 4 total rounds" repeating in every sub-regulation doesn't improve readability either. "Additional round" instead of "subsequent round" or "following round" for me feels like we were rather talking about something that can be added during competition (so it isn't there by default) than about carefully planned schedule.

**Comment by maconard** [comment]
@poiuytre121 A round can have 0 competitors. Imagine a comp in a small area is organized with 7x7 and the delegate doesn't want to solve 7x7 and the 17 people that registered all don't know how to solve it. That round will have 0 competitors and rightfully so should not be allowed any further rounds. I'd imagine it would just be skipped at the real life competition, but it was technically a scheduled round. Another example of a round with 0 competitors would be if all competitors that progressed to that round dropped the event.

Yes, the repetition of "not exceeding 4 total rounds" is unnecessary. I thought I'd mentioned that in my comment but it seems I deleted it before posting; I just left it there for the clarity of this discussion, as it is of course captured by 9m and does not need to be repeated. Maybe 9m could say "and 9m overrules the following 9m# regulations." 

I think additional/subsequent/following all feel about the same, but people that don't have English as their first language may be missing "subsequent" from their vocab. Either way, it's meant to capture rounds that are scheduled and rounds that are added the day of the competition. 

I'm not sure why you had to read it 3 times? 

Regardless, I'm not saying it's perfect, was just another phrasing to spur this sort of discussion :)

**Comment by pedrosino** [comment]
Another try:

>9m) Events may have a maximum of four rounds, with the following limits [applied]:
>9m1) Rounds with less than 100 competitors may have at most (or a maximum of) two subsequent rounds.
>9m2) Rounds with less than 16 competitors may have at most (same as above) one subsequent round.
>9m3) Rounds with less than 8 competitors cannot have any subsequent rounds. 

Or maybe a simpler version:

>9m) Events may have a maximum of four rounds, with the following requirements:
>9m1) For three subsequent rounds, at least 100 competitors.
>9m2) For two subsequent rounds, at least 16 competitors.
> 9m3) For one subsequent rounds, at least 8 competitors.

**Comment by xsrvmy** [comment]
How about "Events may have a maximum of four rounds. Non-final rounds are subject to the following requirements on the number of subsequent rounds: ...(simpler version)"

We should also clarify if restrospective round removals (eg. first result restrospective DNF leads to second round not having enough competitors) should be allowed. In my opinion they shouldn't because competitors would lose results over the misbehaviour of another competitor, and possibly months after the original competition.
