### ISSUE TITLE
Split events into tiers

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#758]
The list of official events has stagnated. The main resistance to adding a new event is that major competitions (especially championships) feel obligated to hold it.

If split events into a "core tier" and other tiers, it could give us more flexibility to breathe life into our puzzles and event formats.

I don't think we're ready to adopt this directly in 2020, but I think we should think about it as a potential solution to work towards. It could be either an alternative to ephemeral events (#636) or a separate solution.

**Comment by HippolyteM** [comment]
Hi,
I am strongly against this idea (and so am I against temporary events).
I don't think it makes sense to officially create a hierarchy between our official events. 333 have a special status, but other than that all events should be equal in our regulations.
> The main resistance to adding a new event is that major competitions (especially championships) feel obligated to hold it.

Well, I don't think this is an issue at all. Actually, I think it should even be mandatory for championship to host every event. It doesn't make sense to me to hold wca championships where all wca events aren't included.
This is why I feel if we're not going to give en event "full attention" (not including it at championships would be the most symptomatic), then we would better not have it at all.
There are countless possibility of events, with thousands of existing puzzles now, and many possibility for each (oh, feet, blind, multi, team-blind, fm, etc.). The arbitrariness of the choice of our set of event will always remains, and I don't see how it's bad, because it has to be.
In my opinion, we already have way too many events for our sake, so this process of allowing many events but with restricted possibilities (defined amount of time, big coms not holding them, etc) would only lead to more frustrations, more angry debates about the status of events, and way more complications for delegates and organizers.

**Comment by maconard** [comment]
I think it's worth pointing out that the community sort of already has 2 tiers for the events - typically "main events" and "side events," where main includes 2, 3, 4, 3BLD, OH and side includes 6, 7, pyra, skewb, mega, 4BLD, 5BLD, etc (roughly). Sometimes even a "slow events" tier too, which includes FMC, 4BLD, 5BLD, mBLD, and sometimes feet.

Non-championship competitions tend to already use this tiering in planning their schedules; such as finishing up main events on the Saturday of a competition and having side events on Sunday so people not interested in side events can leave, or having slow events on Fridays before the rest of the events start on the weekend.

That said, I think it makes sense to leave this tiering to the community and out of the regulations. I'm also not in favor of adding temporary puzzles - what motivation is there to buy equipment and get good at something when your hard work becomes meaningless in a short time? We should add events we're fully committed to maintaining. I think Kilominx, Master Pyraminx, and maybe even Redi Cube are great candidates for this if we are looking to add some "fresh" official events, especially with the (sad) removal of Feet inbound.

**Comment by mintydev789** [comment]
> Hi,
> I am strongly against this idea (and so am I against temporary events).
> I don't think it makes sense to officially create a hierarchy between our official events. 333 have a special status, but other than that all events should be equal in our regulations.
> 
> > The main resistance to adding a new event is that major competitions (especially championships) feel obligated to hold it.
> 
> Well, I don't think this is an issue at all. Actually, I think it should even be mandatory for championship to host every event. It doesn't make sense to me to hold wca championships where all wca events aren't included.
> This is why I feel if we're not going to give en event "full attention" (not including it at championships would be the most symptomatic), then we would better not have it at all.
> There are countless possibility of events, with thousands of existing puzzles now, and many possibility for each (oh, feet, blind, multi, team-blind, fm, etc.). The arbitrariness of the choice of our set of event will always remains, and I don't see how it's bad, because it has to be.
> In my opinion, we already have way too many events for our sake, so this process of allowing many events but with restricted possibilities (defined amount of time, big coms not holding them, etc) would only lead to more frustrations, more angry debates about the status of events, and way more complications for delegates and organizers.

I think you misunderstood something. If there were two tiers of events, the current list would first have to be shrunk. I personally think 12 events would be a good number for tier 1. The events removed (like the obvious candidates 4bld, 5bld, 6x6 and 7x7 and maybe some others) would be moved into tier 2, giving space for a couple new events. The way I see it, the tiers would be there to ensure that tier 1 is going to stick around for a long time (like skewb) and tier 2 would be there to introduce new events to see if the community likes them. I don't think an event being a tier2 event should mean that it will have to go at some point. The tier 2 list just has to be more flexible. I also think that EVERY event introduced into any tier MUST have at least one WC to prove itself and to pick a world champion. I think the minimum time for an event should be 2 years and the maximum is determined by how much the community likes it.

**Comment by mintydev789** [comment]
> I think it's worth pointing out that the community sort of already has 2 tiers for the events - typically "main events" and "side events," where main includes 2, 3, 4, 3BLD, OH and side includes 6, 7, pyra, skewb, mega, 4BLD, 5BLD, etc (roughly). Sometimes even a "slow events" tier too, which includes FMC, 4BLD, 5BLD, mBLD, and sometimes feet.
> 
> Non-championship competitions tend to already use this tiering in planning their schedules; such as finishing up main events on the Saturday of a competition and having side events on Sunday so people not interested in side events can leave, or having slow events on Fridays before the rest of the events start on the weekend.
> 
> That said, I think it makes sense to leave this tiering to the community and out of the regulations. I'm also not in favor of adding temporary puzzles - what motivation is there to buy equipment and get good at something when your hard work becomes meaningless in a short time? We should add events we're fully committed to maintaining. I think Kilominx, Master Pyraminx, and maybe even Redi Cube are great candidates for this if we are looking to add some "fresh" official events, especially with the (sad) removal of Feet inbound.

I partially replied to your question too in my comment above. A tier 2 event can stick around for as long as the community at large enjoys it and it has value.

**Comment by xsrvmy** [comment]
Here is a suggestion:
- Each event is placed in tier 1-3, 1 being best and 3 being worst.
- after each WC, tiers are moved around. Events can only move down one tier at a time, but tier 3 can move up to tier 1.
- If an event stays in tier 3 after the change then it is considered a candidate for removal. If removal is announced then the event is removed after a set period of time (eg. 6 months), so that competitors do not waste time preparing for scheduled comps.
- Depending on community interest, new events are added to tier 3 or 2, but not 1. If an event is added within one year of WC, it does not become a candidate for removal even if it stays tier 3 after the WC (preventing short-living events).
- Community interest should be measured according to number of new competitors, improvement of existing competitors/records, and whether more or less percentage of comps are holding the event.
- Obviously 3x3 should not be tiered.

This would guarantee that events take 2-4 years to remove and the process is transparent.

**Comment by mintydev789** [comment]
> Here is a suggestion:
> 
> * Each event is placed in tier 1-3, 1 being best and 3 being worst.
> * after each WC, tiers are moved around. Events can only move down one tier at a time, but tier 3 can move up to tier 1.
> * If an event stays in tier 3 after the change then it is considered a candidate for removal. If removal is announced then the event is removed after a set period of time (eg. 6 months), so that competitors do not waste time preparing for scheduled comps.
> * Depending on community interest, new events are added to tier 3 or 2, but not 1. If an event is added within one year of WC, it does not become a candidate for removal even if it stays tier 3 after the WC (preventing short-living events).
> * Community interest should be measured according to number of new competitors, improvement of existing competitors/records, and whether more or less percentage of comps are holding the event.
> * Obviously 3x3 should not be tiered.
> 
> This would guarantee that events take 2-4 years to remove and the process is transparent.

I think there are some good ideas here, but I'd say it's better to stick with just 2 tiers, because no matter how many tiers you make, there will always be an extra imaginary tier, because some organizers would still want to have events that aren't official to any degree.

**Comment by xsrvmy** [comment]
Well the main idea is prevent event removal at short notice

**Comment by Samuel-Baird** [comment]
With tiers there are two mains things I want to see, events should be representative of different aspects of twisty puzzles and redundancies should be eliminated.

Here are some rough categories of our current events: 2x2, 3x3, skewb, Big cubes (4x4-7x7), blindfolded (3bld), long blind (4-5bld,mbld), fewest moves, handicap (OH), plutonic solids (pyraminx and megaminx) and shapeshifting (sq-1). 

We should do our best to make sure that these aspects are recognized in championships. Some other categories we may want to look into adding are jumbling, cuboids, and shape mods.

I think that we should categorize events into 2 tiers. "Core events" and "side events".

All core events will be held at every worlds, they should be fairly popular events and should cover most categories.

Side events will fill in the categories not covered by the core events at worlds, these can change between worlds (ex. if 6x6 and 7x7 were side events then 2021 may hold 6x6 while 2023 may hold 7x7 to fulfill the big cube category). Side events can be held at any competition. 

The list of core events should be set up to be somewhat hard to modify, side events should be easier to remove or add.

event  | category | core or side event
3x3, main, core
2x2, Small NxN?, core
4x4, medium NxN?, core
3bld, bld, core
one-handed, handicap, core
FMC, efficiency, core
megaminx, plutonic solid, core
pyraminx, plutonic solid, core
sq-1, shape-shifting, core
5x5, big cube, side
6x6, big cube, side
7x7, big cube, side
4bld, long bld, side
5bld, long bld, side
mbld, long bld, side
skewb, ?, side

Possible events to add:
curvy copter, jumbling, side
team bld, team, core
kilominx, plutonic solid, side
redi cube, ?, side
mirror cube, shape mod, side

Clock should be either be removed since it is not a twisty puzzle and since it already has its own slew of logistical issues or should be thrown into a "non-twisty puzzle" category as a side event, other things that could go into that category are things like 15 puzzle or geranium puzzles.

**Comment by mintydev789** [comment]
> With tiers there are two mains things I want to see, events should be representative of different aspects of twisty puzzles and redundancies should be eliminated.
> 
> Here are some rough categories of our current events: 2x2, 3x3, skewb, Big cubes (4x4-7x7), blindfolded (3bld), long blind (4-5bld,mbld), fewest moves, handicap (OH), plutonic solids (pyraminx and megaminx) and shapeshifting (sq-1).
> 
> We should do our best to make sure that these aspects are recognized in championships. Some other categories we may want to look into adding are jumbling, cuboids, and shape mods.
> 
> I think that we should categorize events into 2 tiers. "Core events" and "side events".
> 
> All core events will be held at every worlds, they should be fairly popular events and should cover most categories.
> 
> Side events will fill in the categories not covered by the core events at worlds, these can change between worlds (ex. if 6x6 and 7x7 were side events then 2021 may hold 6x6 while 2023 may hold 7x7 to fulfill the big cube category). Side events can be held at any competition.
> 
> The list of core events should be set up to be somewhat hard to modify, side events should be easier to remove or add.
> 
> event | category | core or side event
> 3x3, main, core
> 2x2, Small NxN?, core
> 4x4, medium NxN?, core
> 3bld, bld, core
> one-handed, handicap, core
> FMC, efficiency, core
> megaminx, plutonic solid, core
> pyraminx, plutonic solid, core
> sq-1, shape-shifting, core
> 5x5, big cube, side
> 6x6, big cube, side
> 7x7, big cube, side
> 4bld, long bld, side
> 5bld, long bld, side
> mbld, long bld, side
> skewb, ?, side
> 
> Possible events to add:
> curvy copter, jumbling, side
> team bld, team, core
> kilominx, plutonic solid, side
> redi cube, ?, side
> mirror cube, shape mod, side
> 
> Clock should be either be removed since it is not a twisty puzzle and since it already has its own slew of logistical issues or should be thrown into a "non-twisty puzzle" category as a side event, other things that could go into that category are things like 15 puzzle or geranium puzzles.

I like a lot of your ideas. I would still keep 5x5 as a core event though, as I think it adds a few things that 4x4 lacks. One very unique event I would like to propose is Mirror Blocks BLD. I don't think shapemods or cuboids should ever be added, but Mirror Blocks allows for a puzzle that can be solved completely without looking at it and I believe it could add something quite unique to the events list. The current goal is probably to find a good replacement for feet now that it has been removed and I think many people in the community would agree that Team BLD is a good candidate. I haven't heard of existing issues with it that are major enough and/or can't be solved.
