### ISSUE TITLE
Allow clock pins to be distinguishable

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#759]
At Worlds, I learned that application of [3j++](https://www.worldcubeassociation.org/regulations/guidelines.html#3j++) is *extremely* sloppy at most competitions. (A lot of clocks were rejected at Worlds that have been allowed around the world otherwise.)

We already allow clock inserts to give clear clues about orientation and have been moving more towards an "anything goes" puzzle policy. So I think there's little harm in allowing distinguishable clock pins, so long as they are shaped and function roughly like normal.

**Comment by lgarron** [comment]
I've asked the Board whether they'd support a small release of the Regulations just for this, so that we don't have to wait for 2020.

**Comment by Ivan-Brigidano** [comment]
There is no rule that prohibits using stickers of different colors on the sides of the clock. This causes some people to use a sticker to point to the 12 o'clock side.

So it doesn't make sense to keep all the pins equal to each other as you can easily distinguish a side by doing this. So you could allow the pins of the clock to be distinguishable.

**Comment by pedrosino** [comment]
I agree that pins don't make that much of a difference, and should be allowed to be different from each other.

**Comment by maconard** [comment]
Distinguishable to the point that say, a competitor could have the pins on a side labeled with "1", "2", "3", "4" stickers and such? Or just by color and such?

**Comment by Ivan-Brigidano** [comment]
@maconard I guess @lgarron means that some clocks have some pins with plastic caps and some other pins without it.

**Comment by Jambrose777** [comment]
@ivan-Brigidano and little holes poked in some pins and BW engraved in the pin, etc..

**Comment by Jambrose777** [comment]
@ivan-Brigidano and little holes poked in some pins and BW engraved in the pin, etc..

**Comment by EdHollingdale** [comment]
> At Worlds, I learned that application of 3j++ is _extremely_ sloppy at most competitions

I wouldn't totally agree with saying it is "sloppy" (i.e. inconsistent and poor) but rather stems from a different interpretation of the guideline that has a lot of similarities to the logo discussion for blindfolded events. Some will interpret it as a "is it possible with enough time and thought to distinguish the pins" vs others with a "is it possible, in the reasonable course of a speedsolve of the puzzle, to distinguish the pins".

Under the first interpretation, a pin with a half-millimetre diameter hole in it would not be permitted, while it would be under the second. (Having a mix of pins with/without plastic caps would not be allowed under either interpretation).

I'd be in favour of allowing distinguishable pins of whatever range (mix of caps/no caps, stickers labelling them, almost unnoticeable holes) since, unless I'm mistaken, they would give no advantage that cannot be had with custom inserts.

**Comment by xsrvmy** [comment]
Should we allow the 18 clocks to be distinguishable as well? These seem to be similar issues.

**Comment by Samuel-Baird** [comment]
I for one would support this but there is one other thing I think should be added. There are a few things I have seen frequently,  logos on faces of clocks, when people open their clocks they often damage the outer casing a frequently and damage the plastic, people place non-ring or damaged ring magnets on their clocks in weird ways, all make it possible to distinguish orientation but like pins it doesn't allow any real advantages. I have had to reject puzzles for all of the mentioned cases in the past and it almost always ended up just wasting comp time because the competitor had to search to find a legal clock. I think allowing anything that may let you distinguish orientation by feel would make things a lot nicer
