### ISSUE TITLE
Average of 5 for 6x6x6 and 7x7x7

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#760]
6x6x6 and 7x7x7 are the only timed events with rankings determined by a mean rather than an average. I have heard people suggesting that we should switch to average of 5 for consistency.

With a proper choice of cutoff, this wouldn't necessarily affect competition time used for the events, but it would give fast competitors more solves than slower ones. (However, a cumulative time limit could be a good alternative.)

To be clear, I am *not* advocating for this, but I'm creating this issue to track it.

**Comment by xsrvmy** [comment]
This would really allow for more risky puzzle setups (at least I set up my 6 and 7 fairly tight) because pops are less of an issue. I think the main reason for this change is that currently the event that pops are probably most common in is also the event where a pop affects your average the most.

**Comment by pedrosino** [comment]
Please don't :(

That would mean even more scrambling those 80 and 100-movers, which is already a big pain.
I'd rather have 6x6 and 7x7 removed, but that's a whole other discussion.

**Comment by EdHollingdale** [comment]
I agree with @pedrosino - these puzzles are already a logistical challenge at most competitions as they take so long to run (both in terms of scrambling and solving). If the preferred format were changed to average of 5 then I think the portion of competitions that held them would decrease further, or cutoffs would become significantly harsher.

**Comment by maconard** [comment]
I approached a delegate of an upcoming comp and asked if we could do an experimental ao5 (last two solves unofficial) to collect data on time, competitor satisfaction, etc, for 6x6 and/or 7x7. Hopefully if the comp has time we'll be able to test it out, but it is a possibility there just won't be time for it. If it goes through I can put the data here after, and hopefully it can make an impact by going into the delegate's report as well.

Just to leave my comment: I'd support moving to ao5 for this, as Lucas says it's the only speedsolving event that isn't ao5. I think with a proper cumulative time limit everyone will still get a good amount of solves without holding back a competition. If a comp wants to focus on big cubes and let everybody do 5 solves, they can make the schedule reflect that. Otherwise, it's technically only 4 solves needed to get the average, and even slower cubers should always get 1 or 2 full solves. 

Additionally, there is precedent for moving an event from mo3 to ao5, so the WCA site would inherently support this, with minimal adjustments. CubeComps adjustments shouldn't be super challenging either, but hopefully we won't be worrying about that much longer.

**Comment by aneurinhunt** [comment]
I think for the sake of consistency switching is worth it.  Would it be possible for scrambles to be shorter?

**Comment by cubewhiz** [comment]
Like Pedro, I think removing 6 & 7 is better than changing the format to Ao5.

**Comment by xsrvmy** [comment]
I am at a loss for words as to why WCA officials are actually advocating the removal of events that do not pose organisational issues (and the only events under that category are feet and clock). There is a very big difference between saying that an event should not be added, and saying that an event should be removed.
Suggesting the removal of an event necessarily does not help the popularity of an event. In my opinion it demotivates people who want to get into the event because it might be gone by the time they get good.

**Comment by Jambrose777** [comment]
Saying clock and feet pose an organizational issue is a very subjective opinion. In my region the hardest events to hold are square-1 and 5x5.

I do agree that 6x6 and 7x7 pose no additional or unique challenges and by WRC standards would not even be considered to be added today.

**Comment by xsrvmy** [comment]
@Jambrose777 6 and 7 centers are way more complex than 5x5. We need events that are more free-form in the WCA and 6 7 mega are really the only events that achieve that at the moment.
By organisational issue I was referring to hygiene for feet and just the high number of incidents for clock (knocking over or pins moving)

**Comment by SAuroux** [comment]
@xsrvmy Seriously, you need to read what people actually write before coming up with high-sounding sermons. I personally tend to agree with the statement of @cubewhiz, but I am absolutely NOT advocating the removal of these events as I find keeping 6x6x6 and 7x7x7 with the current formats the correct way to go.

On topic: I don't see how consistency is a valid argument here. It would technically be far more consistent to make 333bf an Average of 5 event than 6x6x6 and 7x7x7. It is just arbitrary to call 6x6x6 and 7x7x7 a "speeed event", but 333bf not despite the fact that 333bf is obviously about the fastest speed as well. But if pure solving vs. memo+solving is something that is accepted as additional dimension not touched by consistency, then I don't see why different length classes cannot be either. 6x6x6 and 7x7x7 take significantly longer for both scrambling and solving than all other events currently held as Average of 5 and they are far less luck based.

**Comment by Burnsy101** [comment]
I'm not sure if this has been said before (it may have) but what about allowing both mo3 and ao5 to be held at comps around the world depending on if the organisers / delegates want to have more or less time for a round of big cubes? It seems that if time is of the essence, they can hold mo3 whilst if a lot of people want to participate or simply have a big-cube themed comp, they can do an ao5: cubecomps could be adjusted and the WCA already has both mo3 and ao5 results in the feet top 100 rankings.
The main drawback is the lack of consistency, but we still hold FMC bo1/2 and mo3 (which I support) and so I don't see it as THAT big of an issue

**Comment by dancing-jules** [comment]
I'm highly against it. This would result in ridiculously low time limits and cutoffs (because organisers WILL lower time limits, not just cutoffs) and in very high entry barrier for slow-ish competitors.
