### ISSUE TITLE
Clarify 3h4 "matches the original inserts"

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#763]
> 3h4) For Clock, custom "inserts" (the same shape and size as the traditional paper inserts) are permitted, at the discretion of the WCA Delegate. The inserts must have a clear indication of 12 o'clock that matches the original inserts.

Recently I saw a dispute in a FB group about a clock insert. The dispute stems from the wording "matches the original inserts", which some people believe to mean that the 12 o'clock mark must be yellow with a red 12 inside it (The insert in question had a differently colored dot but not the number 12 at the top of each clock). Also it is not clear to what extend this interpretation would be applied (does color and size matter?)

However, there is another possible interpretation: the 12 o'clock mark must be on every clock (versus at the top of the entire insert), in a direction parallel to the 3x3 grid, and be in the same direction on both sides.

We should clarify what the phrase "matches the original inserts" means exactly so competitors do not unwittingly create inserts that are not allowed.

**Comment by mintydev789** [comment]
I'd word it as "The inserts must have a clear indication of 12 o'clock that is the same on every clock and points in the same direction". No ambiguity.

**Comment by Sixstringcal** [comment]
But does the number 12 have to actually be present though?  I have a clock (I've never used it in comp since putting this insert in because it's illegal now for other reasons) that the spot for 12 is clearly labeled, but the number it says is 11 (it's a guitar amp skin kind of insert and it's a Spinal Tap reference.  [See reference here](https://www.youtube.com/watch?v=KOO5S4vxi0o).  It's 100% obvious where 12 is (it's where 11 is marked) as it's in bright red (the rest of the insert is dark colors) on top of another guitar dial knob that is significantly larger than any of the other dots.

I feel the insert is legal (again, the puzzle right now isn't for other reasons), but the number 12 is not present.
