### ISSUE TITLE
Allow scrambling extra backup cubes for Multi-Blind

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#766]
Duplicate scrambles for two cubes in the same Multi-Blind are bad, **more easily preventable than most duplicate scrambles**, and it's been proven that you can pretty much eliminate the problem with attentive staff.

That said, duplicate scrambles are still happening. This hurts the competitor:
1) The competitor will need to spend extra time looking at cubes out of order to verify whether it's a duplicate scramble.
2) The cube has to be taken out of the total, lowering their maximum result by 1. Granting an extra is not practical at most competitions, and can be a drain on the competitor.
3) This creates an incentive *not* to report the duplicate scramble. Most competitors are honest, but it's better to avoid such incentives.

I've heard a suggestion that we should allow preparing one or two extra cubes for large attempts. They would be kept outside view and reach of the competitor, but the judge could swap out a duplicate scramble with one of these. This reduces the issue to only the first problem (wasted time/distraction for the competitor).

I think we should recommend this for attempts over, say, 10 cubes. This should be better for competitors, and should help us gather better data.

**Comment by pedrosino** [comment]
I think in theory that looks good, but not everybody has another 2 cubes to serve as backups.
Last time I had to use two 7-cm 3x3x3 to fill up the number I wanted.

**Comment by mintydev789** [comment]
I would also propose changing the scrambling procedure a bit, so that all cubes are scrambled in the same orientation to make checking for duplicates easier, and then randomizing the orientation for all of the cubes. This random order may also be printed out for the MBLD event.

To be clear, I am suggesting this in addition to what you proposed, not instead.

**Comment by Jambrose777** [comment]
The scrambles randomize the rotation already and IMO his already makes it easier for checking for duplicates (as cubes will have he same orientation if they have the same scramble)

**Comment by mintydev789** [comment]
> The scrambles randomize the rotation already and IMO his already makes it easier for checking for duplicates (as cubes will have he same orientation if they have the same scramble)

oh yeah, nvm I'm dumb

**Comment by xsrvmy** [comment]
tbh problems like scrambler loosing track of cube number would be solved if there is a dedicated scramble viewer in the future (wasn't that discussed a while ago when the passwords were instroduced?)

**Comment by Samuel-Baird** [comment]
As for the backup cube(s) idea

I’m not sure how I feel about this, definitely has some pros and cons. The competitors will still have to waste time having the judge check to see if they are duplicates (to avoid competitors getting rid of non-duplicate cubes with bad scrambles in exchange for a backup cube) which is bad but necessary and I can still see issue 3 occurring as a result of that (also the fact that having to only memo once for two cubes is easier). 

Also forces the competitors to buy more cubes for backup, in some regions where they already struggle getting cubes this just puts more strains on the competitor. As a result we have to also keep the old system to handle duplicates which means the same situations are being handled differently. To resolve this you could make backup cubes mandatory and in those regions it would just force competitors to attempt a lower number of cubes. 

As for the orientation idea.

During transportation the cubes orientation may be changed meaning 2 duplicates may not be easily distinguishable. 

I would be ok with removing randomized orientation but since competitors using WCA orientation would have an advantage which saves a little bit of time each cube (which adds up). Competitors s could be allowed to request orientation but this could become annoying especially at large comps.

This also would save time in attempts meaning old results would be beaten more easily (more cubes could be attempted or same number could be attempted for faster times). 

A pro about orienting is it would allow people to easily make some tools to assist with checking scrambles (place all cubes down and take a picture, this can only verify 1 face but still could catch misscrambles and duplicates) 

I would prefer orientation over backups (both could be done though) 

Also how do I reply to specific comments and tag people on github XD

**Comment by xsrvmy** [comment]
Backups should ideally be supplied by the organizors since it's not the competitor's responsibility to prevent duplicates. However that can cause hardware related problems (especially if organizors do not know how to setup a cube for bld)

**Comment by AlexKatyukov** [comment]
Don't sure that it is needed.

1. Anyway, MBLD is a very complicated event. It takes a lot of time to explain why 16/21 is better than 10/10 to newcomers. If we will have 20 uncovered cubes plus 2 covered cubes, it will be more complicated.
2. Extra cubes need to be granted by Delegate. What if Delegate will be in another place at the venue? What if Delegate will solve MBLD himself?
3. Is there a real necessity? I'm not heard about case like that.

**Comment by shivambansal42** [comment]
Hi,
I am Shivam Bansal (former wr holder in mbld) and I would like to share my opinion on this issue. 
I think this is a great addition to the regs. I have attempted 40+ cubes on many occasions officially, and have had at least 3-4 cases now of getting duplicate scrambles, despite telling scramblers in advance to be extra careful (including one case with two pairs of duplicate scrambles in the same 42 cube attempt)

The reason this won't affect or bother majority (90%) of competitors is due to the "may" word in the regulation: 
Competitors may submit extra "backup" cubes to be scrambled for Multi-Blind. 

it should be up to the competitor to decide whether they want a backup cube or not. we can even add a clause that say, a minimum of 10 cubes or 20 cubes should be attempted before a competitor is given this option. Better yet, we can say:

A competitor may submit at most one backup cube for every 20 cubes they attempt, if they wish to. 

this will have the added benefit of allowing people attempting 40+ cubes to submit 2 backup cubes
(getting 2 pairs of cubes with same scrambles has happened in official attempts in the past, and has led to a lot of time wastage and frustration for the competitor.

In the last couple of years, MBLD has progressed quickly with an increasing number of people attempting very large numbers in competition, and no matter how carefully they scramble, scramblers are human and are bound to make errors. giving this option will give an extra security to competitors and due to scrambler signatures being recommended. scramblers will still be held accountable for any errors. 

The larger number a competitor attempts, the more likely it is that he will get a duplicate and the larger impact a few wasted seconds can have at a high level where people take less than 40 seconds per cube to memorise, they can instantly have a full cube's memo time gone due to a scrambler's mistake.

As for logistics, I have had this done in an official attempt of mine on more than one occasion and its very simple logistically. every competition already has a supply of cube covers and putting one cover with a cube underneath and placing it say, under the table or on a nearby table and quickly swapping cubes is still much quicker than calling a delegate, having him confirm, then him taking a cube away and re scrambling it. 

the main thing that wastes time is the mental disturbance in an otherwise really focused event, and even thinking about the fact that a duplicate scramble can happen can be detrimental to the attempt. having the mental security of the backup cube will help this. 

Thanks for reading, Please let me know in case of queries.

**Comment by mintydev789** [comment]
I agree with Shivam, but I can't think of a reliable way of implementing this that doesn't involve a delegate. This would require a delegate to be present at all times in the room, where MBLD is being held, but perhaps that should be a requirement anyways.
