### ISSUE TITLE
Should it be possible to make a puzzle legal during a BLD/MBLD attempt

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/wca-regulations#775]
In a recent report it was stated how a competitor submitted an illegal cube (cube with a logo during MBLD). He removed the logo during the attempt but it was still counted as unsolved. 3k2b+ states the following: 

> If a non-permitted puzzle is found during the course of a 3x3x3 Multi-Blind attempt, the puzzle must not be exchanged or removed from the attempt and must be counted as unsolved if the entire attempt is not disqualified.

So it makes sense that I was counted as unsolved. However, I'd say that it would make sense to update this and allow the competitor to make their illegal puzzle legal. The intention behind logos not being allowed is so the competitor cannot feel which side is which, but since the logo has now been removed during memo, the competitor will not be able to use this to any advantage.

I propose the following fix:
3k2b+ If a non-permitted puzzle is found during the course of a 3x3x3 Multi-Blind attempt, the puzzle must not be exchanged or removed from the attempt and must be counted as unsolved if the entire attempt is not disqualified. **Exception: The competitor may make their puzzle legal during the memorization fase (e.g. by removing a logo) at the discretion of the judge.**

Thoughts?

**Comment by maconard** [comment]
Seems like a very very niche fix and is something the staff/Delegate should never allow to happen because of 3k (although the same can be said for 3k1 and 3k2, because of the usage of the word "should" instead of "must" in 3k).

However, I know in practice it does happen, so I think an exception like this is fine. My primary concern is that some puzzles will be unable to be made legal during the attempt - e.g. you can't whip out a set of stickers and re-sticker a puzzle with a terribly worn face mid-attempt - so this may add some confusion about what is okay and not okay to do during your attempt. The use of the word "discretion" is typically seen as an escape route from concerns such as this, but maybe that is fine in this case.

**Comment by xsrvmy** [comment]
@maconard restickering a puzzle mid attempt is receiving assitence from another object.

There is actually a bug in 3k1 that technically prevents a competitor from fixing a puzzle mid round and we should fix that as welk.

**Comment by maconard** [comment]
@xsrvmy I know, that's why I said "you can't" do it. The A5b ruling you just mentioned presents a possible contradiction with "Exception: The competitor may make their puzzle legal during..."  in this ruling, if making it legal requires assistance from another object. 

And yeah, 3k1 requires a replacement, but it is in regards to the rest of the attempts in the round, not the rest of the current attempt (as is the concern with MBLD). That said, I feel like quickly fixing your puzzle makes it worthy of being submitted as a replacement for itself, as a loophole to 3k1's wording.

**Comment by CarterKoala** [comment]
@maconard In my eyes there's a difference between those scenarios. One is delegate discretion and one is just straight up not allowed.

**Comment by maconard** [comment]
Judge's discretion is quite different from Delegate's discretion.
