### ISSUE TITLE
Remove inserts for square-1 (A2b1)

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#778]
Square-1 is the only puzzle the only puzzle in wca history in which we have used inserts, the reason A2b1 was originally added was to help prevent moves during transit. The puzzles at the time most commonly used when this regulation was created were Calvin’s, MF8 and Cubetwist square-1s all of which needed to have extremely loose UD layers in order to even be turntable. With modern square-1s the top and bottom layers are extremely unlikely to turn on their own during transit, much less likely to turn than puzzles such as Skewb. Not only is it unnecessary to use inserts but in many cases it’s also harmful. Many inserts are made from thin pieces of cardboard such as business cards, the problem with this is that many competitors use water based lubricants inside of their puzzles to keep it fast and these inserts will absorb the lubricant and slow their puzzle down. It’s almost the equivalent of taking a paper towel and wiping out some lubricant before each solve. In some cases you may even get lubricants from multiple square-1s “cross contaminating” other puzzles. The last big thing is that this regulation is very rarely done properly, at US nationals 2018 for example it was never announced that they would be using inserts. This issue is very rarely discussed but I feel needs addressed. 

Even if we do not remove A2b1 I would like to see some changes with this reg, perhaps only making it legal with the competitors consent, don’t absorb or pick up lubricant etc.

**Comment by Sixstringcal** [comment]
I also think that "At the desecration of the delegate" where the delegate could give a heads up to the competitor could also be a nice change and a great way to deal with puzzles that do need an insert.

**Comment by maconard** [comment]
If a Square-1 can be *fairly* and consistently judged on whether or not it needs an insert to ensure scramble validity, I think discretion of the delegate per puzzle sounds great. However I'm not sure how fair or consistent that would be. Competitors may be disgruntled if their puzzle has an insert while all the others don't.

**Comment by xsrvmy** [comment]
@UnderwaterCuber Difference between sq1 and other puzzles is that it shapeshifts not that the puzzles are looser. Magnetic cubes do not help. A magnetized old qiyi can still have extremely fast faces. Also sometimes there can be states where no magnets come into play at all on a sq1 where only corners are magnetized but not edges.

**Comment by Sixstringcal** [comment]
@xsrvmy 
I have literally thrown super loose non magnetic volts (loose enough for me to take edges out easily to replace them.  That loose) in random cubeshapes through cube covers (the paper cubicle ones) and they have not moved (they have landed on hard surfaces (the tables of the competition).  They might move a bit on even worse puzzles (I'll admit that the original qiyi is more prone to this), but it would still be within 45 degrees of where it was for certain.  At local competitions I have not used inserts at all for anyone in a very long time and we have had 0 issues related to it.  Also, about your last sentence.  There is only one cubeshape where that can be the case, and it only applies to one layer with one AUF (and it's flipped version with one AUF) where the equator is not flipped.

The tightness of the U/D layers actually do help prevent the puzzle from turning.

[I made a video about this earlier today coincidentally if anyone wants to watch me spend 40 minutes explaining why we don't need inserts.](https://www.youtube.com/watch?v=B5-_acoWbiY&lc=z220jxpruvvltp2bz04t1aokgtflxm5thzwyugpapdhmrk0h00410)

**Comment by julesDesjardin** [comment]
Since we're talking about sq1, the limit when considering the starting state is not 45°, but half an edge (so 7.5°), which now seems very likely.
Michael's last phrase actually could apply to very various scenarios: when only corners are magnetized, the stablest state can be quite random (the case you describe is the most extreme one, but any cubeshape may have magnets not aligned with each other).

I agree that this can remove a tiny bit of lube inside the puzzle, but that's a price to pay to ensure correct scrambles for everyone (think of a cubeshape with many solutions, for example good fist-fist. The initial alignment will determine how you do the cubeshape, and the rest of the solution)

**Comment by Jambrose777** [comment]
I’ve you tried supplying your own insert?

**Comment by dancing-jules** [comment]
This is a difficult topic.

On the one hand I absolutely loathe inserts personally and multiple times I've accidentally left them in during inspection only to be surprised when the puzzle then refuses to turn. 

On the other hand, during German Nationals there were 2-3 competitors that were using puzzles with frictionless U/D layers - in 2019. So yes, while 90% are using the Volt or the YLM, not all are.

There are 3 possibilities:

1. Get rid of them altogether

Good for Volt and YLM and future square-1 solvers who don't like inserts, but as said above there are still people who use old puzzles. Some people are also used to inserts. 

2. Let the competitor decide

Let each competitor have what they want. But if someone with an old square-1 decides not to, the puzzle will mis-align; same problem as option 1. 

3. Let the delegate decide

The delegate decides which puzzles need an insert. But then you are punishing competitors with old puzzles. And decisions will vary from delegate to delegate, which will make the whole thing look very arbitrary.

Ultimately there's no good solution. I think for now the inserts should stay. Or at least on a competition-to-competition basis (which is actually the current rule). Maybe we can talk about this again in 2-5 years, when even fewer people will be using old square-1 puzzles.

**Comment by maconard** [comment]
Side comment, I heard some talk at Nats about an idea to design a 3D printed '+' shape piece of plastic that curves slightly, so it could barely press into the square one whether it's equator is aligned or sliced off. I think it's a neat idea, and a 3D printed + insert wouldn't affect lube I'd think.

**Comment by xsrvmy** [comment]
@maconard You need two + pieces then, which is a disadvantage to the competitor compared to a normal insert.

**Comment by xsrvmy** [comment]
Very strawman idea: turn the puzzle by 90 degrees on the slice when carrying, and turn it back before the competitor receives the puzzle. Unfortunately this only works well if the judge runs the puzzle, which is not the case in NA comps.
Another idea: use another flat cardboard to carry the puzzle, so it does not need to be flipped over twice, and remove it after the competitor picks up the puzzle during inspection.

**Comment by Sixstringcal** [comment]
@dancing-jules While looking through the regs yet again, I was unable to find anything saying that the misalignment for starting the puzzle was anything but 45 degrees.

@Jambrose777 I'm not sure on the fairness for this.  I've heard from one of the organizers I've worked with that when TheCubicle sponsors a competition with square-1 that if there are inserts, that they must use the business cards or they will refuse to give the prizes.  I think a company like TheCubicle would likely be more lenient with the 3d printed solution if you got explicit permission like @maconard mentioned, but I also believe there you could still run into issues.  These 3d printed ones would also end up being reused with many competitors, which would end up spreading people's lubes from cube to cube very easily.

As it is right now, inserts are not required at all.  It's the decision of the organization team.  That means that we don't have to do anything about these scenerios where there are frictionless U/D puzzles, but instead we have the organization teams of competitions that are enforcing inserts on everyone when we aren't required to do it to anyone.  In Utah, we haven't had any issues with this.  Sure we don't throw the puzzle in the cube cover, but we really shouldn't be treating other people's puzzles that harshly anyway.  

Also, I'd like it to be known that at Nationals 2019 (of which I was an organizer and delegate for), I did push for inserts (not initially, but fairly close to the end of the organizational period).  At a comp that big, I do believe inserts were necessary.  I think the total removal of inserts shouldn't be done now, but maybe in 2021 or 2022.

**Comment by julesDesjardin** [comment]
(you tagged the wrong person, but that's quite a normal mistake :p) 

It's actually where we define moves :
12c4) Metric for Square-1: (x, y) counts as one move, "/" counts as one move.

So (1,0) is a move, meaning you can't do that in inspection. Also meaning that a puzzle that gets applied a (1,0) is a misscramble (whereas on a 3x3, the equivalent of a (1,0) is a misalignment small enough so that the competitor can correct it). My point of a half edge was that anything close to (0.5,0) can not be corrected because you don't know where it should be, and (0.5,0) is really a very small move, even on a magnetic square 1 (especially if the scrambled position isn't particularly stable due to corner magnets) 

As for the usual "we didn't have any misscrambles incidents" : there's absolutely no way to test it, unless you check every single solve of the competition afterwards. Maybe the few scrambles checked on video because someone reconstructed them were right, but that's a few averages out of several dozens. 

I'd personally be in favor of enforcing them in a near future.

**Comment by Sixstringcal** [comment]
Correct, but it's within the misalignment as described within the regs.  Also, strictly from 12c4, 0,0 is a move as it doesn't specify nonzero values for x and y.

As for not having misscramble incidents, that's fair.  But we've never had an incident caused by this is what I'm saying.  Misscrambles get sent out as it is on all puzzles without detection (although we are working to correct that to the best of all of our abilities through things like scramble signatures, which only work to a point).

Also, sorry for tagging the wrong Jules.

**Comment by xsrvmy** [comment]
Well scramble signatures does not help at all for this particular sq1 issue.
Actually this whole discussion reminded me of something else. Was the 6.4x OH misscramble done in transport or was that never determined?

**Comment by CarterKoala** [comment]
I'd definitely be in favor of enforcing them. I've never not had them used officially, but at nats I did a comp sim without them, and I'm not joking when I say over 75% of the time it either came misaligned or I misaligned in inspection when CSP tracing. Keep in mind there is no runner in this scenario as well and the cube is carefully put on the table, which isn't something that can be said about official solves.

**Comment by Burnsy101** [comment]
I think for the time being the need for inserts outweighs the problems they would cause re. lube - as well, I used a massively overlubed volt in comp once and did not see the inserts at all have any absoprtion from the lube.

Another question re. miscrambles that I remember @dancing-jules  was talking about:

Is it not inconsistent for (1,0) to be considered a move in inspection yet a cube is considered solved with a (1,0) move and nothing else on it at the end? The rules for sq1 are effectively "treat it like a 3x3 - would a 3x3 look solved?" at the moment regarding +2s and dnfs which feels inconsistent to me

**Comment by CarterKoala** [comment]
@Burnsy101 About your last point, I think that that’s a common misconception. Penalties are for misalignments, not moves. There is a difference. The issue lies more with turning in inspection. Be super strict and allow nothing (which I think is fine if we enforce the cards) or allow up to a misalignment, which gets a little messy. One thing that’s worth noting about the first option is that I wait until the end of my inspection to take out the card.

I do agree though that I have never had or heard anyone in my region complain about problems with lube absorption.

**Comment by dancing-jules** [comment]
@Burnsy101 @CarterKoala - this ties in with issue #699 about square-1 basically having 2 metrics. In that issue I proposed getting rid of one of them (the scramble metric). But thanks to you folks I now realise that this also removes the metric used for "turn in inspection". Back to square one, I guess (LOL).

**Comment by Samuel-Baird** [comment]
Closing issue. With people not upgrading hardware it makes it too difficult to completely eliminate inserts, no matter what problems they may cause for competitors.
