### ISSUE TITLE
Clarify that results matching the time limit are DNF.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#782]
A1a4 specifies:

> A1a4) The competitor must end each solve before the time limit for the attempt is reached. If a competitor's timer reaches the time limit for an attempt, the judge stops the solve immediately and records the result as DNF. Exception: 3x3x3 Multi-Blind (see Regulation H1b1).

However, this only covers the solve, and therefore the original recorded time. It allows 8.00 + 2 = 10.00 to meet a 10-second time limit, while 10.00 on its own does not. We should pick a convention and make it as clear as possible.

**Comment by dancing-jules** [comment]
> However, this only covers the solve, and therefore the original recorded time. It allows 8.00 + 2 = 10.00 to meet a 10-second time limit

Does it though? 

[A1a5)](https://www.worldcubeassociation.org/regulations/#A1a5) says "The time counting towards the time limit for an attempt is either the result after time penalties are applied..."

While from context it looks a bit like A1a5 is specifically talking about cumulative time limits, it does not specify. But yes, it's a bit confusing, because the competitor was not stopped because the time limit was not reached yet. 

Yes, clarifying that time+all penalties must be smaller than the limit, is probably a good idea.

**Comment by Burnsy101** [comment]
My idea for a change:
Previous one: If a competitor's timer reaches the time limit for an attempt the judge stops the solve immediately and records the result as DNF
My idea: if the competitors time is not under the time limit for an attempt the judge records the result as a DNF. If the competitors timer reaches the time limit for an attempt the judge stops the solve immediately and records the result as DNF
this is so that we have the **final** time explicitly being DNFed if the final time is equal or greater than the time limit

This is too verbose for my liking and there is 100% a way to simplify it into 2 sentences, but that catches the case that is being missed out in your scenario I guess
