### ISSUE TITLE
Mention Bluetooth puzzles in 2i

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#783]
Bluetooth puzzles are definitely not allowed, but somehow competitors are not always sure of this. We should explicitly mention them.

**Comment by hanwu85** [comment]
How about   2i3) Competitors must not use puzzles with bluetooth/Wifi functions.  Penalty: disqualification of the attempt (DNF).     In guidelines:  2i3+) REMINDER  Puzzles should be checked by WCA delegates before the competition (see Regulation 3k).

**Comment by Burnsy101** [comment]
@hanwu85 that works, but another solution could be when it says that the competitor must not use electronic equipment to include bluetooth cubes in that since they are electronic - make the regs more concise

**Comment by mirandapedro** [comment]
If we want to simply make explicit mention of bluetooth cubes, I agree a simple rewording of 2i should suffice.

It would look something like this:

`2i) While competing, competitors must not use electronics or audio equipment (e.g. cell phones, MP3 players, dictaphones, additional lighting, bluetooth cubes) apart from the Stackmat timer or stopwatch.`

I understand that bluetooth cubes fall under the category of "eletronics" pretty clearly.

There are two possible issues that may arise with this solution:

1. Whether or not we want to get into what defines "bluetooth cubes". It may be wiser not to try and get into specifics, as (I feel) any definition would quickly be outdated, which get me into issue 2.

2. This solution is a short term one. A year from now, there be a new type of cube that may or may not fit the definition of "bluetooth cubes". In order to make sure everyone knows they are forbidden, we would ammend the Regulations, making explicit mention of them. This process could go on and on, without a definitive solution.

My proposal is that we remove all examples given in 2i and try and word it so there's not any room for doubt. There's something to be said on good lawmaking about trying as much as possible to avoid giving examples, as they will inevitably get outdated (and so will we ;p). If our goal is to make the Regulations a complete document, improving the wording of articles so that examples are unnecessary helps that. 

A draft proposal of what that could look like:

`2i) While competing, competitors must not use any eletronic equipment apart from the Stackmat timer or stopwatch.`

Merriam-Webster defines eletronic as:
> 2a: of, relating to, or utilizing devices constructed or working by the methods or principles of electronics.
> 2b: : implemented on or by means of a computer : involving a computer.

I think this is a broad definition that reaches any device that we understand should be forbidden by 2i.

If we feel there's a need for it (which I don't think is the case), we could add an Example to the Guidelines that would look something like this:

`EXAMPLE - Examples of forbidden equipment include: cell phones, MP3 players, dictaphones, additional lighting and bluetooth cubes.`

On the medium term, I believe we should apply this philosophy to the rest of the Regulations, improving the wording of articles so that explaining them through examples is unnecessary. This goes hand in hand with the goal of simplifying the Regulations as much as possible.

This solution also doesn't tackle the issue of what mechanisms are in place so that we can systematically detect and prevent the use of bluetooth cubes in competition, but I feel this discussion should be held elsewhere.

Quick edit: Just saw the initial prompt was focused on the competitor's understanding of the Regulations. Although this particular solution isn't directly aimed at that face of the problem, and the additon of examples on the Guidelines should suplement that, I feel the main argument of simplifying the Regulations by improved wording and reduced examples still stands. The blanket definition given might make it clearear to the community that any type of eletronic equipment is not allowed, except those that are explicitly allowed.

**Comment by kotarot** [comment]
I understand adding (or updating) words in `2i` would work. However, Section 2 describes about "Competitors", and `2i` defines equipment that belongs to competitors and is not related to the competition directly. Thus, adding "bluetooth puzzle" into here is just a bit unnatural to me.

I think we could add it into Section 3. Section 3 directly describes the definition of available/unavailable puzzles. "Bluetooth puzzles" should be added here. In my thoughts, we could add `3h5` for bluetooth, or we could move `3m` to `3n` and then add new `3m` for bluetooth.

Incidentally, I prefer using "puzzles with bluetooth/WiFi functions" (just Han has introduced) rather than "bluetooth cubes", because the puzzle is not always a cube.

**Comment by xsrvmy** [comment]
Based on what @kotarot said an entry in section 3 like this would work:
- Puzzles must not be electronic (see 2i)

This covers bases also for things, eg. puzzles with a light inside, puzzles with a timer on it (although that puzzle is already disallowed cuz the timer is on the corner).
