### ISSUE TITLE
Idea: delete A4d2 and change A4d1 to making it a DNF if overinspected

### ISSUE THREAD

**Issue by Burnsy101** [thewca/wca-regulations#787]
I don't think that we need to have an overinspection penalty - 15 seconds is plenty and having a +2 penalty might lead to confusion, especially if +2ing people as a whole gets rarer and rarer in competitions  if a misalignment penalty is eliminated. I just think that having this penalty is unnecessary and unneeded if regulation simplification is needed.

As well, 15 seconds (in my opinion) is enough, and having 2 seconds of leeway matters little.

**Comment by CarterKoala** [comment]
I'd be for this, but I'm still not 100% sure because of one thing - Inspection time is very variable as it  depends on when the judge starts and stops the stopwatch. +2s leave a bit of leeway in case of inaccurate timing of inspection.

**Comment by Ivan-Brigidano** [comment]
This does make sense if misalignment penalty is eliminated. But I think that the main issue of doing this is that much more solves will be DNFed just because of that.

**Comment by xsrvmy** [comment]
I think there is no need for this change. The main reason is that the call for 12 seconds can be ambiguously placed. (are you calling 12 so that it ends at 12 seconds or beginning at 12 seconds?)
The penalty makes sense at it stands. You get penalized 2 seconds if you go over inspection by no more than 2. It also eliminates the variability issue with how the judge operates the stopwatch.
IMO this is the same kind of thing as saying you can speed by at most 10% before getting ticketed even though speeding by 1% is illegal. It allows some room for error while also clearing saying: we are not OK with overinspection. And it avoids the dispute: the judge was slightly late on calling 12, so I should get an extra.

**Comment by Burnsy101** [comment]
Ok I've thought a lot about this and I guess here are my thoughts:
On the stopwatch issue with the leeway @CarterKoala : To be frank, stopwatch accuracy is not something that is considered that much in multiBLD - as attempts often go right up to the hour limit (if not for a corner twist, Kamil would have gotten a WR by 5 seconds) and a small inaccuracy could make a large difference. 
Of course this is different with 15s and one hour, but I feel as if it would be inconsistent to talk about leeway in one situation re: timing with stopwatch but not with another.

@xsrvmy  about the ambiguity for the call for 12s: this could be changed if the competitor tutorial explicitly states - as soon as you see 12 seconds pass on the stopwatch, call out "twelve"
I do agree with the allowance for the room for error - its just if / when +2s become rarer if misalignment is eliminated, and +2s get rarer, the regs should be simplified a bit more and make newer competitors' judging experience a bit easier (as without misalignment they might be confused with the concept of a +2) through my proposal

**Comment by xsrvmy** [comment]
@Burnsy101 I don't think trying to remove a +2 because another is removed is a good idea. We would be talking about timer stops next and those are controversial enough already as a +2.

I have a slightly different idea though, which is to change how inspection countdown is handled at some point in the future, and allow the competitor to see the countdown. This would get rid of the "talking speed" issue. And once stackmat patent expires someone can make a timer with inspection built in so no more inaccuracy either.

**Comment by Burnsy101** [comment]
@xsrvmy there is a solution for this actually - cubing.net/inspection has a tool that could ensure there is no discrepancy in when the calls for 8 and 12 are read out. (it doesn't seem to work on my mac browser at the moment but another sort of site could be / app like in a timer, and you could maybe put that on the table with the app on a phone - there are some ideas, but I agree with your suggestion - in my opinion we should remove the stopwatch and the human calling out 8 and 12

**Comment by xsrvmy** [comment]
@Burnsy101 I still think 12 is too late but that's a different concern
