### ISSUE TITLE
Mandate Championships to Hold All WCA Official Events

### ISSUE THREAD

**Issue by saranshgrover** [thewca/wca-regulations#790]
While an assumption currently by the community, I think that it should be mandatory for all Championships to hold all WCA Official events. If certain events aren't held during championships, it is unfair for those who practice that event religiously since they do not have a chance at a Championship title.

**Comment by Claster** [comment]
Regulations don't mention championships anywhere. This should rather go to the Competition Requirements Policy.
Note that there is an idea of event tiers (#758) which would go into the opposite direction.

**Comment by Jambrose777** [comment]
This is already in the wcrp announcement criteria 9.4: https://www.worldcubeassociation.org/documents/policies/external/Competition%20Requirements.pdf

The reason why it is a should is because there are some countries which are incapable of holding all events (due to their competitions being new, or size). These countries shouldn’t be denied the opportunity to hold a championship due to this.

**Comment by Samuel-Baird** [comment]
It’s also pretty unnecessary to hold some events at championships, for example Egypt doesn’t have any bld results so it’s probably fine to not hold big bld :P

**Comment by lgarron** [comment]
Indeed, the WCRP covers this.

As @Claster notes, if we implement tiers (#758) we should revisit this — but I don't think there's anything to do for now.
