### ISSUE TITLE
Systematic Leniency

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#798]
A lot of times, we need to make the Regulations more strict to be more consistent (for "fair and equal conditions"). However, I think we can be more lenient in some situations. I'd like to make a list of them here as they come to mind. Please suggest more!

- Allow video evidence to be used if the time was not recorded properly, as long as we have confidence in the accuracy of the result.
- Tolerating interaction with electronic equipment, as long as we have confidence that no advantage was gained. (via @SAuroux)
- Tolerating camera screen visibility due to realistically no tangible advantage can be gained (similar to the reason why stickerless cubes were eventually allowed) (via @SAuroux)
- Tolerating touching the puzzle (in the context of A6e) if it is clear that no move has been applied. (via @SAuroux)
- Don't remove competitors from rounds they were originally allowed to participate in unless it was *their fault*. In particular, don't enforce https://www.worldcubeassociation.org/regulations/#9p1 if a competitor from a pervious round is retroactively disqualified.
- Allow competitors to use a scramble/get an extra if they lifted a cover and before the attempt and it was clearly by accident.
- Allow an extra attempt if a competitor was accidentally set up camera before the attempt a screen facing them (since they won't be able to make this "mistake" based on seeing the scramble).

**Comment by Baiqiang** [comment]
For video evidence, the screen of timer must be in the evidence because display may be incorrect.

**Comment by xsrvmy** [comment]
I think it depends. If the time written down is ambiguous like 11 vs 17, it is possible to time the video. But if the difference is smaller (eg. 10 was written down instead of 10.00) then the actual timer time would be better.
btw isn't there a way to check if a display is working properly by displaying all 8s?

**Comment by Jambrose777** [comment]
@xsrvmy 

1. Would you rather have a completely bogus time that is known to be incorrect as a time that is in our results, or one that accurately represents what happened for the attempt and can be proven?
2. Display will sometimes lag behind if they don’t work well causing them to display a time that is not on the timer. The all 8s thing only applies to the timer.

**Comment by xsrvmy** [comment]
By the all 8 thing I meant testing to see if the display's LEDs are correctly working. As far as I am aware that's the only reason where I have seen an incorrect time on the display

**Comment by SAuroux** [comment]
> However, I think we can be more lenient in some situations. I'd like to make a list of them here as they come to mind. Please suggest more!

There is a ton of potential systematic leniency could both simplify and improve the current regulations and make decisions more efficient in practice. Some examples:

- Tolerating interaction with electronic equipment, as long as we have confidence that no advantage was gained.
- Tolerating camera screen visibility due to realistically no tangible advantage can be gained (similar to the reason why stickerless cubes were eventually allowed)
- Tolerating touching the puzzle (in the context of A6e) if it is clear that no move has been applied.

> A lot of times, we need to make the Regulations more strict to be more consistent (for "fair and equal conditions").

Note that this ignores the fact how often such mostly hard to catch regulations are then not applied in practice simply because people are not perfect and because not everything can be spotted during a competition.

For example, I would be very confident making the wild claim that at least about 50% of all attempts violating 2i2a) are not caught and not DNF'ed. If that claim is just remotely accurate, it would obviously be more serving "fair and equal conditions" to remove that regulation.

**Comment by xsrvmy** [comment]
Another aspect we could look at is registration.

**Comment by xsrvmy** [comment]
I can agree that 2i2a often missed. I have accidentally broken it twice by not flipping over the screen. Both times I call myself out after realizing at the end of the solve.

**Comment by xsrvmy** [comment]
I can agree that 2i2a often missed. I have accidentally broken it twice by not flipping over the screen. Both times I call myself out after realizing at the end of the solve.

**Comment by lgarron** [comment]
> Some examples:

Thanks, I've added those above!

> Another aspect we could look at is registration.

Could you specify a bit more what you mean?

**Comment by OrangeGreenCuber** [comment]
Would this allow someone to be shirtless (technically violating 2h) potentially if it was agreed upon all competitors and the delegate supposing it was hot enough?

**Comment by lgarron** [comment]
> Would this allow someone to be shirtless (technically violating 2h) potentially if it was agreed upon all competitors and the delegate supposing it was hot enough?

If you think that this violates 2h and think it's important enough to make the WRC and Board vote on it weeks ahead of time... sure.

**Comment by Burnsy101** [comment]
What about much more leniency for newer competitors? Of course they should all be familiar with the regulations, but maybe if they get a timer reset on a timer without O-rings as they have never used a stackmat before, maybe they deserve an extra whilst someone who has been to many comps might not in that situation? I'm not sure if that is 'equal' conditions so to speak but it seems unfair to expect people to be perfect competitors who make no mistakes regarding the competition process on their first solve.

**Comment by lgarron** [comment]
> What about much more leniency for newer competitors? Of course they should all be familiar with the regulations, but maybe if they get a timer reset on a timer without O-rings as they have never used a stackmat before, maybe they deserve an extra whilst someone who has been to many comps might not in that situation?

I think Delegates should (and I believe most would) already use [A7g](https://www.worldcubeassociation.org/regulations/#A7g) to give an extra attempt in that case!

In fact, the success of A7g gives me hope that we can find ways to be more flexible when experienced competitors accidentally cause uncommon but unfortunate incidents.

**Comment by Samuel-Baird** [comment]
I'm not a fan of allowing competitors to use a scramble/get an extra if they lifted a cover and before the attempt, if a competitor somehow got word that a scramble was bad they could just "accidentally" lift the cube cover.

**Comment by alexmaasswca** [comment]
Here's one, make it the responsibility of the judge to ensure that the competitor has signed for solves. It is harsh that a competitor accidentally forgetting to sign a result makes it a DNF.

Also, not signing for a result is not always the competitors fault, I know that in US Nationals 2018, a competitor didn't make it to pyraminx finals because he was forced off the stage before he could sign for his final solve, which is absolutely unfair. 

A7c) The competitor must check the recorded result, and sign (or initial) the score sheet to acknowledge that the result is correct, complete, properly formatted, and clearly readable. This finishes the attempt.
A7c1) If the competitor or the judge refuses to accept and sign the score sheet, the WCA Delegate must resolve the dispute.

It is obvious that simply forgetting/not being able to sign is NOT refusal to accept the result.

**Comment by Samuel-Baird** [comment]
> Here's one, make it the responsibility of the judge to ensure that the competitor has signed for solves. It is harsh that a competitor accidentally forgetting to sign a result makes it a DNF.
> 
> Also, not signing for a result is not always the competitors fault, I know that in US Nationals 2018, a competitor didn't make it to pyraminx finals because he was forced off the stage before he could sign for his final solve, which is absolutely unfair.
> 
> A7c) The competitor must check the recorded result, and sign (or initial) the score sheet to acknowledge that the result is correct, complete, properly formatted, and clearly readable. This finishes the attempt.
> A7c1) If the competitor or the judge refuses to accept and sign the score sheet, the WCA Delegate must resolve the dispute.
> 
> It is obvious that simply forgetting/not being able to sign is NOT refusal to accept the result.

The competitor should know that they need to sign, if they don’t sign that’s entirely their fault. I’m not sure what the situation was at US nationals but the competitor should have have tracked down their scorecard and signed it.

**Comment by Jambrose777** [comment]
> > Here's one, make it the responsibility of the judge to ensure that the competitor has signed for solves. It is harsh that a competitor accidentally forgetting to sign a result makes it a DNF.
> > Also, not signing for a result is not always the competitors fault, I know that in US Nationals 2018, a competitor didn't make it to pyraminx finals because he was forced off the stage before he could sign for his final solve, which is absolutely unfair.
> > A7c) The competitor must check the recorded result, and sign (or initial) the score sheet to acknowledge that the result is correct, complete, properly formatted, and clearly readable. This finishes the attempt.
> > A7c1) If the competitor or the judge refuses to accept and sign the score sheet, the WCA Delegate must resolve the dispute.
> > It is obvious that simply forgetting/not being able to sign is NOT refusal to accept the result.
> 
> The competitor should know that they need to sign, if they don’t sign that’s entirely their fault. I’m not sure what the situation was at US nationals but the competitor should have have tracked down their scorecard and signed it.

Once the scorecard hit the data entry, competitos were not alllowed to sign (for the past 2 years)

**Comment by alexmaasswca** [comment]
> > Here's one, make it the responsibility of the judge to ensure that the competitor has signed for solves. It is harsh that a competitor accidentally forgetting to sign a result makes it a DNF.
> > Also, not signing for a result is not always the competitors fault, I know that in US Nationals 2018, a competitor didn't make it to pyraminx finals because he was forced off the stage before he could sign for his final solve, which is absolutely unfair.
> > A7c) The competitor must check the recorded result, and sign (or initial) the score sheet to acknowledge that the result is correct, complete, properly formatted, and clearly readable. This finishes the attempt.
> > A7c1) If the competitor or the judge refuses to accept and sign the score sheet, the WCA Delegate must resolve the dispute.
> > It is obvious that simply forgetting/not being able to sign is NOT refusal to accept the result.
> 
> The competitor should know that they need to sign, if they don’t sign that’s entirely their fault. I’m not sure what the situation was at US nationals but the competitor should have have tracked down their scorecard and signed it.

It can still easily be also the fault of the judge, if they don't notice it. A judge can easily abuse this with an inexperienced competitor by taking away the scorecard and claiming the competitor already signed when they ask.

Also, the fact that it's been done for the past 2 years is not really a reason, there have been things that have been much much much longer in the WCA that have been changed. I see no reason why the WCA can't afford to be lenient in these situations.

**Comment by Samuel-Baird** [comment]
Something I would be in favor in is allowing non-standard notation for FMC as long as the delegate or judge can tell what the intention behind it is. For example solutions that use U with a tail instead of U without a tail, lowercase letters, writing things like R2’ or [r]’, using brackets or parentheses around xyz rotations.
