### ISSUE TITLE
Encourage cube covers with certain properties?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#801]
The WRC has recently heard of had several incidents where cube covers were accidentally lifted.

Presumably, cube covers with weighted bases would help with this. Similar to O-rings, they could help prevent incidents for competitors who usually don't intend to break any Regulations. And it usually doesn't affect the fairness of the result.

**Comment by xsrvmy** [comment]
I think it's fairly safe to do this, except in blind. IMO lighter covers may give a split second advantage. If there is a way, blders should be allowed to provide their oen covers

**Comment by EdHollingdale** [comment]
I don't think they would solve the main instances of this issue. In my experience, early lifting of the cover occurs when either: 
a) the judge doesn't know what they are doing and they just lift the cover. 
b) the judge misinterprets a slight head movement as a sign of the competitor being ready, instead of waiting for explicit verbal confirmation from the competitor.
Having weighted cube cover bases would improve neither of these things. At the moment getting good cube covers is hard enough as it is (unless they are supplied by a sponsor), so adding further requirements for them to be specially weighted places undue burden on organisers and delegates.

Additionally, it should be possible to easily transport cube covers. I regularly delegate competitions 1000+ km away which requires packing all equipment into a suitcase. Cube covers that can be folded down to hardly any space are crucial for this, and having weights stuck to the bases of all of them would make this worse. Having weights would also increase the weight of competition equipment (my 120 person competition travelling suitcase weighs 22kg when full, and most Australian Airlines have a 23kg weight limit).

**Comment by KatieHull** [comment]
@EdHollingdale I believe Lucas is referring to the cube cover being accidentally lifted by the competitor, not the judge, which is usually the result of the cover being bumped and falling over.

**Comment by maconard** [comment]
Just as another data point for this: I recently had a DNF from trying to move my chair closer to the competitor station, but it was on carpet so it caught and I lightly bumped the table, resulting in the cover tipping over. I was granted a provisional extra which was later deemed invalid. 

I'm of course not upset with this decision, it was my fault after all, but it would indicate that cube covers could use improvement.
