### ISSUE TITLE
Change 6x6x6 and 7x7x7 Round Format to Bo1 (3 Attempts)

### ISSUE THREAD

**Issue by pd159** [thewca/wca-regulations#812]
Essentially just make it like 3BLD. This is optimal because pops and parities can very easily ruin an average—not to mention that a world-class solver can lose to a 5-minute solver in the final round all because of a DNF from a slice move. Additionally, big cubes are all about adrenaline, so getting three attempts to get a nice solve is perfect for competitions, and especially for major championships. The luck factor for being a Bo3 shouldn't be problematic since three attempts is plenty to show your skill. I think this is the best way to deal with these issues, because making it an Ao5 would probably take too long for many competitions.

If there are any downsides to this, let me know

EDIT: Forgot to mention—it should go without saying that cutoffs for these events would be abolished. Time limits are enough for scheduling issues

**Comment by Laura-O** [comment]
How does Bo1 with 3 attempts work?

**Comment by pd159** [comment]
What do mean? Specific questions, please

**Comment by pd159** [comment]
*Bo3. Edited the original post

**Comment by Louis-dM** [comment]
I've always thought Median of 3 could be a good format for 3BLD, perhaps it could also work well for bigcubes? I'm slightly hesitant about letting a single result decide competitions for events with such a high success rate, even if luck doesn't play a big role because of the length of the solve.

(Also, this reminds me of a point from the livestream from today's WRC meeting: there was some discussion about changing misalignment +2s to DNFs. I'll admit I'm not experienced in the Mo3 speedsolving events (6x6 and 7x7) but I expect such a change could impact them significantly if their format is not changed. As mentioned in the livestream this is not a huge problem for Ao5 events)
