### ISSUE TITLE
Receiving someone puzzle: Extra should be granted

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-regulations#816]
The WRC have received some cases where puzzles of two competitor have been accidentally swiped (see [this case](https://www.worldcubeassociation.org/incidents/38)).

There is a need to clarify that an extra must be granted in this cases.

**Comment by EdHollingdale** [comment]
I'm not sure I agree with this - I think we should be careful specifying anywhere that "an extra **must** be granted" in the regulations for certain cases (emphasis mine). Extras are a tool at the disposal of a delegate - an important one, but not something that should be mechanical. If we have regulations saying an extra must be granted for certain cases, then some judges will just grant them without calling over delegates, which can then lead to granting of extras by judges in circumstances when they should not. A6b1 is the only case where the regulations specify an extra attempt - all others are handled by 11e (or A7g).

If we were to specify this, it would be better to do it in the wording of A3c3+ "the attempt should be replaced by an extra attempt, at the discretion of the WCA Delegate."

Additionally, I don't think I agree that all attempts following a cube mix up should get an extra. If the solve was completed and the competitor did not feel they were disadvantaged, then I don't feel an extra is necessary.

**Comment by Jambrose777** [comment]
If the cube is significantly better than the one the comeptitor was originally using (ie if I were to get a world class competitors 7x7, I’d potentially be a lot faster). This would give the competitor an unfair advantage by using a cube they didn’t provide. Thus an extra should be awarded even if the competitor likes the result.

**Comment by Ivan-Brigidano** [comment]
> If we were to specify this, it would be better to do it in the wording of A3c3+ "the attempt should be replaced by an extra attempt, at the discretion of the WCA Delegate."

@EdHollingdale I said `must` and not `should` to avoid a possible unfair decision as @Jambrose777 suggested.

**Comment by EdHollingdale** [comment]
@Jambrose777 in that case it is clear an extra should be given since the puzzles are clearly distinguishable. There are cases where this isn't the case. I am not that particular about tensions and lubrication within a "normal" range and I use the flagship 3x3x3 Cube of a major brand. I could get a cube mix-up and not notice at all, while the other competitor may notice immediately because they have particular tensions that impact their turning style. The second competitor should receive an extra there, but I don't see why I should.

As a less relevant anecdote, getting a world class solver's cube won't always make you faster. I had a pop that snapped a centre piece during a round of 6x6. For my third attempt Feliks lent me his cube (he had unsurprisingly already finished this 3 attempts). Since I was so paranoid about not breaking it and it wasn't as familiar I actually did slightly worse.

@Ivan-Brigidano my concern about `must` vs. `should` is more around who is responsible for granting an extra. This should **always** be the listed WCA Delegate at the competition. If you make it a `must` then you blur this line, and open the door to judges granting extras. I also agree that in 99% of cube mix-up cases an extra should be granted.

**Comment by Jambrose777** [comment]
The issue is that having it be delegate discretion turns your 99% to another delegate’s 50% since hey may not know the same reasonings.

A specific regulation saying that all extras must be granted by delegates (addition to 11e) would probably ease your concerns.

**Comment by xsrvmy** [comment]
Two subtle problems:
1. What if the competitors only realize the puzzle mixup more than 30 minutes after the incident?
2. If all extras must be granted by the listed delegate(s), what if no delegate is available within 30 minutes of an incident (competing in bld for example) or before the start of the next round of the event?

**Comment by Ivan-Brigidano** [comment]
> What if the competitors only realize the puzzle mixup more than 30 minutes after the incident?

That would definitely be a problem. Probably it would have to be changed into a DNF.

> If all extras must be granted by the listed delegate(s), what if no delegate is available within 30 minutes of an incident (competing in bld for example) or before the start of the next round of the event?

This is the case of all extras and not only this one. That's why if a Delegate will be out, he/she should appoint other members of the organization team to carry out specific responsibilities on their behalf (see regulation [1c](https://www.worldcubeassociation.org/regulations/#1c)).

**Comment by EdHollingdale** [comment]
> That would definitely be a problem. Probably it would have to be changed into a DNF.

@Ivan-Brigidano competitors not realising a mix up at all until well after the round is exactly my point! This is the 1% of cases where it is unnecessary to grant an extra because the mix-up had no discernible impact. Being forced to change results to a DNF would be a serious step backwards.

**Comment by Ivan-Brigidano** [comment]
@EdHollingdale maybe the best solution would be to grant an extra if the round is already on. And if the round has finished then no extra are granted.

Something like `at the discretion of the WCA Delegate` might be enough to handle these cases.

**Comment by Laura-O** [comment]
I still think that this should be completely handled at the discretion of the Delegate and I think forcing competitors to do an extra attempt it's not in line with other regulations.

Do we really think it's fairer to force competitors to do an extra attempt than accepting that a puzzle was a bit better/worse than their own puzzle but they were fine with it?
Do we really consider the possibility that someone abuses this regulation as more important than our general approach that everyone gets the same scrambles?

The regulations do not define that competitors must own the puzzle they are using. The only requirement is that the puzzle was approved by a Delegate, which is obviously the case when the puzzle of another competitor was used.
It's not uncommon that competitors borrow puzzles from other competitors because their own puzzle is worse. Do we also think that gives them an unfair advantage?

There several other cases when competitors can decide whether they want to get an extra or not: any kind of disturbance, a judge forgetting to reset the timer... these are all situations in which competitors might have a tendency to ask for an extra if the scramble is bad.

Regarding a potential abuse that was mentioned before: the fact that you get an extra if you used the wrong puzzle can also be abused as well. If you hear that other competitors are not happy about their results and you assume that the scramble is bad, just go to the wrong station or with the wrong judge, quickly start your attempt and you get an extra. I think the result of such abuse is much worse than the risk that someone abuses this to do an attempt with a better puzzle.

**Comment by Ivan-Brigidano** [comment]
Viewing all arguments and some new cases on the WRC I realize that @Laura-O proposal of `at the discretion of the WCA Delegate` would work better.

**Comment by julesDesjardin** [comment]
Although Laura's arguments are quite convicing, I feel like one argument in favor of a systematic extra has been left off: this would remove the usual abuse of competitors choosing extras only for bad solves, since we would force them to do them, no matter what.
It also has no bias the other way round (with good solves being more likely to get extras), opposed to other extra cases, like misscrambles (bad solves are never checked, only good solves can be replaced by extras due to misscrambles) or forgotten sights blockers (DNF are sometimes not given extras, although this is a controversial choice with no obvious solution)

**Comment by xsrvmy** [comment]
Not sure if this is important: we do have a case for when an extra is specified in the regs: when a competitor accidentally stops the timer under 0.06

**Comment by EdHollingdale** [comment]
@xsrvmy but even then A6b1 has a carve out for the delegate to revoke the extra attempt. It could be improved however by making it clear that only the Delegate may grant the extra. Or we could remove A6b1 - I don't see many timer failures where it stops below 0.06, most are caused by an improper start.

**Comment by AlexKatyukov** [comment]
My opinion on this:

| When the Delegate was called | Cube is alike his | Cube is not alike his |
| ----- | ----- | ----- |
| After inspection start but before start timer | - | An extra should be granted |
| When solving | An extra should be granted | An extra should not be granted as competitor accepted this cube |
| After solve | An extra should not be granted as competitor accepted this cube | An extra should not be granted as competitor accepted this cube |

**Comment by Jambrose777** [comment]
> My opinion on this:
> 
> When the Delegate was called	Cube is alike his	Cube is not alike his
> After inspection start but before start timer	-	An extra should be granted
> When solving	An extra should be granted	An extra should not be granted as competitor accepted this cube
> After solve	An extra should not be granted as competitor accepted this cube	An extra should not be granted as competitor accepted this cube

If you are going to set a hard-set rule like this, but leave alike open to interpretation, you aren't solving any problems. Delegate's will still award extra's at their discretion.

**Comment by AlexKatyukov** [comment]
I'll tried to describe 'alike' but it's little hard to me because my English is not so fluent. Maybe word 'similar' will be more suited. 
I agree that now Delegate desicion is best option (despite I don't like At the discretion Regulations). But creating some guidelines for cube swaps will be good not only for Delegates but for competitors who can understand why it works that way.
