### ISSUE TITLE
Allow local competitions to reserve registration spots for newcomers

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#819]
This is an idea motivated by trying to trying to support:

- **WCA Mission** — particularly the "more people and more fun" part
- **Education** — ["To promote the sport of Speedcubing and its values as an educational subject..."](https://www.worldcubeassociation.org/documents/motions/03.2019.1%20-%20Objectives.pdf)
- Publicity/outreach leading up to a competition

Many of us remember the "old days", when it was easy to tell someone "Woah, you know how solve a cube? You should come to the competition in a few weeks!" and there would be spots available. Nowadays, registration in many parts of the world can fill up well ahead of the competition — often weeks or months ahead of time, and sometimes within minutes of when registration opens. It can take sustained interest for months until a newcomer gets a chance to participate at a local competition, and I think we should consider rethinking aspects of the WCA that can help get more people to that point.

I don't want to assume that the "old days" are necessarily better in this case, but I think it's clear that there is more friction to enter the sport. People may conclude "this sport is too serious for me" before they ever meet a welcoming community in person. I think many speedcubers would agree that going to their first official first competition was a critical point in their development.

In addition, there are situations where it is *desirable* to have many new competitors:

- You want to teach cubing at a school/youth center/camp/conference/festival, and hold a WCA competition where the new cubers can get into the sport and meet advanced cubers. (This has proven to be effective for sports like speed stacking and competitive chess.)
- You are able get a lot of press attention in the days leading up to the competition, and you'd like to use this as a chance to draw more people into the sport. (This is what brought me to my first competition!)

So I'd like to propose that competitions are allowed to reserve a certain percentage of their spots for first-time competitors. To keep this initial proposal simple, I'm imagining this:

- The competition announces that the competitor limit is P people, with X% reserved for newcomers.
- If fewer than X% of registrants are newcomers, then the next newcomer who signs up (or the the earliest newcomer on the waitlist) is always allowed to register. Else, everyone is handled on a first-come-first-served basis.
- Competitions with this policy should allow newcomers to sign up at any point before the competition, including on the spot.
  - For practicality, newcomers could be restricted to 3x3x3 if they sign up after a certain point.

(Note: this idea should probably be implemented in the WCRP in https://github.com/thewca/wca-documents . We can transfer the issue in GitHub at any point.)

**Comment by lgarron** [comment]
> * You want to teach cubing at a school/youth center/camp/conference/festival along with an associated competition where the new cubers can get into the sport and meet advanced cubers. (This has proven to be effective for sports like speed stacking and competitive chess.)

I'd like to note some examples:

# Nisei Week

I believe the Nisei Week competitions in LA are designed to welcome new competitors. They have a low number of events (at most three, often only one) and a high competitor limit. This has been a tradition for over 10 years:

https://www.worldcubeassociation.org/search?q=nisei%20week

# Summer Nostos Festival (SNFestival) Athens 2019

An excerpt from [my email on the Delegate report thread](https://groups.google.com/a/worldcubeassociation.org/d/msg/reports/3gDimFwhoSA/u99X2V1nCwAJ):

> The competition was the final event in a weeklong series of cubing events at the Summer Nostos Festival! Most of the effort to host cubing events throughout the week was organized by Mark Mitton and Susanna Mitton. (I hope you'll hear more about their efforts in the future!)
> 
> - The festival took place at the Stavros Niarchos Foundation Cultural Center, which is a beautiful venue that houses the Greek national opera and national library and has a glass-surrounded room inspired by the Parthenon at the very top.
> - Throughout the week, there were a whole bunch of cubing-related events: https://www.youtube.com/watch?v=7e1HuJ_nSGE
> - A series of performances. Most performances were acrobatic, but Daniel Goodman and Ricky Meiler featured in some of them.
> - A panel during a conference that was part of the festival: https://www.youtube.com/watch?v=3nRSJbwP6Qo&feature=youtu.be&t=4070 (Erik Akkersdijk and I were on stage with Mark Mitton and Ernő Rubik, but unfortunately we didn't get a chance to say anything really insightful because Ernő talked a lot. :-P)
> - Several workshops to teach cubing to kids, as well as an attempt at a more advanced workshop.
> - A mosaic of Ernő Rubik.
> - A visit from Viktor Bohm (who is involved in a significant part of the initiatives by Rubik's).
> - An interview with Ernő Rubik.
> - The competition!
> 
> Overall, the theme was "playing with complexity", and it was several people's goal to explore aspects of using the cube for education.
> We had a chance to mingle with the acrobatic folks, as well as people like Lily Hevesh (professional domino artist) and Bryan Berg (professional card stacker).

Unfortunately, the existing pattern of organizing WCA competitions made it difficult to make this engaging across the entire week for newcomers. Reserving spots at the competition for newcomers would have been tremendously useful.

# Arnold Classic 

Some competitions are associated with other events. One pattern that has been common (with various success) is to partner with "Arnold Classic" events around the world: https://www.worldcubeassociation.org/search?q=arnold#competitions

It would be great to give tools to competitions with at such shared events the option to specifically accommodate on-the-spot registration. If we combine this with math/science festivals, I think that would be a huge opportunity.

# More?

I can't think of too many examples off the top of my head, which I don't see as a good signal. I'd like to advocate that we intentionally *course-correct* in order to encourage competitions to bring in new competitors by giving them a tool like this.

**Comment by lgarron** [comment]
Another idea that I've heard brought up is that we can teach "how to solve a cube" workshops to beginners — think of the parents (or other guests: siblings, friends, spouses, extended family) at a competition. Some places like to hold 3x3x3 immediately after lunch. It would be cool to combine this:

- Set aside a corner of the room to teach beginners in the morning (while the normal competition is going on). With a little bit of training, one experienced cuber can teach dozens.
- If there are newcomer spots open, allow newcomers to sign up during lunch!

To some, this may seem to "cheapen" the sport by giving official results people who don't really cube, and might not even remember how to solve it on the following day. However, I think this is outweighed by the service to the WCA mission (more people and more fun), and if this engages even 10% of parents to stick with the sport I think that would be a great way to build an inclusive community. I would also like to see the activities associated with speedcubing competitions to be broadened more.

**Comment by Jambrose777** [comment]
I foresee a couple issues with this idea:

1. We have always had issues with returning competitors registering as new comers. Sometimes these are caught by the delegate, sometimes by wrt after the compeititon, and very few cases many months/years later or not at all. We will not be able to fairly implement a system which allows these registrations to be accepted whenever they would become illegitimate.
2. Official Identification is often not required in some countries (like the US) to compete. This means it is very easy to register under a fake name and birthday as a new competitor and be able to compete with multiple profiles. Even if we did check IDs it is extremely easy to obtain a fake ID and compete under a new fake name with this system. I don’t think we should encourage this abuse by any means, but a system catering to newcomers is likely to cause this.
3. You mention that this is a proposal in order to allow people to register last minute. But I foresee that given time registration can easily fill (especially in areas where people would want this system) with both the comeptitor limit and the % newcomers weeks or months before the competition. There is potential that this solution will ultimately not have any affect on the future. So in reality this is a short term solution and not a sustainable one.
4. What would you say if the world championship enforced such a system? Is that fair to other returning competitors? What about people that abuse 1 or 2?
5. Competitors and organizer and sometimes even delegates, have a hard enough time consistently enforcing current registration requirements (ie the comeptitor limit). How is adding another level of complexity going to help with this? Ultimately more organizers will receive emails asking why their spot isn’t accepted when the limit is not reached, or complaints that some people have precedence over others, there will be more cases of delegates making mistakes, more cases where WRC has to remove results of newcomers or returns registered as newcomers. All of that seems to go against our mission.

**Comment by maconard** [comment]
@lgarron I think my and Sydney Weaver's competition earlier this year is a good example of a competition pairing with a "how to solve" workshop too. However, since it was in such a remote area there would be no need to reserve X% for newcomers, since basically anyone not on the org team was a newcomer.

https://www.worldcubeassociation.org/competitions/CopperCountryCubing2019

**Comment by Samuel-Baird** [comment]
I don’t see why a newcomer who may not even continue with speedcubing should receive registration priority over someone who has been doing the sport for years. In areas where registration fills up fast this does give newbies a chance to get in but it also limits spots for people who consistently compete. 

The idea is cool and all but ultimately is going to cause more problems than it “fixes”, newcomers can register on time just like everyone else.

**Comment by ghost** [comment]
A quick comment on nisei week. As someone who has been to the last 5 of them, and been staff on at least 3 of those, I can tell you it is a nightmare. The amount of incidents from new competitors and the amount of people we have results in us always running behind schedule.

**Comment by alexmaasswca** [comment]
The problem with this is that I can very easily see someone who has competed at one competition before just signing up as a first time competitor, just so they can get into the competition.

**Comment by alexmaasswca** [comment]
I got a better idea, what about if the competition is at a college or school, allow reservation of registration spots for students and faculty of the university? It can be very hard to fake being a student, especially when an organizer is likely a student as well, and it avoids people missing out an extremely accessible competition for them to go to.

**Comment by Jambrose777** [comment]
@alexmaasswca you are asking to give prefential treatment to competitors based on factors outside their control. How is this fair to anyone?

**Comment by Samuel-Baird** [comment]
I think the best solution to allow new competitors to register would be 2 things.

1. Require competitions to be publicly announced and have their registration closed for X amount of time (1-2 weeks?)
2. Add a feature to the site that nofities you when a competition within X km of you is announced (where you can input X) 

With either or both of those in place everyone should have an opportunity to register.

**Comment by pedrosino** [comment]
```
I think the best solution to allow new competitors to register would be 2 things.

    Require competitions to be publicly announced and have their registration closed for X amount of time (1-2 weeks?)
    Add a feature to the site that nofities you when a competition within X km of you is announced (where you can input X)

With either or both of those in place everyone should have an opportunity to register.
```

That still doesn't solve the issue of registration being full very quick and a lot of newcomers not being able to register, when you have demand >>> supply.

**Comment by Samuel-Baird** [comment]
> ```
> I think the best solution to allow new competitors to register would be 2 things.
> 
>     Require competitions to be publicly announced and have their registration closed for X amount of time (1-2 weeks?)
>     Add a feature to the site that nofities you when a competition within X km of you is announced (where you can input X)
> 
> With either or both of those in place everyone should have an opportunity to register.
> ```
> 
> 
> That still doesn't solve the issue of registration being full very quick and a lot of newcomers not being able to register, when you have demand >>> supply.

It gives newcomers equal opportunity to register which seems fine to me, Lucas’ proposed method effectively limits returning competitors from competing.

Let’s say 20 spots are reserved at a 100 person competition. Now instead of having 100 spots to go for returning competitors have 80 to go for. If this happens for every single competition then you are basically cutting down returning numbers by 20% every time, this can in some regions make it impossible for returning competitors to get a spot. 

I would guess at least 50-60% of competitors never compete again after their first comp, probably 70-75% after their first two. 

So it’s great to cater to new people but when the odds are that they won’t ever compete again then why should they be given priority over someone who is going to continue to compete? Why should they get their spot? 

One last thing
If we do allow X% of spots to be reserved for newcomers then the remaining Y% should be reserved for returning competitors. If newcomers have reserved spots then it’s only fair (not that this system is fair at all) that returning competitors should have the same privileges.

**Comment by julesDesjardin** [comment]
All the objections in this thread seem to assume this will happen in every single comp (like Worlds ? Can we seriously imagine a WC orga team that wants to have more newcomers, after 2 Championships that didn't allow them ?), but Lucas gave very specific examples of such competitions. The way I see it, this would require a WCAT vote, and only a handful of competitions (maybe 20 or 50 per year) would be relevant for this. We could then take extra care that these particular newcomers are indeed newcomers, to avoid abuse (although it doesn't solve the issue of people registering under a fake name, but well, what can we do against that. I also highly doubt that many people will do it, that would mean having their results registered in 2 different profiles, it's quite useless)

Maybe we could also (or instead of this) have allocated space for "on the spot newcomers". It makes sense for most of these competitions as well, and would solve the issues of the comp filling up too quickly. (it would probably cause some trouble on the day of the comp if a lot of people want to register though)

**Comment by lgarron** [comment]
I'm not going to reply to everything in the intervening posts, because a lot of it is already addressed in my initial post (the motivation and the intended usage).

> * We have always had issues with returning competitors registering as new comers. Sometimes these are caught by the delegate, sometimes by wrt after the compeititon, and very few cases many months/years later or not at all. We will not be able to fairly implement a system which allows these registrations to be accepted whenever they would become illegitimate.

This is a valid concern, and an area of improvement for the WCA. However, I think it's unlikely that a large fraction of reserved spots will be taken up this way. Even if we can't perfectly solve this problem, the reserved spots can still help introduce a lot of new cubers to the sport.

> * Official Identification is often not required in some countries (like the US) to compete. This means it is very easy to register under a fake name and birthday as a new competitor and be able to compete with multiple profiles. Even if we did check IDs it is extremely easy to obtain a fake ID and compete under a new fake name with this system. I don’t think we should encourage this abuse by any means, but a system catering to newcomers is likely to cause this.

If a competitor intentionally does this, then:

1) they don't get all their results on the same profile, 
2) they have to be pretty creative to do this more than 1 or 2 times in the same area,
3) they risk the consequences of being banned.

If someone really cares about the sport, then getting all their results on the same profile is a significant incentive.

> * You mention that this is a proposal in order to allow people to register last minute. But I foresee that given time registration can easily fill (especially in areas where people would want this system) with both the comeptitor limit and the % newcomers weeks or months before the competition. There is potential that this solution will ultimately not have any affect on the future. So in reality this is a short term solution and not a sustainable one.

If that's happening regularly, new competitors are still benefitting and we are serving the WCA mission quite well! In fact, it would be a signal that we should adjust our strategy to accommodate this surging demand if we want to do the best possible job of serving our mission.

It would be nice if there were spots available to the new competitors up until the competition, but I also think it's reasonable to let organizers pick limits based on their venues/staff/etc.

In any case, this proposal will certainly have an effect, in that more new competitors are getting a chance to compete than otherwise.

> * What would you say if the world championship enforced such a system? Is that fair to other returning competitors? What about people that abuse 1 or 2?

As indicated above, this proposal is not aimed at championships.

(That said, I think that that this proposal could still be useful for large competitions. For example, you might want to hold a large competition to start the official cubing scene in a new area, but need to balance the desire to attract outside cubers with making the competition available to the locals.)

> * Competitors and organizer and sometimes even delegates, have a hard enough time consistently enforcing current registration requirements (ie the comeptitor limit). How is adding another level of complexity going to help with this? Ultimately more organizers will receive emails asking why their spot isn’t accepted when the limit is not reached, or complaints that some people have precedence over others, there will be more cases of delegates making mistakes, more cases where WRC has to remove results of newcomers or returns registered as newcomers. All of that seems to go against our mission.

Adding another level of complexity will probably not help with this, unless it spurs us to implement significantly better tooling for organizers. However, I strongly believe that proposal does a better job of supporting "more people and more fun" than it will cause problems, especially given that the WCAT and Delegates would both need to feel prepared enough to opt into this for a given competition.

**Comment by xsrvmy** [comment]
IMO there should be an option for the reserved spots to be released towards the end of registration, in case that not enough new comers show up.

**Comment by cubewhiz** [comment]
> IMO there should be an option for the reserved spots to be released towards the end of registration, in case that not enough new comers show up.

Yes, this is what I was expecting to find when reading the initial post. I don't think it's necessary to cater to newcomers who are finding about a competition on Friday and then looking to attend on that Saturday, but a newcomer who finds out a few weeks before the competition that a competition is coming up and there is space to register is a neat idea. It does complicate things, though, so I'm still evaluating the idea as a whole.

**Comment by hanwu85** [comment]
One thing I have noticed through the years is that experienced competitors usually have ways to know upcoming competitions information even before they are officially announced.  I know a few new competitors who kept missing the registration because they only know the WCA website.  They have to check very frequently to see if there are upcoming competitions,  and they have to remember which days the competitions are open for registration.  (So the newly bookmark feature is a good idea in my opinion.)

**Comment by EdHollingdale** [comment]
I don't mind this idea. My region has competitons that always fill up, but we don't yet have an issue with newcomers not registering (we have ~30% newcomers at my next comp which filled up quickly). If this changes however I wouldn't mind having the **option** to guarantee a ~20% newcomer ratio for two or three competitons per year. 

This certainly wouldn't be for every competiton! However I see it as being a useful tool for some organisers in specific regions. No reason in my mind not to give this as an option to use after careful discussion with WCAT and recognition that it will take extra work in checking all registrations for "fake-first-timers" as the registrations come in rather than all in one go at the end. We would need to work out if these benefits outweigh the effort and introduced complexity by adding it as a carve-out to the regulations or WCRP if it only gets used at 1% of competitons though.

**Comment by dancing-jules** [comment]
I'm very wary of anything that makes comps not equal-opportunity. I think the following things make it fair for everyone. 

1. Announce the comp early, so competitors can sort out their travelling early and cheap.

2. Leave some significant amount of time between the announcement and start of the registration period, so that people can find out the comp exists, before it's full. And they can decide if and how they want to attend without the stress of signing up.

3. Have the registration period start at a sensible time (IMO preferably between 6pm and 9pm), when most people are neither sleeping, nor at work/school.

4. Don't selectively give out information about to comp only to certain demographics (though if 1 and 2 are followed, this is less of a problem).

Following these makes it equally possible for everyone to sign up (apart from bad internet connection).

You could start the registration period relatively late, if you want to give people the opportunity to sign up late. As long as the announcement happens significantly earlier, everybody has the same chance to find out about the comp.
