### ISSUE TITLE
Allow competitions to reserve spots for a variety of demographics

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#840]
I have seen some good ideas in both #819 and #822 and I would like to build upon them. If we could reserve spots for other factors such as race, gender, age, sexual orientation and nationality it could make cubing a much better experience for everyone.

Ideally the organizer would get to choose which which demographics get reserved sports at each competition and WCAT would have to approve it.

Minority in areas with registration that fill quickly may not be able to register. It's extremely unfair to females for example if the odds of them getting in are slim because there are so many male competitors, reserving spots for them could allow more diversity and growth at competitions. 

Another issue is competitors travelling cross borders often can't register right away for a competition, they have to figure out their travel plans first. This can make it almost impossible for them to actually travel for competitions. 

Final example is age, young competitors. Young competitors are more devastated than older ones if they cannot attend a comp. In addition the WCA's goals even talk specifically about young people  "The World Cube Association wants to bring opportunities for community membership and leadership to young people around the world through increasing the accessibility of our 'twisty puzzle' competitions."

Please add more examples of how allowing organizers to reserve spots could be beneficial!

**Comment by julesDesjardin** [comment]
Please stop polluting our repository with troll issues because we don't agree with you.

**Comment by UnderwaterCuber** [comment]
> Please stop polluting our repository with troll issues because we don't agree with you.

This isn’t a troll, I feel like this could genuinely help build variety in cubing which would be awesome!

**Comment by dancing-jules** [comment]
I don't think either 819 or 822 are a good idea. Announce your comps early and don't start the registration period at 3am. Ideally: make the competitor limit proportional to the local cuber population.

**Comment by Samuel-Baird** [comment]
> I don't think either 819 or 822 are a good idea. Announce your comps early and don't start the registration period at 3am. Ideally: make the competitor limit proportional to the local cuber population.

In many areas that just isn’t feasible, for example China has registration fill up within a few minutes. If they had to make their competitions reflect the local population they would have to either have to turn what would normally be a 1 day comp into a 3 day comp or cut down on their events dramatically. 

I appreciate you giving constructive feedback though :)

**Comment by dancing-jules** [comment]
> either have to turn what would normally be a 1 day comp into a 3 day comp or cut down on their events dramatically

Then do that. I am extremely wary about anything that makes comp not equal-opportunity.

**Comment by ghost** [comment]
Reserving spots for something that is out of control for competitors is not a good idea in general. 

Also I would be in favor of banning this account after the number of troll posts that have come from it.

**Comment by ghost** [comment]
Also for reserving spots for someone with a certain sexual orientation is espically dumb, as something like that is an espically touchy subject in parts of the world, and it would be too easy for someone to fake something like that in order to get a spot at a comp.

**Comment by dancing-jules** [comment]
The only thing, that makes it harder or easier for certain demographics to sign up, that isn't in control of the organisers, is internet connection. Everything else can be controlled by organisers:

1. Announce the comp early, so competitors can sort out their travelling early and cheap.

2. Leave some significant amount of time between the announcement and start of the registration period, so that people can find out the comp exists, before it's full. And they can decide if and how they want to attend without the stress of signing up. 

3. Have the registration period start at a sensible time (IMO preferably between 6pm and 9pm), when most people are neither sleeping, nor at work/school.

4. Don't selectively give out information about to comp only to certain demographics (though if 1 and 2 are followed, this is less of a problem). 

Following these makes it equally possible for everyone to sign up (apart from bad internet connection).
