### ISSUE TITLE
clarify if a phone may be used to record and clarify whether streaming is legal

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#847]
Currently 2i2 explicitly says CAMERAS may be used at a station at the discretion of the delegate. I could see delegates interpreting the use of non-camera recording devices in one of two ways: they are using the camera function of the device so it’s ok, or the device is not a camera therefore it’s not ok. 

Also the regs don’t really discuss anything about streaming (use of a streaming device such as a webcam or phone) at all so it could be nice to clarify the legality of that. (I’m personally not in favor of allowing streams since competitors could view them to see scrambles but lots of people like to stream, especially for large comps)

**Comment by xsrvmy** [comment]
I have never heard of phone cameras being disallowed. IMO disallowing them is a bad idea. Cubing companies have required a HD recording of record footage for prize money since the 3.47 WR. Not everyone capable of a CR (or Chinese NR) would be able to afford a camera with good enough quality, but most phones can record HD. Also if the venue has no charging outlets a camera usually cannot last the entire comp.

**Comment by Samuel-Baird** [comment]
> I have never heard of phone cameras being disallowed. IMO disallowing them is a bad idea. Cubing companies have required a HD recording of record footage for prize money since the 3.47 WR. Not everyone capable of a CR (or Chinese NR) would be able to afford a camera with good enough quality, but most phones can record HD. Also if the venue has no charging outlets a camera usually cannot last the entire comp.

I’m definitely in favor of allowing phones to continue to be used to record solves.

**Comment by AlexKatyukov** [comment]
Main question: why I should have 2 devices (phone and camera) instead 1 (phone)? Don't think that we need to clarify it.
And about livestreaming: the best way is to oversee competitors waiting area and warn/disqualify competitors who watches to avoid it.

**Comment by xsrvmy** [comment]
Banning livestream is not gonna work cuz a non-competitor can stream.
Abnning watching the stream in the competitor's area also doesn't work cuz no one should have the right to see what you are doing on your phone.

**Comment by maconard** [comment]
I don't see how there would be a problem with classifying watching streams while competing as cheating. Everything in the WCA functions on trust and honesty, and if someone happens to be caught watching streams action should be taken. That doesn't mean checking people's phone, since the default would be trusting that they aren't cheating.

**Comment by Samuel-Baird** [comment]
> Banning livestream is not gonna work cuz a non-competitor can stream.
> Abnning watching the stream in the competitor's area also doesn't work cuz no one should have the right to see what you are doing on your phone.

You can ban competitors from using phones in the competitor waiting area,  prevent them from communicating with others and prevent them from leaving the competitor area until the round is over.

**Comment by xsrvmy** [comment]
Then how do you record using your phone? Banning phones completely is unnecessarily strict for sure.

**Comment by Samuel-Baird** [comment]
> Then how do you record using your phone? Banning phones completely is unnecessarily strict for sure.

Not being able to record doesn’t cause anyone harm, a system which makes it easy to cheat does cause people harm. ¯\_(ツ)_/¯

**Comment by maconard** [comment]
I personally don't record my solves, but I think a lot of people would consider not being allowed to record as devastating to their competition experience, or "harm" as you call it.

**Comment by xsrvmy** [comment]
@maconard It can cost you thousands of dollars actually because of the new prize money rules from cubing companies. I think Lucas once said that the WRC views recording as a privilege, but basically everyone else, including Moyu and Qiyi seem to view at as a right.
@UnderwaterCuber You are trying to ban phones for a very specific function that it is seldomly used for. That is not reasonable. In a school exam banning phones is reasonable because a student would most likely be using a phone to cheat. However in a cube competitor phones are barely ever used for cheating so it does not make sense to ban it.
