### ISSUE TITLE
Specify time frames when competitors may compete?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#86]
See the [Cube Factory 2013](https://groups.google.com/forum/#!topic/wca-delegates/FNQlxW-DPbI) report.

Competitors have occasionally been allowed to compete earlier/later than other competitors in a round. This has been allowed inconsistently, and usually requires favorable treatment from the Delegate/organizers.

We could try to strengthen the specifications on when a competitor should compete relative to others, but there are complications like staff groups that compete entire days before the remainder of the first round.

I'm not sure what's good here. A Guideline listing permitted reasons for a competitor to compete at certain unusual times? Specifications about scheduling? A general point addressing preferential/individual treatment?

For reference, the [2010 Regulations](https://www.worldcubeassociation.org/regulations/history/files/regulations2010.html) had the following line:

> 9l)   All competitors must compete in each round during the same time frame.

**Comment by sarahstrong314** [comment]
I don't see any real problem with the way it is now. The Delegate and/or organizers would have the best judgement on whether to allow someone to compete before/after other competitors in a round. I'm not really concerned that it's allowed inconsistently, since it should depend on whether it's feasible for the specific competition. I think it's unnecessary to specify that competitors aren't allowed to compete after/before a certain time, as long as it's during the competition and except for when the next round of that event (if there is one) has begun.

**Comment by pedrosino** [comment]
Agreed with Sarah. This doesn't happen that often, I think, and Delegates have good reasons to allow such things (someone leaving earlier to catch a plane, someone got stuck in traffic or whatever).

As long as no advantage is given to anyone, and as long as everybody competes before the next round, I think this should be allowed.
