### ISSUE TITLE
New format for 3x3x3 Blindfolded

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#860]
My understanding is that top blindfolded cubers would love to see a different format than Best of 3 used for rankings. I've seen the following suggestions:

- Avg5
- Median of 3
- Second-best solve of 5
- Best of 3/Best of 5 #571

**Comment by xsrvmy** [comment]
I'm not sure if ao5 is actually being suggested a ranking format. It seems some people say ao5 but really just want 5 solves per round. I heard someone suggest bo3/bo5 with a mandatory bo3 cutoff though.

**Comment by aneurinhunt** [comment]
If it changes it needs to be fairly simple. Some people have suggested over convoluted formats.

 Average of 5 requires 80% accuracy which is too harsh. Median of 3 requires 66% and second-best of 5 requires 40% which is the smallest increase from the current format. Do you want to favour accuracy more or speed?

**Comment by jronge94** [comment]
I'm by no means a great bld solver, but anything that requires more than 50% success rate I'm strongly opposed to as it shifts the spirit of bld too much. 2nd best of 5 or the mean of the best 2 of 5 which I've seen proposed I'd find acceptable, anything that requires a higher success rate we should leave for multi-bld.

**Comment by sebastianotronto** [comment]
In #571 I suggested a combined Bo3/Bo5 format, which has the advantage of giving 5 attempts each round (as it is for all events of similar length, or even longer) while keeping the required success rate at 1/3. But I am changing my mind about the "best of" format for 3BLD. I think some kind of mean / median might be better.

I do want to see 3BLD changing to **5 attempts** per round (with Ao5 replacing Mo3 for the average rankings, the benefits of which I have explained in #571), and the most reasonble accuracy to require should be 2/5 (40%, only slightly higher than it is now).
With these constraints I see only two possible formats: **mean of best two solves** or **second best solve**. I prefer the former, but I like both ideas.

**Comment by cubewhiz** [comment]
I'm not in favor of creating new formats at this time. I believe this change solves a problem that doesn't really exist.

**Comment by sebastianotronto** [comment]
> I'm not in favor of creating new formats at this time. I believe this change solves a problem that doesn't really exist.

There are two points that one may or may not consider a problem, but could certainly use some improvement:

1. 3BLD rounds only have 3 attempts, while events of similar length (4x4, 3x3 with feet) and even slower events (5x5, Megaminx) have 5. This means fewer chances to set new records and, more importantly, less fun for people specializing in this event. (Con: 3BLD beginners are much slower than 5x5/megaminx beginners; Counterpoint: a suitable cumulative time limits is an easy solution.)
2. Given how scramble-dependent the event is, it is quite common (e.g. in case there are two "bad" scrambles and a "very good" one) that the winner of a round is determined by their performance on the easiest scramble, effectively reducing the format to a Best of 1.

I know that many prefer the "if it ain't broken, don't fix it" point of view, but change isn't inherently a bad thing.

**Comment by xsrvmy** [comment]
> Counterpoint: a suitable cumulative time limits is an easy solution.

Counter-counterpoint: If two successes are required by the new format, then this significantly increases the accuracy requirement but only for beginners.

**Comment by sebastianotronto** [comment]
No, because the best single can be used as a tie-breaker (in case of DNF second best/mean of best 2).

**Comment by Samuel-Baird** [comment]
Average of 5 makes the most sense to me. It’s simple and we already have the format so it makes sense. 

Median of 3 seems good as well but adding new formats seems somewhat unnecessary and I feel like will just confuse people. 

Second best of 5 just sounds a little crazy :P 

Bo5 has similar problems with Bo3 but just takes up more competition time so I’m not a fan of that one.

**Comment by xsrvmy** [comment]
ao5 definitely does not make sense as a ranking format (changes focus to accuracy instead o speed). Bo3/Bo5 is probably the way to go to add solves if you don't want an event to have three different results, but we don't normally have mandatory cutoffs

**Comment by Burnsy101** [comment]
Second best of 5 sounds really reasonable - makes it not harsh to progress, and not as luck based as bo3, where having a solved buffer on what could be a nice scramble changes so much.

However, we want to make sure it is easy enough to get a mean / average - assuming cumulative cutoffs stay the same, it might mean you need to be --30 seconds faster to get an average than previously, which could put, say, a sub 3 solver off the event

**Comment by Samuel-Baird** [comment]
> ao5 definitely does not make sense as a ranking format (changes focus to accuracy instead o speed). Bo3/Bo5 is probably the way to go to add solves if you don't want an event to have three different results, but we don't normally have mandatory cutoffs

The problem with bo5 is it doesn't really have any improvements other than allowing the solvers to get more solves. There is still only a single scramble that matters to perform well on, bo5 helps reduce that a bit but it’s still an issue.

**Comment by xsrvmy** [comment]
@UnderwaterCuber It says second best of 5 not bo5.
 It really depends on whether or not the WCA wants an event to have three different important results each round (best single, ranking result, average). If not then the only way to increase number of solves is a bo3 cutoff.

**Comment by 2017SERG03** [comment]
My opinion regarding this issue
1)ao5
The avg is 100% the best format exist. It's fairly  easy to get the result, that faster than you global with mo3 best out of 5, and also it's easy to get mo3 worse than your actual speed( or don't get it at all).But actually we need to replace this format because it slows down a progress in 3bld.And ao5 can easly fix it ,because it don't require rushing that much to get a good ao and also reducing stress during the attempt.
2)bo5
 Mean of 2 best solves and 2nd best are pretty good in theory ,but when you are very relevant in the round and there are also a few people that averaging the same speed it's hard to get a single solve.Look at the 2nd round of 2019 Worlds , fast people were getting their best solves on different scrambles, or were unable to get a single one.
It's hard to say ,that it is turning to bo1 , because there is a low probability, that scrambles will be 11 8 11 11 11 or so.For the most of the competitions it will be enough to determine the best. Also if you have to get 2 solves out of 5 it will be hard for small comps to compile the podium which isn't that nice for such a small event.

**Comment by 2017SERG03** [comment]
My opinion regarding this issue
1)ao5
The avg is 100% the best format exist. It's fairly  easy to get the result, that faster than you global with mo3 best out of 5, and also it's easy to get mo3 worse than your actual speed( or don't get it at all).But actually we need to replace this format because it slows down a progress in 3bld.And ao5 can easly fix it ,because it don't require rushing that much to get a good ao and also reducing stress during the attempt.
2)bo5
 Mean of 2 best solves and 2nd best are pretty good in theory ,but when you are very relevant in the round and there are also a few people that averaging the same speed it's hard to get a single solve.Look at the 2nd round of 2019 Worlds , fast people were getting their best solves on different scrambles, or were unable to get a single one.
It's hard to say ,that it is turning to bo1 , because there is a low probability, that scrambles will be 11 8 11 11 11 or so.For the most of the competitions it will be enough to determine the best. Also if you have to get 2 solves out of 5 it will be hard for small comps to compile the podium which isn't that nice for such a small event.
------------------
I think , that we should to create a pool for top20 WR ranking persons, because they have a better understanding of developing the event.

**Comment by 2017SERG03** [comment]
My opinion regarding this issue
1)ao5(as average format)
The avg is 100% the best format exists. It's fairly easy to get the result, that faster than you global with mo3 best out of 5, and also it's easy to get mo3 worse than your actual speed( or don't get it at all).But actually we need to replace this format because it slows down a progress in 3bld.And ao5 can easly fix it ,because it don't require rushing that much to get a good ao and also reducing stress during the attempt.
2)bo5(as counting format)
Mean of 2 best solves and 2nd best are pretty good in theory ,but when you are very relevant in the round and there are also a few people that averaging the same speed it's hard to get a single solve.Look at the 2nd round of 2019 Worlds , fast people were getting their best solves on different scrambles, or were unable to get a single one.
It's hard to say ,that it is turning to bo1 , because there is a low probability, that scrambles will be 11 8 11 11 11 or so.For the most of the competitions it will be enough to determine the best. Also if you have to get 2 solves out of 5 it will be hard for small comps to compile the podium which isn't that nice for such a small event.
3)conclusion
I think , that we should to create a pool for top20 WR ranking persons, because they have a better understanding of developing the event.

**Comment by mintydev789** [comment]
> My opinion regarding this issue
> 1)ao5
> The avg is 100% the best format exists. It's fairly easy to get the result, that faster than you global with mo3 best out of 5, and also it's easy to get mo3 worse than your actual speed( or don't get it at all).But actually we need to replace this format because it slows down a progress in 3bld.And ao5 can easly fix it ,because it don't require rushing that much to get a good ao and also reducing stress during the attempt.
> 2)bo5
> Mean of 2 best solves and 2nd best are pretty good in theory ,but when you are very relevant in the round and there are also a few people that averaging the same speed it's hard to get a single solve.Look at the 2nd round of 2019 Worlds , fast people were getting their best solves on different scrambles, or were unable to get a single one.
> It's hard to say ,that it is turning to bo1 , because there is a low probability, that scrambles will be 11 8 11 11 11 or so.For the most of the competitions it will be enough to determine the best. Also if you have to get 2 solves out of 5 it will be hard for small comps to compile the podium which isn't that nice for such a small event.
> 3)conclusion
> I think , that we should to create a pool for top20 WR ranking persons, because they have a better understanding of developing the event.

I believe that if 5 attempts are allowed, ao5 should be recognized, but shouldn't be used for rankings. In my opinion, the best option for rankings is bo5, because this format should be very easy to explain to someone and would only have the same downsides as bo3, but with 5 solves these downsides would already be alleviated to some extent

**Comment by equi1** [comment]
I definitely do think that allowing 5 solves and using ao5 as the average format is a step in the right direction, but there's still a problem (or at least I think of it as a problem). Why does the format used for comp rankings differ from the average format? It isn't like this in any other events (apart from 4 and 5bld ofc). This causes people to either go for singles and better comp rankings or for averages, the latter of which worsens comp results. Just my two cents on the issue.

**Comment by xsrvmy** [comment]
Requiring an ao5 would result in very unoredictable podiums. Plus this would be way above mbld requirement

**Comment by Samuel-Baird** [comment]
> Requiring an ao5 would result in very unoredictable podiums. Plus this would be way above mbld requirement

I think 3bld already has some unpredictable podium problems. 

What does this have to do with mbld?

**Comment by xsrvmy** [comment]
![Screenshot_2020-02-24-13-21-06-576_com algeo algeo](https://user-images.githubusercontent.com/7594338/75179820-ec0f4500-5708-11ea-9e3d-2a7f23d90130.png)

Here is a plot of accuracy vs chances of a non-DNF bo3 result and ao5 result. You can obviously see that making a decision like this would completely change the nature of the event.
The most notable problem with ao5 is that a small variation in accuracy leads to a big change in chance of a non-DNF ao5 between 60-90%.
Additionally, this is extremely beginner unfriendly because cumulative time limits can no longer be applied in the usual way.


BTW the mention of MBLD is that it does not make sense for getting a non-DNF ranking result in 3bld to be harder than mbld.

**Comment by Samuel-Baird** [comment]
> ![Screenshot_2020-02-24-13-21-06-576_com algeo algeo](https://user-images.githubusercontent.com/7594338/75179820-ec0f4500-5708-11ea-9e3d-2a7f23d90130.png)
> 
> Here is a plot of accuracy vs chances of a non-DNF bo3 result and ao5 result. You can obviously see that making a decision like this would completely change the nature of the event.
> The most notable problem with ao5 is that a small variation in accuracy leads to a big change in chance of a non-DNF ao5 between 60-90%.
> Additionally, this is extremely beginner unfriendly because cumulative time limits can no longer be applied in the usual way.
> 
> BTW the mention of MBLD is that it does not make sense for getting a non-DNF ranking result in 3bld to be harder than mbld.

Any format change will change the nature of the event :P if it makes the event better then it’s worth it 

How is it harder?

**Comment by jronge94** [comment]
> How is it harder?

to get ranked using ao5 you need 4/5 or 80% accuracy and I'd assume the time limit per solve will easily be 5min or less if we'd use this system as bld would otherwise take too long.

for mbld 2/4 in 40:00 is a valid result. which I would argue is easier than getting 80% accuracy in rounds with varying time limits.

switching to 5 attempts I like 
using ao5 to rank people in comp is a horrible idea.
