### ISSUE TITLE
Counting rotations as moves in FMC

### ISSUE THREAD

**Issue by aneurinhunt** [thewca/wca-regulations#865]
An alternative to removing wide moves and rotations. 

Pro
-Making grading easier 
-Discourages the use of rotations. 

Note: For advanced techniques like "slicey shenanigans" it can effect it slightly but no where near as much as removing wide moves and rotations. 

Con
- It will disadvantage beginners more than experienced solvers. 
- Rotations are moves that affect the state of the cube.

I thought it would be useful to have this as a separate discussion.

**Comment by ghost** [comment]
While I would like to find a way to discourage rotations in FMC, one problem with this proposal is that rotations are not moves, so it would be wrong to count them as such. If FMC was measured in "actions to the cube" then it wouldn't be misleading to count them as such. On another note, rotations are discouraged because of the 80 action limit, however this isn't that strict as it is still fairly easy for someone who knows F2L to find a solution under 80 moves. I don't see rotations slowing down grading that much, it just takes a few extra seconds to subtract them from the total count of actions, and as someone who has helped grade 90+ solutions from U.S. Nats 2019 only 1-2 people used rotations during their solutions.

**Comment by xsrvmy** [comment]
> It will disadvantage beginners more than experienced solvers.

It's worse. I disadvantages beginners and worl class solvers more than others

> Rotations are moves that affect the state of the cube.

The WCA clearly doesn't consider the orientation of a puzzle to be part of the puzzle state. Scrambled puzzles can be in any orientation. And usually state in only considered with respect to the center stickers anyways.

**Comment by lgarron** [comment]
This would solve a few of the issues that full removal would solve:

- Counting the moves that affect the result is easy.
- We don't need a separate metric for move limit.
- It discourages use of rotations, which could reduce judging issues related to rotations.

Beginners are also more likely to focus on writing *any* valid solution rather than the shortest one, so it doesn't have a strong penalty for them. It would introduce a tradeoff for more advanced competitors.

I know the FMC community has been actively discussing #757. Has anyone determined how they view counting rotations as moves?

> The WCA clearly doesn't consider the orientation of a puzzle to be part of the puzzle state. Scrambled puzzles can be in any orientation. And usually state in only considered with respect to the center stickers anyways.

Not quite! Orientation is part of the scramble for blindfolded events. We also have a puzzle where some "moves" (moving pins with 0 wheel clicks) don't affect the solved state.

**Comment by Samuel-Baird** [comment]
I would be in favor of this over removing rotations entirely. My overall preference would be to keep rotations though.
