### ISSUE TITLE
Clarify how scramble signatures work for 6, 7, mega and mbld

### ISSUE THREAD

**Issue by xsrvmy** [thewca/wca-regulations#866]
With all other events, the scrambler needs to confirm that one puzzle is scrambled correctly. However with 6, 7 and mega, the acramble may be incorrect, and for mbld, there may be multiple scramblers.
I think there should be an explicit statement in the regs on what it means for the scrambler to sign in these cases.

**Comment by Ivan-Brigidano** [comment]
Good point! I've just clarified it in the PR draft (#854)

**Comment by Laura-O** [comment]
It's a common misconception that for 6x6x6, 7x7x7 and Megaminx scrambles "may be incorrect".
According to the regulations _"it is not necessary to correct the puzzle state, at the discretion of the WCA Delegate"_. It might seem like a minor difference, but it's not, especially as it's "at the discretion of the WCA Delegate".

Therefore, I do not see a reason why these events should be completely excluded here. It just should be worded in a way that a signature for these events does not mean the scramble is correct.

**Comment by Ivan-Brigidano** [comment]
I fully agree with @Laura-O

**Comment by maconard** [comment]
I agree with Laura about 6, 7, and mega. These scrambles should be performed correctly, especially if the competition is on schedule, and at delegate discretion they may be allowed to remain incorrect. That means the signatures should function normally.

However, MBLD is special. We should consider not requiring the signature for MBLD, or requiring a batch of all involved scramblers signing on the back of the card or something.

**Comment by Ivan-Brigidano** [comment]
> However, MBLD is special. We should consider not requiring the signature for MBLD, or requiring a batch of all involved scramblers signing on the back of the card or something.

I think is better to require signatures in MBLD. This way could also be a good way to handle MBLD incidents together with [allowing to re-scramble cubes](https://github.com/thewca/wca-regulations/pull/851#issuecomment-540468602)

**Comment by maconard** [comment]
@Ivan-Brigidano I lean in that direction as well, in which case we must find a solution to effectively record multiple scramble signatures for each attempt.

**Comment by Ivan-Brigidano** [comment]
I think that your idea of signing on the back of the card could work pretty well

**Comment by xsrvmy** [comment]
Another idea for mbld: someone checks all the scrambles and sign it so there is only one signature.

**Comment by SAuroux** [comment]
In my experience, multiple people scrambling for one MBF attempt is actually very undesirable and one of the prime causes for duplicate scrambles in the event. Instead of thinking who needs to sign in such a case I would rather propose to add a recommendation guideline that MBF puzzles for one attempt should be scrambles by only one scrambler.

**Comment by xsrvmy** [comment]
@SAuroux assigning one page of scramble per person shouldn't cause duplicates

**Comment by lgarron** [comment]
I agree with Laura's point that Megaminx, 6x6x6, and 7x7x7 scrambles should still have signatures. Someone still needs to vouch that the puzzles went out in a sufficiently scrambled state.

Even though the Delegate approves this, I think it's best for the judge to sign (not the Delegate), since this is a routine process rather than a noteworthy incident.

> However, MBLD is special. We should consider not requiring the signature for MBLD, or requiring a batch of all involved scramblers signing on the back of the card or something.

I don't see that this is a good reason. Even if there are backup cubes, the organizers are still responsible for making sure that the scrambles are correct. Duplicate scrambles in Multi-Blind are the most preventable scramble mistakes.

Having someone check the top faces of the puzzles is very effective (catches any duplicate scrambles, and can reveal most minor mis-scrambles), and should be easy to do if you place 7 cubes per row to match the number of scrambles per page. We can even update TNoodle to include a "scramble checking sheet" showing the tops of puzzles so that you can directly compare the whole pattern of puzzles. (Note: we should probably update [H1a3](https://wca.link/H1a3) if we do this.)

**Comment by xsrvmy** [comment]
> (Note: we should probably update H1a3 if we do this.)

I haven't heard of anyone using 7 packs, and using a big box for 7 cubes doesn't make much sense. Probably better to leave H1a3 as is.

**Comment by dancing-jules** [comment]
For 6/7/mega: 

The few times I scrambled this it went like this: I scramble, I notice it is a mis-scramble, I ask a delegate (or a person appointed by the delegate) "is this sufficiently scrambled?", they say "yes, it's okay", I sign and send out the cube.

Seems like a sensible procedure to me (as long as scramblers don't pre-sign, which is a whole other issue).

**Comment by xsrvmy** [comment]
At local comps my delegate actually asks scramblers to use own judgement to individual scrambles are usually not checked. Sometimes it takes a long time to notice a misscramble on 6 and 7
