### ISSUE TITLE
Require using the same cube model for MBLD

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-regulations#870]
Some people use different cubes for MBLD and then they know the memorization of every single one just by turning it.

To point out an example, a friend was trying 3 cubes and he didn't messed up the memorizations because both three cube were different models (and turns slightly different). This was even more noticeable because one of them was stickered and the other two stickerless.

This used to be impossible because cubes used to be very expensive. But now there are lot of cheap cube so people can use them.

**Comment by Ivan-Brigidano** [comment]
I know this is very controversial but I want to open a debate and see other people opinions!

**Comment by AlexKatyukov** [comment]
I have thought about it 1-2 years ago. But even now a lot of competitors have a problems with cubes search (questions like "do you have a couple of cubes without logo" is very often in Russia).

It's my story, just for record.
I took part in MBF at first time when only two competitors were registered. I had an idea to be a third with 2 cubes — eazy top-3 if I will have successful solve. I didn't think about cubes but I could participate. Second competition was in a week and I have 3/3 success and first place (so much other's DNFs). And I couldn't provide all the same cubes. 

It's a my personal story that takes a good place in my cubing memory. If then there was this rule, story would be impossible.

**Comment by pedrosino** [comment]
I don't think this is practical. It's hard for competitors to provide 40+ cubes of the exact same model, hard for delegate (or someone else) to check all cubes looking for that (already have to check for logos and bad stickers). Also, it would discourage people who like to do MBLD occasionally but don't have a bunch of identical cubes (I'm one of those).

**Comment by maconard** [comment]
When I first competed in MBLD I saw someone using 4 different sized cubes, so they would always know which cube they were grabbing even if they couldn't remember the pack order. I saw this as some sort of unfair disadvantage at first, but I guess it doesn't really bother me. 

Personally, I use a GTS3M + some number of Yuxin Little Magics + a TengYun, so I memo the GTS3M first, then all the Magics, and end on the TengYun.

For now at least, it's 1) a part of strategy and 2) a part of making the event budget friendly.

**Comment by Jambrose777** [comment]
This change would certainly cause many to have to not compete in multi-blind, reduce the number of cubes significantly, or invest in a new set of cubes. In WCA we try to make competitions accessible to everyone; restricting the entry to an event to an even higher level will cause more and more people to be disinterested in an event which is already arguably one of the most problematic in WCA.

I would not think that having distinguishable cubes will give you any advantage ever. If you memorize a cube and associate it to a cube type, along with that you have it in a specific place among the cube arrangement that you associate the cube with. The extra qualities don't provide an advantage. 

I'd also like to point out that if this was ruled as an advantage, then it would not even affect the top competitors in the event, as significantly varying cubes in a large attempt will cause issues in turning style and speed when executing (which is why most top competitors have 1 set of cubes).

**Comment by xsrvmy** [comment]
Also to add to the discussion, for anyone who doesn't main MBLD this just prevents them from using their 3bld main for the last cube in multi

**Comment by lgarron** [comment]
I think that this change is impractical unless the WCA provides Multi-Blind puzzles for competitors. I don't think the WCA should provide Multi-Blind puzzles for competitors.

As Jacob outlines above, this has has a significant impact on "more people" and "more fun". I would say that using different cubes is similar to allowing logos on 2x2x2: definitely can be used to get an advantage once in a while, but not enough to justify a Regulation against it.

> I would not think that having distinguishable cubes will give you any advantage ever. If you memorize a cube and associate it to a cube type, along with that you have it in a specific place among the cube arrangement that you associate the cube with. The extra qualities don't provide an advantage.

Above, @Ivan-Brigidano offers at least one example where it provided an advantage.

As you describe, a good strategy lets you keep track just as well. But it can be used opportunistically for recovery.
(In this regard, it's similar to how you could use a raised logo to sanity check your parity when using M2. In theory your memo gives you enough information to recover this. But feeling a sticker is definitely a shortcut.)

**Comment by SAuroux** [comment]
I remember seeing the exact same discussion years ago. It was then discarded after everyone realized that if someone really wants to have distinguishable puzzles in MBF, this is very well possible with the same cube model by varying tension and lubrication.

**Comment by timreyn** [comment]
I would not be able to enforce this regulation as a judge or delegate, as my ability to recognize cube models is not strong enough.

**Comment by Samuel-Baird** [comment]
This idea is just too difficult to enforce. If you don’t want cubes to be distinguishable there can’t be a mix of differing magnet strengths and cubes without magnets, cubes have to be broken in the same, tensioned the same, can’t have different sticker sizes, lubricantes the same, etc. 

Many competitors also don’t have enough of a single brand of cube to do their usual size multi attempts and it may not be financially feasible to get more cubes for them. In some places where it is already difficult to get a lot of the same cube (I’m thinking Argentina) competitors often borrow cubes from other competitors for multi. So I’m sure that implementing this reg would definitely cause a decrease in sizes of attempts.

In addition competitions just don’t have the time or resources to check every single cube to make sure everyone’s is using the same model of cube.

**Comment by dancing-jules** [comment]
I'd also say: Yes, in an ideal world the cubes should be indistinguishable, but enforcing that creates more issues than it solves. 

And anyone who's actually good at the event, is going to attempt enough cubes that they have neither the time nor the ability to distinguish cubes by feel.

**Comment by sebastianotronto** [comment]
I don't think being able to distinguish the cubes by feeling is inherently bad for the event. I don't see any way one could abuse this that changes the nature of Multi BLD drastically: one still has to memorize the same amount of information. If using different cubes can help a competitor avoiding mistakes, good for them.

For example, in the case described by @Ivan-Brigidano, I don't find it completely correct to say that his friend "didn't messed up the memorizations because both three cube were different models": first of all, he didn't mess up the memorization because he memorized and recalled all the information correctly! It may be that having different cubes helped him recall which memo corresponded to which cube, but the association "cube model 1 - memo 1" is no less information that the association "leftmost cube - memo 1".

**Comment by xsrvmy** [comment]
In response to some of the discussion about, the advantage is not for associating cube with memo. The advantage is it is easier to realize if you picked up the wrong curve.
