### ISSUE TITLE
Allow A2d to be more permissive

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#875]
Similar to #823 
A2d) When taking a puzzle from the scrambler, the judge briefly inspects the puzzle to ensure thorough scrambling of the puzzle. The judge raises any concerns with the scrambler, who then conducts a detailed check.

Since runners happen to neither be scramblers or judges it would make sense to modify this reg, maybe to something like this:

After receiving a puzzle, the judge briefly inspects the puzzle to ensure thorough scrambling of the puzzle. The judge raises any concerns with the scrambler, who then conducts a detailed check.

Or we could modify the regs to acknowledge that runners exist :P

**Comment by xsrvmy** [comment]
Hmm would this be outdated cuz scramble signatures are a thing now?
Also this is just not followed in general. Getting solved cubes happen pretty often.

**Comment by EdHollingdale** [comment]
As has been mentioned in another issue, runners are judges. In the runner system the duties of a judge is essentially split into two roles. The regulations could be updated to make it clearer that this can be done, but they should not specifically require runners, since they are not used in many regions.
