### ISSUE TITLE
Officially Recognizing 3x3 Multi-Blind Mean Of 3 Results

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#876]
In light of Graham's recent results (56 official mean of 3) I'm interested to see the communities thoughts on officially recognizing means.

### Pros

- In multi-blind accuracy is very important. We already award results based on accuracy on a single result, and recognizing means will award an even bigger difficulty of accuracy.

- Gives competitors an additional goal to strive for in their official results.

- Adds consistency since all other events have officially recognized means or averages.

- Competitions already have bo3 format so it would just add recognition for those results

### Cons

- Not many competitors have means

- The "all events Club" becomes an even rarer achievement (can also seen as a Pro).

- Competitors will do safety attempts and/or complete all 3 attempts in order to complete a mean, this will take more competition time and resources. *note using cutoffs can be used to help combat this issue*

- Not all competitions hold Mbld in the bo3 format, so many competitors will not have an opportunity to accomplish these. In addition organizers may feel pressured to hold bo3 format so that competitors can achieve a mean. 

- More attempts take more effort from competitors. 

### Other things to think about

- How many competitions currently hold Bo3 instead of bo2 or bo1?

- Will we do mean of points or mean of the points and means times?

- Should we first recognize it on the [missing averages page](https://www.worldcubeassociation.org/results/misc/missing_averages/)

- Will championships organizers feel like it has to be held, if so how would this affect championships schedules?

- Should we use this to determine tie-breakers?

**Comment by EdHollingdale** [comment]
I think the challenge with means is working out how they should treat times, especially as different attempts have different time limits. Additionally, I don't think we should let one incredible result make us go "that was great, the WCA should recognise this achievement officially".

I believe I saw a stat that only ~10% of competitions that hold Multi-blind use a mean-of-3 format. I know adding the mean as an officially recognised format will increase the number of competitions that do this (see FMC), but that poses serious logistical challenges (challenges that FMC doesn't have) and I'm not sure that is the direction we want to go in. Competitions are getting bigger, schedules are getting tighter, and any attempt to remove the number of events is met with stiff opposition. I'm not sure we should prioritise pushing organisers to devote several extra hours for a less popular event.

> How would this affect championships schedules?

Speaking from experience, it would add considerable challenges. Multi-blind is a huge drain on staffing resources as you need staff to set up, scramble, check, and judge. There could be additional considerable financial challenges depending on the nature of the venue. If you want to have 3 attempts over 3 days this means having a side room available for three days instead of two. If your discount on extra room bookings from booking the main hall is only good for two days this can add a ridiculous price tag (as was the case for WC2019). 

For WC2019 we made the decision to have 2 attempts since having the side room for the third day was not possible financially, and we wouldn't have the staff resources for two attempts on Day 2. That being said, it is still very possible to schedule 3 full attempts for many championships.

**Comment by xsrvmy** [comment]
Just from a results point of view, someone who averages over 10 mins on 3bld can technically get a mean (three 2/4s).
BTW I don't think local comps should use mbld cutoffs.

**Comment by Samuel-Baird** [comment]
> I believe I saw a stat that only ~10% of competitions that hold Multi-blind use a mean-of-3 format. I know adding the mean as an officially recognised format will increase the number of competitions that do this (see FMC), but that poses serious logistical challenges (challenges that FMC doesn't have) and I'm not sure that is the direction we want to go in. Competitions are getting bigger, schedules are getting tighter, and any attempt to remove the number of events is met with stiff opposition. I'm not sure we should prioritise pushing organisers to devote several extra hours for a less popular event.

I wouldn't be surprised if Mbld was treated a lot more like FMC and instead of being held in the Bo3 format at "normal comps" was only a Bo1 or Bo2 and Mo3 was held more commonly at PBQ competitions. 

> Speaking from experience, it would add considerable challenges. Multi-blind is a huge drain on staffing resources as you need staff to set up, scramble, check, and judge. There could be additional considerable financial challenges depending on the nature of the venue. If you want to have 3 attempts over 3 days this means having a side room available for three days instead of two. If your discount on extra room bookings from booking the main hall is only good for two days this can add a ridiculous price tag (as was the case for WC2019).

I would imagine holding 3 attempts would be seen as a lot less necessary than holding averages for other events. The other Bo3 events all take significantly less staffing resources and time than Mbld so I feel like organizers should be able to hold Bo2 without too many people getting upset. If the organizers only had a sideroom for 2 days then Bo2 would be reasonable as well.

If organizers did feel the need to hold Bo3 then they could use cutoffs and/or qualifying times. This would still mean that up to 3 hours of the competition time would be competitors competing but it would reduce scrambling time as well as staffing resources needed

Mbld is the least scramble dependent  event so there isn’t a need for 3 attempts at championships, it’s more for smaller specialized comps where the goal is to try and farm good results. 

> BTW I don't think local comps should use mbld cutoffs.

Why?

**Comment by xsrvmy** [comment]
> > BTW I don't think local comps should use mbld cutoffs.
>
> Why?

Most noticeably, if there is a bo1/bo3 cutoff, competitors trying to barely qualify for Nats will have to waste one attempt for a safety. Unlike 3bld, in mbld better competitors are actually less likely to DNF so this is a really big disadvantage for beginners. So at least I don't think bo1/bo3 is a good format for local comps.
Also it could be possible that the cutoff will be set so high that only the best competitor in the area can make it, so even forcing all mbld rounds to be bo3 would not really work.

**Comment by Samuel-Baird** [comment]
> > > BTW I don't think local comps should use mbld cutoffs.
> > 
> > 
> > Why?
> 
> Most noticeably, if there is a bo1/bo3 cutoff, competitors trying to barely qualify for Nats will have to waste one attempt for a safety. Unlike 3bld, in mbld better competitors are actually less likely to DNF so this is a really big disadvantage for beginners. So at least I don't think bo1/bo3 is a good format for local comps.
> Also it could be possible that the cutoff will be set so high that only the best competitor in the area can make it, so even forcing all mbld rounds to be bo3 would not really work.

Really just depends on how the organization team view it I guess :P

A cutoff that was set in mind with only allowing one competitor to get 3 attempts would most certainly not be allowed.

**Comment by xsrvmy** [comment]
@UnderwaterCuber I was under the impression that the WCA can only make recommendations regarding time limits, but not force the organization team to change it.
Also, just a technical point, I'd be in favor of requiring even point cutoffs, or allowing an attempted cubes lower limit instead.

**Comment by casiku** [comment]
I support mo3 in MBLD, because some organizers already do these, but they are not valid, since only single ranks are recognized.

**Comment by mintydev789** [comment]
I think most of the issues you mentioned are also present in FMC. I am strongly in favor of recognizing MBLD means.
