### ISSUE TITLE
Reconsider the thresholds for number of competitors to hold additional rounds

### ISSUE THREAD

**Issue by cubewhiz** [thewca/wca-regulations#879]
Currently, we use this:
< 8 competitors, 1 round only
< 16 competitors, max 2 rounds
< 100 competitors, max 3 rounds
100 or more, max 4 rounds

These were decided a long time ago when competitors were on average much smaller. Another thread made me wonder if we should reconsider these thresholds. I was originally thinking the following:
< 16 competitors, 1 round
< 64 competitors, 2 rounds
< 256 competitors, 3 rounds
256+ competitors, 4 rounds

There was a concern about smaller competitions needing to have multiple rounds to use different groups, so maybe it is better to stick with 8 competitors for a second round.

I think that 100 competitors for 4 rounds is far too low--competitions with 4 rounds of events should be reserved for huge competitions.

**Comment by Jambrose777** [comment]
> I'd be interested in seeing the stats of how many competitions/events had 8 - 15 competitors and held two rounds.

In 2019 there were 939 rounds with this criteria (I included non-final non-first rounds as well.
[Results (2).txt](https://github.com/thewca/wca-regulations/files/3867140/Results.2.txt)

**Comment by timreyn** [comment]
In 2019 there have been 62 events with 4 rounds: https://pastebin.com/nsCvnQAB

**Comment by xsrvmy** [comment]
I'm not sure if the concern with scramble groups is valid. There is no requirement for finals to use one single scramble set, and at a small comp scramble group by psych sheet would sort out the podium anyways.
However I am concerned with the lower 3 round criteria because small comps usually don't hit 64. I think the main increase should be for 4 rounds from 100 to 200.
Is there actually any way to figure out the effect of such a change without doing some kind of experiment?

**Comment by julesDesjardin** [comment]
> There was a concern about smaller competitions needing to have multiple rounds to use different groups, so maybe it is better to stick with 8 competitors for a second round.

I'm not sure I understand this correctly. You mean it's hard to ensure all potential podium/winners are in the same group without a 2nd round, because you need them to scramble in the 1st round?
You're gonna end up with "slow" scramblers for the 2nd round (here final round) anyway, so you can already do groups this way with only 1 round. Surely, this round will go slower than a 1st round where you can split good people to scramble, but the fast group won't be slower than the final if you have one.

**Comment by Ivan-Brigidano** [comment]
Related with #878

**Comment by xsrvmy** [comment]
@julesDesjardin Maybe the concern is guideline 1h++

**Comment by aneurinhunt** [comment]
Some areas still have small comps. New Zealand is one of these. So changing the round numbers requirement has an effect. Maybe it could be ajusted for 4. But the numbers for 2 and 3 seem fine to me.

**Comment by Ivan-Brigidano** [comment]
I'm usually more in favor of giving organizers more options to go. As an organizer, I try not to abuse of the number of rounds.
However, for this particular case, this change could be a good way to encourage organizers to add more events and more rounds of other events rather than classics ones.
