### ISSUE TITLE
"Cube puzzles"

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#89]
Make a pass to ensure that Regulations talk about puzzles accurately.
In particular, look at [3l](https://www.worldcubeassociation.org/regulations/#3l).

Also see Stefan's email to WRC, November 12, 2013.

**Comment by lgarron** [comment]
The [skewb diff](https://github.com/cubing/wca-documents/compare/skewb) will require us to give a name to the NxNxN puzzles. I'm in favor of `NxNxN` because it has the visual "shape" of the puzzle names (as opposed to `nxnxn`, which looks like 5 letters in a row).

**Comment by SAuroux** [comment]
According to Ron, the term "cube puzzles" has always been used to address all puzzles except Magics.

**Comment by lgarron** [comment]
Clock?

In any case, we should move away from any phrases/words where we mean non-obvious interpretations.

**Comment by SAuroux** [comment]
I fully agree. In case this wasn't clear, I just wanted to provide some background information of this terma origin.

The full quote:

"In the days we had Magic, the text 'cube puzzles' was supposed to
designate every puzzle but the Magics.
Now the 'cube puzzles' seem to designate only the 2x2-7x7 and Square1,
because they are cube shaped."
