### ISSUE TITLE
Reasons to remove or keep 7x7 as an event

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/wca-regulations#905]
Positive outcomes of removing 7x7
* 6x6 and 7x7 are almost exactly the same in terms of methods. They share almost identical podiums and rankings and if a competitor is fast at one then they are also fast at the other. Removing 7x7 would eliminate the redundancy.
 * Major championships have to hold it despite it being almost the same to 6x6, removing it would save the long amounts of time it takes competitors to solve it and the long amounts of time that it takes scramblers to scramble it. 

Negative outcomes of removing 7x7
* Removing the event would allow no more official 7x7 solves, and all 7x7 solves in future competitions would be unofficial and less likely to he held. This would disappoint those who enjoy participating in the event and those who enjoy watching it at competitions.

Neutral outcomes of removing 7x7
 * it's not as spectator friendly as some other events, its very long and the progress is slow. It's almost the same as watching 6x6 but it takes longer. 
 * 7x7 isn't a hugely popular event and since it is not very unique in speedsolving methods many competitors may not care if it is removed

(Please note that this does not have anything to do with the recent announcement of the removal of feet, I have been meaning to post this for a while)

**Comment by ccbaird** [comment]
> (Please note that this does not have anything to do with the recent announcement of the removal of feet, I have been meaning to post this for a while)

Your feeling your oats, and you won't convince me otherwise. I don't believe you'll be happy until the only WCA events left are Clock, 3x3, and MBLD.

The arguments for keeping 7x7 are weaker than the arguments for keeping Feet, but that's not saying much. The arguments for keeping both are very strong, the arguments for getting rid of either are very weak. It's really just that some people want to be at the top of Sum-of-Ranks or Kinchranks without putting in as much work on events they aren't already good at. Rather than putting in the work they would rather get rid of the events that other people are good at or enjoy.

**Comment by UnderwaterCuber** [comment]
> > (Please note that this does not have anything to do with the recent announcement of the removal of feet, I have been meaning to post this for a while)
> 
> Your feeling your oats, and you won't convince me otherwise. I don't believe you'll be happy until the only WCA events left are Clock, 3x3, and MBLD.

Please try and keep things civil :)

Also I did make a proposal to remove clock so I am not sure why you would list that as an event I would want kept. I have firsthand experienced the issues it can bring to competitions and the lack of depth of the event. 

> The arguments for keeping 7x7 are weaker than the arguments for keeping Feet, but that's not saying much. The arguments for keeping both are very strong, the arguments for getting rid of either are very weak. 

Please don't state opinions as facts

> It's really just that some people want to be at the top of Sum-of-Ranks or Kinchranks without putting in as much work on events they aren't already good at. Rather than putting in the work they would rather get rid of the events that other people are good at or enjoy.

Nice conspiracy theory but contrary to belief, a lot of us on here are trying to improve the WCA. 

Please keep in mind that ideas on here are nothing more than that, not all of them are perfect and not all of them are going to happen. We bring them up to discuss them and analyze them, we try to improve upon them if we see potential and if we find out that they aren't worth it then we drop the idea. Instead of resorting to petty insults and stating opinion as fact to get what you want, please try to discuss ideas civilly on here in the future :)

**Comment by lgarron** [comment]
We should not remove more events until we have a better idea of how we want to handle our list of events and have a good process to decide how to add/remove events.

Folks are welcome to keep commenting on this issue, but I'm closing it for now because it isn't actionable until we've done that.

**Comment by jamesquinn1** [comment]
> We should not remove more events until we have a better idea of how we want to handle our list of events and have a good process to decide how to add/remove events.

This is very true, but also this reasoning should have been applied to feet. Why wasn't it?
