### ISSUE TITLE
Add a process for adding and removing events.

### ISSUE THREAD

**Issue by mihlefeld** [thewca/wca-regulations#913]
I don't have a concrete draft on how this process would look.
But basically define the steps that need to be taken in order to remove an event (or maybe add an event) with delegate votes wrc votes or even community votes.

**Comment by dancing-jules** [comment]
Additionally:
Lucas Garron said repeatedly that they want to introduce a proper procedure. 

Removing feet just before introducing a proper procedure, makes it look a lot like an arbitrary decision that was pushed through, because with a proper procedure it would not have worked.

**Comment by ccbaird** [comment]
I was just thinking about this, but the process should be the same for all major changes, not just adding or removing events.

A community wide survey should be conducted annually. Votes would be unequally distributed as follows:
- 1 vote for competing at a competition in the last year
- 3 votes for organizing a competition in the last year
- 6 votes for delegating a competition in the last year
- 10 votes for working with the WCA in an official capacity outside of competitions (serving on the board, rules committee, etc.)

For example: Competing at two competitions and organizing one of those two would be 4 votes. A WCA board member or Rules committee member who organized and and served as delegate for 2 competitions and competed at 3 others would have 25 votes. 

This survey would have the following purposes:
- Elect WCA Board members 
- Gauge community support for major (I.e., non-clarification) rule changes

Additionally, I propose that the following requirements be implemented for eligibility to sit on the WCA board:
- At least 21 years old
- Pass a criminal background check 
- Maintain community involvement sufficient for 25 votes in the annual community survey.

**Comment by xsrvmy** [comment]
Setting a number for WCA board member might not be a appropriate. Will a board member be too busyto organize a comp?

**Comment by ccbaird** [comment]
@xsrvmy my thought there is to require a high level of involvement, but credit for other service. The exact figures are definitely open for debate, but I think the general principle is sound.

**Comment by Ivan-Brigidano** [comment]
I fully agree that my Committee needs to make a clear guide/policy on how to add new events or removing existing ones. For the moment we have this [draft](https://github.com/thewca/wca-regulations/wiki/Criteria-for-adding-or-removing-events).

> Additionally, I propose that the following requirements be implemented for eligibility to sit on the WCA board:
> - At least 21 years old
> - Pass a criminal background check
> - Maintain community involvement sufficient for 25 votes in the annual community survey.

@ccbaird this is more likely a Motion change. You may want to open an issue about it on the [Documents Repository](https://github.com/thewca/wca-documents/issues).

> Setting a number for WCA board member might not be a appropriate. Will a board member be too busyto organize a comp?

@xsrvmy arguably busy but some Board members are active organizers, such as Bob Burton.

**Comment by cubewhiz** [comment]
Before you waste too much time on your idea, I will let you know that I do not support it at all. I think the processes in place for electing Board members are sufficient and I insist that decisions will remain as the results of Board votes--community input may be taken into consideration, but will not have any binding impact on any decision. Changing the current process for electing Board members or how votes are decided would require a change to the Motions. Any change to the Motions requires unanimous support from the Board, so there is no chance that this will be considered.

**Comment by casiku** [comment]
> Changing the current process for electing Board members or how votes are decided would require a change to the Motions. Any change to the Motions requires unanimous support from the Board, so there is no chance that this will be considered.

That's ... convenient

**Comment by lgarron** [comment]
Note that we currently have drafts at https://github.com/thewca/wca-regulations/wiki/Criteria-for-adding-or-removing-events

While it's important to give people a stake, people are already complaining that there is too much bureaucracy. Unless we fundamentally change how we approach the list of official events, a process with more people and more votes is likely to lead either to politics or stagnation. These outcomes might seem acceptable to some, but it is not the best way to serve the mission of the WCA.

As I've mentioned in other places, we should be aiming to bridge the gap between official and unofficial events so that these decisions don't have such an impact on the community.

**Comment by ccbaird** [comment]
@lgarron is there any way to comment directly on that draft? I feel like the criteria offered for adding events is sufficient and well thought out, but the criteria for removing an event are woefully underdeveloped, and a healthy discussion could be very helpful.

**Comment by Ivan-Brigidano** [comment]
@ccbaird no, anyone can't comment on the wiki. But please, write your concerns here.

**Comment by ccbaird** [comment]
> @ccbaird no, anyone can't comment on the wiki. But please, write your concerns here.

Ok, I’ll go point by point

>Not necessarily complete list of criteria:

>Drop of the number of competitions that held it in more than 5% in 5 years

I’m not even sure what this means, I think there’s a typo in there somewhere. It looks like it’s referring to a drop in popularity. That is a reasonable thing to consider, but should be written clearly. 

>Being held by less than 30% of competitions

That’s probably a reasonable threshold. 

>Less than 4.5% of competitors participate in this event

Again, probably reasonable, but I’m curious why 4.5% was chosen, rather than a round number like 5% or 2%? And on what time frame? Does “participate” mean having an official attempt in the last 5 years? An official average in the last year? That should be spelled out. 

>Difficult to hold at competitions

This should be explicitly determined by a poll of delegates and organizers, that includes questions about scrambling, judging, equipment, and other concerns. 

>Having the approval of it removal of at least 50% of Delegates (from an internal poll)

This is low. Using Feet as an example, the poll of delegates was 56-58 in favor of removal, if just two delegates changed their minds then more would be in favor of keeping than removing. Because of what organizers, delegates, competitors, and puzzle manufacturers and retailers have invested in events the default should always be to avoid changing the event list unless there is a clear reason to change. Both adding and removing events should be approved by a vote of 2/3 of delegates, 60% would be a minimum in my opinion. 

There should also be explicit consideration of whether an event adds a unique challenge to the rest of the lineup (as mentioned in criteria for adding events).

There should also be a community poll of active competitors. The results of the poll need not be binding, but a clear majority with strong feelings one way or the other should be STRONGLY considered. Perhaps formatting the poll with a range from 1-10 rather than a simple yes/no would give a better idea of true sentiment.

**Comment by Samuel-Baird** [comment]
@ccbaird to clarify some things and discuss points

> Drop in the number of competitions that held it in more than 5% in 5 years.
This is supposed to mean that in a 5-year window if the percent of competitions drop by 5% or more. For example, we can see that the percent of feet competitions dropped by 11% from 2013 to 2018.

                                2013	2014	2015	2016	2017	2018	2019
% of competitions	32%	        28%	         26%	25%	        23%	         21%	23%
% of competitors	4.3%	3.4%	3.1%	2.7%	2.8%	2.9%	3.1%

maybe to make it more clear it could be changed to "Drop in the percent competitions that held the event by 5% or more, in 5 years" @lgarron @Ivan-Brigidano 

> Less than 4.5% of competitors participate in this event
This is for all time I believe, # of competitors who have competed in X / # of all competitors. It could be nice to clarify that and round it up to 5% to make it cleaner.

> Difficult to hold at competitions
If a poll was sent out to organizers and everyone knew that sending such a poll out would mean that the event removal process was going on then there would be a rush of people holding more competitions with the event and convincing more people to compete in order to inflate the numbers enough for the event to be kept. The WRC and WQAC already gather info about different aspects of competitions and events from delegates so just asking delegates is fair I think.

> Having the approval of its removal of at least 50% of Delegates (from an internal poll)
I don't think that it is low, 50% is pretty good. Many governments use a majority vote to decide the outcomes of super important things like to vote for political leaders or to pass new laws or policies. 

> There should also be explicit consideration of whether an event adds a unique challenge to the rest of the lineup (as mentioned in criteria for adding events).
I think the idea behind this is nice but I don't think it has its place in this. To me, it looks like these are supposed to be as objective as possible and considering uniqueness is just another thing to debate. I also feel like it's pretty unnecessary, if event B is hated, it causes all sorts of issues, and its well below the numbers necessary to keep it then we should hold onto it because it has something unique.

> There should also be a community poll of active competitors. The results of the poll need not be binding, but a clear majority with strong feelings one way or the other should be STRONGLY considered. Perhaps formatting the poll with a range from 1-10 rather than a simple yes/no would give a better idea of true sentiment.
I think the idea behind this is also nice is unnecessary and could cause issues. As I mentioned above its supposed to be as objective of a decision as possible, the fewer opinions we have to ask the better. 

With a vote people would think they have some sort of influence, if they "win" the vote and the decision made doesn't reflect that then it becomes less of a matter of whether the event hits all the criteria or not and it becomes a matter of "the WCA doesn't care about what we think" 

I want to also address why I find a delegate vote necessary while I find a community vote unnecessary. Delegates see far more than any competitor in the WCA, they see are the budgeting cost of buying new equipment for an event, they see the issues with it slowing down the competitions they delegate, they see all of the extras they have to give, all the calls they have to make, they see competitors engagement or lack of interest in an event, they see all the incidents being reported by other delegates. A delegate is able to take all of those experiences and put them together to make a decision that they believe is best for the community. A competitor often just sees themselves competing and how fun it is for them to compete. While this may not be true in all cases, generally delegates vote in the interest of the community while competitors vote in self-interest.

**Comment by ccbaird** [comment]
>This is for all time I believe, # of competitors who have competed in X / # of all competitors. It could be nice to clarify that and round it up to 5% to make it cleaner.

If we're looking at popularity over time, as it appears the part about how many competitions hold the event is looking at, this should look at current or recent statistics.

>If a poll was sent out to organizers and everyone knew that sending such a poll out would mean that the event removal process was going on then there would be a rush of people holding more competitions with the event and convincing more people to compete in order to inflate the numbers enough for the event to be kept. The WRC and WQAC already gather info about different aspects of competitions and events from delegates so just asking delegates is fair I think.

If there are enough people willing to put the work in to organize more competitions with an event then it's perfectly reasonable to consider that in deciding whether to keep it. I don't care about Clock, if the WCA announced that they were removing it I would still try to compete, but I don't care enough to organize a competition around it. I know that you have stated in the past that you enjoy solving Clock, if you are willing to put the work in to organize a competition that offers Clock it is perfectly reasonable that your opinion would count more than mine on the issue of whether Clock should be removed.

>I don't think that it is low, 50% is pretty good. Many governments use a majority vote to decide the outcomes of super important things like to vote for political leaders or to pass new laws or policies.

50% is break-even. It's a reasonable threshold for minor changes, like whether to allow stickerless cubes, for example. For major changes the standard should be higher. If allowing stickerless cubes is passing a law, adding or removing an event is a constitutional amendment.

>I think the idea behind this is nice but I don't think it has its place in this. To me, it looks like these are supposed to be as objective as possible and considering uniqueness is just another thing to debate. I also feel like it's pretty unnecessary, if event B is hated, it causes all sorts of issues, and its well below the numbers necessary to keep it then we should hold onto it because it has something unique.

This is just grasping at straws. Uniqueness does not have to be a deciding factor, but it is in the criteria for considering adding an event (I believe appropriately so) it should also be considered in removing an event. There is only one dodecahedral puzzle in the current lineup of events, if Megaminx were to be considered for removal that would be a reasonable part of the argument for not removing it.

>the fewer opinions we have to ask the better.

This is ridiculous, quite frankly. It is reasonable to have somebody in charge to make hard decisions, but the step from benevolent dictator to dictator is short.

>With a vote people would think they have some sort of influence, if they "win" the vote and the decision made doesn't reflect that then it becomes less of a matter of whether the event hits all the criteria or not and it becomes a matter of "the WCA doesn't care about what we think"

Call it a poll instead of a vote. If 50% of people want an event and the Board decides there are stronger arguments against it, then 50% of people will be disappointed, but if there is good data showing that 50% of people disagree with them, then that sucks but life goes on. The only problem would be if 70, 80, or 90% of people wanted to keep (or add) an event and the Board decided to ignore that without a very good explanation. Right now with regard to Feet as far as I can tell there are 4 WCA Board members and about 10 people on the internet who are happy with Feet being removed, and everybody else either doesn't care or wants it to stay. The WCA has the power to collect the data to prove me wrong, and has chosen to not do so.

>A delegate is able to take all of those experiences and put them together to make a decision that they believe is best for the community. A competitor often just sees themselves competing and how fun it is for them to compete. While this may not be true in all cases, generally delegates vote in the interest of the community while competitors vote in self-interest.

I don't share your unbridled faith in the inherent goodness of Delegates, although all of my experiences with Delegates have been positive. That said, the rest of your points are right, about how they see other aspects than the competitors or even organizers see. For that reason I was suggesting that a non-binding competitor poll be strongly considered in making major decisions, but that a delegate vote be binding. Delegates should undeniably have a stronger voice in the governance of the WCA than competitors.

**Comment by xsrvmy** [comment]
IMO there is a pretty big flaw in many of the criterias described: statistical comparisons need to be made relative to other events.

Also another stats suggestion: somehow measure improvement, for example, the percent increase/decrease of competitor times over one year.

**Comment by danielA757** [comment]
I suggest (re)moving to the SEE association, just like Feet has been moved to SEE. The events can be monitored on SEE, and the WRC can evaluate if any SEE event should be added to WCA based on popularity/incident reports, or if WCA events should be moved to SEE.
https://speedcubingextraevents.org/Events

**Comment by cubewhiz** [comment]
> I suggest (re)moving to the SEE association, just like Feet has been moved to SEE. The events can be monitored on SEE, and the WRC can evaluate if any SEE event should be added to WCA based on popularity/incident reports, or if WCA events should be moved to SEE.
> https://speedcubingextraevents.org/Events

The WCA has no affiliation with SEE. To proceed with a plan like this, a proper collaboration would need to be coordinated. Preferably, we would monitor and track the top candidate events internally.

**Comment by ccbaird** [comment]
> The WCA has no affiliation with SEE. To proceed with a plan like this, a proper collaboration would need to be coordinated. Preferably, we would monitor and track the top candidate events internally.

The SEE explicitly discusses reciprocity with the WCA in their regulations, what is preventing the WCA from doing the same?
