### ISSUE TITLE
Delay the removal of feet until the Community Survey is released

### ISSUE THREAD

**Issue by jamesquinn1** [thewca/wca-regulations#914]
Pretty self-explanatory, many many people are upset that the community was not given a proper voice in this decision, so delaying the removal of an entire event from the WCA until the survey is released makes sense. Should be doable with announcing a tentative removal for July 1st, giving the WRC, WAC, and WCA time to analyze the results of the survey.

Delaying the rest of the regulations until July 1 could also be a possibility, last year they were released May 1 and that was not a big issue. I believe that we should always prioritize putting the best set of regulations forward, instead of a quick and not as good set.

**Comment by dancing-jules** [comment]
Yes, please. The community was neither asked nor heard and the reasons for removal that are being cited make no sense.

**Comment by ccbaird** [comment]
Seconded and thirded. The WCA screwed up, it would do wonders for their credibility to admit that and seek feedback rather than just issuing a generic promise to do better next time.

**Comment by Samuel-Baird** [comment]
I feel like under current circumstances it wouldn’t really help with things, the decision has been made and I don’t think minds are going to be changed unless those vote numbers are extremely high. I see a ton of people online saying that the WRC didn’t listen just because the WRC didn’t do what they want. The WRC has to give a weighting to how much the survey would mean and if the community felt it was wrong then it just I would imagine almost the exact same thing would happen again, people would just be upset, trust the WCA/WRC less and would bash them.

I think a better course of action would be to get things going so that we can add feet back as a second tier event in 2021, maybe  a survey asking if people would support adding feet as an event could be held? 

If people aren’t in support of trying to add feet back as a second tier event though then I would be cool with a community survey about removing feet.

**Comment by ccbaird** [comment]
@UnderwaterCuber people are saying the WCA didn’t listen because the WCA didn’t listen, not because they made a decision people disagree with. Until I see the results of a community wide survey saying otherwise I believe the only reason that the idea of a survey was scrapped was that the people who would have organized the survey had an agenda that they believed would be sidetracked by a survey showing that their position was unpopular.

**Comment by Samuel-Baird** [comment]
> @UnderwaterCuber people are saying the WCA didn’t listen because the WCA didn’t listen, not because they made a decision people disagree with. Until I see the results of a community wide survey saying otherwise I believe the only reason that the idea of a survey was scrapped was that the people who would have organized the survey had an agenda that they believed would be sidetracked by a survey showing that their position was unpopular.

How do you know that? Have you personally talked with the people involved with removing feet? If not then it’s nothing more than a conspiracy theory. 

Also why would the WRC bring up a survey if they had intentions to never hold it? That would only hurt them, just basic reason leads me to the conclusion that they had some sort of valid reason to not hold it. 

If you really do feel like the WRC aren’t listening and they have some sort of agenda to remove feet because they hate it then report it, maybe start a petition or something. Almost anything is better than unfair criticisms revolving around speculative theories.

**Comment by ccbaird** [comment]
I don’t believe the WRC floated the idea of a survey with no intention of holding it, I believe they considered holding a survey, and leaked potential questions regarding keeping Feet. A few YouTubers jumped on that with a campaign to “save feet.” When the WRC saw that I believe they realized that the community would not stand behind their decision to remove feet, and chose to go ahead anyway. If the survey is held after all, and a plurality support the removal of Feet, I will stand corrected.

**Comment by julesDesjardin** [comment]
Sorry about the closure, these buttons are sensitive :p

Saying that we purposefully didn't hold the survey just because we wanted to remove feet is really a conspiracy theory. Do you really think that we purposefully do changes that hurt the community more than it serves it? (if we do them, it's by accident, and obviously not because we just like to hurt people)

As always with conspiracies, the truth is simple: we just didn't have time. We have limited resources (we have a life on the side, although some people seem to think this is outrageous that we're not robots dedicated to their own fun) and being on the WRC is already very time-consuming. Therefore, we simply didn't have time to finish the survey in time for a release on Jan 1st 2020. Sure, we could have postponed the date, but I'm personally (don't take that as a WRC-wide opinion) not sure that we would have ended with a survey even with more time. Other things would still have caught up, and anytime the deadline approaches, we would have postponed again.
Lesson learned: we should have let WAC handle this, since that's their role, not ours. 

I'll conclude with what I already wrote on Facebook : just having a majority vote isn't enough to decide such an issue. Some people want to remove it because they don't believe the "I have fun, I put lots of work in it". Some people want to keep it because they don't believe the organizational arguments, because they never organized a comp. Just taking the result of a survey as a binding vote on removal (or not) of Feet does not seem a good idea in my opinion.

**Comment by ccbaird** [comment]
Ok, so it wasn’t sinister and it wasn’t a conspiracy. Hold the survey anyway. Let’s find out what the results are. 

As far as organization: I’ve organized two competitions, one with Feet and one without. I grant that I had some great help from Josh Feran and his family, as well as other volunteers, but at the end of the day IT’S JUST NOT THAT HARD! I want to compete in 3x3 with Feet, and I am willing to put in the work to make that possible. Stop trying to save me from myself.

**Comment by Samuel-Baird** [comment]
> Ok, so it wasn’t sinister and it wasn’t a conspiracy. Hold the survey anyway. Let’s find out what the results are.
> 
> As far as organization: I’ve organized two competitions, one with Feet and one without. I grant that I had some great help from Josh Feran and his family, as well as other volunteers, but at the end of the day IT’S JUST NOT THAT HARD! I want to compete in 3x3 with Feet, and I am willing to put in the work to make that possible. Stop trying to save me from myself.

It’s most definitely a conspiracy.

That’s just one data point out of many. And difficulty of holding it isn’t the sole reason that it’s being removed.

**Comment by ccbaird** [comment]
>It’s most definitely a conspiracy

I’m not saying that the allegation isn’t a conspiracy theory, I’m saying that I’m granting that it wasn’t a conspiracy. On the condition that the promised survey is held after all.

**Comment by casiku** [comment]
If the WCA can't even make a simple yes/no survey, they will need time to mature and become more professional. Removing an event is the absolute priority in WCA, so saying "we have other things to do" is a bad excuse. Removing the event entirely is a quick fix, and will not make the WCA anymore professional, because you will still have "something else to do, I'm busy" (hmm let me guess, netflix and computer games?).
WCA will never become professional, and my opinion is that they simply need money to pay officials. If there is no money, nothing will get done.

**Comment by Samuel-Baird** [comment]
> If the WCA can't even make a simple yes/no survey, they will need time to mature and become more professional. Removing an event is the absolute priority in WCA, so saying "we have other things to do" is a bad excuse. Removing the event entirely is a quick fix, and will not make the WCA anymore professional, because you will still have "something else to do, I'm busy" (hmm let me guess, netflix and computer games?).
> WCA will never become professional, and my opinion is that they simply need money to pay officials. If there is no money, nothing will get done.

Yeah it would be nice if they could devote more time to it without giving up even more of their personal lives. I think paying wca staff could be great. But bashing wrc members because they aren’t giving enough time is ridiculous, they spend hours working every week for free.

**Comment by julesDesjardin** [comment]
> "something else to do, I'm busy" (hmm let me guess, netflix and computer games?).
Oh my god, how dare we have free time? 

But to be honest I was also thinking about working. You know, the things your parents do 40 hours/week to make a living (I assume that with this maturity you're not an adult). 

> WCA will never become professional, and my opinion is that they simply need money to pay officials. If there is no money, nothing will get done. 

This is however quite true. If we earned money, we could afford to take reduced-time jobs (not everyone of course, but some staff would probably do it), and have more time to work on WCA.

**Comment by casiku** [comment]
> > "something else to do, I'm busy" (hmm let me guess, netflix and computer games?).
> > Oh my god, how dare we have free time?
> 
> But to be honest I was also thinking about working. You know, the things your parents do 40 hours/week to make a living (I assume that with this maturity you're not an adult).
> 
> > WCA will never become professional, and my opinion is that they simply need money to pay officials. If there is no money, nothing will get done.
> 
> This is however quite true. If we earned money, we could afford to take reduced-time jobs (not everyone of course, but some staff would probably do it), and have more time to work on WCA.

Dear Jules,
I am an adult, and I would appreciate you keep a level of respect towards other people, since this is a serious forum. I have seen other threads where you insult the original poster, and then lock the thread so you can get the last word. Talk about "mature". I look forward to the development of the WCA forum, so we can have serious discussions.

**Comment by lgarron** [comment]
We discussed this within the Board, and after weighing the options we decided it was not appropriate at this time.
