### ISSUE TITLE
Adding a portion of the WCA that takes results for non-WCA events

### ISSUE THREAD

**Issue by LLayug** [thewca/wca-regulations#944]
I believe that non-WCA events have been increasing in popularity, and I do think that there should be a way for non-WCA event times to be compiled at the very least. An idea that I came up with is for the non-WCA page to be a subsection of the current site, similar in a way to WCA Live. Records and results would be in a portion, but would not appear under a person's profile on the site. In terms of adding events, I suggest for any delegate to be able to propose any event, and for a sub-committee to approve/deny and to create a scrambling notation. To make it a lot easier to handle, I would suggest partnering up with the current sites that have statistics for non-WCA events already such as funcubing.org. As much as this idea is very raw in terms of details and execution, I definitely think it would be a good way to acknowledge results and lessen the gap between official and non-official events. (and it could be a way to execute #857 and be a part of #913)

**Comment by danielA757** [comment]
WRC has agreed to transfer Feet results from WCA to the SEE association. They are already on SEE:

https://speedcubingextraevents.org/Event/333ft

As for scrambling notation, adding and removing non-WCA events and delegation, it is handled by the SEE association.
SEE events are in all regards official events, as there are rankings, regulations, quality control and delegation just like the WCA.

**Comment by jamesquinn1** [comment]
I believe the point of this was to propose keeping unofficial results on the WCA somewhere, as *very* few people have heard of the SEE.

**Comment by danielA757** [comment]
> I believe the point of this was to propose keeping unofficial results on the WCA somewhere, as _very_ few people have heard of the SEE.

This can be solved by referencing SEE on the WCA website.
The event logos can be imported from https://speedcubingextraevents.org/Icons
Thus, they can appear more clearly on the time schedule.
The WCA can make a special tab under "information" explaining the collaboration with SEE with a link to the SEE website: https://speedcubingextraevents.org

**Comment by danielA757** [comment]
Just like CubingChina imports WCA results, I'm sure WCA can import SEE results to make them more accessible.

**Comment by ccbaird** [comment]
1. This is on the SEE site (which I hadn’t known about previously), why isn’t it on the front page of the WCA site?
2. Can SEE registration be be integrated into WCA registration, to facilitate signing up for other events?
3. Will WCA assist SEE in verifying records for Guinness or any other record keeping organizations, and media relations?
4. The WCA has a well-established network of delegates, will SEE recognize all WCA delegates automatically? Edit: or at least by default, if not automatically.

**Comment by LLayug** [comment]
I'm actually pleasantly surprised that the WCA has taken some action on this. At this point, I think what this SEE just needs to be more popularized and a bit more integrated into the WCA for the organizers' convenience. (which I think @ccbaird emphasized through his questions)

**Comment by HippolyteM** [comment]
Why are you even discussing adding non-wca content on the wca website?
Don't you think the software team has enough work to do?
I hope you guys do realise that since a few months, some of you are just discussing here as if it was a chat. And without even having any feedback from the wca staff, you just keep discussing changes or rules that don't have any chance to happen (and for a reason).

**Comment by ccbaird** [comment]
> Why are you even discussing adding non-wca content on the wca website?

Because these other events, particularly Feet, are closely related to the WCA and its mission. 

> Don't you think the software team has enough work to do?
> I hope you guys do realise that since a few months, some of you are just discussing here as if it was a chat. And without even having any feedback from the wca staff, you just keep discussing changes or rules that don't have any chance to happen (and for a reason).

People care about what the WCA does, policy proposals are not usually created fully formed, and debate is valuable. This is the one place that people can discuss potential changes that they know the WCA is aware of what is said.

**Comment by danielA757** [comment]
> 1. This is on the SEE site (which I hadn’t known about previously), why isn’t it on the front page of the WCA site?
> 2. Can SEE registration be be integrated into WCA registration, to facilitate signing up for other events?
> 3. Will WCA assist SEE in verifying records for Guinness or any other record keeping organizations, and media relations?
> 4. The WCA has a well-established network of delegates, will SEE recognize all WCA delegates automatically? Edit: or at least by default, if not automatically.

1. and 2: It sounds like the WST have a lot on their plates, but hopefully such features will come in a couple years. 
As of now, registration is through the SEE website or "on the spot". SEE automatically imports competitors registered at the WCA competition, so technically you only need to register at WCA, but it's convenient for the organizers to have both, as scorecards will then be filled automatically.

3. Records are verified by the trusted SEE Delegates and the SEE Comittée, parallel to WCA. SEE competitions can only be held at WCA competitions, so this facilitates quality control (i.e. WCA Delegates, WCA organizers and WCA Team Members are always welcome to participate in SEE event organization).

4. WCA Delegates are not automatically SEE Delegates, since SEE has different regulations and require technical introduction to the SEE website.
However, WCA Delegates are allowed to delegate certain SEE events without an SEE Delegate, as described in Article 2.2 of the [SEE Main Regulations](https://speedcubingextraevents.org/MainRegulations). I.e. you don't need an SEE Delegate to organize Kilominx, Mirror Blocks and other simple-regulation events.

Since SEE is still new, it's also possible to add past results of SEE events, if the organizer and WCA Delegate were unaware of the existence of SEE at the time the competition was held, as desribed in Article 2.3 of the [SEE Main Regulations](https://speedcubingextraevents.org/MainRegulations).

I bet WCA Delegates will more likely be accepted as SEE Delegates than common competitors, although many WCA Delegates will not have the time (you need to write an SEE report after each competition etc, and WCA Delegates are already busy).

**Comment by Claster** [comment]
>WRC has agreed to transfer Feet results from WCA to the SEE association.

I'm not sure when such agreement happened. Would you remind me please? This is the first time I hear about this association.

**Comment by ccbaird** [comment]
> > WRC has agreed to transfer Feet results from WCA to the SEE association.
> 
> I'm not sure when such agreement happened. Would you remind me please? This is the first time I hear about this association.

SEE has an announcement [here](https://speedcubingextraevents.org/News), although they don’t reference the WRC.

**Comment by LLayug** [comment]
> Why are you even discussing adding non-wca content on the wca website?

I believe that adding this portion/subsection/separate website would be under the mission statement of the WCA and the goals of the WCA. Additionally, it would be a good transition for a non-WCA event to become a WCA event. (As aforementioned in the original thread) And from what I interpret, I believe the WRC is interested in doing this as proven by the action they are currently taking and their previous thread, #857

> And without even having any feedback from the wca staff, you just keep discussing changes or rules that don't have any chance to happen (and for a reason).

I believe the main reason that the WCA staff have not been replying is due to the fact that they have already been taking action on this, and it just has not been made public yet (view thread replies from @danielA757 ). The last portion of this statement to me does not make sense. I personally see it as a way of discouraging people to bring up issues and suggestions. As much as I believe that people should think through every post they make and think twice about every single post and comment, I do not think we should be restricting anyone to suggest or comment something they believe makes sense.

> rules that don't have any chance to happen (and for a reason).

If you do not think that rules like this do not have a chance of happening, please read the replies above. The WCA is already taking action on this (granted, not because of this thread). This only proves that this statement is wrong.


I will close the thread since the WRC and SEE have already been taking action on this. Kudos to both for their continued efforts to try and make our community a better one.

**Comment by Claster** [comment]
@LLayug, your reply sounds like there was already an active collaboration and an agreement between WRC and SEE. To my best knowledge this is not the case.
Which actions do you mean the WCA is already taking that are demonstrated in #857? That thread was just a proposal that was not implemented, at least for now.

**Comment by LLayug** [comment]
Daniel has mentioned earlier that there already has been a discussion on the transferring of feet results, and that the SEE already handles the suggestion I put up. There has already been some form of collaboration and I do think that they will collaborate more over the next few months. 



> The WCA can make a special tab under "information" explaining the collaboration with SEE with a link to the SEE website: https://speedcubingextraevents.org

**Comment by Ivan-Brigidano** [comment]
> Daniel has mentioned earlier that there already has been a discussion on the transferring of feet results, and that the SEE already handles the suggestion I put up. There has already been some form of collaboration and I do think that they will collaborate more over the next few months.
> 
> > The WCA can make a special tab under "information" explaining the collaboration with SEE with a link to the SEE website: https://speedcubingextraevents.org

No, there has been no official agreement between SEE and WRC. SEE has not contacted the WRC yet.

**Comment by lgarron** [comment]
> No, there has been no official agreement between SEE and WRC. SEE has not contacted the WRC yet.

Just to clarify some things here: I *have* been talking to someone working with (what is now called) SEE about potentially coordinating with the WCA, as they are the taking charge in wider community tracking of unofficial results at official comps. However, this hasn't reached any official stage.
