### ISSUE TITLE
Clarify that a cutoff is a requirement, not a result

### ISSUE THREAD

**Issue by Goosly** [thewca/wca-regulations#957]
As discussed in the report thread of Guildford Open 2020

**Comment by UnderwaterCuber** [comment]
I think changing the wording to what you proposed could be nice but it ultimately does not fix the issue in the report thread. If that issue is to be fixed then the line in question would need to changed from A to B.

A. Current line in 9g
If the competitor meets the cutoff requirement in at least one of their cutoff phase attempts, they are eligible for the remaining attempts.

B. Improved line in 9g
If the competitor meets or achieves a result better than the cutoff requirement in at least one of their cutoff phase attempts, they are eligible for the remaining attempts.
