### ISSUE TITLE
Make A7g more flexible

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/wca-regulations#960]
Related to #743 and #742.

Sometimes a competitor commits some procedure mistakes at their second or third competition. A part of these mistakes is arguably due to competitor inexperience.

A great example is if the competitor only competes in speedsolving events at his first competition but compete at blindfolded events at his second competition. His inexperience at competitions may cause some procedural mistakes that _might_ be an A7g worthy.

**Comment by EdHollingdale** [comment]
I would describe such a competitor as a "new competitor" per the regulation and potentially grant an extra. They are new to competing in blindfolded solving/clock etc. I feel a guideline to describe this would be useful but I feel like this is how many Delegates already feel about A7g.

**Comment by Ivan-Brigidano** [comment]
> I would describe such a competitor as a "new competitor" per the regulation and potentially grant an extra. They are new to competing in blindfolded solving/clock etc. I feel a guideline to describe this would be useful but I feel like this is how many Delegates already feel about A7g.

I agree with you. I think a Guideline is necessary to make this "Delegate's+WRC unwritten rule" a real Guideline.

**Comment by Samuel-Baird** [comment]
I think removing the word "new" in A7g could help since it's a bit ambiguous. If it was removed then I think A7g would be clear enough that we wouldn't need to add any more guidelines about it.

**Comment by xsrvmy** [comment]
There is currently ambiguity in the purpose of A7g.
Some have tried to say that A7g is intended to cover cases where the competitor does not know the regs existed at all. I don't think this is a valid interpretation since it would be a weird way of understanding lack of experience.
If we wanted to be specific, we could make A7g only apply to cases where a competitor breaks a regulation that was relevant to him/her at a previous comp.
eg.
Only done blind before, takes cover off before speedsolve -> extra
Only down speedsolve before, fails the timer start on bld solve -> DNF
