### ISSUE TITLE
Dealing with competitors arriving late to rounds with cumulative time limits

### ISSUE THREAD

**Issue by KitClement** [thewca/wca-regulations#964]
Delegates have had issues with coming up with fair agreements to allow competitors to compete when showing up late to rounds with cumulative time limits, most notably for 4/5BLD. Handshake agreements have been done to exclude them for a subset of the attempts, but this is often subjective and based off the competitor's speed, which is variable. I would like to propose the following:

If a competitor submits their cube late to a round with a cumulative time limit, the delegate may allow them to compete with this limit reduced by any number of minutes, but no more than the amount of time they were late. 

I feel like there will be objections to this idea but I wanted to throw it out there to discuss what fair options can be considered for these circumstances.

**Comment by xsrvmy** [comment]
I feel like there needs to be something to prevent this being applied when there there is a lot of scheduling slack, or when the competitor is only late for a few minutes.

Another question is whether the limit would be lifted if the late compeititor is no longer the person that will finish last.

**Comment by Goosly** [comment]
If you really want to allow competitors to compete even though they arrive late, you can already use [2u1](https://www.worldcubeassociation.org/regulations/#2u1)
Schedule the individual attempts one after another, and if someone is late for the first, they get DNS and can still do the other attempts.

Reducing the limit by _"any number of minutes"_ sounds very arbitrary.

**Comment by xsrvmy** [comment]
2u1 does not work with a cumulative time limit.

**Comment by Goosly** [comment]
Sure it does
The cumulative time limit stays the same after DNS'ing the first attempt for the competitor, but if you would want a time limit per attempt then you shouldn't be using cumulative limits anyway.

**Comment by KitClement** [comment]
Why would you schedule attempts individually if setting a cumulative time
limit though? Would that not imply a time limit per attempt? Seems like you
are suggesting that the schedule should be intentionally misleading to take
advantage of 2u1, which also doesn't really solve the problem here as you
mention, as they would still have the full cumulative limit.

I agree that "any minutes" sounds weird even with the restrictions given.
Maybe the better implementation of my idea would be to just allow the
delegate to lower the cumulative time limit for late competitors, and have
a guideline that suggests that the reduction in time limit should be no
more than the number of minutes the computer is late.

**Comment by Goosly** [comment]
I would not schedule attempts individually. In my opinion it's very simple, either they compete with the full limit, or they don't compete at all.
I was merely suggesting that scheduling attempts individually can be an alternative to consider if (for some reason) you want to allow late competitors to still compete.

Anyway, why would this new regulation only apply to rounds with cumulative limits? Why not extend it to any round, and let the delegate arbitrarily lower the (per solve) time limit for a competitor that is late?

**Comment by Jambrose777** [comment]
I'm strongly in favor of this. A lot of Delegates want to give their competitors the most amount of opportunity to compete, and this would only encourage that. (instead of having to either deny them or allow them to compete with a risk that they may not honor an unofficial agreement).

Scheduling individual attempts goes completely the opposite way of what a cumulative limit is designed to do. The point is to allow as many competitors an ample amount of time to complete as many attempts as they can. So, If I can schedule 1h for 4x4 Blindfolded, If I scheduled individual attempts, there would be a 15minute time limit per attempt, whereas scheduling them all together gives a 1 hour cumulative and gives slower competitors more opportunities to compete.

This would not work for normal events due to a larger issue with scramble secrecy, grouping competitors, etc... In the end, this would just be an additional option to what we have now, it would not force Delegates to make such decisions.

I think it is fair for a delegate to decrease any amount of minutes for a late competitor. They could have just denied them to compete anyways.

**Comment by xsrvmy** [comment]
> Anyway, why would this new regulation only apply to rounds with cumulative limits? 

I think part of the problem here is that 4bld and 5bld cannot happen at the same time as another event, and that the time variation for 4bld and 5bld is huge. The main problem with late competitors seems to be scheduling. For normal events, a group change should not affect schedule. Additionally, bld events are bo3 so there is a reason for someone to do a single attempt.

> Why not extend it to any round, and let the delegate arbitrarily lower the (per solve) time limit for a competitor that is late?

There would be no standard. Cumulative limits are used for scheduling purposes. Limits for small events are usually much longer than necessary for scheduling, and basically no one hits them. It would be hard to make a regulation to prevent a delegate from lowering the time limit below a reasonable number (eg. 15 seconds).

**Comment by xsrvmy** [comment]
Actually, a slightly different idea, although it does become a bit complicated:
Allow the delegate, before the last solve of the competitor, to tell the competitor that he/she must finish before a certain time. This time is either when the other competitors are done, or when the round is supposed to end, whichever comes last. The competitor MUST be notified before the attempt (debatable of course).

**Comment by AlexKatyukov** [comment]
I'm not favour about this. It will slightly relax fast competitors and make a problem with scramble secrecy (one competitor can make one attempt, two DNFs and go out, second competitor can came only after this).

**Comment by xsrvmy** [comment]
@AlexKatyukov I don't think that is a relevant point here. This new regulation would just give delegates an additional way of handling late competitors. The delegate already has the right to allow a late competitor to compete.
